akkadotnet/akka.net

- docs/articles/clustering/cluster-sharding.md
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/InactiveEntityPassivationSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
Port [#27177](https://github.com/akka/akka/pull/27177)
> Don't passivate idle for remembering entities

- src/core/Akka.Remote.Tests/RemotingSpec.cs
These specs seemed to be especially sensitive to timeouts due to some of them being long-running - forcing them to run serially to see if it helps.
> disable some racy RemotingSpecs [Akka.Remote.Tests]

- build.fsx
- build.ps1
- src/common.props
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
This is the first in a few pull requests aimed at offering better performance testing support for Akka.NET - this upgrades the solution to use NBench 1.2.2 and uses the `dotnet-nbench` command, but I will need to make some changes to NBench in order to make `dotnet-nbench` fully compatible with `common.props` before it can be run officially.
I'll also be submitting another pull request aimed at introducing .NET Core tests for Akka.NET, which NBench 1.2.2 is a pre-requisite for.
> NBench standardization

- src/core/Akka.Cluster.Tests/SplitBrainResolverConfigSpec.cs
Multiple tests were trying to bind to the same port, which created issues when running them in parallel.
> fixed racy SplitBrainResolverConfigSpec

- RELEASE_NOTES.md
- src/common.props
**First pre-release candidate for Akka.NET 1.4**
Akka.NET v1.4 has a ways to go before it's fully ready for market, but this is the first publicly available release on NuGet and it contains some massive changes.
* Akka.Cluster.Sharding's default "persistent" mode has been stabilized and errors that users have ran into during `ShardCoordinator` recovery, such as [Exception in PersistentShardCoordinator ReceiveRecover](https://github.com/akkadotnet/akka.net/issues/3414)
* StreamRefs have been added to Akka.Streams, which allows streams to run across process boundaries and over Akka.Remote / Akka.Cluster.
* Akka.NET now targets .NET Standard 2.0, which means many annoying polyfills and other hacks we needed to add in order to support .NET Core 1.1 are now gone and replaced with standard …
> added Akka.NET v1.4 beta1 release notes

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientHandoverSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/RingOrderingTests.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClient.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/Serialization/ClusterClientMessageSerializer.cs
- src/core/Akka/Routing/ConsistentHash.cs
Using the test cases provided by @mwpro on #2535 
Also ports:
https://github.com/akka/akka/pull/22992
https://github.com/akka/akka/pull/24167
Close #2535 
Close #2312
Close #3840
> ClusterClient fixes

- src/common.props
When compiling Akka.NET locally on some of my development machines, ran into the following known issue with `Microsoft.SourceLink`: https://github.com/dotnet/sourcelink/issues/337
Upgrading to the latest, 1.0.0-beta2-19367-01, should resolve this issue.
> update Microsoft.SourceLink.Github to 1.0.0-beta2-19367-01

- docs/examples/Tutorials/Tutorial1/IotApp.cs
edit the code sample of the main app to properly utilize the "...recommended creational pattern for actors; define a static Props() method".
i.e. using the static Props method instead of Props.Create.
I read the Contributing guide for Akka.NET after I made the edits in the browser so I'm not sure if the edits are inline with the guide. If not, I can issue a new, more correct, pull request.
> Update IotApp.cs sample code for tutorial 1 documentation.

- src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.nuspec.template
This bug caused issues with being able to consume the Akka.MultiNodeTestRunner NuGet package for v1.4.0-beta1.
> updated MNTR NuGet to correctly target .NET Core 2.1 and .NET Framework 4.6.1

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
Looks like an indefinitely waiting `Task` was the issue causing persistent failures with https://github.com/akkadotnet/akka.net/pull/3881#issuecomment-525392481
> resolved lock-up with DistributedPubSubMediatorSpecs

- build.ps1
- build.sh
Has a bugfix which should ensure that CI runs when someone changes only an embedded resource file, like the timeout settings here https://github.com/akkadotnet/akka.net/pull/3897
> upgraded to Incrementalist v0.1.5

- src/core/Akka.Remote.TestKit/Internals/Reference.conf
> increase Akka.Remote.TestKit TestConductor timeout to 30s by default

- src/core/Akka/Akka.csproj
Going to begin the task of converting our APIs to use `ValueTuple` instead of `Tuple` one step at a time. Adding a reference to `System.ValueTuple` in the core project so it's available everywhere.
> add System.ValueTuple reference

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs
- src/core/Akka.Persistence.TestKit.Xunit2/PersistenceTestKit.cs
- src/core/Akka.Persistence.TestKit/Journal/JournalRecoveryBehavior.cs
- src/core/Akka.Persistence.TestKit/Journal/JournalWriteBehavior.cs
- src/core/Akka.Persistence/PersistentView.Recovery.cs
- src/core/Akka.Remote/EndpointRegistry.cs
- src/core/Akka.Remote/Transport/Transport.cs
- src/core/Akka.Streams/ActorMaterializer.cs
- src/core/Akka.Streams/Dsl/Flow.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
- src/core/Akka/Event/ILoggingAdapter.cs
- src/core/Akka/Event/LoggingAdapterBase.cs
- src/core/Akka/IO/Tcp.cs
- src/core/Akka/Pattern/BackoffOnRestartSupervisor.cs
- src/core/Akka/Util/Base64Encoding.cs
This PR fixes a number of broken cross references and adds a couple of missing parameter references.
Most of the cross references were referencing fields in the subclass. For some reason MSBuild doesnt like that. The fix was to reference the fields of the base class and the link text pointed to the correct subclass field.
> [xml-docs] Fixed broken xrefs / missing field refs

- src/core/Akka.Remote.Tests/Transport/AkkaProtocolStressTest.cs
Turned this back on in a recent PR and it turns out to be extremely racy still. Disabling it once again.
> disabling AkkaProtocolStressTest

- src/contrib/cluster/Akka.DistributedData.Tests/GSetSpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/PNCounterSpec.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpecExtensions.cs
- src/core/Akka.Tests/Actor/LocalActorRefProviderSpec.cs
This PR fixes a few xunit warnings.
Most of these warnings were in the form of Assert.Equals(<bool>, <some value>) where xunit suggests the more readable Assert.<bool>(<some value>).
Also removed a duplicate InlineData entry that wasn't testing duplicates.
> [xunit] Fix xunit warnings

- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpecKit.cs
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphInterpreter.cs
- src/core/Akka.Tests/Pattern/BackoffOnRestartSupervisorSpec.cs
- src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs
- src/core/Akka/Actor/Props.cs
- src/core/Akka/Dispatch/AbstractDispatcher.cs
This PR fixes a number of warnings related to CS0162 (Unreachable code detected).
Most of these are related to conditional debugging flags that aren't necessarrily set during a normal compilation. There are some however that are there as to clear any compile errors that would happen due to ambigious references.
The pragmas are added to the function boundaries so as not to pollute the logic in the function.
> [build] Fix CS0162 warnings

- build-system/nightly-builds.yaml
Reverts akkadotnet/akka.net#3957
It now runs on merge as well. Template is probably correct and im seriously suspecting an AzureDevops bug
> Revert "Fix nightly-build template"

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence/Fsm/PersistentFSM.cs
- src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
Also replaces all internal calls with calls to Copy, so Using can safely be removed in the future.
> Deprecate PersistentFSM+State.Using (#3955)

- build-system/windows-release.yaml
- build.fsx
Updates the build script to handle the newer snupkg format.
Please try and check if this works - can't test it with the official nuget packages obviously.
refs #3954
> fix: NuGet symbols not published (#3954)

- build.fsx
Disables the --no-build flag when packing NuGet packages of F# projects as that causes build errors when .net core SDK 3.0.100 is installed.
refs #3967
> fix: build fails when SDK 3.0.100 is installed (#3967)

- build.fsx
Reverts akkadotnet/akka.net#3968
I think this may have caused an issue with building our NuGet packages. We might need to take another whack at it.
> Revert "fix: build fails when SDK 3.0.100 is installed (#3967) (#3968)"

- src/core/Akka/Akka.csproj
> only reference System.ValueTuple NuGet package when building against .NET Framework

- src/core/Akka.Persistence.TCK/Journal/JournalSpec.cs
`DeadLetters` is the correct output from `IActorRef` deserialization when `null` is found - needed to add a check for that inside the Akka.Persistence.TCK. Found this while working on https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/71
> Akka.Persistence.TCK fix - check Persistent.Sender == DeadLetters

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
> Singleton - missing state change fix

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardCoordinator.cs
The RebalanceWorker actor needs to watch the shard regions that it's
expecting a BeginHandOffAck message from, in case the ShardRegion shuts
down before it can receive the BeginHandOff message, preventing hand
off.  This can be a problem when two nodes are shut down at about the
same time.
Migrated from https://github.com/akka/akka/pull/27261
> Sharding - RebalanceWorker should watch shard regions

- build.fsx
Removes --no-build flag from all NuGet builds to make sure F# projects can be packed when .net Core 3 SDK is used.
refs #3967 
refs #3968
refs #3969
> fix: build fails when SDK 3.0.100 is installed, second attempt (#3967)

- RELEASE_NOTES.md
**Third pre-release candidate for Akka.NET 1.4**
This release contains some more significant changes for Akka.NET v1.4.0.
* All APIs in Akka.Streams, Akka, and elsewhere which used to return `Tuple<T1, T2>` now support the equivalent `ValueTuple<T1,T2>` syntax - so new language features such as tuple deconstruction can be used by our users.
* Upgraded to Hyperion 0.9.10, which properly supports .NET Core 3.0 and cross-platform communication between .NET Framework and .NET Core.
* All `ILoggingAdapter` instances running inside Akka.NET actors will now include the full Akka.Remote `Address` during logging, which is very helpful for users who aggregate their logs inside consolidated systems.
* Various Akka.Cluster.Sharding fixes.
To [follow our progress on the Akka.NET v1.4 milestone, click …
> added v1.4.0-beta3 release notes

- src/benchmark/Akka.Benchmarks/Actor/PingPongBenchmarks.cs
- src/benchmark/Akka.Benchmarks/Actor/SpawnActorBenchmarks.cs
- src/benchmark/Akka.Benchmarks/Akka.Benchmarks.csproj
- src/benchmark/Akka.Benchmarks/Configurations/Configs.cs
- src/benchmark/Akka.Benchmarks/IO/TcpOperationsBenchmarks.cs
This is improvement of #4015 benchmark, which adds support for multiple parallel clients sending requests to server actor.
Also, I had to increase `BenchmarkDotNet` package version to `0.12.0`, because current version `0.10.14` is a year old and does not contain some issue fixes (like it was failing to perform benchmark if there was any output to a console).
> Akka.IO.Tcp benchmark with parallel clients

- RELEASE_NOTES.md
- build-system/windows-release.yaml
- build.fsx
- src/common.props
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingInternalsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingSettingsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeave2Spec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs
- src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj
- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceQuery.approved.txt
- src/core/Akka.Persistence.Query.Tests/OffsetCompareSpecs.cs
- src/core/Akka.Persistence.Query/Offset.cs
- src/core/Akka.Persistence.TCK/Query/TestActor.cs
- src/core/Akka.Persistence.Tests/Fsm/PersistentFSMSpec.cs
- src/core/Akka.Persistence/Fsm/PersistentFSM.cs
- src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
- src/core/Akka/Actor/ActorCell.ReceiveTimeout.cs
- src/core/Akka/Routing/RouterMsg.cs
Putting this into draft mode for now - need to see CI pass before we try releasing this against the v1.3.* branch.
> V1.3.16 Release

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Event/DeadLetterListener.cs
Looks like we never had a chance of disabling `log-dead-letters-during-shutdown`
> Stop DeadLetterListener on terminate if LogDeadLettersDuringShutdown is disabled

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster.Tests/ShutdownAfterJoinSeedNodesSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka/Actor/CoordinatedShutdown.cs
Port [#23551](https://github.com/akka/akka/pull/23551)
> Add timeout to abort joining of seed nodes

- src/core/Akka.MultiNodeTestRunner.Shared/TrxReporter/TrxSinkActor.cs
Close #4035 
Here is the code that is failing with NRE:
```csharp
private static void ReportFailure(SpecSession session, Dictionary<int, UnitTestResult> nodeResults)
{
foreach (var (time, message) in session.Fails)
{
var result = nodeResults[message.NodeIndex];
result.Outcome = TestOutcome.Failed;
result.EndTime = time;
result.Output = new Output();
result.Output.StdErr.Add(message.Message);
result.Output.DebugTrace.Add(message.Message);
result.Output.ErrorInfo.Message = message.Message;
}
}
```
Since we do not have exact like, there are few candidates to throw NRE (expressions that could be `null` in this case): 
`session`
`noreResults
`message` from `var (time, message) in session.Fails`
`nodeResults[message.NodeIndex]`
`result.Output.StdErr` or `result.Output.DebugTrace` or …
> MNTR NRE fix for #4035

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TimelineLogCollectorActor.cs
- src/core/Akka.MultiNodeTestRunner/Program.cs
Working on #4059 here.
So far, added aggregation of all log messages into single `aggregated.txt` file, ordered by timestamp. So, now it should be easier to review what is happening across the nodes.
I guess we will also need to output this aggregated timeline to Azure Pipelines output. This should be as simple as writing all of this logs into a console.
> MNTR logs representation improvements

- src/core/Akka.Tests/IO/TcpIntegrationSpec.cs
- src/core/Akka/IO/TcpConnection.cs
Close #3775
Since internal writes buffering is something built-in now, it is pretty simple to handle this inside of `TcpConnection` actor. So both logging and buffering are implemented.
Also, internal buffer overflow should be handled.
> Logging and buffering Tcp.Write before Tcp.Register received

- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TimelineLogCollectorActor.cs
Related to #4059
Looks like in my #4067 PR I missed the fact that logger will format log record date and time depending on current locale. Current code was trying to parse single format (the once that is used on my local machine) - so need to fix this to support current locate. This will also fix parsing logs from CI run.
P.S. By the way, actually even if it will fail to parse the format, current implementation takes date and time of receiving the log for sorting. So, it will still give some more or less valid record order (but obviously some surprises may come up in that case).
> Fix MNTR logs datetime parsing

- docs/articles/intro/tutorial-1.md
I was reading the documentation and stumbled upon the description of the user guardian which caught my attention since it seemed a bit too generic.
By looking at the description of the other guardians I came to the conclusion that the description probably meant to say: _user guardian_ instead of just: _guardian_.
What do you think? :smiley:
> Possible correction in one of the intro documents. Changed to 'user guardian'.

- src/core/Akka.Tests/IO/TcpIntegrationSpec.cs
- src/core/Akka/IO/TcpManager.cs
- src/core/Akka/IO/UdpManager.cs
> Detailed error message on sending Tcp.Close to TcpManager

- src/core/Akka.TestKit/EventFilter/IEventFilterApplier.cs
- src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka.TestKit/TestKitBase_AwaitAssert.cs
- src/core/Akka.TestKit/TestKitBase_AwaitConditions.cs
- src/core/Akka.TestKit/TestKitBase_Within.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
Close #3854
Close #3774
The core of #4072 PR - adding async overloads for TestKit API to avoid blocking threads.
> Added async API to Akka.TestKit

- src/core/Akka.Cluster/Cluster.cs
Usage of string interpolation prevents some loggers (i.e., Serilog) from applying the correct format to the output template.
> Remove string interpolation from cluster logs

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ConstantRateEntityRecoveryStrategySpec.cs
This test was giving me a fairly high flip rate locally - and the fix is quite straight forward.
Previous code was equating an IEnumerable<T> to an ImmutableHashSet<T> which yields inconsistent results due to the way a ImmutableHashSet<T> is structured.  For consistency, we now convert to a ImmutableHashSet<T> before the comparison.
> Convert to ImmutableHashSet for consistency in comparison

- src/core/Akka.Remote/Endpoint.cs
The ordering of the 2nd and 3rd parameters for C#'s `ConcurrentDictionary.TryUpdate` are inverted from Scala's `Map.replace`.
`public bool TryUpdate (TKey key, TValue newValue, TValue comparisonValue);` [docs](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.tryupdate?view=netframework-4.8#System_Collections_Concurrent_ConcurrentDictionary_2_TryUpdate__0__1__1_
)
vs
`abstract def replace(k: A, oldvalue: B, newvalue: B): Boolean` [docs](https://www.scala-lang.org/api/2.12.1/scala/collection/concurrent/Map.html#replace(k:A,oldvalue:B,newvalue:B):Boolean)
A quick review of the entire Akka.NET code base only shows a few usages of `TryUpdate`.  One in particular appears to have the old and new parameters backwards.
(Scala implementation for …
> Fix #4083 - Endpoint receive buffer stack overflow

- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka.Tests/Util/TypeExtensionsTests.cs
- src/core/Akka/Util/TypeExtensions.cs
Ported type name extraction from Hyperion into Akka's `TypeExtensions.TypeQualifiedName`.
This PR resolves #3767
> TypeExtensions.TypeQualifiedName like in Hyperion

- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
> Default number of nodes that each node is observing for failure detection has increased from 5 to 9. The reason is to have better coverage and unreachability information for downing decisions.
Port: [#27173](https://github.com/akka/akka/pull/27173)
> Increase default number of nodes for cluster failure detection

- src/benchmark/RemotePingPong/Program.cs
In order to capture changes in the overall performance of the system, especially with upcoming changes like flush batching, it's necessary to run the benchmark for longer periods of time.
> increased RemotePingPong by an order of magnitude

- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
In some instances with Akka.Remote, even during a normal graceful shutdown where a node terminates its `ActorSystem`, it's still possible to get errors such as
```
[ERROR][12.16.2019 13:50:26][Thread 0021][Akka.Remote.Transport.DotNetty.TcpServerHandler] Error caught channel [[::ffff:127.0.0.1]:56060->[::ffff:127.0.0.1]:51761](Id=73c17098)
Cause: System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuffer byteBuf)
at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
```
I spent several hours looking into this today, trying to understand whether this was a bug …
> Akka.Remote: don't log aborted connection as disassociation error

- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
So long as we are looking to support Mono, this patch will be necessary to help mitigate race conditions within Mono's TermInfoDriver.  I've already got an active PR to fix Mono, but I'm not sure if it's going to be back-merged into other streams.
Please speak up if there's concerns about the way this hack works.  I don't like it, but can't quite think of any less-worse way to do it.
> Add initializer for console properties

- src/common.props
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
- src/core/Akka/Util/Internal/TaskEx.cs
Still need to:
1. [x] Add API approvals
2. [x] Possibly mark some of these APIs are obsolete and / or remove them, since they're no longer needed.
> Refactor TaskEx API to deprecate pre-4.6.1 methods

- src/core/Akka.Tests/Actor/Dispatch/CurrentSynchronizationContextDispatcherSpecs.cs
- src/core/Akka.Tests/Routing/ConsistentHashingRouterSpec.cs
Turned out that few tests have bad HOCON configuration specified - fixed this.
> Added missing brackets in HOCON test configs

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs
- src/core/Akka.Persistence/Serialization/PersistenceSnapshotSerializer.cs
- src/core/Akka.Remote/Serialization/DaemonMsgCreateSerializer.cs
- src/core/Akka.Remote/Serialization/MessageContainerSerializer.cs
- src/core/Akka.Remote/Serialization/WrappedPayloadSupport.cs
- src/core/Akka.Streams/Serialization/StreamRefSerializer.cs
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Serialization/Serialization.cs
This PR adds `Serializer.ManifestFor` and calls it wherever it's needed through Akka.NET various serialization areas. This is designed to replace a bunch of boilerplate and inconsistent code used for determining what manifest needs to be included inside an outbound payload.
The functionality matches what we already do today inside Akka.Remote and Akka.Persistence, but now it's standard.
Relates to https://github.com/akkadotnet/akka.net/issues/3811 and https://github.com/akkadotnet/akka.net/issues/3248
> Standardize serialized type manifest lookup process

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/LeastShardAllocationStrategySpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/SupervisionSpec.cs
- src/core/Akka/Akka.csproj
These tests are long-running, access shard memory journals, et al... We'd get better results running them serially rather than in parallel.
> disable parallelism in Akka.Cluster.Sharding.Tests

- src/core/Akka.Tests/IO/TcpIntegrationSpec.cs
- src/core/Akka/ActorState.cs
Related to #3786
Fix racy test: Akka.Tests.IO.TcpIntegrationSpec.Should_fail_writing_when_buffer_is_filled
Test is pretty straightforward, and failes on sending data to `TcpConnection` actor and waiting for response. Maybe related to the fact that it is sending 2 messages by `10Kb` each.
Anyway, lets try to increase timeouts, and use `AwaitAssertAsync` to make several tries with pauses
> Fix racy test: Akka.Tests.IO.TcpIntegrationSpec.Should_fail_writing_when_buffer_is_filled

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/CoordinatedShutdownShardingSpec.cs
- src/core/Akka/ActorState.cs
Related to #3786
This PR should improve/fix flip rate of this test:  Akka.Cluster.Sharding.Tests.CoordinatedShutdownShardingSpec.Sharding_and_CoordinatedShutdown_must_run_successfully
It is time sensitive and failing due to timeouts (because of remote address gating). Seems like the test is correct by itself, so lets start with using `async` test APIs and increasing timeouts.
> Fix racy test: Akka.Cluster.Sharding.Tests.CoordinatedShutdownShardingSpec.Sharding_and_CoordinatedShutdown_must_run_successfully

- RELEASE_NOTES.md
- src/common.props
**Fourth pre-release candidate for Akka.NET 1.4**
Akka.NET v1.4.0-beta4 represents a significant advancement against the v1.4.0 milestone, with numerous changes and fixes. 
**Akka.NET now targets .NET Standard 2.0 going forward** - this first big change in this release is that we've dropped support for .NET Framework 4.5. We will only target .NET Standard 2.0 going forward with the v1.4.0 milestone from this point onward. .NET Standard 2.0 can be consumed by .NET Framework 4.6.1+ and .NET Core 2.0 and higher.
**Introduction to Akka.Cluster.Metrics** - in this release we introduce a brand new Akka.NET NuGet package, Akka.Cluster.Metrics, which is designed to allow users to share data about the relative busyness of each node in their cluster. Akka.Cluster.Metrics can be consumed inside …
> V1.4.0 beta4 release notes

- src/core/Akka.MultiNodeTestRunner/Discovery.cs
Close #4179
While exception in referenced issue is thrown from `Discovert.RoleNames` method (from `Activator.CreateInstance` there), generally speaking we need to handle "loading test details" process - which is now moved to separate method and handles any exception that may occur (logs it and keeps going).
Did not find easy way to add test for it, but it was easy to reproduce and pretty straightforward to fix.
> Added test details loading exception handling

- src/core/Akka.Persistence.TCK/Snapshot/SnapshotStoreSpec.cs
Found this bug while working on https://github.com/akkadotnet/Akka.Persistence.MongoDB/pull/108
Need to be able to skip the `ShouldSerializeSnapshots` spec if `SupportsSerialization` is set to `false`.
> Akka.Persistence.TCK.SnapshotStoreSpec ignores ShouldSerializeSnapshots if SupportsSerialization == false

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/CoordinatedShutdownShardingSpec.cs
Part of #3786 
Still having issues with this spec even after https://github.com/akkadotnet/akka.net/pull/4158 - believe the problem was having multiple shards reply back.
Going to keep this in draft form and run it a few times.
> make CoordinatedShutdownShardingSpec use murmur hash for shard distributions

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/CoordinatedShutdownShardingSpec.cs
https://github.com/akkadotnet/akka.net/pull/4186 didn't do the trick.
Marking this spec as racy in the suite and skipping it.
Per #3786
> disable Sharding_and_CoordinatedShutdown_must_run_successfully spec

- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
- src/core/Akka.Remote.TestKit/Player.cs
This was a configuration issue that may be responsible for a number of "racy" tests we have in the multi node test runner (MNTR) suite.
Specifically, this fix disables coordinated shutdown so the `ActorSystem` does not terminate by default when a node leaves the cluster - that way the `PlayerFSM` on the node that has left can still successfulyl call `EnterBarrier(string name)` and not blow up the entire test suite.
> fix race conditions with node exits in MNTR

- src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/JepsenInspiredInsertSpec.cs
closes #3078 - pleased to report that, locally, this passed on the very first try after fixing one N-1 error in the constructor.
> DData: enable and fix Jepsen inspired insert spec

- src/contrib/cluster/Akka.Cluster.Metrics.Tests/ClusterMetricsExtensionSpec.cs
Noticed this spec failed due to timeout issues here: https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=28690&view=logs&j=d83928d8-8bfe-51de-721e-9025f72ee732&t=21d77f07-2bef-56ac-91e9-8618e6456479
So improved the code to be more robust.
> Improve racy Clustet.Metrics Metrics_extension_Should_control_collector_on_off_state spec

- src/core/Akka.Remote/Endpoint.cs
close #4246 
Rewrote To no longer use ConcurrentDictionary methods that can throw
> no throw inside EndpointReader.UpdateState

- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
close #3879 
close #3273 
close #4244 
For reasons that are fundamentally structural, it's not safe for Akka.Remote to use DotNetty's buffer pooling of any kind - the reason being that serialization and deserialization is handled outside of the `ChannelPipeline` itself thus the bytes returned from the channel aren't safe for release until after they're successfully decoded by Akka.Remote's endpoint actors.
In order to take advantage of buffer pooling, Akka.Remote will need to be redesigned with a more integrated serialization pipeline in mind - something we've discussed on #2378 
Ran some local benchmarks on my development machine here - no major changes in observed performance at all.
```
ProcessorCount:                    8
ClockSpeed:                        0 MHZ
Messages sent/received …
```
> disable buffer pooling in DotNetty transport

- src/core/Akka.Tests/Dispatch/DispatchersSpec.cs
> harden DispatchersSpec

- src/contrib/cluster/Akka.DistributedData.Tests/WriteAggregatorSpec.cs
> harden DData.Tests.WriteAggregatorSpecs

- build-system/pr-validation.yaml
Reverts akkadotnet/akka.net#4294
Turns out this was wrong - worked fine. Had to update the v1.3 branch to trigger CI, which I've done here: https://github.com/akkadotnet/akka.net/pull/4296
> Revert "explicitly support CI for the v1.3 branch"

- src/core/Akka/IO/TcpConnection.cs
Close #4264
Issue was that after socket operation was completed, we started sending pending packages without setting "Sending" status. So it was only a matter of time when there will be some sender that will send his package at the same time last "pending" package was sent, and we got this error.
Setting "Sending" status in both cases, and all is running smooth.
> SAEA already in use error fix

- src/core/Akka/Actor/ActorCell.DeathWatch.cs
- src/core/Akka/ActorState.cs
I made the PR against v1.3 as that's what we're using and where I could confirm the bug and the fix.
> Fixes actor ref leak in AddressTerminatedTopic (#4304)

- src/core/Akka/Event/AddressTerminatedTopic.cs
Submitting PR against v1.3, as that's what we're using and I was able to test the fix with.
The new implementation fixes both the race condition as well as optimizes the full copies of the _subscribers HashSet during Subscribe() and Unsubscribe(). The updates are protected with locks which makes the code simple and efficient. Publish() only takes a copy under lock to minimize the amount that the data is not available for other threads, which should be ok, as Publish() is only needed when a node is lost, so not too frequently.
> Fix address terminated topic atomic updates (#4306)

- RELEASE_NOTES.md
- src/common.props
1.3.18 consists of non-breaking bugfixes and additions that have been contributed against the [Akka.NET v1.4.0 milestone](https://github.com/akkadotnet/akka.net/milestone/17) thus far.
This patch includes some important fixes for Akka.Remote including
* [Akka Bugfix: Atomicity bug and bad performance in AddressTerminatedTopic](https://github.com/akkadotnet/akka.net/issues/4306)
* [Akka Bugfix: Actor reference leak in AddressTerminatedTopic](https://github.com/akkadotnet/akka.net/issues/4304)
* [Akka.Remote Bugfix: DotNetty.Codecs.CorruptedFrameException: negative pre-adjustment length field](https://github.com/akkadotnet/akka.net/issues/3879)
* [Akka.Remote Bugfix: "The given key was not present in the dictionary" …
> added v1.3.18 release notes

- src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/AssemblyVersioning/BackwardsCompatSqliteSnapshotStoreSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteConfigSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteSnapshotStoreConnectionFailureSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Extension.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Snapshot/SqliteSnapshotStore.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/sqlite.conf
Closes #4079 
Extra bug fix: Sqlite plugin default config was not applied as a fallback to populate `JournalSettings` instance in `SqlJournal` constructor
This might be a breaking change for users that copy pasted sqlite journal configuration from a sample that contains a `table-name = not_called_snapshot` entry because it will start to use the property declaration instead of using the hard coded `snapshot` table.
> FIX: #4079 sqlite table name was hardcoded

- RELEASE_NOTES.md
- docs/community/whats-new/akkadotnet-v1.4.md
- src/common.props
**Stable release candidate for Akka.NET 1.4**
In Akka.NET v1.4.1-rc2 we rolled back all of the stand-alone HOCON additions and made Akka.NET v1.4 non-breaking. 
For information on the full set of changes between RC1 and RC2, [please see "What's New in Akka.NET v1.4" on the official Akka.NET website](https://getakka.net/community/whats-new/akkadotnet-v1.4.html) 
| 13 | 9431 | 5347 | Aaron Stannard |
| 2 | 3 | 3 | dependabot-preview[bot] |
| 1 | 97 | 73 | Gregorius Soedharmo |
| 1 | 6 | 1 | Igor Fedchenko |
> V1.4.1 rc2 release notes

- RELEASE_NOTES.md
- src/common.props
**Stable release candidate for Akka.NET 1.4**
In Akka.NET v1.4.1-rc2 we rolled back all of the stand-alone HOCON additions and made Akka.NET v1.4 non-breaking. 
* [Akka.Persistence.Sql.Common: Fix, unsealed `JournalSettings` and `SnapshotStoreSettings` classes](https://github.com/akkadotnet/akka.net/pull/4319)
> added v1.4.1-RC3 release notes

- RELEASE_NOTES.md
- src/common.props
**Major release for Akka.NET 1.4**
Akka.NET v1.4 is a non-breaking upgrade for all Akka.NET v1.3 and earlier users. It introduces many new features, all of which can be found in our ["What's new in Akka.NET v1.4" page](https://getakka.net/community/whats-new/akkadotnet-v1.4.html).
Major changes include:
* Akka.Cluster.Sharding and Akka.DistributedData are now out of beta status and are treated as mature modules.
* Akka.Remote's performance has significantly increased as a function of our new batching mode (see the numbers) - which is tunable via HOCON configuration to best support your needs. [Learn how to performance optimize Akka.Remote here](https://getakka.net/articles/remoting/performance.html).
* Added new Akka.Cluster.Metrics module to measure and broadcast the performance of each …
> added v1.4.1 final release notes

- src/core/Akka/Actor/ActorRef.cs
> IActorRef Equals and CompareTo behavior change

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.2 fixes two issues that affected users as part of the Akka.NET v1.4.1 rollout:
* [Bugfix: Missing v1.4.1 NuGet packages](https://github.com/akkadotnet/akka.net/issues/4332)
* [Bugfix: App.config loading broken in Akka.NET v1.4.1](https://github.com/akkadotnet/akka.net/issues/4330)
To see the full set of changes for Akka.NET 1.4.2, please [see the 1.4.2 milestone(https://github.com/akkadotnet/akka.net/milestone/32).
> 1.4.2 release notes

- RELEASE_NOTES.md
- docs/articles/remoting/performance.md
- src/common.props
- src/contrib/cluster/Akka.Cluster.Metrics/Akka.Cluster.Metrics.csproj
- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
- src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj
- src/core/Akka.Tests/App.config
- src/core/Akka.Tests/Configuration/ConfigurationSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
Akka.NET v1.4.2 fixes two issues that affected users as part of the Akka.NET v1.4.1 rollout:
* [Bugfix: Missing v1.4.1 NuGet packages](https://github.com/akkadotnet/akka.net/issues/4332)
* [Bugfix: App.config loading broken in Akka.NET v1.4.1](https://github.com/akkadotnet/akka.net/issues/4330)
To see the full set of changes for Akka.NET 1.4.2, please [see the 1.4.2 milestone](https://github.com/akkadotnet/akka.net/milestone/32).
> v1.4.2 Release

- docs/articles/utilities/circuit-breaker.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Docs.Tests/Utilities/CircuitBreakerDocSpec.cs
- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Pattern/CircuitBreakerState.cs
- src/core/Akka/Util/Internal/AtomicState.cs
> Current implementation works great when the call is wrapping a future with direct response. However, if the actor is expecting a message back or ReceiveTimeout, then using the circuit breaker is awkward -- there's no way to access the circuit breaker's current state, or signal a failure or success directly.
PR [#21074](https://github.com/akka/akka/pull/21074)
> Expose success and fail methods in CircuitBreaker

- src/common.props
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/examples/AppConfig/App.config
- src/examples/AppConfig/AppConfig.csproj
- src/examples/AppConfig/Program.cs
Closes #4343 
Bugfix:
* Add System.Configuration.ConfigurationManager support for NET standard 2.0 build.
> CONFIGURATION compiler directive is missing from Akka.Persistence.Sql.Common netstandard2.0 build target

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.3 fixes one major issue that affected Akka.Persistence.Sql users as part of the v1.4 rollout:
* [Bugfix: No connection string for Sql Event Journal was specified](https://github.com/akkadotnet/akka.net/issues/4343)
To see the full set of changes for Akka.NET 1.4.3, please [see the 1.4.3 milestone](https://github.com/akkadotnet/akka.net/milestone/34).
| 1 | 78 | 2 | Gregorius Soedharmo |
| 1 | 2 | 2 | dependabot-preview[bot] |
| 1 | 172 | 11 | Ismael Hamed |
> added v1.4.3 release notes

- RELEASE_NOTES.md
- docs/articles/utilities/circuit-breaker.md
- src/common.props
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Docs.Tests/Utilities/CircuitBreakerDocSpec.cs
- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.FSharp/Akka.FSharp.fsproj
- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Pattern/CircuitBreakerState.cs
- src/core/Akka/Util/Internal/AtomicState.cs
- src/examples/AppConfig/App.config
- src/examples/AppConfig/AppConfig.csproj
- src/examples/AppConfig/Program.cs
Akka.NET v1.4.3 fixes one major issue that affected Akka.Persistence.Sql users as part of the v1.4 rollout:
* [Bugfix: No connection string for Sql Event Journal was specified](https://github.com/akkadotnet/akka.net/issues/4343)
To see the full set of changes for Akka.NET 1.4.3, please [see the 1.4.3 milestone](https://github.com/akkadotnet/akka.net/milestone/34).
| 1 | 78 | 2 | Gregorius Soedharmo |
| 1 | 2 | 2 | dependabot-preview[bot] |
| 1 | 172 | 11 | Ismael Hamed |
> v1.4.3 Release

- docs/articles/intro/tutorial-3.md
Remove a word that doesn't fit the sentence in an the part three of the introdcution doc.
> Remove typo in introduction doc.

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorPath.cs
I was seeing a lot of allocations happening in a system with tens of thousands of actors, which was causing the system to slow down over hours or days due to the increase of time spent in GC. This PR optimizes away some allocations from commonly used ActorPath methods, in order of importance.
1. Added ChildActorPath.GetHashCode(), which is able to compute the hash code without invoking ActorPath.Elements, which allocates memory for the segments. The implementation iterates the segments in reverse order compared to the original implementation. It didn't seem to cause any problems, but I might not understand all the repercussions. It is possible to go back to the original order, but it requires some additional trickery.
The GetHashCode() code path is invoked a lot in the code due to the …
> Optimize some memory allocations from ActorPath.

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Persistence.Tests/TimerPersistentActorSpec.cs
- src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
- src/core/Akka.TestKit/Internal/InternalTestActorRef.cs
- src/core/Akka.Tests/Actor/TimerSpec.cs
- src/core/Akka/Actor/ActorBase.Lifecycle.cs
- src/core/Akka/Actor/ActorBase.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/FSM.cs
- src/core/Akka/Actor/Scheduler/ITimerScheduler.cs
- src/core/Akka/Actor/Scheduler/IWithTimers.cs
- src/core/Akka/Actor/Scheduler/TimerScheduler.cs
migrated from https://github.com/akka/akka/pull/22873
> Timers for self scheduled messages added, FSM timers fixes

- src/core/Akka.Cluster.Tests.MultiNode/Bugfix4353Specs.cs
- src/core/Akka/Actor/Deploy.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Configuration/Config.cs
- src/core/Akka/Configuration/Hocon/HoconObject.cs
Possible fix for #4353, there might be other factors involved.
> #4353 Config.WithFallback is acting inconsistently

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingLeaseSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/TestLease.cs
sharding is currently not releasing lease when shard is moved to another server.
Added fix & test for this scenario
Not sure how it works in scala implementation, because I don't see there lease being released anywhere, so maybe there is the same issue. It's released only for singletons.
> sharding - release shard lease when shard stopped

- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster/Member.cs
Recently, I needed an AgeComparer to calculate the oldest member of the cluster. `Member` class already has a comparer that could be used, but unlike the `Member.AddressOrdering` public field, the `Member.AgeOrdering` is marked internal. 
I also noticed there's another [AgeComparer](https://github.com/akkadotnet/akka.net/blob/735aafbc7d70948d8f58d770bbbed50908745bc8/src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs#L240) inside the `ShardRegion` class that should be safe to remove and replace with the above.
> Mark Member.AgeOrdering as public

- src/core/Akka.Persistence.TestKit.Xunit2/PersistenceTestKit.cs
Added constructor for PersistenceTestKit class that takes a configuration. Added this so we can pass in custom configurations similar to what is possible for the TestKit class.
>     Added constructor that takes a configuration for PersistenceTestKit

- docs/articles/clustering/split-brain-resolver.md
The word  'arbitrary' here is used to describe 'define', which is a
verb. Verb descriptors should be adverbs whereas noun descriptors
should be adjectives.
> Grammar: Convert adjective to adverb

- docs/articles/actors/untyped-actor-api.md
It appears as though this page of documentation was copied from the
`ReceiveActor` documentation and this reference to `ReceiveActor` did
not get updated.
> Fix copy pasta from ReceiveActor doc

- src/core/Akka.Persistence.FSharp/FsApi.fs
Currently `DeferEvent` exists in the FSharp Persistence Api. It however processes through _every_ event and _mutates_ state (without persisting events).
This method differs in that it mirrors `UntypedPersistentActor` `DeferAsync` method that allows for a callback function to be called _once_ without persisting events and does _not mutate_ state.
> Adding DeferAsync access to Eventsourced mailbox in FSharp.

- src/core/Akka.Persistence.TestKit.Xunit2/PersistenceTestKit.cs
In a previous commit I added a constructor that takes in a custom configuration. If a custom configuration is passed in that doesn't contain the definitions of the test journal and test snapshot-store, tests will break. 
For defining the default test journal and test snapshot-store we had a default configuration. This commit takes the custom config and merges it with the default configuration so that the client doesn't have to worry about setting up defaults.
> Merge custom config with default config

- RELEASE_NOTES.md
Akka.NET v1.4.6 consists of mainly minor bug fixes and updates:
* [Akka.Cluster.DistributedData: Akka.DistributedData.ORDictionary Unable to cast object of type](https://github.com/akkadotnet/akka.net/issues/4400)
* [Akka: add CoordinatedShutdown.run-by-actor-system-terminated setting](https://github.com/akkadotnet/akka.net/issues/4203) - runs `CoordinatedShutdown` whenever `ActorSystem.Terminate()` is called.
* [Akka.Actor: Inconsistent application of SupervisorStrategy on Pool routers](https://github.com/akkadotnet/akka.net/issues/3626)
To see the full set of changes for Akka.NET 1.4.6, please [see the 1.4.6 milestone](https://github.com/akkadotnet/akka.net/milestone/37).
| 3 | 746 | 96 …
> Added v1.4.6 release notes

- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs
- src/core/Akka.Streams.Tests/Dsl/FlowDelaySpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowThrottleSpec.cs
- src/core/Akka.Tests.Shared.Internals/RepeatAttribute.cs
- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_ActionScheduler_Cancellation_Tests.cs
- Add RepeatAttribute to repeatedly run a single test
- Change the test attribute from `[Fact]` to `[Theory]`
- Add `[Repeat(count)]` where count = the number of times the test should be run.
- Fix flaky ORMultiValueDictionary DeltaValue test
> Unit test hardening

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FlowBatchSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowThrottleSpec.cs
- src/core/Akka.Streams.Tests/Dsl/GraphStageTimersSpec.cs
- src/core/Akka.Streams.Tests/Dsl/QueueSinkSpec.cs
- src/core/Akka.Streams.Tests/Dsl/TickSourceSpec.cs
- src/core/Akka.Tests/Event/LoggerSpec.cs
- src/core/Akka.Tests/Loggers/LoggerStartupSpec.cs
- src/core/Akka/Actor/Futures.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Event/LoggingBus.cs
Continuation of #4422 , trying to make loggers to start without blocking and not blow up the test suite
> Make loggers to not block ActorSystem creation

- src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj
- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj
- Remove `Akka.DistributedData.LightningDB` beta status
- Add reference to `Akka.DistributedData.LightningDB` in `Akka.Cluster.Sharding` for easier end user implementation.
> Move LMDB into release version

- build-system/azure-pipeline.mntr-template.yaml
- build-system/azure-pipeline.template.yaml
- build-system/nightly-builds.yaml
- build-system/pr-validation.yaml
- build-system/windows-release.yaml
Azure Pipelines are not using the .NET SDK installed by the build script, it is using the .NET SDK installed by the system and is cached across the workers. 
By default, it is set to `LATEST` version, the latest version causes a `Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute'` error inside the `AssemblyAttributes.cs`  auto-generated file
Fixed by forcing the cached SDK version to 3.1.100 by using `UseDotNet@2` azure pipeline task
> Fix dotnet SDK to 3.1.100 on all Azure Pipelines YAML script

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster/ClusterEvent.cs
Too many deadletter messages when shutting down nodes.
> Mute deadletter logging of cluster events

- src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs
- src/core/Akka.Persistence.TestKit.Xunit2/PersistenceTestKit.cs
- src/core/Akka.TestKit.Tests/ActorSystemSetupSpecs.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
Allows the TestKit to take an `ActorSystemSetup` object we added in v1.4.7 as an input instead of `Config`
> added ActorSystemSetup overload for TestKits

- src/core/Akka.Streams/Dsl/Restart.cs
Sometimes exceptions thrown from inside of a stage don't have any stack traces. Other times the actual meaningful content lies within error message itself. This PR changes the logging behavior of Backoff akka.streams stage to log exception using its default `ToString()` method, which includes both error message and stack trace.
> Changed Akka.Streams backoff error logging to include full exception message

- docs/articles/clustering/cluster-sharded-daemon-process.md
- docs/articles/toc.yml
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ShardedDaemonProcessSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardedDaemonProcessSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardedDaemonProcess.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardedDaemonProcessSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.approved.txt
> This is a feature backported from Lagom which essentially works like a sharded singleton. A number of actor instances are kept alive and balanced across the cluster.
The main motivation to bring it into Akka is the use case where workers that update projections. By tagging akka-persistence events with N different tags and then running N workers, one for each tag which consumes that partition of the events and updates a projection.
This feature was implemented in Akka typed, not yet available in Akka.NET. But given that users will either borrow Lagom's implementation anyway or roll their own, IMO it's worthwhile having this on classical Akka.
> Backport of the feature called ClusterDistribution in Lagom

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
Possible fix for #4474
Use defensive coding to prevent an exception from being thrown from duplicate key insertion
> Code didn't check if key already exist in an ImmutableDictionary before insertion

- docs/articles/configuration/akka.streams.md
I've read your contributing guidelines, but decided not to do create feature branch only for one word typo fix.
If for some reason it's not acceptable, for example because of some _CI/CD_ rules, I don't mind rejecting this pull request and fixing typo some other way :)
> Fix one typo in Akka Streams configuration doc

- src/contrib/cluster/Akka.Cluster.Sharding/ShardCoordinator.cs
- src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
> For cases where rebalance takes a long time due to a relatively large cluster change
> e.g. when doubling number of nodes (common for 1-2, 3-6 etc) there is
> little insignt into what is happening unless DEBUG logging is enabled.
> 
> This adds an INFO log per rebalance-interval (default is 10s) to show
> what is in progress and which new shards are starting rebalancing.
> Log rebalance progress at INFO per rebalance info

- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
Seeing some "An Item with the same key but different value already exists" exceptions in an App on InitRemovedNodePruning. Usually see this happen after rotating nodes during a deployment.
No tests added, but all existing tests pass. Also This change appears to be in line with Scala codebase, they use `.updated`: https://github.com/akka/akka/blob/142a63f600af6b8b805a10f0f401a4615237be48/akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala#L937
> DData: Use SetItem() instead of Add() for InitRemovedNodePruning

- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/IO/TcpManager.cs
Switch some Akka.IO TCP-related actor creation to use Props.Create<TActor>(..) instead of Props.Create(() => new TActor(..)) to avoid the costly compilation of the lambda expression tree.
With lots of connections being opened, the compilation related to TCP actor creation was affecting our application's performance.
> Optimize TCP-related actor creation in Akka.IO

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/DeadLetterSuspensionSpec.cs
- src/core/Akka.Tests/Configuration/ConfigurationSpec.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Event/DeadLetterListener.cs
This could be added to the release notes:
>#### Logging of dead letters
>
>When the number of dead letters have reached configured `akka.log-dead-letters` value it didn't log
>more dead letters in previous version. In Akka.NET 1.4.9 the count is reset after configured `akka.log-dead-letters-suspend-duration`.
>
>`akka.log-dead-letters-during-shutdown` default configuration changed from `on` to `off`.
> Re-enable dead letter logging after specified duration

- src/core/Akka/Actor/ActorPath.cs
Optimize ActorPath.Join() to perform fewer allocations. Accessing Elements causes quite a bit of garbage to get generated.
In .NET Core or .NET Standard 2.1, the char[] buffer allocation could be avoided, but I'm sure this isn't good enough reason to require either.
The calls are mainly triggered by serialization of ActorRefs when running with Akka.Remote. We have thousands of actors running on each node and sometimes sending ActorRefs over the wire. We're mostly sending unique ActorRefs (each gets sent only once), so the caching doesn't help.
> Optimize allocations in ActorPath.Join()

- src/core/Akka.Remote/RemoteActorRefProvider.cs
> skip call to LogSource.FromActorRef to prevent NRE during RemotingTerminator startup

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Pattern/CircuitBreakerState.cs
- src/core/Akka/Pattern/OpenCircuitException.cs
- src/core/Akka/Pattern/UserCalledFailException.cs
- src/core/Akka/Util/Internal/AtomicState.cs
Closes #4314
- `CircuitBreaker` remembers the last exception that passes it inside the `LastCaughtException` property. 
This exception is passed to the `OpenCircuitException` whenever it is thrown.
- Changed the `OpenCircuitException` message when it is thrown because of a half-open circuit breaker state.
> Enhance OpenCircuitException error reporting

- docs/articles/actors/routers.md
Currently the router documentation is missing information about management messages.
These message are supported according to the Routing test spec.
This change adds information about these messages
> Add docs about routing management messages

- RELEASE_NOTES.md
Akka.NET v1.4.10 includes some minor bug fixes and some major feature additions to Akka.Persistence.Query:
* [Fixed: Akka.Persistence.Sql SqlJournal caching all Persistence Ids in memory does not scale](https://github.com/akkadotnet/akka.net/issues/4524)
* [Fixed Akka.Persistence.Query PersistenceIds queries now work across all nodes, rather than local node](https://github.com/akkadotnet/akka.net/pull/4531)
* [Akka.Actor: Akka.Pattern: Pass in clearer error message into OpenCircuitException](https://github.com/akkadotnet/akka.net/issues/4314)
* [Akka.Persistence: Allow persistence plugins to customize JournalPerfSpec's default values](https://github.com/akkadotnet/akka.net/pull/4544)
* [Akka.Remote: Racy RemotingTerminator actor crash in …
> added v1.4.10 release notes

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
Fixed bugs:
- CurrentAllEvents uses improper highest sequence number instead of the highest ordering number.
- AllEventsPublisher, the CurrentAllEvents publisher may overshoot the intended ToOffset target.
> Fix bug in BatchingSqlJournal CurrentAllEvents and AllEventsPublisher.

- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
OnTimer may close the group just before OnUpstreamFinish is called (race condition), dropping the last element in the stream.
Fix is done by forcing a check inside OnUpstreamFinished for a dangling last element.
close https://github.com/akkadotnet/akka.net/issues/4514
> Fix race condition in GroupedWithin

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence/Eventsourced.Recovery.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/Journal/PersistencePluginProxy.cs
- src/core/Akka.Persistence/JournalProtocol.cs
A fix for:
> Possible race condition in Akka Persistence that can lead to lost events when using persistAsync() [#28629](https://github.com/akka/akka/issues/28629)
The idea is not to reset the writeInProgress flag prematurely before the actor gets stopped by WriteMessageFailure.
> Fix premature reset of the 'writeInProgress' flag in case of persistence failure

- src/core/Akka.Cluster/Configuration/Cluster.conf
The default cluster config for keep-referee had a typo. This should have no impact whatsoever as the default values in the KeepReferee class were correct.
> Fix typo in cluster.conf

- src/common.props
Updated the `common.props` file to serve the Akka.NET logo over HTTPS by default, now that our site supports it.
> NuGet: serve Akka.NET logo over HTTPS

- src/core/Akka.Streams.Tests/BugSpec.cs
- src/core/Akka/Util/ByteString.cs
Closes #4580
The problem was an empty byte array buffer passed into the `CopyTo` function. `CopyTo` failed immediately with an `ArgumentOutOfRangeException`.
Fixed by immediately returning `Array.Empty<byte>()` when `ToArray()` is called on an empty `ByteString`.
> Fix ByteString.Empty throws when ToArray was called

- src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
disseminate downing decisions faster (Migrated from  https://github.com/akka/akka/pull/29640)
* when SBR downs the reachable side (minority) it's important
to quickly inform everybody to shutdown
* send gossip directly to downed node, STONITH signal
* gossip to a few random immediately when self is downed, which
is always the last from the SBR downing
* enable gossip speedup when there are downed members
* adjust TransitionSpect to the new behavior
* update ValidNodeForGossip behavior
> akka.cluster - disseminate downing decisions faster

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Actor/ActorPublisherSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowCollectSpec.cs
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka/Util/Option.cs
Closes #4496.
Original problem was that 
- `Option<T>` failed to report that it has no value when passed a null value.
- `TestKitBase` did not check for `Option<Config>.None`
> Fix TestKitBase and Option<T>

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.11 includes some significant additions to Akka.NET:
* [Akka: How prevent "Scheduled sending of heartbeat was delayed" and occasionally network partitions](https://github.com/akkadotnet/akka.net/issues/4432) - all `/system` actors now run on a dedicated dispatcher. This should significantly improve reliablity for Akka.Cluster, Akka.Persistence, and other built-in Akka.NET systems inside heavily utilized environments.
* [Akka: Double wildcard implementation for ActorSelection](https://github.com/akkadotnet/akka.net/pull/4375)
* [Akka.Remote: Null reference exception due to RemoteActorRefProvider.RemoteInternals](https://github.com/akkadotnet/akka.net/issues/4579)
* [Akka.Persistence: Fix premature reset of the 'writeInProgress' flag in …
> added Akka.NET v1.4.11 release notes

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/Setup/ActorSystemSetup.cs
ActorSystemSetup is part of the public API and is used in the creation of `ActorSystem`s. It should not be marked as `InternalApi`.
> removed InternalApi attribute from ActorSystemSetup

- docs/articles/discovery/index.md
- docs/articles/discovery/toc.yml
- docs/articles/toc.yml
- src/core/Akka.Discovery/Akka.Discovery.csproj
Cleaned up documentation and linked it from the table of contents
Changed Akka.Discovery to release under `beta` version prefix
> Akka.Discovery Release Cleanup

- RELEASE_NOTES.md
Akka.NET v1.4.12 is a relatively minor release, but it includes some breaking changes:
* **BREAKING CHANGE**: [Akka.Cluster.Sharding: batch update](https://github.com/akkadotnet/akka.net/pull/4600) - includes some important updates for rebalancing shards more quickly, handling rolling updates, and using the new `AppVersion` type introduced in Akka.NET v1.4.11 to avoid allocating shards onto nodes that are being replaced during an upgrade. The breaking change: renamed the `Akka.Cluster.Sharding.TunningParameters` to `Akka.Cluster.Sharding.TuningParameters` in order to fix a misspelling. This changes the public API of all of the Akka.Cluster.Sharding settings classes - it shouldn't affect your Akka.NET application directly, but it will affect any …
> Akka.NET v1.4.12 Release Notes

- docs/web.config
Need this so other applications that build on top of Akka.NET can reference Akka.NET's `xrefmap` via DocFx remote references: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#advanced-more-options-for-cross-reference
> added .YML and .YAML mime types to IIS

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
Ignore possible state change in start. (Migrated from https://github.com/akka/akka/pull/29069)
> akka.singleton -  Ignore possible state change in start

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/TopicMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/Topics.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/PerGroupingBuffer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/reference.conf
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
new setting `send-to-dead-letters-when-no-subscribers`, some collections in messages switched to immutable, bugfix in PerGroupingBuffer
> akka.PublishSubscribe - new setting and small fixes

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.13 includes a number of bug fixes and enhancements:
**`AppVersion` now uses Assembly Version by Default**
The new `AppVersion` setting, which is used to communicate application version numbers throughout Akka.Cluster and is used in scenarios such as Akka.Cluster.Sharding to help determine which nodes receive new shard allocations and which ones do not, now uses the following default HOCON setting:
```
akka.cluster.app-version = assembly-version
```
By default now the `AppVersion` communicated inside Akka.Cluster `Member` events uses the `Major.Minor.BuildNumber` from the `Assembly.GetEntryssembly()` or `Assembly.GetExecutingAssembly()` (in case the `EntryAssembly` is `null`). That way any updates made to your executable's (i.e. the …
> added v1.4.13 release notes

- src/core/Akka.Remote.Tests/Transport/DotNettyBatchWriterSpecs.cs
- src/core/Akka.Remote/Transport/DotNetty/BatchWriter.cs
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
work for https://github.com/akkadotnet/akka.net/issues/4563 and https://github.com/akkadotnet/akka.net/issues/4636
> Move DotNetty batching scheduling off of DotNetty STEE and onto HashedWheelTimer

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.TestKit/TestScheduler.cs
- src/core/Akka.Tests/Actor/Scheduler/SchedulerShutdownSpec.cs
- src/core/Akka/Actor/Scheduler/HashedWheelTimerScheduler.cs
- src/core/Akka/Actor/Scheduler/IActionScheduler.cs
- src/core/Akka/Actor/Scheduler/SchedulerBase.cs
Purpose of this change is to make it possible to take Akka.Dispatch.IRunnable, the abstraction we use inside Dispatchers for processing mailboxes among other things, and pass it directly to the IScheduler for execution without having to wrap it.
This is largely a performance optimization and I don't expect this API to be used outside of Akka.NET's dispatching system.
> API - added overload for IScheduler that accepts IRunnable

- src/common.props
- src/core/Akka.Remote.Tests/RemoteConfigSpec.cs
- src/core/Akka.Remote.Tests/Transport/DotNettyBatchWriterSpecs.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Transport/DotNetty/BatchWriter.cs
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
Ported the `FlushConsolidationHandler` from Netty and used it to auto-tune batching inside Akka.Remote without having to set explicit thresholds and without having to rely on the `IScheduler`.
This accomplishes:
1. Lower Idle CPU consumption than even https://github.com/akkadotnet/akka.net/pull/4678
2. Significantly lower latencies on systems that don't write heavily
3. No need for users to manually tune their threshold settings in `akka.remote.dot-netty.tcp.batching` - this is now handled automatically by the `FlushConsolidationHandler`.
close https://github.com/akkadotnet/akka.net/issues/4636
close https://github.com/akkadotnet/akka.net/issues/4563
We still have some more work to do optimizing the `DedicatedThreadPool` to scale down automatically, but this eliminates most of the CPU …
> Auto-tuning DotNetty batching + removing scheduler from batching system

- build.sh
- src/core/Akka/ActorState.cs
Standardize the build system to pull all of its .NET / .NET Core dependencies from Azure DevOps, not from `build.ps1` or `build.sh`
> remove .NET install scripts from build.sh

- build.fsx
- src/common.props
- src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.nuspec.template
Added this to solve build problems related to https://github.com/akkadotnet/akka.net/pull/4713 - which comes from the .NET 4.6.1 target referencing the .NET 4.5 version of FluentAssertions 5.10, which in turn depends on the System.ValueTuple NuGet package - which causes a build conflict on Linux.
Moving off of .NET 4.6.1 and onto 4.7.1 forces the system to resolve that dependency as .NET Standard 2.0 instead.
> upgraded test target for .NET framework to .NET 4.7.2

- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Bugfix4360Spec.cs
resolves minor race condition in unit test where Terminated message can be delivered before UserGuardian has updated its ChildContainer collection.
> harden Bugfix4360Spec.Should_recover_persistentactor_sqlite

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.15 introduces a new module, Akka.DependencyInjection, which will replace Akka.DI.Core and all of the libraries which depend on it. This seemed like the easiest way to preserve backwards compatibility - simple deprecate the old package and replace it with a new one.
So what does Akka.DependencyInjection do differently than Akka.DI.Core?
1. **Allows users to pass in an [`IServiceProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider) into the `ActorSystem` before the latter is created, via [a new kind of programmatic configuration `Setup` that was introduced in Akka.NET v1.4](https://getakka.net/articles/concepts/configuration.html#programmatic-configuration-with-setup)**. This ensures that the `IServiceProvider` …
> added Akka.NET v1.4.15 release notes

- docs/articles/actors/dependency-injection.md
- docs/articles/actors/di-core.md
- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/ActorServiceProviderPropsWithScopesSpecs.cs
- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/AkkaDiFixture.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Actors/AkkaService.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Actors/HasherActor.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Startup.cs
Rewrote the DI documentation to explain how to use the new Akka.DependencyInjection library, as part of the 1.4.15 release.
> Updated Akka.DependencyInjection documentation

- src/contrib/dependencyinjection/Akka.DependencyInjection/Akka.DependencyInjection.csproj
set the metadata for the Akka.DependencyInjection package to point at https://getakka.net/articles/actors/dependency-injection.html
> set the metadata for the Akka.DependencyInjection package to point at specific page on Akka.NET website

- src/contrib/dependencyinjection/Akka.DependencyInjection/Akka.DependencyInjection.csproj
Instead of multi-targeting, we can just allow lower versions of MS nuget package to be used, since all we need is `ActivatorUtilities` which exists in a wide version range of that package.
> Allow different versions of MS Abstractions nuget package for Akka.DependencyInjection

- RELEASE_NOTES.md
This is a tiny release of Akka.NET, aimed at solving a transient dependency issue with Akka.DependencyInjection:
* [Akka.DependencyInjection: Allow different versions of MS Abstractions nuget package for Akka.DependencyInjection](https://github.com/akkadotnet/akka.net/pull/4739) - rolls back to Microsoft.Extensions.DependencyInjection.Abstractions 3.1 instead of 5.0
> Added v1.4.16 release notes

- src/core/Akka.Remote.Tests/Transport/DotNettySslSupportSpec.cs
Made the test somewhat more robust - might have to lengthen timeouts on it though to account for the `ExpectMsg` measurement.
> harden Akka.Remote.Tests.DotNettySslSupport.Secure_transport_should_be_possible_between_systems_sharing_the_same_certificate

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/core/Akka.API.Tests/Akka.API.Tests.csproj
- src/core/Akka.API.Tests/CoreAPISpec.cs
- src/core/Akka/Done.cs
> Fix approval specs to use Xunit2Reporter when v2 runner is used

- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonProxySpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxySettings.cs
- src/core/Akka.Docs.Tests/Actors/ReceiveTimeoutSpecs.cs
> Allow cluster singleton zero buffer size to disable buffering

- src/core/Akka.Cluster.Tests.MultiNode/RestartFirstSeedNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/RestartNode2Spec.cs
- src/core/Akka.Cluster.Tests.MultiNode/RestartNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/UnreachableNodeJoinsAgainSpec.cs
Close #4772
Actually, initially I was going to remove `InternalsVisibleTo` attribute from `Akka.Cluster` assembly for test assemblies, so that we were using only public API in our own tests - but turned out that sometimes we really need this internals to be visible for assertions, and replacing them with public-only properties would be complicated (and would lead to code duplication). Users still do not need those internals.
So I have just did what I can - basically, replaced only those internals which were referenced in documentation. The specs where other internal properties were used are unlikely to be referenced in documentation since they are assertion our "internal stuff".
> Updated specs that might be used in documentation to not use internal properties

- src/core/Akka.Remote.Tests/Serialization/BugFix4399Spec.cs
- src/core/Akka.Remote/AckedDelivery.cs
> Add default constructor to Akka.Remote.Ack

- src/core/Akka.Streams/Implementation/IO/FilePublisher.cs
- src/core/Akka.Streams/Implementation/IO/InputStreamPublisher.cs
Close #4744
Making our code to match scala implementation:
```scala
def receive = {
case ActorPublisherMessage.Request(elements) ⇒ readAndSignal()
case Continue                                ⇒ readAndSignal()
case ActorPublisherMessage.Cancel            ⇒ context.stop(self)
}
```
> Fixed actor cancellation message namespace for SourceRef

- src/Akka.sln
- src/benchmark/SerializationBenchmarks/Program.cs
- src/benchmark/SerializationBenchmarks/SerializationBenchmarks.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Serialization/Serialization.cs
This PR adds the following method to Akka.Serialization.Serialization:
```
public static T WithTransport<TState, T>(ExtendedActorSystem system, TState state, Func<TState, T> action)
```
The purpose of this overload is to allow a TState value to be passed into the `action` when executed, allowing consumers to avoid allocations due to delegate captures if present.
It looks like remoting already does something similar to this internally since it has access to the right internals, but there are other aspects of Akka (specifically persistence) that could benefit from this overload.
This PR also contains a benchmark of both versions of `WithTransport`. It looks like we are a little bit faster:
|                              Method |     Mean |     Error |    StdDev | …
> Add Serialization.WithTransport overload that takes TState

- src/core/Akka.Tests/Serialization/SerializationSetupSpec.cs
- src/core/Akka/Serialization/Serialization.cs
> Fix broken SerializationSetup, bindings insertion was reversed between HOCON and SerializationSetup.

- src/core/Akka.Remote/Endpoint.cs
cleaning up the error message logged by the `EndpointWriter` that occurs when the underlying serializer throws an `ArgumentException`.
> clarified Akka.Remote.EndpointWriter ArgumentException error message

- src/contrib/cluster/Akka.DistributedData/DeltaPropagationSelector.cs
Related to #4806
Minimize the number of changes to only those that directly relates to the bug.
> Fix potential NoDelta leak into IReplicatedData.Merge()

- src/core/Akka/Event/DeadLetterListener.cs
This PR fixes #4815 by checking if a message is null prior evaluating its type, so the DeadLetterListener does not crash.
> Add check for null message in LogDeadLetter.

- RELEASE_NOTES.md
- src/common.props
This is a more significant release of Akka.NET that solves a number of bugs, introduces new features, and more.
**Introduction of Akka.Cluster.SBR - Lightbend's Split Brain Resolvers**
In Akka.NET v1.4.17 we introduce a new set of Akka.Cluster split brain resolvers for Akka.NET, which are based on the recently open sourced Lightbend implementations of the same. We've [documented how to work with each of the new SBR types here](https://getakka.net/articles/clustering/split-brain-resolver.html), but here's the complete list:
* `static-quorum` 
* `keep-majority`
* `keep-oldest`
* `down-all`
* `lease-majority`
* `keep-referee` - only available with the legacy split brain resolver (still ships with Akka.NET.)
Other bug fixes:
* [Akka: Parse expressions …
> Akka.NET v1.4.17 release

- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/ActorServiceProviderPropsWithScopesSpecs.cs
- src/contrib/dependencyinjection/Akka.DependencyInjection/ServiceProvider.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote.Tests/RemotingSpec.cs
- src/core/Akka.Tests/Actor/PropsSpec.cs
- src/core/Akka/Actor/Props.cs
- src/core/Akka/Util/Reflection/ExpressionExtensions.cs
close #4853 
close #3599
API approvals and `ServiceProviderProps` changes aren't done yet - just wanted to kick off the test suite to make sure I haven't massively blown it on introducing these changes safely.
> ServiceProviderProps and Props Changes

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/IO/FileSinkSpec.cs
- src/core/Akka.Streams/Dsl/FileIO.cs
- src/core/Akka.Streams/Implementation/IO/FileSubscriber.cs
- src/core/Akka.Streams/Implementation/IO/IOSinks.cs
> Add flush feature into Akka.Streams.Implementation.IO.FileSubscriber

- RELEASE_NOTES.md
This is a minor release of Akka.NET that redesigns how the `Props` class and Akka.DependencyInjection uses it. _These changes are non-breaking_, but please let us know if you run into any trouble at all.
* [Akka: `Props` methods for propagating and setting `IActorProducer` are pretty weird](https://github.com/akkadotnet/akka.net/issues/3599)
* [Akka: made `Deploy` methods virtual](https://github.com/akkadotnet/akka.net/pull/4868)
* [Akka.DependencyInjection: `ServiceProviderProps` is broken - needs to be rewritten](https://github.com/akkadotnet/akka.net/issues/4853)
* [Akka.Streams: FileIO sinks don't flush until completed](https://github.com/akkadotnet/akka.net/issues/4851)
To see the [full set of fixes in Akka.NET v1.4.18, please see the …
> added v1.4.18 release notes

- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/IO/TcpManager.cs
- src/core/Akka/IO/UdpManager.cs
I was able to recreate the error by setting akka.actor.serialize-creators = on in the TcpIntegrationSpec, however to make all the tests pass with this setting, I also had to mark the TcpIncomingConnection with local deploy in TcpListener:
https://github.com/akkadotnet/akka.net/blob/d2b88753ac8fa0ed7c479712ef38182a02e706bc/src/core/Akka/IO/TcpListener.cs#L90-L97
should this also be changed?
> close #4860 - use local deploy for TcpManager child actors.

- src/contrib/cluster/Akka.Cluster.Sharding/ShardedDaemonProcess.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedMessages.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/DeadLetterSupressionSpec.cs
- src/core/Akka.Tests/Actor/DeadLetterSuspensionSpec.cs
- src/core/Akka.Tests/Event/EventStreamSpec.cs
- src/core/Akka/Actor/ActorSelection.cs
- src/core/Akka/Actor/BuiltInActors.cs
- src/core/Akka/Actor/EmptyLocalActorRef.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Event/DeadLetter.cs
- src/core/Akka/Event/DeadLetterListener.cs
- src/core/Akka/Event/UnhandledMessage.cs
- src/core/Akka/Routing/ConsistentHashRouter.cs
Supress ActorSelectionMessage with DeadLetterSuppression (migrated from https://github.com/akka/akka/pull/28341)
* for example the Cluster InitJoin message is marked with DeadLetterSuppression
but was anyway logged because sent with actorSelection
* for other WrappedMessage than ActorSelectionMessage we shouldn't unwrap and publish
the inner in SuppressedDeadLetter because that might loose some information
* therefore those are silenced in the DeadLetterListener instead
Better deadLetter logging of wrapped messages (migrated from https://github.com/akka/akka/pull/28253)
Logging of UnhandledMessage (migrated from https://github.com/akka/akka/pull/28414)
* make use of the existing logging of dead letter
also for UnhandledMessage
Add Dropped to Akka.Actor (migrated partially from …
> DeadLetterSuppression for ActorSelection and other deadletter enhancements

- RELEASE_NOTES.md
- src/core/Akka/Event/Logging.cs
> add CultureInfo for Turkish OS

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence.Tests/PersistentActorDeleteFailureSpec.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpec.Actors.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpec.cs
- src/core/Akka.Persistence/Eventsourced.Recovery.cs
- src/core/Akka.Persistence/Eventsourced.cs
- src/core/Akka.Persistence/JournalProtocol.cs
some small persistence fixes:
* Enforce valid seqnr for deletes, migrated from https://github.com/akka/akka/pull/25488
* lastSequenceNr should reflect the snapshot sequence and not start with 0 when journal is empty. Migrated from https://github.com/akka/akka/pull/27496
* snapshot RecoveryTick ignored, part of https://github.com/akka/akka/pull/20753
> Persistence fixes

- RELEASE_NOTES.md
- docs/articles/networking/serialization.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Docs.Tests/Networking/Serialization/ProgrammaticJsonSerializerSetup.cs
- src/core/Akka.Tests/Serialization/NewtonSoftJsonSerializerSetupSpec.cs
- src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
- src/core/Akka/Serialization/NewtonSoftJsonSerializerSetup.cs
Closes #4877
Possible issue: will a bad serializer settings break Akka serialization?
> Add Setup class for NewtonSoftJsonSerializer

- src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoveryCases.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoverySpec.cs
- src/core/Akka.MultiNodeTestRunner/Discovery.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
> replace reflection magic in MNTR with reading of `MultiNodeConfig` properties

- src/core/Akka.Cluster/SBR/SplitBrainResolver.cs
This format error would cause the StandardOutLogger to throw a `FormatException` internally
> fixed SBR logging error that blew up StandardOutLogger

- src/core/Akka.MultiNodeTestRunner.Shared.Tests/ParsingSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/Spec.cs
Small change designed to make it easier to correlate the failure that triggered a node death in the MNTR with the other captured logs.
> added timestamp to node failures in MNTR

- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/Spec.cs
- src/core/Akka.NodeTestRunner/Sink.cs
more cleanup on the `SpecPass` and `SpecFail` message types - removed unnecessary hiding and some of the message procssing inside `Sink`
> cleaned up the SpecPass / SpecFail messages

- src/core/Akka.Remote/PhiAccrualFailureDetector.cs
made `HeartbeatHistory` into a `readonly struct` and cleaned up some other old LINQ calls inside the data structure
> reduce allocations inside PhiAccrualFailureDetector

- src/core/Akka.MultiNodeTestRunner/Program.cs
- src/core/Akka.MultiNodeTestRunner/README.md
- src/core/Akka.MultiNodeTestRunner/WildcardPatterns.cs
> [MNTR] Add include and exclude test filter feature

- src/core/Akka.Streams.Tests/Dsl/FlowIntersperseSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
System.ArgumentNullException
Element must not be null, rule 2.13
Имя параметра: element
в Akka.Streams.Implementation.ReactiveStreamsCompliance.RequireNonNullElement(Object element) в D:\GitHubDesktop\akka.net\src\core\Akka.Streams\Implementation\ReactiveStreamsCompliance.cs:строка 361
в Akka.Streams.Stage.GraphStageLogic.Push[T](Outlet`1 outlet, T element) в D:\GitHubDesktop\akka.net\src\core\Akka.Streams\Stage\GraphStage.cs:строка 1214
в Akka.Streams.Stage.GraphStageLogic.EmitMultiple[T](Outlet`1 outlet, IEnumerator`1 enumerator, Action andThen) в D:\GitHubDesktop\akka.net\src\core\Akka.Streams\Stage\GraphStage.cs:строка 1462
в Akka.Streams.Stage.GraphStageLogic.EmitMultiple[T](Outlet`1 outlet, IEnumerable`1 elements, Action andThen) в …
> Fixed System.ArgumentNullException in Interspase operation on empty stream finish.

- src/core/Akka.Persistence.Tests/Serialization/PersistenceMessageSerializerSpec.cs
- src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs
> Fix case where PersistenceMessageSerializer.FromBinary got a null for its type parameter

- docs/articles/clustering/cluster-sharding.md
- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
close #4096 
Updated the Akka.Cluster.Sharding documentation to explain how to terminate remembered-entities.
> documented how to terminate remembered entities

- src/core/Akka.MultiNodeTestRunner/Program.cs
- src/core/Akka.Remote.TestKit/CommandLine.cs
> [MNTR] Add CLI switches to show help and version number

- src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/DurablePruningSpec.cs
> Fix MNTK specs for DData: DurablePruningSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests/ClusterHeartbeatReceiverSpec.cs
- src/core/Akka.Cluster.Tests/ClusterHeartbeatSenderSpec.cs
- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
- src/core/Akka.Cluster.Tests/Serialization/ClusterMessageSerializerSpec.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/Serialization/ClusterMessageSerializer.cs
- src/core/Akka.Cluster/Serialization/Proto/ClusterMessages.g.cs
- src/core/Akka.Remote.TestKit/CommandLine.cs
- src/protobuf/ClusterMessages.proto
port https://github.com/akka/akka/pull/27281
port https://github.com/akka/akka/pull/25183
port https://github.com/akka/akka/pull/24625
This PR introduces three changes:
1. Migrates the Akka.Cluster `ClusterMessageSerializer` to use `SerializerWithStringManifest` in order to avoid the wire format being broken by future type changes - all of the current type names are used as the string manifests to preserve backwards-compatible wire compatibility for now.
2. Introduces the wire format changes for measuring heartbeat latency, which can be useful for troubleshooting reachability issues inside a cluster. However, these wire format changes can be deserialized starting with Akka.NET v1.4.19 but none of these new message types will be emitted until at least Akka.NET v1.5 since introducing the …
> porting Cluster heartbeat timings, hardened Akka.Cluster serialization

- build.fsx
- src/common.props
- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/Bugfix4353Specs.cs
- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/Gossip.cs
- src/core/Akka.Cluster/Member.cs
- src/core/Akka.Cluster/Reachability.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
- src/core/Akka.Remote/DefaultFailureDetectorRegistry.cs
- src/core/Akka.Remote/PhiAccrualFailureDetector.cs
close #4849 
Fixes Akka.Cluster failure detector removal for new nodes that appear in the gossip regardless of what their current membership status is - useful for scenarios where:
1. Node A heartbeats Node B;
2. Network split occurs - Node B gets downed, Node A stays up and maintains heartbeat record for Node A;
3. Node A restarts - rejoins unstable cluster and quickly gets promoted to `WeaklyUp`;
4. Network split heals - Node A has massive PhiAccrual value for Node B and immediately marks it as UNREACHABLE due to old data that occurred in previous split.
This resolves that issue by making it so when Node A appears as a new member in Node B's gossip (due to its different UID) the failure detector records get reset anyway, even if Node A appears as `WeaklyUp` initially and not `Joining`.
> ClusterStressSpec and Cluster Failure Detector Cleanup

- build.fsx
- src/core/Akka.Cluster/Cluster.cs
Per some of the suggestions on https://github.com/akkadotnet/akka.net/pull/4940 PR review
> cleanup `AKKA_CLUSTER_ASSERT` environment variable

- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/ActorServiceProviderPropsWithScopesSpecs.cs
Added some `AwaitAssert` calls to check for disposed dependencies - these calls can be racy due to background actor thread calling `Dipose` after foreground test thread checks the `Disposed` property.
> harden Akka.DependencyInjection.Tests

- src/benchmark/Akka.Benchmarks/Akka.Benchmarks.csproj
- src/benchmark/Akka.Benchmarks/Cluster/HeartbeatNodeRingBenchmarks.cs
- src/benchmark/Akka.Benchmarks/Cluster/ReachabilityBenchmarks.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests/ClusterHeartBeatSenderStateSpec.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/Properties/AssemblyInfo.cs
- src/core/Akka/Util/Internal/ArrayExtensions.cs
per https://github.com/akkadotnet/akka.net/issues/4849
Investigating some potential performance issues with the data structures used by the heartbeat system, since we have never really looked at their performance as a possible cause for heartbeat issues inside rapidly changing clusters (i.e. large K8s deployments) or clusters with large node counts.
> HeartbeatNodeRing performance

- src/benchmark/PingPong/Program.cs
- src/benchmark/RemotePingPong/Program.cs
Using this to gauge the impact certain dispatcher changes have on the total number of active threads per-process
> modified PingPong / RemotePingPong benchmarks to display threadcount

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/MemberWeaklyUpSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/MinMembersBeforeUpSpec.cs
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
port of https://github.com/akka/akka/pull/29665
close https://github.com/akkadotnet/akka.net/issues/4849
> Configure duration for applying `MemberStatus.WeaklyUp`  to joining nodes

- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Cluster.Tests/ClusterGenerators.cs
- src/core/Akka.Cluster.Tests/MemberOrderingModelBasedTests.cs
- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.Tests.Shared.Internals/Akka.Tests.Shared.Internals.csproj
- src/core/Akka.Tests.Shared.Internals/Helpers/FSharpDelegateHelper.cs
Going to attempt to use these, and specs similar to these, to track down https://github.com/akkadotnet/akka.net/issues/4948 and any other bugs that might be possibly related to it.
> restored Akka.Cluster model-based FsCheck specs

- src/benchmark/Akka.Benchmarks/Cluster/VectorClockBenchmarks.cs
- src/core/Akka.Cluster/VectorClock.cs
Starting a thread for optimizing the `VectorClock` class, which is heavily used in all `Gossip` and decision-making inside the cluster.
part of #4849
> Performance optimize `VectorClock`

- src/core/Akka.Cluster.Tests.MultiNode/RestartFirstSeedNodeSpec.cs
Found a race condition inside `RestartFirstSeedNodeSpec`:
```
[Node #2(seed2)][WARNING][4/19/2021 8:33:24 PM][Thread 0021][akka.tcp://RestartFirstSeedNodeSpec@localhost:52468/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka.tcp://RestartFirstSeedNodeSpec@localhost:52473,akka.tcp://RestartFirstSeedNodeSpec@localhost:52467,akka.tcp://RestartFirstSeedNodeSpec@localhost:61313]
[Node #3(seed3)][WARNING][4/19/2021 8:33:24 PM][Thread 0022][akka.tcp://RestartFirstSeedNodeSpec@localhost:52467/system/cluster/core/daemon/joinSeedNodeProcess-1] Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka.tcp://RestartFirstSeedNodeSpec@localhost:52473,akka.tcp://RestartFirstSeedNodeSpec@localhost:52468,akka. …
```
> harden RestartFirstSeedNodeSpec

- docs/articles/actors/receive-actor-api.md
- docs/articles/concepts/supervision.md
* removed confusing and conflicting examples in the `ReceiveActor` documentation
* Embedded reference to "how actors restart" YouTube video in supervision docs
> cleaned up `ReceiveActor` documentation

- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
Did this to make it easier to search for output logs produced during each phase of the `StressSpec`
> added indicator for `ClusterResultsAggregator` in `StressSpec` logs

- src/benchmark/Akka.Benchmarks/Actor/ActorSelectionBenchmark.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
- src/core/Akka.Tests.Performance/Actor/ActorSelectionSpecs.cs
- src/core/Akka.Tests/Actor/ActorSelectionSpec.cs
- src/core/Akka/Actor/ActorSelection.cs
- src/core/Akka/Util/Internal/Collections/Iterator.cs
Saw some of the same inefficient / allocate-y patterns from `VectorClock` and elsewhere show up in this class and wanted to clean it up.
> Perf optimize `ActorSelection`

- src/benchmark/Akka.Benchmarks/Cluster/ReachabilityBenchmarks.cs
- src/core/Akka.Cluster/Gossip.cs
- src/core/Akka.Cluster/Reachability.cs
Creating a new PR to track performance fixes to `Reachability`
> `Reachability` performance optimziation

- src/benchmark/Akka.Benchmarks/Actor/SpawnActorBenchmarks.cs
Now actually measures spawning of 100,000 actors.
Baseline performance:
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.928 (2004/?/20H1)
.NET Core SDK=5.0.201
[Host]     : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
Job-USATMF : .NET Core 3.1.13 (CoreCLR 4.700.21.11102, CoreFX 4.700.21.11602), X64 RyuJIT
InvocationCount=1  IterationCount=10  RunStrategy=Throughput  
UnrollFactor=1  WarmupCount=5  
```
|      Method | ActorCount |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|------------ |----------- |--------:|---------:|---------:|------------:|-----------:|----------:|----------:|
| Actor_spawn |     100000 | 2.353 s | 0.1107 s | 0.0732 s | 111000.0000 …
> Fix `SpawnActor` benchmark

- src/core/Akka/Dispatch/Mailbox.cs
This error has no impact on extremely busy actors, but for actors who have to process small bursts of messages this can make the difference between getting everything done in one dispatch vs. doing it in two.
> fixed N-1 error inside `Mailbox`

- src/core/Akka.Remote/Endpoint.cs
port of https://github.com/akka/akka/pull/20093
Might be responsible for some quarantines in Akka.Cluster / Akka.Remote when nodes are restarting on identical addresses.
> Clean up bad outbound ACKs in Akka.Remote

- src/core/Akka.Streams.Tests/Dsl/UnfoldResourceSourceSpec.cs
- src/core/Akka.Streams/Implementation/Sources.cs
Ported fix for [#24924](https://github.com/akka/akka/issues/24924)
> UnfoldResourceSource closing twice on failure

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Pattern/RetrySpec.cs
- src/core/Akka/Pattern/RetrySupport.cs
Ported `Retry` pattern that will retry a `Task` some number of times with a delay between each attempt.
> Add retry pattern with delay calculation support

- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
Did this to make it easier to set the maximum node count in PowerShell,
i.e. `$env:MNTR_STRESSSPEC_NODECOUNT="50"`
> simplified the environment variable name for StressSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
- src/core/Akka.Tests/IO/TcpIntegrationSpec.cs
- src/core/Akka.Tests/IO/TcpListenerSpec.cs
- src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs
- src/core/Akka.Tests/IO/UdpIntegrationSpec.cs
- src/core/Akka.Tests/IO/UdpListenerSpec.cs
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/IO/Dns.cs
- src/core/Akka/IO/Tcp.cs
- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/IO/Udp.cs
- src/core/Akka/IO/UdpConnected.cs
> Fix serialization verification problem with Akka.IO messages

- src/core/Akka.Cluster/ClusterDaemon.cs
close https://github.com/akkadotnet/akka.net/issues/4967
Reviewed the code in the seed node process actors to try to address issues with the failing `FirstSeedNodeSpec` and everything looks kosher. Spec failed because of an issue with the non-first-seed nodes replying back on-time.
> clean up seed node process

- src/core/Akka.Tests/Actor/Dispatch/ActorModelSpec.cs
fixed `A_dispatcher_must_handle_queuing_from_multiple_threads` - we were using the wrong message type the entire time, and the previous instance caused `Thread.Sleep` to be called repeatedly.
> fixed racy ActorModelSpec

- docs/articles/clustering/cluster-singleton.md
Cluster singletons won't create duplicates in a cluster split scenario, and it's much safer to run them _with_ a split brain resolver on than without. This documentation was just out of date.
> Removed inaccurate warning from Cluster Singleton docs

- RELEASE_NOTES.md
Akka.NET v1.4.19 is a _substantial_ release that includes a number of critical Akka.Cluster fixes, baseline Akka.NET performance improvements, and entirely new dispatcher that has shown to improve performance when used across all of the major actor groups that run both inside the `/user` hierarchy and the `/system` actor hierarchy as well.
**Akka.Cluster Improvements**
One of the most demanding issues of the v1.4.19 release was "[Akka.Cluster: quarantining / reachability changes appear to be extremely sensitive](https://github.com/akkadotnet/akka.net/issues/4849)" - and this is because debugging this issue touched so many different parts of Akka.Cluster.
We ultimately solved the problem - it is now quite feasible to rapidly scale an Akka.NET …
> added v1.4.19 release notes

- .github/dependabot.yml
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote.Tests/Serialization/PrimitiveSerializersSpec.cs
- src/core/Akka.Remote/Serialization/PrimitiveSerializers.cs
> Change the base class of PrimitiveSerializers to SerializerWithStringManifest

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/QueueSinkSpec.cs
- src/core/Akka.Streams.Tests/Dsl/QueueSourceSpec.cs
- src/core/Akka.Streams/Implementation/Sinks.cs
- src/core/Akka.Streams/Implementation/Sources.cs
- src/core/Akka.Streams/StreamTcpException.cs
Ports [#23151](https://github.com/akka/akka/pull/23151)  and [#23509](https://github.com/akka/akka/pull/23509)
> Fixed QueueSource PostStop and added a missing test case

- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
- src/core/Akka.TestKit/Internal/InternalTestActor.cs
- src/core/Akka.Tests/Loggers/LoggerSpec.cs
- src/core/Akka/Event/StandardOutLogger.cs
> Prevent loggers to throw FormatException and show a friendly message instead.

- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
Due to https://github.com/akkadotnet/akka.net/pull/4953 - we decided to mark `Akka.Persistence.Sql.Common` as a beta package until we can validate that the changes to the `BatchingSqlJournal` didn't totally destroy performance / functionality for actual end-users.
> marking Akka.Persistence.Sql.Common as `beta` for v1.4.20

- RELEASE_NOTES.md
Akka.NET v1.4.20 is a minor release that includes some bug fixes and improvements to Akka.NET.
* [Akka: Fixed some `internal-dispatcher` usages ](https://github.com/akkadotnet/akka.net/pull/4995)
* [Akka: Remove restrictions required by netstandard 1.x but available in 2.0 ](https://github.com/akkadotnet/akka.net/pull/3790)
* [Akka: Prevent loggers to throw `FormatException` and show a friendly message instead. ](https://github.com/akkadotnet/akka.net/pull/4998)
* [Akka.Persistence.Sql.Common: Some persistent actors are stuck with `RecoveryTimedOutException` after circuit breaker opens](https://github.com/akkadotnet/akka.net/issues/4265)
* [Akka.Persistence.Sql.Common: marking Akka.Persistence.Sql.Common as `beta` for …
> added v1.4.20 release notes

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/TestLease.cs
Hello,
This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the "IEnumerable LINQs should be simplified" [rule](https://rules.sonarsource.com/csharp/RSPEC-2971)  in SonarQube.
Let me know if you are interested in similar contributions.
Best,
Martin
> Fix SonarQube's "IEnumerable LINQs should be simplified" / Code Smell

- src/core/Akka.Persistence.Tests/PersistentActorSpec.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpecAsyncAwait.cs
The issue blocking the test was resolved, spec tested and working.
> Enable skipped Akka.Persistence.Tests specs

- src/core/Akka.Streams.Tests/Dsl/KeepAliveConcatSpec.cs
With a 2 second initial delay, the spec is squeazing it too close to the default default timeout of 3 seconds, increased the timeout to avoid sporadic spec fail.
> Increase timeout value to avoid timeout failure

- src/Akka.sln
- src/benchmark/Akka.Benchmarks/DData/ORSetBenchmarks.cs
- src/benchmark/Akka.Benchmarks/DData/VersionVectorBenchmark.cs
- src/contrib/cluster/Akka.DistributedData.Tests/ORSetSpec.cs
- src/contrib/cluster/Akka.DistributedData/ORSet.cs
- src/contrib/cluster/Akka.DistributedData/VersionVector.cs
- src/examples/Cluster/DData/DDataStressTest/DDataStressTest.csproj
- src/examples/Cluster/DData/DDataStressTest/Program.cs
Working on https://github.com/akkadotnet/akka.net/issues/4956
> adding ORSet benchmarks

- src/benchmark/Akka.Benchmarks/Remoting/FastHashBenchmarks.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote/Properties/AssemblyInfo.cs
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19041.985 (2004/May2020Update/20H1)
.NET SDK=5.0.203
[Host]     : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
DefaultJob : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
```
|                  Method |      Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |----------:|----------:|----------:|-------:|------:|------:|----------:|
|       FastHash_OfString | 20.598 ns | 0.2125 ns | 0.1884 ns | 0.0095 |     - |     - |      40 B |
| FastHash_OfStringUnsafe |  6.172 ns | 0.0379 ns | 0.0336 ns |      - |     - |     - |         - |
> added `FastHash` benchmark

- src/core/Akka.Streams/Implementation/IO/FileSubscriber.cs
Port [#19594](https://github.com/akka/akka/pull/19594)
This basically does the same thing @Arkatufus did in #4874 but uses the original code. Up to you guys.
> Fix a potential race condition in FileSubscriber

- src/core/Akka.Remote.Tests/Transport/AkkaProtocolSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowAskSpec.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
- src/core/Akka.Tests/Actor/CoordinatedShutdownSpec.cs
Currently there are a few `Intercept` methods included in `AkkaSpec`, but they lack cohesion in their implementations. This PR aims at solving this by consolidating all of them under a single one that also overcome their biggest limitation: not unwrapping `AggregateExceptions`, which force users to deal with these inside the tests themselves. 
This PR also brings along the `AssertThrows` method (a proper implementation of the `Intercept` that returns `void` instead), which should be the preferred  between the two when no further inspection of the caught exception is needed.
Hopefully this will make it porting unit tests more straight forward and better aligned with the JVM.
> Consolidate intercept

- src/core/Akka.Remote/RemoteActorRefProvider.cs
Provided that this works, should eliminate an entire source of allocations from the Akka.Remote deserialization pipeline.
> remove `ActorPath.ToString` call from `ResolveActorRefWithLocalAddress`

- src/contrib/cluster/Akka.DistributedData/ORSet.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/SerializationSupport.cs
- src/contrib/cluster/Akka.DistributedData/VersionVector.cs
- src/core/Akka/Actor/Address.cs
- src/core/Akka/Util/MurmurHash.cs
Closes #5023
Edit by @Aaronontheweb : Removed the reference to #5022 since that has other issues still affecting it
> Improve MurmurHash string hash memory footprint

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/IO/FileSinkSpec.cs
- src/core/Akka.Streams.Tests/IO/OutputStreamSinkSpec.cs
- src/core/Akka.Streams/IO/IOResult.cs
- src/core/Akka.Streams/Implementation/IO/FileSubscriber.cs
- src/core/Akka.Streams/Implementation/IO/OutputStreamSubscriber.cs
Ports of [#24577](https://github.com/akka/akka/pull/24577) and [#25089](https://github.com/akka/akka/pull/25089)
> A couple of fixes affecting the FileSubscriber

- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
- src/core/Akka.TestKit/TestKitBase.cs
> [MNTR] Add ActorSystemSetup support

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Util/Base64Encoding.cs
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19041.985 (2004/May2020Update/20H1)
.NET SDK=5.0.203
[Host]     : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
DefaultJob : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
```
|                        Method | Iterations |       Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |-----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 100.723 ms | 2.0080 ms | 5.6308 ms | 5000.0000 |     - |     - |     20 MB |
|          CreateActorSelection |      10000 |   7.564 ms | 0.2305 ms | 0.6795 ms | …
> Removed `StringBuilder` allocation from `Base64Encoding`

- ISSUE_TEMPLATE.md
We now get issue templates from the Akka.NET organization itself https://github.com/akkadotnet/.github
> remove ISSUE_TEMPLATE.md

- src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/Proto/OtherMessage.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs
> Fix DData infinite status/gossip round

- src/core/Akka/Actor/ActorSystem.cs
Based on user feedback on https://github.com/akkadotnet/akka.net/discussions/4983
> Revert `ThreadPool.SetMinThreads(0,0)`

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
- src/core/Akka/Actor/ReceiveActor.cs
- src/core/Akka/Dispatch/ActorTaskScheduler.cs
* Made `ActorCell.SendSystemMessage` `virtual` so it can be subclassed
* Made a number of `ActorCell` methods `static` to reduce object memory footprint
* Reduced number of possible `Task` allocations where they weren't needed
> Reduced allocations around `ActorCell` and `Task` handling

- docs/articles/actors/dispatchers.md
> the document needs to be reverted too. https://getakka.net/articles/actors/dispatchers.html
_Originally posted by @christallire in https://github.com/akkadotnet/akka.net/issues/5059#issuecomment-853560485_
> Remove `ThreadPool.SetMinThreads(0,0)` mention from dispatchers documentation

- src/core/Akka/Actor/Address.cs
This PR:
1. Improves `ActorPath.Parse` performance
2. Reduces `Address` memory allocation
> eliminate `Lazy<string>` from `Address`

- RELEASE_NOTES.md
Akka.NET v1.4.21 is a significant release that includes major performance improvements, bug fixes, and a major update to the [Akka.DependencyInjection NuGet package](https://getakka.net/articles/actors/dependency-injection.html).
**Performance Improvements**
Akka.NET v1.4.21 includes some major performance fixes and improvements:
* [`Ask` is now ~10% faster](https://github.com/akkadotnet/akka.net/pull/5051)
* [`MurmurHash` is 33% faster and allocates 0 memory](https://github.com/akkadotnet/akka.net/pull/5028) - used _heavily_ in DData, Cluster Sharding, and Consistent Hash Routers
* `ActorPath.Parse` went from 1672 ns/op to 527 ns/op - a 68% improvement in throughput and a 50% reduction in memory. See …
> v1.4.21-beta1 Release Notes

- src/core/Akka.Cluster/SBR/SplitBrainResolver.cs
- src/core/Akka.Coordination/LeaseProvider.cs
Cleaned up some internal issues with Akka.Coordination and how it's used inside Akka.Cluster.
> Akka.Coordination: minor cleanup

- src/core/Akka.Tests/Actor/ActorPathSpec.cs
> added FQDN reproduction for `ActorPath.Parse`

- src/core/Akka.TestKit/CallingThreadDispatcher.cs
- src/core/Akka.TestKit/Internal/InternalTestActorRef.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Dispatch/Dispatchers.cs
Found some methods that could be made static on `ActorCell`, which should help with total actor memory footprint.
> cleaned up internal ActorCell and TestKit methods

- src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs
Just like ORSet, GSet elements need to be sorted during serialization so that the digest of any same GSets with the same elements with different element positioning will always be the same.
> GSet elements needs to be sorted during serialization

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
Add missing failure handling, following SqlJournal failure handling behaviour
> Add failure handling for BatchingSqlJournal SelectCurrentPersistenceIds message batching

- RELEASE_NOTES.md
Akka.NET v1.4.21 is a significant release that includes major performance improvements, bug fixes, and a major update to the [Akka.DependencyInjection NuGet package](https://getakka.net/articles/actors/dependency-injection.html).
**Performance Improvements**
Akka.NET v1.4.21 includes some major performance fixes and improvements:
* [`Ask` is now ~10% faster](https://github.com/akkadotnet/akka.net/pull/5051)
* [`MurmurHash` is 33% faster and allocates 0 memory](https://github.com/akkadotnet/akka.net/pull/5028) - used _heavily_ in DData, Cluster Sharding, and Consistent Hash Routers
* `ActorPath.Parse` went from 1672 ns/op to 527 ns/op - a 68% improvement in throughput and a 50% reduction in memory. See …
> v1.4.21 final release notes

- src/contrib/cluster/Akka.Cluster.Sharding/ShardedDaemonProcess.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.approved.txt
These API changes allow to specify a custom `handOffMessage` that will be sent to all entities when they're supposed to stop themselves due to rebalance or cluster shutdown.
> [ShardedDaemonProcess] Support for custom stop message

- src/core/Akka/Actor/ActorRef.Extensions.cs
Remote Messages with a sender set to ActorRefs.NoSender should return true for IsNobody()
> IsNobody for remote DeadLetters

- src/core/Akka.Remote/Endpoint.cs
We weren't capturing the exception thrown during deserialization anymore, just logging the error message. A throwback from before Akka.NET v1.4 when only the `ILoggingAdatper.Error` method accepted `Exception` arguments
> log full exception upon deserialization failure

- src/core/Akka.Remote.Tests/Serialization/BugFix5062Spec.cs
- src/core/Akka.Remote/Serialization/MessageContainerSerializer.cs
> `MessageContainerSerializer` reports on serializerId and manifest of failed payload

- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
close #5130  
Calling `Endpoint.ToString()` should be good enough:
```csharp
EndPoint ipEndpoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 2002);
EndPoint dnsEndpoint = new DnsEndPoint("localhost", 2003);
Console.WriteLine(ipEndpoint.ToString());
Console.WriteLine(dnsEndpoint.ToString());
```
Output:
```
127.0.0.1:2002
Unspecified/localhost:2003
```
> include attempted bind address in DotNetty binding failure messages

- src/core/Akka/Actor/PipeToSupport.cs
Canceled Task will have null as tresult.Exception.
The error handler need have a TaskCanceledException instance to indicate the cancellation.
> Pipe of Canceled Tasks

- src/common.props
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingCustomShardAllocationSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingFailureSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStateSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStatsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGracefulShutdownSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingLeavingSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingMinMembersSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRegistrationCoordinatedShutdownSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesNewExtractorSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/HyperionSerializerWrapper.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Serialization/ClusterShardingMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Serialization/Proto/ClusterShardingMessages.g.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.approved.txt
- src/protobuf/ClusterShardingMessages.proto
Fishing for possible serializer problem with Akka.Cluster.Sharding. It should never use the default object serializer for any of its message types.
> Akka.Cluster.Sharding should not use Hyperion serializer

- docs/articles/streams/error-handling.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Docs.Tests/Streams/RestartDocTests.cs
- src/core/Akka.Streams.Tests/Dsl/RestartSpec.cs
- src/core/Akka.Streams/Dsl/Restart.cs
- src/core/Akka.Streams/RestartSettings.cs
Port [#29591](https://github.com/akka/akka/pull/29591)
This PR also adds a few missing tests, and attempts to fix the racy ones.
> Restart(Source|Flow|Sink): Configurable stream restart deadline

- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorResiliencySpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSettingsSpec.cs
- src/contrib/cluster/Akka.DistributedData/DistributedData.cs
- src/contrib/cluster/Akka.DistributedData/ReplicatorSettings.cs
- src/contrib/cluster/Akka.DistributedData/reference.conf
- src/core/Akka.API.Tests/CoreAPISpec.ApproveDistributedData.approved.txt
> Add a HOCON setting to control DData replicator restart on failure

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs
- src/contrib/serializers/Akka.Serialization.TestKit/AkkaSerializationSpec.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote.Tests/RemotingSpec.cs
- src/core/Akka.Tests/Actor/AskSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Re-working the internals of `Ask<T>` to be more type safe, to `await` less internally, and to allocate fewer objects.
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19041.1052 (2004/May2020Update/20H1)
.NET SDK=5.0.203
[Host]     : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
DefaultJob : .NET Core 3.1.15 (CoreCLR 4.700.21.21202, CoreFX 4.700.21.21402), X64 RyuJIT
```
|                        Method | Iterations |      Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 83.313 ms | 0.7553 ms | 0.7065 ms | …
> Reworked `Ask<T>` to allocate fewer objects, `await` less

- src/core/Akka/Pattern/CircuitBreakerState.cs
> CircuitBreaker's open state now returns a faulted Task instead of throwing

- src/core/Akka.Remote/Endpoint.cs
Hyperion can throw an InvalidCastException when deserializing a message that came from a system that uses a different sorting order compared to the receiving system. This exception should be treated like a SerializationException and should not cause the EndpointReader to fail.
> Prevent EndpointDisassociatedException from being thrown from EndpointReader

- RELEASE_NOTES.md
Akka.NET v1.4.22 is a fairly large release that includes an assortment of performance and bug fixes.
**Performance Fixes**
Akka.NET v1.4.22 includes a _significant_ performance improvement for `Ask<T>`, which now requires 1 internal `await` operation instead of 3:
*Before*
|                        Method | Iterations |      Mean |     Error |    StdDev |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----------- |----------:|----------:|----------:|----------:|------:|------:|----------:|
| RequestResponseActorSelection |      10000 | 83.313 ms | 0.7553 ms | 0.7065 ms | 4666.6667 |     - |     - |     19 MB |
|          CreateActorSelection |      10000 |  5.572 ms | 0.1066 ms | 0.1140 ms |  953.1250 |     - |     - | …
> added v1.4.22 release notes

- src/core/Akka.Remote/RemoteActorRefProvider.cs
No meaningful code changes. Just cleaning up some compiler warnings, XML-DOC comments, and some code formatting issues I noticed while looking at this code for another issue.
> minor cleanup to RemoteActorRefProvider

- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote/RemoteActorRefProvider.cs
Technically could be considered a breaking change, but this method was only just introduced in v1.4.22 and it's part of the RARP internals, so not likely.
Changed this because it needs to be consistent with the other overload of the same name - a detail that myself and the team missed during https://github.com/akkadotnet/akka.net/pull/5161
> fix `RemoteActorRefProvider.CreateRemoteRef` signature to return `IInternalActorRef`

- src/core/Akka/Actor/ActorRef.cs
close #3091 - part of the `Ask` API that's never been fully implemented.
> use `Failure` to programmatically cancel `Ask`

- RELEASE_NOTES.md
Akka.NET v1.4.23 is designed to patch an issue that occurs on Linux machines using Akka.Cluster.Sharding with `akka.cluster.sharding.state-store-mode=ddata` and `akka.cluster.sharding.remember-entities=on`: "[System.DllNotFoundException: Unable to load shared library 'lmdb' or one of its dependencies](https://github.com/akkadotnet/akka.net/issues/5174)"
In [Akka.NET v1.4.21 we added built-in support for Akka.DistributedData.LightningDb](https://github.com/akkadotnet/akka.net/releases/tag/1.4.21) for use with the `remember-entities` setting, but we never received any reports about this issue until shortly after v1.4.22 was released. Fundamentally, the problem was that our downstream dependency, Lightning.NET, doesn't include any of the necessary …
> added v1.4.23 release notes

- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.FSharp.Tests/ApiTests.fs
> re-enabled Akka.FSharp.Tests on .NET Core 3.1, .NET 5.0

- src/common.props
- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.FSharp.Tests/ApiTests.fs
- src/core/Akka.FSharp.Tests/RemoteSpecs.fs
- src/core/Akka.FSharp.Tests/SerializationSpecs.fs
- src/core/Akka.FSharp/FsApi.fs
> added reproduction for DU serialization

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs
- src/core/Akka.Remote/Routing/RemoteRouterConfig.cs
- src/core/Akka/Routing/RoutedActorCell.cs
- src/core/Akka/Routing/Router.cs
- src/core/Akka/Routing/RouterConfig.cs
* Marked a handful of key methods as `virtual`
* Replaced `TBD` with relevant XML-DOC comments in most areas
* Cleaned up outdated code styles
* Made `UnWrap` `protected` so it can be used in subclasses
> make `Router` open to extension

- RELEASE_NOTES.md
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/ITimestampProvider.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Akka.Persistence.Sqlite.csproj
PR #5077 fixed using timestamp provider for SqlJournal.
With this new PR the timestamp provider will be used in BatchingSqlJournal as well.
> Use TimestampProvider in BatchingSqlJournal

- src/core/Akka.Tests/Actor/AskSpec.cs
- src/core/Akka/Actor/ActorRef.cs
> allow `null` response to `Ask<T>` operation

- src/Akka.sln
- src/benchmark/Akka.Benchmarks/Akka.Benchmarks.csproj
- src/benchmark/Akka.Cluster.Benchmarks/Akka.Cluster.Benchmarks.csproj
- src/benchmark/Akka.Cluster.Benchmarks/Program.cs
- src/benchmark/Akka.Cluster.Benchmarks/Sharding/ShardMessageRoutingBenchmarks.cs
- src/benchmark/Akka.Cluster.Benchmarks/Sharding/ShardSpawnBenchmarks.cs
- src/benchmark/Akka.Cluster.Benchmarks/Sharding/ShardingInfrastructure.cs
- src/common.props
close #3083
Initial numbers:
``` ini
Job-HXSFLM : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
```
|                              Method |   StateMode | MsgCount |         Mean |      Error |      StdDev |       Median |
|------------------------------------ |------------ |--------- |-------------:|-----------:|------------:|-------------:|
|  **SingleRequestResponseToLocalEntity** | **Persistence** |    **10000** |   **110.158 ms** |  **2.1994 ms** |   **3.0832 ms** |   **109.456 …
> Akka.Cluster.Sharding performance benchmarks

- src/benchmark/Akka.Cluster.Benchmarks/Sharding/HashCodeMessageExtractorBenchmarks.cs
https://github.com/akkadotnet/akka.net/issues/5203#issuecomment-901914810 - doesn't capture the boxing mentioned here, but I want some baseline numbers to compare against a statically typed generic version of this.
> added `HashCodeMessageExtractor` benchmarks

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
Since the number of possible shards is bounded at startup, we can avoid allocating a string each time we route a message by pre-calculating them in the constructor of the `HashCodeMessageExtractor`.
This improvement reduces all allocations and reduces latency by 50%.
``` ini
DefaultJob : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
```
|             Method |     Mean |    Error |   StdDev |   Median |  Gen 0 | Allocated |
|------------------- |---------:|---------:|---------:|---------:|-------:|----------:|
| …
> cached ShardIds generated by HashCodeMessageExtractor

- src/core/Akka.Tests/Actor/ActorRefSpec.cs
- src/core/Akka/Actor/ActorRef.Extensions.cs
fix and unit test for https://github.com/akkadotnet/akka.net/issues/5213
> fix IsNobody for actorref-mock and add unit test for it.

- src/benchmark/Akka.Cluster.Benchmarks/Program.cs
- src/benchmark/Akka.Cluster.Benchmarks/Sharding/ShardMessageRoutingBenchmarks.cs
- src/benchmark/Akka.Cluster.Benchmarks/Sharding/ShardingInfrastructure.cs
Adding benchmark to test performance of sending messages to a remote entity without relying on remote `ASK` as per the approach discussed at https://github.com/akkadotnet/akka.net/issues/5203#issuecomment-907587322
> Benchmark to test SingleRequestResponseToRemoteEntity with a local proxy

- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
If there were a major issue with the batching journals since v1.4.19, it would have been reported by now.
> Take Akka.Persistence.Sql.Common out of beta

- src/benchmark/Akka.Benchmarks/Actor/GetChildBenchmark.cs
Working on cleaning up the read-side resolve pipeline inside Akka.Cluster.Sharding and Akka.Remote. This seemed like a good place to start.
> adding `GetChild` benchmark

- src/benchmark/Akka.Benchmarks/Actor/GetChildBenchmark.cs
turns out my original benchmark was wrong - as it ran headfirst into a bad resolve for `GetChild`.
This benchmark results in a good resolve.
> fixed `GetChild` benchmark

- src/benchmark/Akka.Benchmarks/Actor/GetChildBenchmark.cs
designed to help measure how quickly we can resolve a temporary actor upon deserialization
> added benchmark for `VirtualPathContainer` resolution

- src/benchmark/Akka.Benchmarks/Actor/GetChildBenchmark.cs
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/ActorCell.cs
Baseline performance from https://github.com/akkadotnet/akka.net/pull/5239
Done, expanded the benchmark to include some more scenarios.
``` ini
DefaultJob : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
```
|                               Method |      Mean |    Error |   StdDev |  Gen 0 | Allocated |
|------------------------------------- |----------:|---------:|---------:|-------:|----------:|
|                         ResolveChild |  64.69 ns | 0.145 ns | 0.129 ns |      - |         - |
| …
> improve child lookup performance

- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka.Remote/Serialization/ActorRefResolveCache.cs
```
OSVersion:                         Microsoft Windows NT 6.2.9200.0
ProcessorCount:                    16
ClockSpeed:                        0 MHZ
Actor Count:                       32
Messages sent/received per client: 200000  (2e5)
Is Server GC:                      True
Thread count:                      111
Num clients, Total [msg], Msgs/sec, Total [ms]
1,  200000,     98232,    2036.89
5, 1000000,    187266,    5340.11
10, 2000000,    187776,   10651.83
15, 3000000,    186963,   16046.41
20, 4000000,    186142,   21489.67
25, 5000000,    186721,   26778.20
30, 6000000,    186568,   32160.53
```
```
OSVersion:                         Microsoft Windows NT 6.2.9200.0
ProcessorCount:                    16
ClockSpeed:                        0 MHZ
Actor Count:                       32 …
```
> added LRU cache support to inbound Akka.Remote IActorRef resolution

- src/benchmark/Akka.Benchmarks/Remoting/LruBoundedCacheBenchmarks.cs
Initial performance benchmarks:
``` ini
Job-ALMZBX : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
```
|                       Method |      Mean |     Error |    StdDev |    Median | Allocated |
|----------------------------- |----------:|----------:|----------:|----------:|----------:|
| ActorRefResolveMissBenchmark | 13.042 μs | 2.5188 μs | 6.7666 μs | 12.250 μs |     136 B |
|  ActorRefResolveHitBenchmark |  1.952 μs | 0.3344 μs | 0.8926 μs |  1.700 μs |         - |
| …
> added `LruBoundedCache` benchmarks

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/AskSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Currently invalid or timed out answers of Ask getting invisibly ignored by FutureActorRef<T>
This PR will push all invalid answers into deadletter.
Invalid answers are timeout-answer, too many answers, answer in a bad state of FutureActorRef<T>.
The only exception is a canceled Ask, this answer will still be ignored.
> Ask should push unhandled answers into deadletter

- src/benchmark/Akka.Benchmarks/Remoting/LruBoundedCacheBenchmarks.cs
``` ini
Job-ZKSOFC : .NET Core 3.1.17 (CoreCLR 4.700.21.31506, CoreFX 4.700.21.31502), X64 RyuJIT
InvocationCount=10000000  
```
|                       Method |      Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Allocated |
|----------------------------- |----------:|---------:|---------:|-------:|-------:|----------:|
| ActorRefResolveMissBenchmark | 315.21 ns | 1.730 ns | 1.445 ns | 0.0325 | 0.0001 |     136 B |
|  ActorRefResolveHitBenchmark |  58.23 ns | 0.332 ns | 0.294 ns |      - |      - |         - |
|          AddressHitBenchmark |  70.96 …
> pumped up the LruCache benchmark invocation count to get more accurate numbers

- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Bugfix4360Spec.cs
The `AwaitAssert` is actually what made this spec racy
> harden Bugfix4360Spec

- src/core/Akka.Persistence.TCK/Query/PersistenceIdsSpec.cs
Not a good test - tightly couples to private implementation details for a given journal, plus it's racy. Better to test the stream stage it uses directly or use Akka.Streams completion semantics to check.
> disabled Akka.Persistence.TCK.Query.ReadJournal_should_deallocate_All_PersistenceIds_publisher_when_the_last_subscriber_left

- src/core/Akka.Streams.Tests/Dsl/SubstreamSubscriptionTimeoutSpec.cs
Added a detailed comment explaining why this test is somewhat unreliable
> skip racy substream spec

- src/core/Akka.Streams.Tests/Dsl/UnfoldFlowSpec.cs
No need to check for `ExpectNoMsgs` here - if any messages do arrive they'll blow up the `ExpectError` assertion below. All this did was make these two tests racy.
> hardened UnfoldFlowSpec

- src/core/Akka.Persistence.Tests/ManyRecoveriesSpec.cs
This spec can fail because on a low CPU count machine, such as the type that can be used by Azure DevOps, 3 blocked threads can also mean 3 blocked CPUs. I believe most Azure DevOps machines run using ~2 vCPU.
It's possible there could be a deeper underlying issue with the `DedicatedThreadPool` that could cause this problem, but instead I tried to constrain the `max-concurrent-recoveries=1` to limit the number of blocked CPUs to less than 1.
> harden ManyRecoveriesSpec

- src/benchmark/Akka.Benchmarks/Actor/ActorRefBenchmarks.cs
Demonstrates the `IActorRef.Equals` and many of the other "hot path" methods during message routing are extremely fast (~2ns)
> added `IActorRef` benchmarks

- src/core/Akka.Streams.Tests/Dsl/GraphStageTimersSpec.cs
Timings were too closely fitted with the timers programmed inside the `TestStage` - added margins to allow for less-than-perfect clock resolution.
> harden GraphStageTimersSpec

- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentAllEventsSpec.cs
Accidentally shared a database with the "all events by tag" query, which caused the spec to have a dirty read
> harden SqliteCurrentAllEventsSpec

- src/core/Akka.Persistence.Tests/ReceivePersistentActorAsyncAwaitSpec.cs
so the `PipeTo` _can_ be delayed because it's running inside the `ActorTaskScheduler`, which also schedules the `Task.Delay` below.
> disable Actor_PipeTo_should_not_be_delayed_by_async_receive

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/AskSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Re-PR of https://github.com/akkadotnet/akka.net/pull/5221
> Ask should push unhandled answers into deadletter 2

- src/common.props
- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka/Actor/Address.cs
Per @to11mtm 's reporting in our Gitter chat room...
```
OSVersion:                         Microsoft Windows NT 6.2.9200.0
ProcessorCount:                    16
ClockSpeed:                        0 MHZ
Actor Count:                       32
Messages sent/received per client: 200000  (2e5)
Is Server GC:                      True
Thread count:                      111
Num clients, Total [msg], Msgs/sec, Total [ms]
1,  200000,     96154,    2080.77
5, 1000000,    187442,    5335.46
10, 2000000,    188307,   10621.24
15, 3000000,    190767,   15726.12
20, 4000000,    189988,   21054.78
25, 5000000,    188694,   26498.56
30, 6000000,    188543,   31823.73
```
```
OSVersion:                         Microsoft Windows NT 6.2.9200.0
ProcessorCount:                    16 …
```
> experimenting with RemoteActorRefProvider address resolution performance

- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/SqlSnapshotStore.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorBase.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
`Akka.Actor.Failure` and `Akka.Actor.Failures` are unused and got obsoleted.
`Akka.Actor.Status.Success` and `Akka.Actor.Status.Failure` got sealed to improve pattern matching perf.
Failure got a new Field 'State' that the receiver can send the command or a correlation-id to the sender back.
> Improve status messages

- RELEASE_NOTES.md
Akka.NET v1.4.25 includes some _significant_ performance improvements for Akka.Remote and a number of important bug fixes and improvements.
**Bug Fixes and Improvements**
* [Akka.IO.Tcp: connecting to an unreachable DnsEndpoint never times out](https://github.com/akkadotnet/akka.net/issues/5154)
* [Akka.Actor: need to enforce `stdout-loglevel = off` all the way through ActorSystem lifecycle](https://github.com/akkadotnet/akka.net/issues/5246)
* [Akka.Actor: `Ask` should push unhandled answers into deadletter](https://github.com/akkadotnet/akka.net/pull/5259)
* [Akka.Routing: Make Router.Route` virtual](https://github.com/akkadotnet/akka.net/pull/5238)
* [Akka.Actor: Improve performance on `IActorRef.Child` …
> Akka.NET v1.4.25 Release Notes

- RELEASE_NOTES.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote.Tests/RemoteConfigSpec.cs
- src/core/Akka.Remote.Tests/Serialization/BugFix5279Spec.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Serialization/PrimitiveSerializers.cs
> Add backward compatibility to PrimitiveSerializers

- docs/community/whats-new/akkadotnet-v1.4-upgrade-advisories.md
- docs/community/whats-new/toc.yml
In instances where we need to document a regression or an edge-case that has to be factored in during upgrades, we will put them on this area of the website.
> Added Akka.NET v1.4 upgrade advisories area to website

- RELEASE_NOTES.md
Akka.NET v1.4.26 is a very small release that addresses one wire format regression introduced in Akka.NET v1.4.20.
**Bug Fixes and Improvements**
* [Akka.Remote / Akka.Persistence: PrimitiveSerializers manifest backwards compatibility problem](https://github.com/akkadotnet/akka.net/issues/5279) - this could cause regressions when upgrading to Akka.NET v1.4.20 and later. We have resolved this issue in Akka.NET v1.4.26. [Please see our Akka.NET v1.4.26 upgrade advisory for details](https://getakka.net/community/whats-new/akkadotnet-v1.4-upgrade-advisories.html#upgrading-to-akkanet-v1426-from-older-versions).
* [Akka.DistributedData.LightningDb: Revert #5180, switching back to original LightningDB …
> added v1.4.26 release notes

- docs/articles/actors/routers.md
about routee selection algorithm
closes #5291
> Doc clarification: SmallestMailboxPool

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams/StreamTcpException.cs
Reverts some of the changes made to the StreamTcpException's API in #5338
> Brings back StreamTcpException static field Instance

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams/Stage/GraphStage.cs
Also, changed the default `LogSource` to be the output of the `Stage.ToString()` method. Right now all `GraphStageLogic` log sources default to just "Logic (akka://{ActorSystemName})"
> made `GraphStageLogic.LogSource` virtual and change default `StageLogic` `LogSource`

- docs/articles/streams/builtinstages.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FlowWireTapSpec.cs
- src/core/Akka.Streams.Tests/Dsl/GraphWireTapSpec.cs
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/Graph.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Dsl/SubFlowOperations.cs
- src/core/Akka.Streams/Implementation/Stages/Stages.cs
This should also help with #4852
> Ported WireTap combinator

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.28 is a minor release that contains some enhancements for Akka.Streams and some bug fixes.
**New Akka.Streams Stages**
Akka.NET v1.4.28 includes two new Akka.Streams stages:
* [`Source.Never`](https://getakka.net/articles/streams/builtinstages.html#never) - a utility stage that never emits any elements, never completes, and never fails. Designed primarily for unit testing.
* [`Flow.WireTap`](https://getakka.net/articles/streams/builtinstages.html#wiretap) - the `WireTap` stage attaches a given `Sink` to a `Flow` without affecting any of the upstream or downstream elements. This stage is designed for performance monitoring and instrumentation of Akka.Streams graphs.
In addition to these, here are some other changes introduced Akka.NET …
> Added v1.4.28 release notes

- src/benchmark/RemotePingPong/Program.cs
Added this to help diagnose throughput drops on .NET 6, which we suspect are related to https://github.com/dotnet/runtime/pull/53471
Now displays a data table that looks like this - with the Start Threads and End Threads columns attached.
> added thread count tracking to RemotePingPong

- src/core/Akka.Discovery/Akka.Discovery.csproj
Given how things are going with [Akka.Management](https://github.com/akkadotnet/Akka.Management), I think it would be worthwhile to take Akka.Discovery out of beta so we can also begin releasing Akka.Management RTM packages in the near future.
> make Akka.Discovery RTM, rather than beta status

- build.ps1
- docs/docfx.json
close https://github.com/akkadotnet/akka.net/issues/5406
> Upgraded DocFx to 2.58.9, dropped `TargetFramework`

- docs/toc.yml
Now that https://github.com/akkadotnet/akka.net/issues/5406 is fixed we can roll this back
> changed API doc root link back to `index.md`

- src/core/Akka/IO/Tcp.cs
- src/core/Akka/IO/Udp.cs
- src/core/Akka/IO/UdpConnected.cs
Closes #5318
Socket connection messages like SocketReceived can arrive late to a dead socket listener after the socket actor is closed.
The log message from the deadletter actor made it look like it is a bigger problem than it is, when we know that this is a benign behaviour.
Marking these messages as IDeadLetterSuppression so it will not confuse user when it happens.
> Mark socket connection messages with IDeadLetterSuppression

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
Description of the PR purpose is provided in Issue https://github.com/akkadotnet/akka.net/issues/5419
> Fixes performance issue with HighestSequenceNrSql query

- src/core/Akka.Tests/Serialization/CustomSerializerSpec.cs
Closes #5371
Add reproduction spec, not a bug, works as intended.
Error was thrown from here: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Serialization/Serialization.cs#L172-L177
It was caused by `Type.GetType()` not being able to convert the supplied string into a concrete Type.
> Custom serializer did not resolve to actual type

- src/core/Akka.TestKit/Akka.TestKit.csproj
- src/core/Akka.TestKit/TestKitBase_Receive.cs
This pull request is based on a thread I had with @Aaronontheweb on Gitter: https://gitter.im/akkadotnet/akka.net?at=61ae5b0acd3f06175df32eda.
> Added InverseFishForMessage and nuget package fluent-assertions

- src/core/Akka.TestKit.Tests/TestKitBaseTests/ReceiveTests.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
InverseFishForMessage aka FishUntil. 
I am unable to fetch your latest commits for some reason. 
eg:
When I look at: 
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.TestKit/TestKitBase_Receive.cs
I see the method: InverseFishForMessage and not FishUntil. 
Hence, this PR is written for InverseFishForMessage.
> Added a positive test and a negative test for InverseFishForMessage

- src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs
- src/core/Akka.Cluster.Tests/ClusterSpec.cs
- src/core/Akka.Cluster/Cluster.cs
I think some of the race conditions that began to appear as a result of .NET 6's threadpool changes hid some of the faults exposed by this PR and some of the other Akka.Cluster ones. We need to carefully and quickly restore this functionality since https://github.com/akkadotnet/akka.net/issues/5435 is a critical issue.
> Resolve Akka.Cluster startup

- src/core/Akka.Tests/Pattern/BackoffOnRestartSupervisorSpec.cs
issue was that using `AutoReset` could cause a race where if the scheduler could reset the count in-flight and throw off the estimates used by the tests. Using a `ManualReset` avoids this issue.
> racy spec fix: `BackoffOnRestartSupervisor_must_respect_maxNrOfRetries_property_of_OneForOneStrategy`

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FramingSpec.cs
- src/core/Akka.Streams/Dsl/Framing.cs
Original issue: [#22129](https://github.com/akka/akka/issues/22129)
> Custom frame size computation support in Framing

- src/core/Akka/Actor/Props.cs
per https://github.com/akkadotnet/akka.net/pull/5416#discussion_r768272397
cc @to11mtm
> optimize `Props` `NewExpression` allocations

- src/core/Akka.TestKit/TestKitBase_Receive.cs
The old comment that I previously wrote in ("we are not returning anything") was based on an old variable name that threw me off. 
Here is the old code with the old variable name: 
```C#
probe.ReceiveWhile<object>(max: max, shouldIgnore: x =>
{
x.Should().NotBeOfType<T>();
return false; // we are not returning anything
});
```
When I looked into the code of the method ReceiveWhile(), I realized that "shouldIgnore" was a misleading variable name. 
So I changed it to "shouldContinue" which much better reflects the code and the docs around it. 
But I did not update the comment: "we are not returning anything". 
So now, it is time to update the comment as well.
The new comment is: "please continue receiving, don't stop". 
Which much better reflects the code and the variable name …
> fixed wrong comment

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Pattern/CircuitBreakerState.cs
> So the motivation for this change is that when a heavily-used server (which is used by many clients that use a circuitbreaker) goes out, it will be ramped up more gracefully instead of 'hammered' when the reset timeout triggers for all circuitbreakers at once.
Original PR: [#29478](https://github.com/akka/akka/pull/29478)
> Add random factor for CircuitBreaker

- docs/docfx.json
Needed to add this to support our manual approach for creating redirects for old content https://getakka.net/community/contributing/documentation-guidelines.html#moving-documentation-pages
> Added support for copying .HTML files in DocFx

- docs/articles/streams/builtinstages.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/LazyFlowSpec.cs
- src/core/Akka.Streams.Tests/Dsl/LazySinkSpec.cs
- src/core/Akka.Streams.Tests/IO/FileSinkSpec.cs
- src/core/Akka.Streams/Dsl/Flow.cs
- src/core/Akka.Streams/Dsl/Sink.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Streams/Implementation/Sinks.cs
- src/core/Akka.Streams/Implementation/Stages/Stages.cs
Currently, we have `LazySource` and `LazySink`. This PR adds the missing `LazyFlow` and the `Flow.LazyInitAsync` stage that builds on top of it. 
Also, `Sink.LazyInit` materialized value is a now wrapped in a `Task` to clearly indicate whether the internal sink was materialized or not. It is marked deprecated in favor of the new `Sink.LazyInitAsync`, aligned with `Flow.LazyInitAsync`.
Don't apply.
Don't apply.
> Add Flow.LazyInitAsync, and fix materialized value of Sink.LazyInit

- src/core/Akka.Persistence/Eventsourced.Lifecycle.cs
- src/core/Akka.Persistence/Eventsourced.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
Cleaning up some of the `Eventsourced` and `AsyncWriteJournal` code to use newer C# features - should help improve with compiler optimization in some small areas, but mostly serves to help improve readability.
> code cleanup on Akka.Persistence

- docs/community/contributing/debugging.md
Describes how to reboot `wsl` after an update.
> Added `wsl` reboot instructions to debugging documentation

- src/common.props
- src/contrib/serializers/Akka.Serialization.Hyperion.Tests/HyperionConfigTests.cs
- src/contrib/serializers/Akka.Serialization.Hyperion.Tests/HyperionSerializerSetupSpec.cs
- src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializer.cs
- src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializerSetup.cs
- src/contrib/serializers/Akka.Serialization.Hyperion/reference.conf
* Bump Hyperion from 0.11.2 to 0.12.0
* Add Hyperion ITypeFilter unit tests
* Add Hyperion ITypeFilter feature
* Implement TypeFilter "allowed-types" HOCON settings
* Implement TypeFilter in HyperionSerializerSetup
> Bump Hyperion to 0.12.0

- src/core/Akka.TestKit/TestKitBase_Receive.cs
When I wrote this comment originally, it applied. Since then, the implementation of the method has changed. Now, the comment no longer applies. Therefore, I removed the comment.
> Removed comment that no longer applies.

- docs/index.md
Home page link was broken during https://github.com/akkadotnet/akka.net/pull/5500
Not sure how to bring this inline with DocFx Guidelines since this is a CSS link, not markdown.
> fix getting started link

- docs/articles/intro/getting-started/tutorial-1.md
- docs/articles/intro/getting-started/tutorial-2.md
- docs/articles/intro/getting-started/tutorial-3.md
- docs/articles/intro/getting-started/tutorial-4.md
Fixed broken code references caused by moving the `tutorial*` into a new location.
> Fixed broken links

- src/core/Akka.TestKit.Tests/TestKitBaseTests/ReceiveTests.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
This PR renaming breaks backwards compatibility. 
But since the original fixed code is very young - I think it is worth it.
> Renamed FishUntilMessage to FishUntilMessageAsync

- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
* [Exp.] Increase `TimeOut` to 1 mins from default 3s
* Converted test to `async/await`
* Added `JoinAsync` and `DownAsync`
> Fixing Racy ClusterLogVerboseEnabledSpec

- src/core/Akka.Tests/Loggers/LoggerSpec.cs
Fixes #
Refactored to `async` Tests
> Async LoggerSpec

- src/core/Akka/Actor/LocalActorRef.cs
Fixes #5553
Remove reference to Props in LocalActorRef, this have a huge memory impact when LocalActorRef is being cached.
> Remove direct reference to Props in LocalActorRef

- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubConfigSpec.cs
Fixes #5557
Assert `true` to be the default value for `SendToDeadLettersWhenNoSubscribers`
> Added `SendToDeadLettersWhenNoSubscribers` to `DistributedPubSubConfigSpec`

- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/Topics.cs
The summary of the PubSub design is this, as it relates to #5352, if there are no subscribers, wait on the Deadline and if no new subscriber within that window terminate the Topic actor.
It is the `waiting on the Deadline` that is the actual issue.
> Fix: no `DeadLetter`s when publishing to a `Topic` with no subscribers

- src/core/Akka.Streams/Implementation/StreamLayout.cs
Deleted `inheritdoc` for external assembly in `Akka.Streams.Implementation.StreamLayout.cs`
> Docs: Fixed `inheritdoc` issue in `Akka.Streams.Implementation.StreamLayout.cs`

- docs/articles/actors/routers.md
- docs/articles/clustering/cluster-sharding.md
- docs/articles/clustering/split-brain-resolver.md
- docs/articles/intro/getting-started/tutorial-3.md
- docs/articles/persistence/custom-persistence-provider.md
- docs/articles/streams/basics.md
- docs/articles/streams/builtinstages.md
- docs/community/contributing/debugging.md
- docs/community/whats-new/akkadotnet-v1.4-upgrade-advisories.md
> Consistent Markdown Styling

- build-system/pr-validation.yaml
Fixes #5583
Lock build script dependency versions, markdownlint-cli version to 0.31.0 and markdownlint-rule-titlecase to 0.1.0
> Lock markdownlint-cli version to 0.31.0 and markdownlint-rule-titlecase to 0.1.0

- src/core/Akka/Actor/LocalActorRef.cs
Remove `/// <inheritdoc/>` from overriden members that can not be resolved by DocFx
> Docs: Fix `LocalActorRef.cs` unresolved base documentaion

- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
> Docs: Fix `ISystemMessage.cs` unresolved base documentaion

- src/core/Akka/Routing/Resizer.cs
- src/core/Akka/Routing/Router.cs
- src/core/Akka/Routing/RouterConfig.cs
> Docs: Fix `Routing` unresolved base documentaion

- src/core/Akka/Util/Option.cs
- src/core/Akka/Util/Result.cs
> Docs: Fix `Akka.Util` unresolved base documentaion

- src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs
> Docs: Fix `AtLeastOnceDeliverySemantic.cs` unresolved base documentaion

- src/core/Akka.Persistence/Persistent.cs
> Docs: Fix unresolved base documentaion in `Persistent.cs.cs`

- src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs
> Docs: Fix unresolved base documentaion WARNINGS in `AsyncWriteProxy.cs`

- src/core/Akka.Persistence/Journal/EventSequences.cs
> Docs: Fix unresolved base documentaion WARNINGS in `EventSequences.cs`

- src/core/Akka.Persistence/Serialization/Snapshot.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Snapshot.cs`

- src/core/Akka.TestKit/TestProbe.cs
> Docs: Fix unresolved base documentaion WARNINGS in `TestProbe.cs`

- src/core/Akka.Streams/Util/EnumeratorEnumerable.cs
> Docs: Fix unresolved base documentaion WARNINGS in `EnumeratorEnumerable.cs`

- src/core/Akka.Coordination/LeaseSettings.cs
- src/core/Akka.Coordination/LeaseUsageSettings.cs
- src/core/Akka.Coordination/TimeoutSettings.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.Coordination`

- src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs
- src/core/Akka.Remote/Transport/Transport.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.Remote.Transport.Transport*.cs`

- src/core/Akka.Cluster/ClusterEvent.cs
> Docs: Fix unresolved base documentaion WARNINGS in `ClusterEvent.cs`

- src/contrib/cluster/Akka.Cluster.Metrics/Collectors/DefaultCollector.cs
- src/contrib/cluster/Akka.Cluster.Metrics/Serialization/Metric.cs
- src/contrib/cluster/Akka.Cluster.Metrics/Serialization/NodeMetrics.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Cluster.Metrics`

- src/core/Akka.Cluster/Member.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Cluster.Member.cs`

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedMessages.cs
> Docs: Fix unresolved base documentaion WARNINGS in `PublishSubscribe.DistributedMessages.cs`

- src/core/Akka.Remote/Deadline.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Deadline.cs`

- src/core/Akka.Remote/RemoteActorRef.cs
- src/core/Akka.Remote/RemoteWatcher.cs
- src/core/Akka.Remote/RemotingLifecycleEvent.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Remote*.cs`

- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparer.cs
- src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs
- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Persistence.TCK/PluginSpec.cs
- src/core/Akka.Remote.TestKit/DataTypes.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
> Docs: Fix unresolved base documentaion WARNINGS in TestKits

- src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.Replicator.Messages.cs`

- src/contrib/cluster/Akka.DistributedData/ReadAggregator.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.ReadAggregator.cs`

- src/contrib/cluster/Akka.DistributedData/PNCounter.cs
- src/contrib/cluster/Akka.DistributedData/PNCounterDictionary.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.PNCounter*`

- src/contrib/cluster/Akka.DistributedData/ORSet.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.ORSet.cs`

- src/contrib/cluster/Akka.DistributedData/ORDictionary.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.ORDictionary.cs`

- src/contrib/cluster/Akka.DistributedData/LWWRegister.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.LWWRegister.cs`

- src/contrib/cluster/Akka.DistributedData/LWWDictionary.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.LWWDictionary.cs`

- src/contrib/cluster/Akka.DistributedData/Key.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.Key.cs`

- src/contrib/cluster/Akka.DistributedData/GCounter.cs
- src/contrib/cluster/Akka.DistributedData/GSet.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.GCounter.cs`

- src/contrib/cluster/Akka.DistributedData/Flag.cs
> Docs: Fix unresolved base documentaion WARNINGS in `Akka.DistributedData.Flag`

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubSettings.cs
- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs
Part fix for https://github.com/akkadotnet/akka.net/pull/5542
> Docs: Fix Invalid cref values

- src/contrib/dependencyinjection/Akka.DI.TestKit/DiResolverSpec.cs
- src/core/Akka.Remote/RemoteActorRef.cs
Part fix for https://github.com/akkadotnet/akka.net/pull/5542
> Docs: Fix unresolved base documentaion WARNINGS

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Dsl/SubFlowOperations.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
Fixes `WatchTermination` signature.
Change ` WatchTermination` signature from `Task` to `Task<Done>`. I don't think there's a way to introduce this change without breaking binary compatibility.
> Change WatchTermination signature to Task<Done>

- docs/articles/configuration/akka.html
- docs/articles/configuration/modules/akka.md
- docs/articles/configuration/modules/toc.yml
- docs/articles/configuration/toc.yml
Moved the `akka core` configuration page into `modules`
> Change the location of core Akka configuration page 

- docs/articles/toc.yml
- docs/index.md
Fixes https://github.com/akkadotnet/akka.net/pull/5542. 
DocFx warnings down to zero.
> Resolved invalid links

- src/core/Akka.TestKit/TestKitBase_Receive.cs
- Created `InternalTryReceiveOneAsync` and `InternalTryPeekOneAsync`
- Changed the old `InternalTryReceiveOne` and `InternalTryPeekOne` methods to use their async counterpart by wrapping them in sync-over-async pattern.
> Switch internal implementation to async

- src/core/Akka.TestKit/Internal/AsyncQueue.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
Part fix for https://github.com/akkadotnet/akka.net/issues/5617
- Change `ReceiveOne()` to sync over async that calls `ReceiveOneAsync()`
- Create `ReceiveOneAsync()` method
- Change `TryReceiveOne()` to sync over async that calls `TryReceiveOneAsync()`
- Create `TryReceiveOneAsync()`
- Change `PeekOne()` to sync over async that calls `PeekOneAsync()`
- Create `PeekOneAsync()` method
- Change `TryPeekOne()` to sync over async that calls `TryPeekOneAsync()`
- Create `TryPeekOneAsync()`
- Change `FishForMessage()` to sync over async that calls `FishForMessageAsync()`
- Create `FishForMessageAsync()`
> Change Receive Test Methods to `Sync` over `Async`

- src/core/Akka.TestKit.Tests/TestKitBaseTests/ReceiveTests.cs
- src/core/Akka.TestKit/Akka.TestKit.csproj
- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
Part fix for https://github.com/akkadotnet/akka.net/issues/5617
- Changed `ReceiveWhile()` to sync over `async` that calls `ReceiveWhileAsync()`
- Created `ReceiveWhileAsync()`
- Changed `ReceiveN()` to sync over `async` that calls `ReceiveNAsync()`
- Created `ReceiveNAsync()`
- Changed `InternalReceiveN()` to sync over `async` that calls `InternalReceiveNAsync()`
- Created `InternalReceiveNAsync()`
> Change ReceiveWhile Test Methods to Sync over Async

- src/core/Akka.Remote.Tests/Serialization/SerializationTransportInformationSpec.cs
Call `base.AfterAll()` to kill TestKit ActorSystem. The unit test file overrides the `AfterAll()` method but failed to call the base class method. This causes the TestKit ActorSystem to leak and can freeze the test runner.
As can be seen from the screenshot, the "no currently active test" error got repeated over and over until the test runner can kill the process.
> Fix AbstractSerializationTransportInformationSpec

- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/Gossip.cs
Fixes logging when receiving gossip from unknown node.
Port: [#23883](https://github.com/akka/akka/pull/23883)
> Fix confusing logging when receiving gossip from unknown

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FlowWithContextSpec.cs
- src/core/Akka.Streams.Tests/Dsl/SourceWithContextSpec.cs
- src/core/Akka.Streams.Tests/Dsl/WithContextUsageSpec.cs
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/FlowWithContext.cs
- src/core/Akka.Streams/Dsl/FlowWithContextOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Dsl/SourceWithContext.cs
Fixes `FlowWithContext` parameters order to follow actual shape of elements
Reorder Source/FlowWithContext type parameters
> Reorder Source/FlowWithContext type parameters

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/PersistentShardSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Bugfix4360Spec.cs
- src/core/Akka.Docs.Tests/Debugging/RacySpecs.cs
- src/core/Akka.Docs.Tests/Streams/HubsDocTests.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpec.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpecAsyncAwait.cs
- src/core/Akka.Persistence.Tests/SnapshotSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteReDeploymentSpec.cs
- src/core/Akka.Remote.Tests/Serialization/SerializationTransportInformationSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowSelectAsyncUnorderedSpec.cs
- src/core/Akka.Streams.Tests/Dsl/QueueSourceSpec.cs
- src/core/Akka.Streams.Tests/Dsl/SinkForeachParallelSpec.cs
- src/core/Akka.Streams.Tests/IO/InputStreamSinkSpec.cs
- src/core/Akka.TestKit.Tests/TestKitBaseTests/DilatedTests.cs
- src/core/Akka.TestKit.Tests/TestKitBaseTests/ExpectTests.cs
- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
* Convert all async methods that returns an `IReadOnlyCollection` to `IAsyncEnumerable`
* Clean sync over async codes to always call `.ConfigureAwait(false)`
* Clean async await codes to always call  `.ConfigureAwait(false)`
* Fix erroneous HOCON strings
* Add missing `base.AfterAll()` in `AbstractSerializationTransportInformationSpec`, leaving a leaked ActorSystem living in the background.
> [TEST] Fix and cleanup TestKit codes

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllPersistenceIdsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentEventsByPersistenceIdSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentEventsByTagSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentPersistenceIdsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteEventsByPersistenceIdSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteEventsByTagSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqlitePersistenceIdSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentEventsByPersistenceIdSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentEventsByTagSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentPersistenceIdsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteEventsByPersistenceIdSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteEventsByTagSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqlitePersistenceIdsSpec.cs
- src/core/Akka.Persistence.TCK/Query/PersistenceIdsSpec.cs
Fixes #5714
* `SelectCurrentPersistentIds` command returns the wrong `HighestOrderingNumber`
* Fix `AllPersistenceIdsPublisher` receive state
* Fix all Akka.Persistence.Sqlite unit test `refresh-interval` settings
> Fix PersistenceId Query and Sqlite unit tests

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Event/Bugfix5717Specs.cs
- src/core/Akka/Event/EventBusUnsubscriber.cs
- src/core/Akka/Event/EventStream.cs
Reproduced `IActorRef` leak inside the `EventStream`
Fixes #5717
`IActorRef`s leaked because:
* `EventStreamUnsubscriber` actor subscribed to the wrong `Terminated` event and
* `EventStream`'s unsubscriber management code was immensely complicated and very likely wrong.
> Fixed `IActorRef` leak inside `EventStream`

- src/core/Akka.TestKit/TestKitBase.cs
Using sync over async in constructors can cause deadlocks
> Convert AwaitCondition in TestKitBase initializer, can not use `.Wait()` in ctor

- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
Whenever I have a test run long and the `ActorSystem` has to shutdown behind the scenes, my logs are filled with thousands of `InvalidOperationException: no active test" as a result of calling `_output.WriteLine` once the XUnit test has been terminated. Each time this actor crashes and restarts it generates another one of those logs.
Added `InvalidOperationException` to the `catch` list and we just write out to `Console` now when this occurs, as xUnit test `IOutputHelper` is no longer available.
> supress `InvalidOperationException` in xUnit OutputLogger

- src/core/Akka.Tests/Actor/Setup/ActorSystemSetupSpec.cs
- src/core/Akka/Actor/Setup/ActorSystemSetup.cs
close #5728 
Modified the `ActorSystemSetup.WithSetup` method to evaluate the type of the `Setup` object being passed in rather than the generic method argument type.
> fix `ActorSystemSetup.And`

- RELEASE_NOTES.md
Not done yet, still waiting for GroupBy fix
> Update RELEASE_NOTES.md for 1.4.35 release

- src/core/Akka.Docs.Tests/Persistence/PersistentActor/PersistAsync.cs
This is supposed to be the example for persistAsync, but persistAsync doesn't get used at all.
https://getakka.net/articles/persistence/event-sourcing.html#relaxed-local-consistency-requirements-and-high-throughput-use-cases
I changed the code to match what is here:
https://doc.akka.io/docs/akka/current/persistence.html#relaxed-local-consistency-requirements-and-high-throughput-use-cases
> Update PersistAsync to match docs.

- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
Minor cleanups to the XUnit `TestOutputLogger` - a continuation of https://github.com/akkadotnet/akka.net/pull/5722
> cleanup XUnit TestKit output logger

- src/common.props
- src/contrib/cluster/Akka.Cluster.Metrics.Tests.MultiNode/Akka.Cluster.Metrics.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/Akka.Cluster.Sharding.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/Akka.DistributedData.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
Added xunit.runner.visualstudio nuget package, MSBuild fails to copy the dlls from the MNTR package
> Fix MSBuild does not copy xunit.runner dlls correctly

- docs/articles/intro/getting-started/tutorial-1.md
- docs/articles/persistence/persistence-query.md
Ports CI's spellcheck fix from `dev`
> Fix spelling (#5745)

- src/core/Akka.Tests/Actor/Stash/ActorWithStashSpec.cs
- Changed `An_actor_Should__not_throw_an_exception_if_the_same_message_is_received_and_stashed_twice` to `async/await`
- Changed `An_actor_must_unstash_all_messages_on_PostStop` to `async/await`
- Changed `An_actor_that_clears_the_stash_on_preRestart_Must_not_receive_previously_stashed_messages` to `async/await`
- Changed `An_actor_must_rereceive_unstashed_Terminated_messages` to `async/await`
> Port `Akka.Tests.Actor.Stash` tests to `async/await`

- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_ActionScheduler_Cancellation_Tests.cs
- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_ActionScheduler_Schedule_Tests.cs
- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_TellScheduler_Cancellation_Tests.cs
- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_TellScheduler_Schedule_Tests.cs
- Changed `When_ScheduleOnce_using_canceled_Cancelable_Then_their_actions_should_not_be_invoked` to `async/await`
- Changed `When_ScheduleRepeatedly_using_canceled_Cancelable_Then_their_actions_should_not_be_invoked` to `async/await`
- Changed `When_ScheduleOnce_and_then_canceling_before_they_occur_Then_their_actions_should_not_be_invoked` to `async/await`
- Changed `When_ScheduleRepeatedly_and_then_canceling_before_they_occur_Then_their_actions_should_not_be_invoked` to `async/await`
- Changed `When_canceling_existing_running_repeaters_Then_their_future_actions_should_not_be_invoked` to `async/await`
- Changed `When_canceling_existing_running_repeaters_by_scheduling_the_cancellation_ahead_of_time_Then_their_future_actions_should_not_be_invoked` to `async/await`
- Changed …
> Port `Akka.Tests.Actor.Scheduler` tests to async/await

- src/core/Akka.Tests/Actor/Dispatch/ActorModelSpec.cs
- src/core/Akka.Tests/Actor/Dispatch/Bug2640Spec.cs
- src/core/Akka.Tests/Actor/Dispatch/Bug2751Spec.cs
- src/core/Akka.Tests/Actor/Dispatch/CurrentSynchronizationContextDispatcherSpecs.cs
- Chnaged `A_dispatcher_must_handle_queuing_from_multiple_threads` to `async/await`
- Changed `ForkJoinExecutorShouldShutdownUponActorSystemTermination` to `async/await`
- Changed `ForkJoinExecutorShouldShutdownUponAllActorsTerminating` to `async/await`
- Changed `PinnedDispatcherShouldShutdownUponActorTermination` to `async/await`
- Chnaged `ShouldReceiveSysMsgBeforeUserMsg` to `async/await`
- Chnaged `CurrentSynchronizationContextDispatcher_should_start_without_error_Fix2172` to `async/await`
> Port `Akka.Tests.Actor.Dispatch` tests to async/await

- src/core/Akka.Tests/Actor/ActorDslSpec.cs
- Changed `A_lightweight_creator_must_support_creating_regular_actors` to `async/await`
- Changed `A_lightweight_creator_must_support_become_stacked` to `async/await`
- Changed `A_lightweight_creator_must_support_actor_setup_and_teardown` to `async/await`
- Changed `A_lightweight_creator_must_support_nested_declarations` to `async/await`
- Changed `A_lightweight_creator_must_support_actor_base_method_calls` to `async/await`
- Changed `A_lightweight_creator_must_support_async_receives` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `ActorDsl`

- src/core/Akka.Tests/Actor/ActorProducerPipelineTests.cs
- Changed `Pipeline_application_should_survive_internal_plugin_exceptions` to `async/await`
- Changed `Pipeline_should_allow_to_register_multiple_generic_plugins_with_different_generic_types` to `async/await`
- Changed `Pipeline_application_should_apply_plugins_in_specified_order` to `async/await`
- Changed `DefaultPipeline_should_apply_stashing_to_actors_implementing_it` to `async/await`
- Changed `DefaultPipeline_should_unstash_all_terminated_actors_stashed_messages_on_stop` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `ProducerPipeline`

- src/core/Akka.Tests/Actor/ActorLifeCycleSpec.cs
- src/core/Akka.Tests/Actor/DeadLettersSpec.cs
- Changed `Actor_lifecycle_test1` to `async/await`
- Changed `Actor_lifecycle_test2` to `async/await`
- Changed `Actor_lifecycle_test3` to `async/await`
- Changed `Log_failures_in_PostStop` to `async/await`
- Changed `Clear_behavior_stack_upon_restart` to `async/await`
- Changed `Clear_child_upon_terminated` to `async/await`
- Changed `Call_PreStart_with_correct_message_and_sender` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - ActorLifeCycle

- src/core/Akka.Tests/Actor/ActorRefSpec.cs
- Changed `Intercept` in `An_ActorRef_should_not_allow_actors_to_be_created_outside_an_ActorOf` to `Assert.Throws`
- Changed `Intercept` in `An_ActorRef_should_throw_an_exception_on_deserialize_if_no_system_in_scope` to `Assert.Throws`
- Changed `An_ActoRef_should_return_EmptyLocalActorRef_on_deserialize_if_not_present_in_actor_hierarchy_and_remoting_is_not_enabled` to `async/await`
- Changed `An_ActorRef_should_restart_when_Killed` to `async/await`
- Changed `An_ActorRef_should_support_nested_ActorOfs` to `async/await`
- Changed `An_ActorRef_should_support_ActorOfs_where_actor_class_is_not_public` to `async/await`
- Changed `An_ActorRef_should_stop_when_sent_a_poison_pill` to `async/await`
- Changed `An_ActorRef_should_be_able_to_check_for_existence_of_the_children` to `async/await`
- …
> Port `Akka.Tests.Actor` tests to `async/await` - `ActorRefSpec`

- src/core/Akka.Tests/Actor/CoordinatedShutdownSpec.cs
- src/core/Akka.Tests/Util/TaskHelpers.cs
- Changed `CoordinatedShutdown_must_detect_cycles_in_phases_non_DAG` to `Assert.Throws`
- Changed `CoordinatedShutdown_must_run_ordered_phases` to `async/await`
- Changed `CoordinatedShutdown_must_run_from_given_phase` to `async/await`
- Changed `CoordinatedShutdown_must_only_run_once` to `async/await`
- Changed `CoordinatedShutdown_must_continue_after_timeout_or_failure` to `async/await`
- Changed `CoordinatedShutdown_must_abort_if_recover_is_off` to `async/await` [failing @Arkatufus ]
- Changed `CoordinatedShutdown_must_be_possible_to_add_tasks_in_later_phase_from_earlier_phase` to `async/await`
- Changed `CoordinatedShutdown_must_terminate_ActorSystem` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `CoordinatedShutdownSpec`

- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.Tests/Actor/ActorRefIgnoreSpec.cs
- Changed `IgnoreActorRef_should_ignore_all_incoming_messages` to `async/await`
- Changed `IgnoreActorRef_should_make_a_Future_timeout_when_used_in_a_ask` to `async/await`
- Changed `IgnoreActorRef_should_be_watchable_from_another_actor_without_throwing_an_exception` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - RefIgnoreSpec

- src/core/Akka.Tests/Actor/BugFix4376Spec.cs
- Changed `Supervisor_with_Broadcast_Pool_router_should_handle_multiple_child_failure` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `BugFix4376Spec`

- src/core/Akka.Tests/Actor/ActorSystemDispatcherSpec.cs
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
WAITING ON https://github.com/akkadotnet/akka.net/pull/5756
- [ActorSystemDispatcherSpec] Changed `The_ActorSystem_must_not_use_passed_in_SynchronizationContext_if_executor_is_configured_in` to `async/await`
- Changed `Logs_config_on_start_with_info_level` to `async/await`
- Changed `Does_not_log_config_on_start` to `async/await`
- Changed `Allow_valid_names` to `async/await`
- Changed `Log_dead_letters` to `async/await`
- Changed `Block_until_exit` to `async/await`
- Changed `Run_termination_callbacks_in_order` to `async/await`
- Changed `Reliably_create_waves_of_actors` to `async/await`
- Changed `Find_actors_that_just_have_been_created` to `async/await`
- Changed `Reliable_deny_creation_of_actors_while_shutting_down` to `async/await`
- Changed …
> Port `Akka.Tests.Actor` tests to async/await - `ActorSystemSpec`

- src/core/Akka.Tests/Actor/DeadLetterSupressionSpec.cs
- src/core/Akka.Tests/Actor/DeadLetterSuspensionSpec.cs
- Changed `Must_suppress_message_from_default_dead_letters_logging_sent_to_deadActor` to `Assert.Throws`
- Changed `Must_suppress_message_from_default_dead_letters_logging_sent_to_dead_letters` to `Assert.Throws`
- Changed `Must_suspend_dead_letters_logging_when_reaching_akka_log_dead_letters_and_then_re_enable` to `Assert.Throws`
> Port `Akka.Tests.Actor` tests to `async/await` - `DeadLetter*Spec`

- src/core/Akka.Tests/Actor/DeathWatchSpec.cs
- Changed `DeathWatch_must_notify_with_one_Terminated_message_when_an_Actor_is_already_terminated` to `async/await`
- Changed `Bug209_any_user_messages_following_a_Terminate_message_should_be_forwarded_to_DeadLetterMailbox` to `async/await`
- Changed `DeathWatch_must_notify_with_one_Terminated_message_when_actor_is_stopped` to `async/await`
- Changed `DeathWatch_must_notify_with_one_custom_termination_message_when_actor_is_stopped` to `async/await`
- Changed `DeathWatch_must_notify_with_all_monitors_with_one_Terminated_message_when_Actor_is_stopped` to `async/await`
- Changed `DeathWatch_must_notify_with_current_monitors_with_one_Terminated_message_when_Actor_is_stopped` to `async/await`
- Changed `DeathWatch_must_notify_with_a_Terminated_message_once_when_Actor_is_stopped_but_not_when_res …
> Port `Akka.Tests.Actor` tests to `async/await` - `DeathWatchSpec`

- src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
- src/core/Akka.Tests/Actor/BugFix4823Spec.cs
- Changed `Actor_should_not_loose_self_context_after_async_call` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `BugFix4823Spec`

- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
- General API and global ask timeout setting fix
> General Akka.TestKit fixes that are found while porting tests to async

- src/core/Akka.Tests/Actor/FSMActorSpec.cs
- Changed `FSMActor_must_log_termination` to `async/await`
- Changed `FSMActor_must_run_onTermination_upon_ActorRef_Stop` to `async/await`
- Changed `FSMActor_must_run_onTermination_with_updated_state_upon_stop` to `async/await`
- Changed `FSMActor_must_cancel_all_timers_when_terminated` to `async/await`
- Changed `FSMActor_must_allow_transforming_of_state_results` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `FSMActorSpec`

- src/core/Akka.Tests/Actor/FSMTimingSpec.cs
- Changed `FSM_must_receive_StateTimeout` to `async/await`
- Changed `FSM_must_cancel_a_StateTimeout` to `async/await`
- Changed `FSM_must_cancel_a_StateTimeout_when_actor_is_stopped` to `async/await`
- Changed `FSM_must_allow_StateTimeout_override` to `async/await`
- Changed `FSM_must_receive_single_shot_timer` to `async/await`
- Changed `FSM_must_resubmit_single_shot_timer` to `async/await`
- Changed `FSM_must_correctly_cancel_a_named_timer` to `async/await`
- Changed `FSM_must_not_get_confused_between_named_and_state_timers` to `async/await`
- Changed `FSM_must_receive_and_cancel_a_repeated_timer` to `async/await`
- Changed `FSM_must_notify_unhandled_messages` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `FSMTimingSpec`

- src/core/Akka.Tests/Actor/FSMTransitionSpec.cs
- Changed `FSMTransitionNotifier_must_not_trigger_onTransition_for_stay` to `async/await`
- Changed `FSMTransitionNotifier_must_notify_listeners` to `async/await`
- Changed `FSMTransitionNotifier_must_not_fail_when_listener_goes_away` to `async/await`
- Changed `FSM_must_make_previous_and_next_state_data_available_in_OnTransition` to `async/await`
- Changed `FSM_must_trigger_transition_event_when_goto_the_same_state(` to `async/await`
- Changed `FSM_must_not_trigger_transition_event_on_stay` to `async/await`
- Changed `FSM_must_not_leak_memory_in_nextState` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `FSMTransitionSpec`

- src/core/Akka.Tests/Actor/HotSwapSpec.cs
- Changed `Must_be_able_to_become_in_its_constructor` to `async/await`
- Changed `Must_be_able_to_become_multiple_times_in_its_constructor` to `async/await`
- Changed `Must_be_able_to_become_with_stacking_in_its_constructor` to `async/await`
- Changed `Must_be_able_to_become_with_stacking_multiple_times_in_its_constructor` to `async/await`
- Changed `Must_be_to_hotswap_its_behaviour_with_become` to `async/await`
- Changed `Must_be_able_to_revert_hotswap_its_behaviour_with_unbecome` to `async/await`
- Changed `Must_be_able_to_revert_to_initial_state_on_restart` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `HotSwapSpec`

- src/core/Akka.Tests/Actor/InboxSpec.cs
- Changed `Inbox_support_watch` to `async/await`
- Changed `Inbox_have_maximum_queue_size` to `async/await`
- Changed `Inbox_have_a_default_and_custom_timeouts` to `async/await`
- Changed `Inbox_Receive_will_timeout_gracefully_if_timeout_is_already_expired` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `InboxSpec`

- src/core/Akka.Tests/Actor/LocalActorRefProviderSpec.cs
- Changed `A_LocalActorRefs_ActorCell_must_not_retain_its_original_Props_when_Terminated` to `async/await`
- Changed `An_ActorRefFactory_must_only_create_one_instance_of_an_actor_from_within_the_same_message_invocation` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `LocalActorRefProviderSpec`

- src/core/Akka.Tests/Actor/PatternSpec.cs
- src/core/Akka.Tests/Actor/PipeToSupportSpec.cs
- Changed `Should_immediately_PipeTo_completed_Task` to `async/await`
- Changed `Should_by_default_send_task_result_as_message` to `async/await`
- Changed `Should_by_default_not_send_a_success_message_if_the_task_does_not_produce_a_result` to `async/await`
- Changed `Should_by_default_send_task_exception_as_status_failure_message` to `async/await`
- Changed `Should_use_success_handling_to_transform_task_result` to `async/await`
- Changed `Should_use_failure_handling_to_transform_task_exception` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `PipeToSupportSpec`

- src/core/Akka.Tests/Actor/ReceiveActorTests.cs
- src/core/Akka.Tests/Actor/ReceiveActorTests_Become.cs
- src/core/Akka.Tests/Actor/ReceiveActorTests_LifeCycle.cs
- Changed `Given_actor_When_it_calls_Become_Then_it_switches_handler` to `async/await`
- Changed `Given_actor_that_has_called_Become_When_it_calls_Unbecome_Then_it_switches_back_handler` to `async/await`
- Changed `Given_actor_that_has_called_Become_at_construction_time_When_it_calls_Unbecome_Then_it_switches_back_handler` to `async/await`
- Changed `Given_actor_When_it_restarts_Then_uses_the_handler` to `async/await`
- Changed `Given_actor_that_has_replaced_its_initial_handler_When_it_restarts_Then_uses_the_initial_handler` to `async/await`
- Changed `Given_actor_that_has_pushed_a_new_handler_When_it_restarts_Then_uses_the_initial_handler` to `async/await`
- Changed `Given_actor_with_no_receive_specified_When_receiving_message_Then_it_should_be_unhandled` to `async/await`
- Changed …
> Port `Akka.Tests.Actor` tests to `async/await` - `ReceiveActorTests`

- src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs
- `An_actor_with_receive_timeout_must_not_receive_timeout_message_when_not_specified`
- `An_actor_with_receive_timeout_must_get_timeout_while_receiving_NotInfluenceReceiveTimeout_messages`
- `An_actor_with_receive_timeout_must_be_able_to_turn_off_timeout_in_NotInfluenceReceiveTimeout_message_handler`
- Changed `Issue469_An_actor_with_receive_timeout_must_cancel_receive_timeout_when_terminated` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `ReceiveTimeoutSpec`

- src/core/Akka.Tests/Actor/SystemGuardianTests.cs
- Changed `Should_Send_Hook_When_UserGuardian_Terminated` to `async/await`
- Changed `Should_Terminate_When_Hooks_Complete` to `async/await`
- Changed `Should_Remove_Registration_When_Registree_Terminates` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `SystemGuardianTests`

- src/core/Akka.Tests/Actor/TimerSpec.cs
- Changed `Timers_combined_with_stashing_should_work` to `async/await`
- Changed `Must_schedule_non_repeated_ticks` to `async/await`
- Changed `Must_schedule_repeated_ticks` to `async/await`
- Changed `Must_replace_timer` to `async/await`
- Changed `Must_cancel_timer` to `async/await`
- Changed `Must_cancel_timers_when_restarted` to `async/await`
- Changed `Must_discard_timers_from_old_incarnation_after_restart_alt_1` to `async/await`
- Changed `Must_discard_timers_from_old_incarnation_after_restart_alt_2` to `async/await`
- Changed `Must_cancel_timers_when_stopped` to `async/await`
- Changed `Must_handle_AutoReceivedMessages_automatically` to `async/await`
> Port `Akka.Tests.Actor` tests to `async/await` - `TimerSpec`

- src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs
- Changed `Actors_should_be_able_to_supervise_async_exceptions` to `async/await`
- Changed `Actors_should_be_able_to_supervise_exception_ContinueWith` to `async/await`
- Changed `Actor_should_be_able_to_ReceiveTimeout_after_async_operation` to `async/await`
- Changed `Actor_PreRestart_should_give_the_failing_message` to `async/await`
- Changed `ActorTaskScheduler_reentrancy_should_not_be_possible` to `async/await`
- Changed `Actor_PipeTo_should_not_be_delayed_by_async_receive` to `async/await`
- Changed `Actor_receiveasync_overloads_should_work` to `async/await`
> Port `Akka.Tests.Dispatch` tests to `async/await` - `ActorAsyncAwaitSpec`

- src/core/Akka.Tests/Event/EventBusSpec.cs
- Changed `EventBus_publish_to_the_only_subscriber` to `async/await`
- Changed `EventBus_publish_to_the_only_subscriber_multiple_times` to `async/await`
- Changed `EventBus_not_publish_event_to_unindented_subscribers` to `async/await`
- Changed `EventBus_not_publish_event_to_former_subscriber` to `async/await`
> Port `Akka.Tests.Event` tests to `async/await` - `EventBusSpec`

- src/core/Akka.Tests/Event/LoggerSpec.cs
- Changed `LoggingAdapter_should_log_all_information` to `async/await`
> Port `Akka.Tests.Event` tests to `async/await` - `LoggerSpec`

- src/core/Akka.Tests/Event/EventStreamSpec.cs
- Changed `Manage_subscriptions` to `async/await`
- Changed `Be_able_to_log_unhandled_messages` to `async/await`
- Changed `Bugfix3267_able_to_log_unhandled_messages_with_nosender` to `async/await`
- Changed `Manage_sub_channels_using_classes` to `async/await`
- Changed `Manage_sub_channels_using_classes_and_interfaces_update_on_subscribe` to `async/await`
- Changed `Manage_sub_channels_using_classes_and_interfaces_update_on_unsubscribe` to `async/await`
- Changed `Manage_sub_channels_using_classes_and_interfaces_update_on_unsubscribe_all` to `async/await`
- Changed `Manage_log_levels` to `async/await`
> Port `Akka.Tests.Event` tests to `async/await` - `EventStreamSpec`

- src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs
- Changed `The_UDP_connection_oriented_implementation_must_be_able_to_send_and_receive_without_binding` to `async/await`
- Changed `The_UDP_connection_oriented_implementation_must_be_able_to_send_and_receive_with_binding` to `async/await`
- Changed `The_UDP_connection_oriented_implementation_must_to_send_batch_writes_and_reads` to `async/await`
- Changed `The_UDP_connection_oriented_implementation_must_not_leak_memory` to `async/await`
> Port `Akka.Tests.IO` tests to `async/await` - `UdpConnectedIntegrationSpec`

- src/core/Akka.Tests/IO/UdpIntegrationSpec.cs
- Changed `The_UDP_Fire_and_Forget_implementation_must_be_able_to_send_without_binding` to `async/await`
- Changed `The_UDP_Fire_and_Forget_implementation_must_be_able_to_send_multipart_ByteString_without_binding` to `async/await`
- Changed `BugFix_UDP_fire_and_forget_must_handle_batch_writes_when_bound` to `async/await`
- Changed `The_UDP_Fire_and_Forget_implementation_must_be_able_to_send_several_packet_back_and_forth_with_binding` to `async/await`
- Changed `The_UDP_Fire_and_Forget_implementation_must_be_able_to_send_several_packets_in_a_row` to `async/await`
- Changed `The_UDP_Fire_and_Forget_implementation_must_not_leak_memory` to `async/await`
- Changed `The_UDP_Fire_and_Forget_SimpleSender_implementation_must_not_leak_memory` to `async/await`
- Changed …
> Port `Akka.Tests.IO` tests to `async/await` - `UdpIntegrationSpec`

- src/core/Akka.Tests/IO/UdpListenerSpec.cs
- Changed `UDP_should_return_IPv4_endpoint_if_bound_using_IPv4_address` to `async/await`
- Changed `UDP_should_return_IPv6_endpoint_if_bound_using_IPv6_address` to `async/await`
> Port `Akka.Tests.IO` tests to `async/await` - `UdpListenerSpec`

- src/core/Akka.Tests/Pattern/BackoffOnRestartSupervisorSpec.cs
- Changed `BackoffOnRestartSupervisor_must_terminate_when_child_terminates` to `async/await`
- Changed `BackoffOnRestartSupervisor_must_restart_the_child_with_an_exponential_back_off` to `async/await`
- Changed `BackoffOnRestartSupervisor_must_stop_on_exceptions_as_dictated_by_the_supervisor_strategy` to `async/await`
- Changed `BackoffOnRestartSupervisor_must_forward_messages_from_the_child_to_the_parent_of_the_supervisor` to `async/await`
- Changed `BackoffOnRestartSupervisor_must_respect_maxNrOfRetries_property_of_OneForOneStrategy` to `async/await`
- Changed `BackoffOnRestartSupervisor_must_respect_withinTimeRange_property_of_OneForOneStrategy` to `async/await`
> Port `Akka.Tests.Pattern` tests to `async/await` - `BackoffOnRestartSupervisorSpec`

- src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs
- Changed `BackoffSupervisor_must_start_child_again_when_it_stops_when_using_Backoff_OnStop` to `async/await`
- Changed `BackoffSupervisor_must_forward_messages_to_the_child` to `async/await`
- Changed `BackoffSupervisor_must_support_custom_supervision_strategy` to `async/await`
- Changed `BackoffSupervisor_must_support_default_stopping_strategy_when_using_Backoff_OnStop` to `async/await`
- Changed `BackoffSupervisor_must_support_manual_reset` to `async/await`
- Changed `BackoffSupervisor_must_reply_to_sender_if_replyWhileStopped_is_specified` to `async/await`
- Changed `BackoffSupervisor_must_not_reply_to_sender_if_replyWhileStopped_is_not_specified` to `async/await`
- Changed `BackoffSupervisor_must_stop_restarting_the_child_after_reaching_maxNrOfRetries_limit_using_BackOff_OnStop` to …
> Port `Akka.Tests.Pattern` tests to `async/await` - `BackoffSupervisorSpec`

- src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs
- src/core/Akka.Tests/Routing/ConfiguredLocalRoutingSpec.cs
- Changed `RouterConfig_must_be_fail_with_exception_if_not_correct` to `async/await`
- Changed `RouterConfig_must_not_get_confused_when_trying_to_wildcard_configure_children` to `async/await`
- Changed `RouterConfig_must_support_custom_router` to `async/await`
- Changed `RouterConfig_must_load_settings_from_config_for_local_child_router_of_system_actor` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `ConfiguredLocalRoutingSpec`

- src/core/Akka.Tests/Routing/RoundRobinSpec.cs
- Changed `Round_robin_pool_must_be_controlled_with_management_messages` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `RoundRobinSpec`

- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/CoordinatedShutdown.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
Fixes #5802
* Fix possible infinite loop 
* Fix circular reference memory leak
> Fix leaky coordinated shutdown

- src/core/Akka.Tests/Routing/RouteeCreationSpec.cs
- Changed `Creating_routees_must_result_in_visible_routees` to `async/await`
- Changed `Creating_routees_must_allow_sending_to_context_parent` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `RouteeCreationSpec`

- src/core/Akka.Tests/Routing/RoutingSpec.cs
- Changed `Routers_in_general_must_evict_terminated_routees` to `async/await`
- Changed `Routers_in_general_must_not_terminate_when_resizer_is_used` to `async/await`
- Changed `Routers_in_general_must_use_configured_nr_of_instances_when_FromConfig` to `async/await`
- Changed `Routers_in_general_must_use_configured_nr_of_instances_when_router_is_specified` to `async/await`
- Changed `Routers_in_general_must_use_specified_resizer_when_resizer_not_configured` to `async/await`
- Changed `Routers_in_general_must_set_supplied_supervisorStrategy` to `async/await`
- Changed `Routers_in_general_must_set_supplied_supervisorStrategy_for_FromConfig` to `async/await`
- Changed `Routers_in_general_must_default_to_all_for_one_always_escalate_strategy` to `async/await`
- Changed …
> Port `Akka.Tests.Routing` tests to `async/await` - `RoutingSpec`

- src/core/Akka.Tests/Routing/ScatterGatherFirstCompletedSpec.cs
- Changed `Scatter_gather_pool_must_without_routees_should_reply_immediately` to `async/await`
- Changed `Scatter_gather_group_must_only_return_one_response` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `ScatterGatherFirstCompletedSpec`

- src/core/Akka.Tests/Routing/TailChoppingSpec.cs
- Changed `Tail_chopping_group_router_must_return_response_from_second_actor_after_inactivity_from_first_one` to `async/await`
- Changed `Tail_chopping_group_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time` to `async/await`
- Changed `Tail_chopping_group_router_must_reply_ASAP` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `TailChoppingSpec`

- src/core/Akka.Cluster/ClusterDaemon.cs
Port: [#26861](https://github.com/akka/akka/pull/26861)
> Be more explicit that a node is shutting down as it was marked as DOWN

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
Closes #5834
This doesn't really fix a bug. We're just making sure that an error is logged even when nothing is catching the stream failure exception.
> Change the failure log inside `AllEventPublisher` from Debug to Error

- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
When we abort, we want to make sure that we shutdown the actor system aggressively, hence we need to skip CoordinatedShutdown.
> Make ActorSystemImpl.Abort skip the CoordinatedShutdown check

- RELEASE_NOTES.md
- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Akka.Persistence.Sqlite.csproj
- src/core/Akka.Coordination/LeaseProvider.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/examples/Akka.Persistence.Custom/Akka.Persistence.Custom.csproj
Akka.NET v1.4.37 is a minor release that contains some minor bug fixes.
* [Persistence.Query: Change AllEvents query failure log severity from Debug to Error](https://github.com/akkadotnet/akka.net/pull/5835)
* [Coordination: Harden LeaseProvider instance Activator exception handling](https://github.com/akkadotnet/akka.net/pull/5838)
* [Akka: Make ActorSystemImpl.Abort skip the CoordinatedShutdown check](https://github.com/akkadotnet/akka.net/pull/5839)
If you want to see the [full set of changes made in Akka.NET v1.4.37, click here](https://github.com/akkadotnet/akka.net/milestone/68?closed=1).
| COMMITS | LOC+ | LOC- | AUTHOR              |
|---------|------|------|---------------------|
| 3       | 15   | 4    | Gregorius Soedharmo |
| 1       | 2    | 2    | dependabot[bot]     |
> v1.4.37 Release

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/core/Akka.Persistence.TCK/Journal/JournalSpec.cs
- src/core/Akka.Persistence.TCK/Query/TestActor.cs
- src/core/Akka.Persistence/Eventsourced.Lifecycle.cs
- DeleteMessagesFailure message stack trace were suppressed in log
- Make JournalSpec facts overridable
> Fix Persistence.TCK specs

- docs/articles/streams/builtinstages.md
- docs/articles/streams/integration.md
- src/core/Akka.Streams.Tests/Dsl/ActorRefSourceSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ActorRefSourceActor.cs
(cherry picked from commit 1a3d5cd8a7dc6a0e6865215bfebc5513abee5ca0)
> Backport of #5875: Fixes Source.ActorRef not completing

- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransportSettings.cs
`Thumbprint` was named `thumpbrint` and `thumprint` in the dotnetty remote ssl setting
> Fix typo in `akka.remote.dot-netty.ssl.certificate`

- src/core/Akka.Remote.Tests/AddressUidExtensionSpecs.cs
- src/core/Akka.Remote.Tests/RemoteDaemonSpec.cs
* AddressUidExtensionSpecs
* RemoteDaemonSpec
> Convert Akka.Remote.Tests to async - Assorted small changes

- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransportSettings.cs
(cherry picked from commit 51465599485dc1532039534ef71cd45cfb19d455)
Bakport #5895
> Backport of #5895: Fix typo in `akka.remote.dot-netty.ssl.certificate`

- build.fsx
Modify build.fsx dotnet test to target the assembly dll directly instead of targetting the .csproj file, this provides a better debugging feedback when the CI/CD froze/hung as it gives an indication on which project it is actually froze on.
> Modify build.fsx dotnet test to target the assembly dll directly instead of targetting the .csproj file

- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
> Cluster Log Spec

- src/core/Akka.Cluster.Tests/ClusterDomainEventPublisherSpec.cs
> Cluster Domain Even Publisher

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.verified.txt
- src/core/Akka.Cluster.Tests/Bugfix5962Spec.cs
- src/core/Akka.Cluster.Tests/DowningProviderSpec.cs
- src/core/Akka.Cluster.Tests/StartupWithOneThreadSpec.cs
- src/core/Akka.Cluster/AutoDown.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Cluster/DowningProvider.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolver.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolverProvider.cs
- src/core/Akka.Cluster/SplitBrainResolver.cs
close #5962
Fixes #5962
Passes a `Cluster` instance directly into the SBR constructor in order to avoid same-thread issues with `Lazy<Cluster>`.
> pass `Akka.Cluster.Cluster` into `IDowningProvider` directly

- docs/articles/utilities/serilog.md
Add list of properties one can use to customize serilog output template for akka logging adapter.
This information is missing from documentation and it took me 1 hour to find that information. It is going to be helpful to people that would also like to see actor path in logs.
> feat: info about serilog context properties

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
Fixes #5604
Allows the `PersistentShardCoordinator` to tolerate multiple `ShardHomeAllocated` messages in the journal for the same shard - this is done in order to allow the sharding system to try its best to restart itself without bringing the system offline in the event of duplicate data appearing in the journal.
> Allow `PersistentShardCoordinator` to tolerate duplicate `ShardHomeAllocated` messages

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.Net.verified.txt
- src/core/Akka.Cluster.Tests/Bugfix5962Spec.cs
- src/core/Akka.Cluster.Tests/DowningProviderSpec.cs
- src/core/Akka.Cluster.Tests/StartupWithOneThreadSpec.cs
- src/core/Akka.Cluster/AutoDown.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Cluster/DowningProvider.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolver.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolverProvider.cs
- src/core/Akka.Cluster/SplitBrainResolver.cs
Backport of #5965 
> Passes a Cluster instance directly into the SBR constructor in order to avoid same-thread issues with Lazy<Cluster>.
> Backport of #5965 - pass Akka.Cluster.Cluster into IDowningProvider directly

- src/core/Akka.Remote/Endpoint.cs
Trap all exceptions when we try to dispatch/deserialize an InboundPayload in Akka.Remote.EndpointReader receiver.
> Trap all exception thrown while trying to dispatch messages in Akka.Remote.EndpointReader

- src/core/Akka.Remote/Endpoint.cs
Backport of #5971 from `1.4` branch into `dev` branch
> Backport #5971 - Trap all exception thrown while trying to dispatch messages in Akka.Remote.EndpointReader

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
Fixes #5604 
Reverts https://github.com/akkadotnet/akka.net/pull/5967
De-duplicate only exact `ShardHomeAllocated` duplicate data, makes the changes to the `PersistentShardCoordinator` safer and more narrow in scope than https://github.com/akkadotnet/akka.net/pull/5967
> Fix sharding tolerant reader

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.39 is a minor release that contains some very important bug fixes for Akka.Remote and Akka.Cluster users.
* [Akka.Cluster: Error in `SplitBrainResolver.PreStart` when using `ChannelTaskScheduler` for internal-dispatcher](https://github.com/akkadotnet/akka.net/issues/5962)
* [Akka.Cluster.Sharding: make PersistentShardCoordinator a tolerant reader](https://github.com/akkadotnet/akka.net/issues/5604) - Akka.Persistence-backed sharding is more lenient when recovering state.
* [Akka.Remote: Trap all `Exception`s thrown while trying to dispatch messages in `Akka.Remote.EndpointReader`](https://github.com/akkadotnet/akka.net/pull/5971) - any kind of exception thrown during deserialization can no longer force a disassociation to occur in Akka.Remote.
If you want to see the [full …
> added v1.4.39 release notes

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardCoordinatorStateModelTests.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardedDaemonProcessSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/core/Akka.Tests.Shared.Internals/Helpers/FSharpDelegateHelper.cs
Fixes #5604
Added model-based test with FsCheck to validate that `PersistentShardCoordinator.State` is designed correctly.
> Model-based tests for `PersistentShardCoordinator.State`

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
- src/core/Akka.Docs.Tests/Streams/HubsDocTests.cs
- src/core/Akka.Docs.Tests/Streams/StreamRefsDocTests.cs
- src/core/Akka.Streams.Tests/Dsl/GraphMatValueSpec.cs
- src/core/Akka.Streams.Tests/Dsl/GraphZipSpec.cs
- src/core/Akka.Streams.Tests/IO/TcpSpec.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/Sink.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
Incidentally, this also fixes signature for `Sink.ForEach`, `Sink.ForEachParallel`.
Breaking changes to the public API of the above-mentioned methods to fix their signatures.
> Fixes Sink.Ignore signature from Task to Task<Done>

- docs/articles/configuration/config.md
Fixes #3880
Only one file from documentation has been changed (config.md)
> TcpTransport class instead of DotNettyTransport class in hocon config

- src/core/Akka.Cluster.Tests/ClusterSpec.cs
- src/core/Akka.Cluster/Cluster.cs
Change how `Cluster.JoinAsync()` and `Cluster.JoinSeedNodesAsync()` work, does not rely on `MemberRemoved` anymore, work on a fixed timer instead, configurable via the `akka.cluster.seed-node-timeout` HOCON settings.
> [Async TestKit] Convert Akka.Cluster.Tests to async - ClusterSpec

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
- src/core/Akka.Streams.Tests/Dsl/SourceWithContextSpec.cs
- src/core/Akka.Streams/Dsl/SourceWithContext.cs
Added missing `SourceWithContext.FromTuples` operator
> Added missing `SourceWithContext.FromTuples` operator

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Streams/Implementation/IO/TcpStages.cs
- src/core/Akka/IO/Tcp.cs
- src/core/Akka/IO/TcpListener.cs
Changes:
Make TcpListener binding and unbinding code non-blocking by running them on another thread.
> [Async TestKit] Modernize TcpStage and TcpListener

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/PersistentShardSpec.cs
Add spec to make sure that Cluster.Sharding can survive any transient exceptions thrown from entity constructor and PreStart method
> Add Cluster.Sharding ActorInitializationException spec

- docs/articles/streams/builtinstages.md
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
- src/core/Akka.Streams.Tests/Dsl/FlowGroupedWithinSpec.cs
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Dsl/SubFlowOperations.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Streams/Implementation/Stages/Stages.cs
Adds `GroupedWeightedWithin` operator and `GroupedWeightedWithin{T}` stage. `GroupedWithin` operator is now based on this stage too.
> Added GroupedWeightedWithin operator

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceQuery.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceQuery.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceQuery.Net.verified.txt
- src/core/Akka.Persistence.Query.Tests/OffsetSpec.cs
- src/core/Akka.Persistence.Query.Tests/Utils/TimeUuid.cs
- src/core/Akka.Persistence.Query/Offset.cs
Adds TimeBasedUuid offset used in Cassandra.
Sadly, there's no built-in support for time-based guids in .NET. The CSharp cassandra driver has a struct (`TimeUuid`) compatible with `v1` of `java.utils.uuid`. And since we can't have a reference to the cassandra driver in the Core, this implementation of the `TimeBasedUuid` takes a `Guid` instead. But then there's no way to check whether the `Guid` passed to `TimeBasedUuid` is actually a `TimeUuid`.
`TimeUuid` code has been pulled into the Tests to enable proper testing.
Feedback?
> Added TimeBasedUuid offset

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Tests/Actor/PipeToSupportSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Actor/PipeToSupport.cs
Enable `ValueTask` and `ValueTask<T>` support for `PipeTo`
> Add ValueTask support to PipeTo

- src/core/Akka.Streams.Tests/Dsl/HubSpec.cs
Needed to boost time to process 20,000 elements with buffer size =1 from 3 cumulative seconds to 300. On low quality AzDo machines there's no telling what delays we'll hit.
> harden `HubSpec` duration

- src/core/Akka.Cluster.Tests/ClusterSpec.cs
The probable cause for failure is a bit convoluted, but it started here:
https://github.com/akkadotnet/akka.net/blob/0c9677f700b6115090d3a277d28f310046e0235f/src/core/Akka.Cluster/CoordinatedShutdownLeave.cs#L64-L67
The cluster shutdown watcher actor allows for MemberStatus.Leaving to signal a complete cluster shutdown, and if CoordinatedShutdown reaches its completion faster than the cluster exit flow, it will trigger the `Shutdown` method registered here:
https://github.com/akkadotnet/akka.net/blob/0c9677f700b6115090d3a277d28f310046e0235f/src/core/Akka.Cluster/Cluster.cs#L144
invoking a hard ClusterDaemon stop here:
https://github.com/akkadotnet/akka.net/blob/0c9677f700b6115090d3a277d28f310046e0235f/src/core/Akka.Cluster/Cluster.cs#L579
stopping the ClusterDomainEventPublisher, which …
> Harden ClusterSpec CoordinatedShutdown

- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
The `JoinAsync` method wasn't written correctly - need to force `JoinAsync` to run to completion for assertion to make any kind of sense.
> harden `ClusterLogSpec`

- src/core/Akka.Remote.Tests/Transport/DotNettySslSupportSpec.cs
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransportSettings.cs
Fixes # https://github.com/akkadotnet/akka.net/issues/3594
If remote:dot-netty:enablessl property is set false and certificate and a password are not provided, a SslSettings object is still trying to be created. 
After this change, SslSettings object will be attempted to create only if enablessl property is set to false.
> SSL Configuration Fails even EnbleSsl property is set to false

- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
Use `ExpectOneAsync` with timeout support instead of using a `Within` block
> Fix ClusterLogSpec, EventFilter does not play nice with Within

- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
Better to use `await` around `ValueTask` rather than converting to `Task` and doing `ContinueWith`
Cleanup from #6044
> cleaned up `IAsyncEnumerable` Source to use local functions

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.verified.txt
- src/core/Akka.Streams.TestKit.Tests/StreamTestDefaultMailbox.cs
- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
Cherry-picked from https://github.com/akkadotnet/akka.net/commit/af513b05c2128bc916bfe2ef9598e4c5b4d78960
Backport of #6044
- Adapted the API verify list
- Change the `OnDownstreamFinish` override signature, 1.4 does not support downstream failure propagation.
- Added missing StreamTestDefaultMailbox.DefaultConfig
> [BACKPORT #6044] Add IAsyncEnumerable as Akka.Streams Source

- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
Cherry-picked from https://github.com/akkadotnet/akka.net/commit/0c92aac98c9421a4112692155ec33b28dbc4940d
> [BACKPORT  #6045] cleaned up `IAsyncEnumerable` Source to use local functions

- src/core/Akka.Tests/Loggers/LoggerStartupSpec.cs
- src/core/Akka/Event/LoggingBus.cs
Exception handling inside AddLogger is wrong
> Fix faulty AddLogger in LoggingBus

- src/core/Akka.Tests/Loggers/LoggerStartupSpec.cs
- src/core/Akka/Event/LoggingBus.cs
Backport of #6028
* Fix faulty AddLogger in LoggingBus
* Ignore logger async start setting, not relevant anymore
* Simplify unit test
* Send Stop instead of PoisonPill
* Make loggers load asynchronously by default
* Change logging back to exceptions
* Remove _startupState, use closure instead
Co-authored-by: Aaron Stannard <aaron@petabridge.com>
(cherry picked from commit c8b46b44ee0f2f1b4f1f88e624d5b611aa10912a)
> [BACKPORT #6028] Fix faulty AddLogger in LoggingBus

- src/core/Akka.Streams.Tests/Dsl/HubSpec.cs
Fixes #6051
- Removed the `.Take()` stage, suspected culprit.
- Check each event manually instead of relying on `ExpectNextNAsync`
> Fix Streams.Tests.Dsl.MergeHub_must_work_with_long_streams_when_buffer_size_is_1

- src/core/Akka.Docs.Tutorials/Tutorial3/DeviceGroupSpec.cs
- src/core/Akka.Docs.Tutorials/Tutorial3/DeviceManager.cs
- src/core/Akka.Docs.Tutorials/Tutorial4/DeviceGroupQueryInProgress.cs
This PR improves the tutorial by:
- adding an assertion to tutorial 3. Without this assertion, there is no check of the newly implemented functionality.
- removing unused arguments that would otherwise stop the code from compiling.
- including code that is relevant for step 4, that would stop the code from compiling at that point in the tutorial.
I made all the changes while following the tutorial.
> Tutorial improvements

- docs/articles/clustering/cluster-singleton.md
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonApiSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingleton.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonSettings.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.Net.verified.txt
Fixes #6036
Since this already exists in Akka Typed and it isn't built on top of anything Akka-Typed specific, I put together a quick port with this functionality:
- If there already is a manager running for the given `singletonName` on this node, no additional manager is started.
- If there already is a proxy running for the given `singletonName` on this node, an IActorRef to that is returned.
```
var singleton = ClusterSingleton.Get(system);
var settings = ClusterSingletonSettings.Create(system).WithRole("singleton");
var proxy = singleton.Init(SingletonActor.Create(Props.Create<GlobalCounter>(), "GlobalCounter").WithSettings(settings));
proxy.Tell(Counter.Increment);
```
This will required a complete cluster restart though, since the names for both the `ClusterSingletonManager` and …
> Singleton class and settings based on current Akka Typed implementation

- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonRestart3Spec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/MemberAgeOrderingSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxy.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxySettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/MemberAgeOrdering.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/reference.conf
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterTools.Net.verified.txt
- src/core/Akka.Cluster/Properties/AssemblyInfo.cs
- src/core/Akka/Util/AppVersion.cs
Fixes #6035
Changes the way oldest member sorting comparator works, taking Member.AppVersion into consideration. Members with higher AppVersion will always be bumped to the front of the list, regardless of Member age.
> Cluster singleton should consider Member AppVersion during hand over.

- src/core/Akka/Actor/SupervisorStrategy.cs
Modified the default `SupervisorStrategy` to record the full `Exception` when a `Warning` is issued when a `Directive.Resume` is returned by the `Decider` when handling child actor failures. The only material impact of this is improved visibility into the stack trace and error details.
> enabled `Directive.Resume` to log the full `Exception`

- src/benchmark/Akka.Benchmarks/Configurations/Configs.cs
- src/benchmark/Akka.Benchmarks/Remoting/AkkaPduCodecBenchmark.cs
Measures the memory and throughput impact of the `AkkaPduCodec` - essentially simulates inbound read / write latency.
Worth noting: understates the level of GC impact in the real Akka.Remote endpoint system - everything here gets GC0; in Akka.Remote it's GC1/2 since these messages also get delivered into the DotNetty across scope boundaries.
> `AkkaPduCodec` serializer benchmark

- src/benchmark/Akka.Benchmarks/Configurations/Configs.cs
- src/benchmark/Akka.Benchmarks/Remoting/AkkaPduCodecBenchmark.cs
* added benchmark to measure `AkkaPduCodec` overhead
* completed `AkkaPduCodec` benchmarks
* broke down read-side deserialization
* added second ActorSystem
* added full cache debug logs
(cherry picked from commit eee47ac19c3a4fa8e803a4cc5f70b585c7f1ed31)
> [BACKPORT] (#6078) `AkkaPduCodec` serializer benchmark 

- src/contrib/cluster/Akka.DistributedData/Replicator.cs
Improves #6074 
Akka.NET version 1.4.41 introduced verbose-debug-logging switch that is used to disable by default higher level of details in the debug log. However, in my previous PR I overlooked another "Received gossip" log statement that also result in high volume of log messages, as well as "Sending gossip" log messages. This PR adds VerboseDebugLogging requirement for these messages.
I checked the remaining log messages and they do not seem to cause excessive logging. There is one "Sending gossip..." log statement that I didn't wrap with a check for VerboseDebugLogging because it's written when requesting missing keys and only occurs occasionally, so I suppose it can be OK to always write it when Debug logging is enabled.
> Require verbose logging for more gossip send/receive log statements.

- src/contrib/cluster/Akka.DistributedData/Replicator.cs
Backport of #6089
(cherry picked from commit 3b4ed91485f0dfe280bcb9315eadaa84b3895fca)
> [BACKPORT #6089] Require verbose logging for more gossip send/receive log statements.

- src/core/Akka.TestKit.Tests/TestKitSpec.cs
- src/core/Akka.TestKit/TestKitBase.cs
Problem when passing arbitrary `ActorSystem` into a TestKit, it would throw a `ConfigurationException` because the TestKit HOCON configuration was not injected into the `ActorSystem`
- Injects `TestKitBase._defaultConfig` if the TestKit did not create the `ActorSystem` being tested
- Add unit tests
> [Akka.TestKit] TestKitBase should take arbitrary ActorSystem without throwing

- src/core/Akka.TestKit.Tests/TestKitSpec.cs
- src/core/Akka.TestKit/TestKitBase.cs
Backport of #6092
(cherry picked from commit 015de371f92717c2d4c4c4e6ae3252166335a7a2)
> [BACKPORT #6092] [Akka.TestKit] TestKitBase should take arbitrary ActorSystem without throwing

- src/core/Akka.Tests/Actor/ActorLifeCycleSpec.cs
- src/core/Akka.Tests/Actor/GracefulStopSpecs.cs
Adding some unit tests for `GracefulStop` since apparently we've never had any dedicated tests for this in the test suite. This is in preparation for some changes I'm going to introduce in https://github.com/akkadotnet/akka.net/pull/6102
> Add graceful stop specs

- docs/articles/clustering/cluster-sharding.md
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardRegionQueriesSpecs.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.verified.txt
Designed to make it easier for testing and telemetry, the new `GetEntityLocation` is an `IShardRegionQuery` that checks for the presence of an entity in a given `ShardRegion` and reports back if this entity is able to be located.
This query is not designed to be supported over the network and is meant to be local-only.
I've added this primary for _testing and telemetry_ purposes - as we're going to look at using this inside the [`pbm cluster-sharding` palette for Petabridge.Cmd](https://cmd.petabridge.com/articles/commands/cluster-sharding-commands.html).
> Akka.Cluster.Sharding `GetEntityLocation` Query

- docs/articles/clustering/cluster-sharding.md
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardRegionQueriesSpecs.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterSharding.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterSharding.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterSharding.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveClusterSharding.verified.txt
cherry-picked from 231c8c9179c37c658bd7963bd0085b4f1919e87a
> [PORT #6101] Akka.Cluster.Sharding `GetEntityLocation` Query

- README.md
Fixes #5375
Made `README.md` NuGet-friendly.
> close #5375 - made README.md NuGet-friendly

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardRegionQueriesHashCodeSpecs.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
Fixes:
`GetEntityLocation` does not work with `HashCodeMessageExtractor`
> Fix GetEntityLocation use wrong actor path

- src/core/Akka/Event/LogEvent.cs
Allow `LogLevel` template to display milliseconds. This is specially useful in time-sensitive tests.
> Allow `LogLevel` template to display milliseconds

- src/core/Akka/Dispatch/Mailbox.cs
Reduces delegate allocations while processing actor mailbox contents to zero - eliminates the vast majority of allocations that occur during mailbox processing.
Running on .NET 6 - note: I modified the `MailboxThroughputBenchmarks` to only use the `CallingThreadDispatcher` as that's a cleaner signal for measuring throughput impact of these changes, which otherwise won't show up as easily using the .NET ThreadPool.
``` ini
Job-OMCNHR : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
InvocationCount=1 …
```
> eliminate mailbox delegate allocations

- src/benchmark/Akka.Benchmarks/Dispatch/DispatcherBenchmarks.cs
- src/benchmark/Akka.Benchmarks/Dispatch/MailboxThroughputBenchmarks.cs
Added Benchmark.NET ports of our old NBench benchmarks in order to measure memory allocation and throughput for various benchmark configurations.
``` ini
DefaultJob : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
```
|        Method | TaskCount |      Configurator |       Mean |    Error |    StdDev |       Gen 0 | Allocated |
|-------------- |---------- |------------------ |-----------:|---------:|----------:|------------:|----------:|
| **RunDispatcher** |   **1000000** |          **ChannelD** | **2,422.2 ms** …
> Added Dispatcher Benchmarks

- src/benchmark/Akka.Benchmarks/Actor/FsmBenchmarks.cs
Fixes #2560
added performance benchmarks for FSM
``` ini
DefaultJob : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
```
|           Method | MsgCount |     Mean |    Error |   StdDev | Ratio | RatioSD |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|----------------- |--------- |---------:|---------:|---------:|------:|--------:|-----------:|----------:|----------:|----------:|
|     BenchmarkFsm |  1000000 | 758.8 ms | 10.92 ms | 10.21 ms |  1.67 |    0.03 | 69000.0000 | 4000.0000 | 1000.0000 |    287 MB |
| …
> added performance benchmarks for FSM

- src/core/Akka/Dispatch/Dispatchers.cs
- src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
Instead of having the `DedicatedThreadPool` operate on `Action` delegates, we now just take the `IRunnable` directly. Avoids a delegate allocation per-invocation.
``` ini
DefaultJob : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
```
|        Method | TaskCount |      Configurator |       Mean |    Error |    StdDev |       Gen 0 | Allocated |
|-------------- |---------- |------------------ |-----------:|---------:|----------:|------------:|----------:|
| **RunDispatcher** |   **1000000** |          **ChannelD** …
> remove delegate allocation from `ForkJoinDispatcher` and `DedicatedThreadPool`

- src/benchmark/Akka.Benchmarks/Actor/ActorMessagingMemoryPressureBenchmark.cs
- src/benchmark/Akka.Benchmarks/Actor/FsmBenchmarks.cs
purpose of this benchmark is not to measure processing time - it's meant to measure allocation pressure created by Akka.NET infrastructure:
* `Envelope`s
* `Mailbox` and `MessageDispatcher` overhead
* `ActorCell` and `ActorBase` invocation overhead
Ideally the memory pressure, given a `const string` as messaging input, should be close to zero - but between mailbox queue segment allocations, delegate + closure allocations, and probably some boxing we know that's not the case. Purpose of this benchmark is to measure that impact across threads.
> **N.B.** - this benchmark makes no attempt to measure processing time nor does it wait for actors to process all messages. _That is by design_. …
> added actor messaging pressure benchmark

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka/Actor/Message.cs
Converts `Envelope` back into a `sealed class` rather than a `struct` - believe it or not, this significantly reduces total memory allocation and mailbox write latency.
All benchmarks are running on .NET 6.
``` ini
Job-AMVGCN : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
```
|             Method | MsgCount |           Mean |        Error |       StdDev |         Median |     Gen 0 |  Allocated |
|------------------- |--------- …
> Make `Envelope` a reference type again

- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs
Fixes #6125
Note that since we're blocking during test start, there are a chance that some tests that timed to system startup might start to racily fail.
> Block Xunit2 TestKit until unit test logger is ready

- src/benchmark/Akka.Benchmarks/Actor/FsmBenchmarks.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Tests/Actor/FSMActorSpec.cs
- src/core/Akka/Actor/FSM.cs
Reduced some unnecessary allocations inside the `FSM<TState, TData>` class.
``` ini
DefaultJob : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
```
|           Method | MsgCount |     Mean |    Error |   StdDev | Ratio | RatioSD |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|----------------- |--------- |---------:|---------:|---------:|------:|--------:|-----------:|----------:|----------:|----------:|
|     BenchmarkFsm |  1000000 | 772.8 ms | 13.20 ms | 12.35 ms |  1.74 |    0.06 | 68000.0000 | 4000.0000 …
> Reduce `FSM<TState, TData>` allocations

- src/benchmark/Akka.Benchmarks/Logging/LoggingBenchmarks.cs
The Akka.NET logging system fundamentals haven't really changed much since 2014 or so, and I suspect we are doing some _extremely ugly_ things in that code. Adding some benchmarks using a custom `ILoggingAdapter` implementation so I can measure the overhead.
``` ini
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19043.2006/21H1/May2021Update)
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100
[Host]     : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
Job-JJNOTA : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
```
|                      Method |     Mean |    Error |   StdDev | Ratio | RatioSD |   Gen0 | …
> Logging Benchmarks

- build-system/pr-validation.yaml
- docs/cSpell.json
- docs/community/contributing/documentation-guidelines.md
Just a quick drive-by. I've been doing some other similar PR work and figured I'd bump the versions since I know they work.
* Updates node version of spellcheck task from 12.x --> 16.x
* Updates cSpell version to the latest 6.12.0
> Update version numbers in spellcheck pipeline

- src/benchmark/Akka.Benchmarks/Logging/LoggingBenchmarks.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Streams.Tests/Dsl/FlowLogSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Tests/Loggers/LoggerSpec.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Event/DefaultLogMessageFormatter.cs
- src/core/Akka/Event/Logging.cs
`DefaultLogMessageFormatter` is essentially a `static` class - removed its constructor and made it a singleton. This won't help with actor performance at all, but will reduce the total actor memory footprint especially in larger `ActorSystem`s.
> Eliminate `DefaultLogMessageFormatter` allocations

- src/benchmark/Akka.Benchmarks/Logging/LoggingBenchmarks.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Streams.Tests/Dsl/FlowLogSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Tests/Loggers/LoggerSpec.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Event/DefaultLogMessageFormatter.cs
- src/core/Akka/Event/Logging.cs
> [BACKPORT #6166] Eliminate `DefaultLogMessageFormatter` allocations

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
> Fix DbCommand.CommandTimeout

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
(cherry picked from commit 695fada8f3abebc94d096bcd3945c9ab0a051e00)
> [BACKPORT #6175] Fix DbCommand.CommandTimeout

- src/core/Akka/Actor/FSM.cs
The `object.Equals` call here generated hundreds of mb in boxing allocations inside RemotePingPong - using the `EqualityComparer<TState>.Default.Equals` eliminates them.
Used Rider's Dynamic Program Analysis to verify that the allocations were removed.
> removed boxing allocations inside `FSM.State.Equals`

- src/core/Akka/Actor/FSM.cs
The `object.Equals` call here generated hundreds of mb in boxing allocations inside RemotePingPong - using the `EqualityComparer<TState>.Default.Equals` eliminates them.
(cherry picked from commit 183ec5ae1229b2948e1b18c2e90aa75eb52f8955)
> [PORT #6183] removed boxing allocations inside `FSM` 

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka/Configuration/ConfigurationException.cs
Fixes #6200
Revert changes to the static method
> Revert ConfigurationException due to binary incompatibility

- docs/articles/actors/testing-actor-systems.md
Fixes #
The call to `Within()` in the documents contained invalid c# syntax.
> Fix syntax error in Testing actor systems documentation

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
This is a usability improvement aimed at making sure we contain the full context of what topic we were trying to publish to or which `Put`-ed actor we were trying to publish to when there are no subscribers available on the local node.
> Make sure that `DeadLetter`s published by `DistributedPubSubMediator` contain full context of topic

- src/common.props
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Akka.csproj
Backport of #6229
(cherry-picked from 94756d644d7bb1ae6e3b591222176d7a189205da)
> [BACKPORT #6229] Upgrade to System.Configuration.ConfigurationManager 6.0.1 

- src/common.props
Backport of #6230
(cherry picked from commit 5e66bf004d2286940d252ef82d6a08c32360899b)
> [BACKPORT #6230] Upgrade to Newtonsoft.Json 13.0.1 as minimum version 

- RELEASE_NOTES.md
Akka.NET v1.4.46 is a security patch for Akka.NET v1.4.45 but also includes some other fixes.
**Security Advisory**: Akka.NET v1.4.45 and earlier depend on an old System.Configuration.ConfigurationManager version 4.7.0 which transitively depends on System.Common.Drawing v4.7.0. The System.Common.Drawing v4.7.0 is affected by a remote code execution vulnerability [GHSA-ghhp-997w-qr28](https://github.com/advisories/GHSA-ghhp-997w-qr28).
We have separately created a security advisory for [Akka.NET Versions < 1.4.46 and < 1.5.0-alpha3 to track this issue](https://github.com/akkadotnet/akka.net/security/advisories/GHSA-gpv5-rp6w-58r8).
**Fixes and Updates**
* [Akka: Upgrade to Newtonsoft.Json 13.0.1 as minimum version](https://github.com/akkadotnet/akka.net/pull/6252)
* [Akka: Upgrade to …
> added v1.4.46 release notes

- RELEASE_NOTES.md
Akka.NET v1.5.0-alpha3 is a security patch for Akka.NET v1.5.0-alpha2 but also includes some other fixes.
**Security Advisory**: Akka.NET v1.5.0-alpha2 and earlier depend on an old System.Configuration.ConfigurationManager version 4.7.0 which transitively depends on System.Common.Drawing v4.7.0. The System.Common.Drawing v4.7.0 is affected by a remote code execution vulnerability [GHSA-ghhp-997w-qr28](https://github.com/advisories/GHSA-ghhp-997w-qr28).
We have separately created a security advisory for [Akka.NET Versions < 1.4.46 and < 1.5.0-alpha3 to track this issue](https://github.com/akkadotnet/akka.net/security/advisories/GHSA-gpv5-rp6w-58r8).
**Fixes and Updates**
* [Akka: Revert ConfigurationException due to binary incompatibility](https://github.com/akkadotnet/akka.net/pull/6204) …
> Update RELEASE_NOTES.md for 1.5.0-alpha3 release

- docs/articles/clustering/split-brain-resolver.md
> Update cluster SBR documentation on lease and how it works

- src/core/Akka.Streams.TestKit/Akka.Streams.TestKit.csproj
- src/core/Akka.Streams.TestKit/SubscriberFluentBuilder.cs
- src/core/Akka.Streams.TestKit/TestSubscriber_Shared.cs
- src/core/Akka.Streams.TestKit/Utils.cs
- src/core/Akka.Streams.Tests/BaseTwoStreamsSetup.cs
- src/core/Akka.Streams.Tests/ScriptedTest.cs
- src/core/Akka.Streams.Tests/TwoStreamsSetup.cs
> Remove Akka.Tests.Shared.Internals from Akka.Streams.TestKit dependency

- src/common.props
- src/core/Akka/Akka.csproj
Cleaned up duplicate System.Collections.Immutable package reference and also standardized all System.* packages on a common version.
N.B. - have not actually changed any of the versions being used, just sync'd them;.
> cleaned up duplicate System.Collections.Immutable package reference

- src/benchmark/Akka.Benchmarks/Actor/ActorPathBenchmarks.cs
While working on https://github.com/akkadotnet/akka.net/pull/6195 I realized that none of those `ActorPath`s actually have a set UID, thus we're missing that entire facet from both the parsing and serialization benchmarks.
``` ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.2251 (21H2)
.NET SDK=7.0.100
[Host]     : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT
DefaultJob : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT
```
|                                     Method |        Uid |       Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------------------------- |----------- …
> added real UID to `ActorPathBenchmarks`

- src/benchmark/PingPong/PingPong.csproj
- src/benchmark/RemotePingPong/RemotePingPong.csproj
Enables dynamic PGO and server GC for both RemotePingPong and PingPong benchmarks.
I'm enabling these because I hope that it will be easier to measure small differences in performance when we're working on problems like https://github.com/akkadotnet/akka.net/pull/6195
> Enable dynamic PGO for RemotePingPong and PingPong

- src/core/Akka.TestKit.Tests/TestActorRefTests/ExceptionHandling.cs
- src/core/Akka.TestKit/Internal/InternalTestActorRef.cs
- src/core/Akka.TestKit/TestActorRefBase.cs
- src/core/Akka/Dispatch/ActorTaskScheduler.cs
Backport of #6281
Fixes #6265
- Add ReceiveAsync feature to Akka.TestKit TestActorRef
- Add IAsyncResultInterceptor interface to tap directly into ReceiveAsync execution result
(cherry-picked from 5605d8303f3e901b297d9dface7efce51e90d27b)
> [BACKPORT #6281] Add ReceiveAsync to TestActorRef

- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
- src/core/Akka.Streams/Akka.Streams.csproj
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
Backports #6290
Fixes #6280
We no longer attempt to dispose IAsyncEnumerators inside Source stages due to the reasons outlined here: #6280 (comment)
This prevents the log from being filled with NotSupportedException warnings from failed DisposeAsync operations.
(cherry-picked from 3156272a480db1ee0faa80555695757c702a2dcd)
> [Backports #6290] Akka:Streams Resolve `IAsyncEnumerator.DisposeAsync` bug

- src/core/Akka.Remote.Tests/Serialization/Bugfix3903Spec.cs
- src/core/Akka.Remote.Tests/Serialization/MiscMessageSerializerSpec.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Serialization/ExceptionSupport.cs
- src/core/Akka.Remote/Serialization/MessageContainerSerializer.cs
- src/core/Akka.Remote/Serialization/MiscMessageSerializer.cs
- src/core/Akka.Remote/Serialization/Proto/ContainerFormats.g.cs
- src/protobuf/ContainerFormats.proto
Fixes #3903 
Adding support to any built-in messages that support `Exception` types. Won't be adding any serialization magic to Newtonsoft.Json for exception handling as that starts to get into CVE territory given the deep amount of context the serialization payloads contain. 
Some of the designs we're considering for 1.5 / later, namely using source generators to create compile-time serialization for everything, will make this issue easier to manage in the future. For now I think it's good to preserve the location transparency of Akka.NET's own built-in messages for end-user convenience and consistency.
> `Exception` serialization support for built-in messages

- RELEASE_NOTES.md
Akka.NET v1.4.47 is a maintenance patch for Akka.NET v1.4.46 that includes a variety of bug fixes, performance improvements, and new features.
**Actor Telemetry**
Starting in Akka.NET v1.4.47 local and remotely deployed actors will now emit events when being started, stopped, and restarted:
```csharp
public interface IActorTelemetryEvent : INoSerializationVerificationNeeded, INotInfluenceReceiveTimeout
{
/// <summary>
/// The actor who emitted this event.
/// </summary>
IActorRef Subject {get;}
/// <summary>
/// The implementation type for this actor.
/// </summary>
Type ActorType { get; }
}
/// <summary>
/// Event emitted when actor starts.
/// </summary>
public sealed class ActorStarted : IActorTelemetryEvent
{
public IActorRef Subject { get; }
public Type ActorType { get; }
}
/// …
```
> added v1.4.47 release notes

- src/core/Akka.Remote.Tests/Serialization/Bugfix3903Spec.cs
- src/core/Akka.Remote.Tests/Serialization/MiscMessageSerializerSpec.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Serialization/ExceptionSupport.cs
- src/core/Akka.Remote/Serialization/MessageContainerSerializer.cs
- src/core/Akka.Remote/Serialization/MiscMessageSerializer.cs
- src/core/Akka.Remote/Serialization/Proto/ContainerFormats.g.cs
- src/protobuf/ContainerFormats.proto
Port of #6297
* added end to end spec to validate error serialization for remote actor supervision
* defined `.proto`s for `Status.Failure` and `Status.Success`
* added `Status.,Failure` and `Status.Success` support to the `MiscMessageSerializer`
* added tests to `MiscMessageSerializerSpec`
* close #3903
(cherry picked from commit 998dcca6039d037be9a380bff5b19b9112db33af)
> [PORT #6297] `Exception` serialization support for built-in messages

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.verified.txt
- src/core/Akka.Streams.Tests/Implementation/ChannelSinkSpec.cs
- src/core/Akka.Streams.Tests/Implementation/ChannelSourceSpec.cs
- src/core/Akka.Streams/Dsl/ChannelSink.cs
- src/core/Akka.Streams/Dsl/ChannelSource.cs
- src/core/Akka.Streams/Dsl/Sink.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ChannelSinks.cs
- src/core/Akka.Streams/Implementation/ChannelSources.cs
Backport of https://github.com/akkadotnet/akka.net/pull/6268
- Moves Alpakka Channels Extension into the main project.
- Appends DSLs for main `Source` and `Sink` to have Channel methods
- Adds capability for a Channel Source with a materialized `ChannelWriter<T>` result
- This feels more symmetrical with the Sink API that allows both options, and allows for a better option-in-place-of `Source.Queue<T>`. 
The main motivations for this are as follows:
- We already take `System.Threading.Channels` as a dep in core Akka
- We can probably get rid of the ugly backing code behind `RunAsAsyncEnumerable`, even if it is a minorly-breaking API change it may be better long term.
> [BACKPORT] move Move Channel Stages from Alpakka to main project.

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Tests/Actor/Stash/ActorWithBoundedStashSpec.cs
- src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
- src/core/Akka/Actor/Stash/Internal/BoundedStashImpl.cs
- src/core/Akka/Actor/Stash/Internal/UnboundedStashImpl.cs
- src/core/Akka/Dispatch/Dispatchers.cs
- src/core/Akka/Dispatch/Mailbox.cs
- src/core/Akka/Dispatch/Mailboxes.cs
Fixes reading stash capacity from actor's mailbox or dispatcher configuration.
> Read stash capacity from actor's mailbox or dispatcher configuration

- RELEASE_NOTES.md
- src/common.props
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Made `FutureActorRef<T>` unsealed in order to resolve https://github.com/petabridge/phobos-issues/issues/74 - working on testing this to verify that is actually does work.
> make `FutureActorRef<T>` unsealed

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.48 is a minor release that introduces some additional APIs to Akka.NET.
* [Akka.Streams: `ChannelSource<T>` and `ChannelSink<T>` moved from Alpakka into main project](https://github.com/akkadotnet/akka.net/pull/6317) - these stages are now part of the normal Akka.Streams.Dsl.
* [Akka: make `FutureActorRef<T>` unsealed](https://github.com/akkadotnet/akka.net/pull/6322)
You can see the [full set of tracked issues for Akka.NET v1.4.48 here](https://github.com/akkadotnet/akka.net/milestone/79).
| 3 | 846 | 29 | Aaron Stannard |
> added v1.4.48 release notes

- src/core/Akka/Actor/ActorRef.Extensions.cs
Fixes #6313 
Documentaation of ActorRefExtensions.IsNobody was fixed
> Documentation for ActorRefExtensions.IsNobody was fixed #6313.

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Tests/Serialization/NewtonsoftJsonConfigSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
- Adds `use-compression` to NewtonSoftJsonSerializer
- When enabled, serialized data are compressed using `System.IO.Compression.GZip`
> Add compression option for NewtonSoftJsonSerializer

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Tests/Serialization/NewtonsoftJsonConfigSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
Reverts akkadotnet/akka.net#6341
Decided that this was too dangerous to introduce into a serializer that everyone already uses for a large percentage of messages; introduced https://github.com/akkadotnet/Akka.Serialization.Compressed instead.
> Revert "Add compression option for NewtonSoftJsonSerializer"

- docs/articles/actors/receive-actor-api.md
- docs/articles/actors/untyped-actor-api.md
- docs/cSpell.json
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.Net.verified.txt
- src/core/Akka/Actor/Stash/IWithBoundedStash.cs
- src/core/Akka/Actor/Stash/IWithStash.cs
- src/core/Akka/Actor/Stash/IWithUnrestrictedStash.cs
- src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
- src/core/Akka/Actor/Stash/Internal/UnrestrictedStashImpl.cs
- src/core/Akka/Actor/Stash/StashFactory.cs
- src/core/Akka/Dispatch/IRequiresMessageQueue.cs
Currently, once you've marked your actor with any of the Stash interfaces (`IWithUnboundedStash` or `IWithBoundedStash`) there's no way to change it afterward via configuration (it is a design-time operation that requires recompiling).
But there are two traits that allow users to do that in the JVM:
- A default `Stash` trait (`IWithStash` in this PR) which allows using any Deque-based mailbox (i.e., bounded or unbounded) via configuration. By default, it uses an UnboundedDeque mailbox, so it is akin to the current `IWithUnboundedStash` if you don't specify a custom mailbox type.
- `UnrestrictedStash` trait, which does not enforce any mailbox type. The proper mailbox *must* be configured
manually.
> Added support for `UnrestrictedStash`

- docs/articles/actors/untyped-actor-api.md
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka/Actor/UntypedActorWithStash.cs
Added utility abstract classes for `UntypedActor`s that support stashing: 
- `UntypedActorWithStash`
- `UntypedActorWithUnboundedStash` 
- `UntypedActorWithUnrestrictedStash`
Depends on #6325
> Add API for UntypedActorWithStash types

- docs/articles/actors/receive-actor-api.md
- docs/articles/actors/untyped-actor-api.md
- docs/cSpell.json
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.verified.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommon.verified.txt
- src/core/Akka.Tests/Actor/Stash/ActorWithBoundedStashSpec.cs
- src/core/Akka/Actor/Stash/IWithBoundedStash.cs
- src/core/Akka/Actor/Stash/IWithStash.cs
- src/core/Akka/Actor/Stash/IWithUnboundedStash.cs
- src/core/Akka/Actor/Stash/IWithUnrestrictedStash.cs
- src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
- src/core/Akka/Actor/Stash/Internal/BoundedStashImpl.cs
- src/core/Akka/Actor/Stash/Internal/UnboundedStashImpl.cs
- src/core/Akka/Actor/Stash/Internal/UnrestrictedStashImpl.cs
- src/core/Akka/Actor/Stash/StashFactory.cs
- src/core/Akka/Actor/UntypedActorWithStash.cs
- src/core/Akka/Dispatch/Dispatchers.cs
- src/core/Akka/Dispatch/IRequiresMessageQueue.cs
- src/core/Akka/Dispatch/Mailbox.cs
- src/core/Akka/Dispatch/Mailboxes.cs
Backport:
- #6323
- #6325
- #6327
> [BACKPORT] Several stashing improvements (#6323, #6325 and #6327)

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
> Fixes FailChunkExecution does not handle `DbExceptions` wrapped in an `AggregateException`

- src/core/Akka.Tests/Routing/RoutingSpec.cs
- src/core/Akka/Routing/RouterConfig.cs
Fixes #6295 - this fixes a _very_ old bug in Akka.NET where any time a routee on a `Pool` router restarted, the default supervision directive on the router was set to `Escalate` which would cause _the router itself_ to restart and _kill all of the routees in the process_. I believe this was done as a result of misunderstanding what Escalate does and how it works. We now know better and this sets the supervision directive to `Restart`, which is the safe default we use for everything else.
> close #6295 - set default PoolRouter SupervisorStrategy to Restart

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllPersistenceIdsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/SqlReadJournal.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommonQuery.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommonQuery.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommonQuery.Net.verified.txt
Fixes #6365
* Change `Tell` to `Ask`
* Handle failures to maintain consistent actor receive state
> Fix PersistenceIdsPublisher hung on failure messages

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllPersistenceIdsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/SqlReadJournal.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommonQuery.verified.txt
Fixes #6365
Backport of #6374
* Fix PersistenceIdsPublisher hung on failure messages
* Downgrade failure messages from Warning to Info
* Update API Verify list
(Cherry-picked from d3b89da6faaf06b394382aad78e475982cded23f)
> [BACKPORT #6374] Fix PersistenceIdsPublisher hung on failure messages

- src/core/Akka.Tests/Actor/ActorTelemetrySpecs.cs
- src/core/Akka.Tests/Routing/RoutingSpec.cs
- src/core/Akka/Routing/RouterConfig.cs
Port of #6366
* close #6295 - set default PoolRouter SupervisorStrategy to Restart
* use the `SupervisionStrategy.DefaultStrategy`
* Fix unit test
* Change unit test to use RoundRobinPool router
(cherry-picked from ffd9a9e15e2841cabb7ac9e71db937c7ea320cbd)
> [PORT #6366] set default PoolRouter SupervisorStrategy to Restart

- RELEASE_NOTES.md
Version 1.5.0-alpha3 contains several bug fixes and new features to Akka.NET
* [Akka.TestKit: Remove Akka.Tests.Shared.Internal dependency](https://github.com/akkadotnet/akka.net/pull/6258)
* [Akka.TestKit: Added ReceiveAsync feature to TestActorRef](https://github.com/akkadotnet/akka.net/pull/6281)
* [Akka.Stream: Fix `IAsyncEnumerator.DisposeAsync` bug](https://github.com/akkadotnet/akka.net/pull/6296)
* [Akka: Add `Exception` serialization support for built-in messages](https://github.com/akkadotnet/akka.net/pull/6300)
* [Akka: Add simple actor telemetry feature](https://github.com/akkadotnet/akka.net/pull/6299)
* [Akka.Streams: Move Channel stages from Alpakka to Akka.NET repo](https://github.com/akkadotnet/akka.net/pull/6268)
* [Akka: Set actor stash capacity to actor mailbox or …
> Update RELEASE_NOTES.md for 1.5.0-alpha4 release

- src/core/Akka.TestKit.Tests/TestEventListenerTests/DeadLettersEventFilterTests.cs
- src/core/Akka.TestKit/EventFilter/TestEventListener.cs
Fixes #6316 
The problem was in TestEventListenerClass because it calls `ShouldFilter` for deadLetter twice - first time with real parameter type and the second one with string param. So, for tests with `DeadLetter<string>` it might became false positive.
> Fix of EventFilter.And from Akka.testKit when one parameter is string (#6316).

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Tests/Configuration/ConfigurationSpec.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Serialization/Serialization.cs
* created a setting property LogSerializerOverrideOnStart to reflect if warning should be logged or not
* updated default config to enable logging for this issue by default
* added property to the configuration specification
Fixes #6377
Allows to suppress the WARNING message about changes in the serializer settings.
Set the value in the config
`log-serializer-override-on-start = off`
to disable the logging of the message.
The default value is `on` to get notified at the first time and check if the change was by intention.
It is worth to mention that the solution has the shortcomming of a global enable/disable behavior. It would be nice to just mark the intended change (for example by …
> Fix for issue #6377

- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
Multiple xUnit types can be thrown here, so handle the base `xUnitException` and not `TrueException`.
> harden `ClusterLogVerboseSpec`

- src/core/Akka.Tests/Actor/ActorCellSpec.cs
harden racy `ActorCellSpec`s - also modernized these specs to use built-in `TestKit` methods and `async Task` unit tests.
> harden racy `ActorCellSpec`s

- src/core/Akka.Persistence.Tests/AtLeastOnceDeliverySpec.cs
fixed ordering assertion in `AtLeastOnceDelivery_must_warn_about_unconfirmed_messages`
`AtLeastOnceDeliveryActor`s inherently do no guarantee delivery order, especially when messages are sent to multiple destinations - therefore we should not enforce it in the assertions.
> Akka.Persistence.Tests: fixed ordering assertion in `AtLeastOnceDelivery_must_warn_about_unconfirmed_messages`

- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
- src/core/Akka.Streams.Tests/Dsl/HubSpec.cs
harden timing on racy Akka.Streams specs
> harden timing on racy Akka.Streams specs

- src/benchmark/Akka.Cluster.Benchmarks/Persistence/AtomicWriteBenchmark.cs
- src/benchmark/Akka.Cluster.Benchmarks/Program.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/Journal/WriteJournal.cs
- src/core/Akka.Persistence/Persistent.cs
Fixes #
As discussed in #5505 closure object creation for `WithCircuitBreaker<TResult>` was fixed. Also all local functions like `ProcessResults`, `ExecuteBatch`, `Resequence` was moved into class method because every call ends with closure object creation. 
For `AtomicWrite` linq methods was removed usage because it ends in memory allocation.
It shows good consumed memory performance for write journal critical path:
`JournalWriteBenchmarks`  - 4% lower.
`AtomicWriteBenchmark` - 25% lower
BenchmarkDotNet=v0.13.2, OS=macOS Monterey 12.5.1 (21G83) [Darwin 21.6.0]
Apple M1 2.40GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=7.0.101
[Host] : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT SSE4.2 …
> Fix persistence allocations #5505.

- src/benchmark/Akka.Benchmarks/EventStream/EventStreamBenchmarks.cs
Added some benchmarks to clock the throughput of the `EventStream` before we consider making some changes to it.
``` ini
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2486/21H2/November2021Update)
.NET SDK=7.0.100
[Host]     : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
Job-JPMJGS : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
```
|  Method |     Mean |    Error |   StdDev | Allocated |
|-------- |---------:|---------:|---------:|----------:|
| Publish | 54.90 ns | 0.498 ns | 0.441 ns |         - |
> added `EventStreamBenchmark`

- src/contrib/persistence/Akka.Persistence.Query.Sql/Akka.Persistence.Query.Sql.csproj
- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByPersistenceIdPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj.DotSettings
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryApi.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistenceSqlCommon.Net.verified.txt
All of the old SubscribeTo___ methods from the Akka.Persistence.Sql.Common journal implement some bad practices, i.e. not able to detect events published in other instances of the Akka.NET processes targeting the same journal. This method deletes them and marks the old queries in Sql.Common as `Obsolete`. Rewrote existing queries to poll the database rather than rely on in-memory events, which is the correct way to implement these.
Also: significantly reduces allocations and overheads for writes for all Akka.Persistence.Sql.Common implementations.
Related: https://github.com/akkadotnet/akka.net/issues/5522
> Delete unnecessary / bad Sql.Common.Journal subscriptions

- RELEASE_NOTES.md
- src/common.props
Version 1.5.0-beta1 contains **breaking API changes** and new API changes for Akka.NET.
**Breaking Changes: Logging**
In [https://github.com/akkadotnet/akka.net/pull/6408](https://github.com/akkadotnet/akka.net/pull/6408) the entire `ILoggingAdapter` interface was rewritten in order to improve extensibility and performance (logging is now 30-40% faster in all cases and allocates ~50% fewer objects for large format strings).
All of the changes made here are _source compatible_, but not _binary compatible_ - meaning that users and package authors will need to do the following:
* Add `using Akka.Event` in all files that used the `ILoggingAdapter` and
* Recompile.
> NOTE: you can use a [`global using Akka.Event` directive](https://devblogs.microsoft.com/dotnet/welcome-to-csharp-10/#global-usin …
> Akka.NET v1.5.0-beta1 Release notes

- src/core/Akka/Event/LogEvent.cs
The "K" formatting adds timezone information. "Z" for UTC, and "+/-7:00" for time offsets
> Add K to the DateTime format string to include TZ information

- src/core/Akka.Tests/Actor/CoordinatedShutdownSpec.cs
- src/core/Akka.Tests/Actor/SupervisorHierarchySpec.cs
- src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs
- src/core/Akka.Tests/Dispatch/MailboxesSpec.cs
- src/core/Akka.Tests/Event/LoggerSpec.cs
- src/core/Akka/Actor/ActorPath.cs
- src/core/Akka/Actor/Futures.cs
- src/core/Akka/Actor/IAutoReceivedMessage.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Actor/Props.cs
- src/core/Akka/Configuration/Config.cs
- src/core/Akka/Dispatch/Dispatchers.cs
- src/core/Akka/Dispatch/ThreadPoolBuilder.cs
- src/core/Akka/Event/ILoggingAdapter.cs
- src/core/Akka/Event/LogMessage.cs
- src/core/Akka/Event/StandardOutLogger.cs
- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/Routing/RoutedActorCell.cs
- src/core/Akka/Serialization/Serialization.cs
Cleaning up some build warnings.
> cleaned up build warnings

- src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs
Reintroduce `Dispose` and `AfterAll` method to `TestKit`
> [TESTKIT] Reintroduce old code and mark them obsolete

- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.Cluster.Tests.MultiNode/StressSpec.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Streams.Tests/Dsl/FlowRecoverSpec.cs
- src/core/Akka.Streams.Tests/Dsl/LastElementSpec.cs
- src/core/Akka.Streams.Tests/Dsl/PagedSourceSpec.cs
- src/core/Akka.Streams.Tests/Dsl/QueueSinkSpec.cs
- src/core/Akka.Streams.Tests/Dsl/UnfoldFlowSpec.cs
- src/core/Akka.Streams.Tests/Dsl/UnfoldResourceAsyncSourceSpec.cs
- src/core/Akka.Streams/Dsl/AccumulateWhileUnchanged.cs
- src/core/Akka.Streams/Dsl/Internal/GraphImpl.cs
- src/core/Akka.Streams/Dsl/LastElement.cs
- src/core/Akka.Streams/Dsl/PagedSource.cs
- src/core/Akka.Streams/Implementation/Sinks.cs
- src/core/Akka.Tests/Actor/Setup/ActorSystemSetupSpec.cs
- src/core/Akka/Actor/Setup/ActorSystemSetup.cs
- src/core/Akka/Util/Extensions/ObjectExtensions.cs
- src/core/Akka/Util/Option.cs
Fixes #4604
Hardens Option<T>
* Make `Option<T>` constructor throw an `ArgumentNullException` when null value is passed in
* Add a `Create` static method that returns a `None` when null is passed in
> Harden `Option<T>` by disallowing null value

- src/core/Akka.Streams.Tests/IO/TcpSpec.cs
Harden `Outgoing_TCP_stream_must_handle_when_connection_actor_terminates_unexpectedly`
> Fix racy Akka.Streams.IO.Tcp spec

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApprovePersistence.Net.verified.txt
- src/core/Akka.Persistence.Tests/Journal/ChaosJournal.cs
- src/core/Akka.Persistence/Eventsourced.Lifecycle.cs
- src/core/Akka.Persistence/Eventsourced.Recovery.cs
- src/core/Akka.Persistence/Eventsourced.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs
- src/core/Akka.Persistence/Journal/WriteJournal.cs
Fixes #5522
@F0b0s has already eliminated a ton of allocations from the journal - I'm addressing some more based on @to11mtm 's feedback. 
Include data from the [relevant benchmark](https://getakka.net/community/contributing/index.html#improve-performance) prior to this change here.
Include data from after this change here.
> Akka.Persistence: improve `AsyncWriteJournal` and `PersistentActor` performance

- RELEASE_NOTES.md
Version 1.5.0-beta2 contains **breaking API changes** and new API changes for Akka.NET.
* [Akka.Event: Add K to the DateTime format string to include TZ information](https://github.com/akkadotnet/akka.net/pull/6419)
* [Akka.TestKit: Reintroduce old code and mark them obsolete](https://github.com/akkadotnet/akka.net/pull/6420) - fixes major regression in Akka.TestKit.Xunit2 where we removed `IDipsoable` before. This PR reintroduces it for backwards compat.
* [Akka.Cluster.Sharding: clean its internal cache if region/proxy died](https://github.com/akkadotnet/akka.net/pull/6424)
* [Akka.Util: Harden `Option<T>` by disallowing null value](https://github.com/akkadotnet/akka.net/pull/6426)
* [Akka.Util: move `DateTime` / `TimeSpan` extension APIs out of Akka.Util and into …
> added v1.5.0-beta2 release notes

- src/contrib/persistence/Akka.Persistence.Query.Sql/reference.conf
Need to be able to run additional queries by default due to pagination being highly interleaved. `100` is a safe value according to our tests.
> Set `akka.persistence.query.journal.sql.max-concurrent-queries = 100` by default

- docs/community/contributing/api-changes-compatibility.md
Update documentation on adding `Obsolete` attibute on old public API
> Update `Obsolete` attribute guideline

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka/Routing/Broadcast.cs
- src/core/Akka/Routing/ConsistentHashRouter.cs
- src/core/Akka/Routing/RoundRobin.cs
- src/core/Akka/Routing/RouterConfig.cs
- src/core/Akka/Routing/ScatterGatherFirstCompleted.cs
All methods were obsolete since v1.1.0
> Remove obsolete methods from Akka.Routing

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
- src/core/Akka.Streams.Tests/ActorMaterializerSpec.cs
- src/core/Akka.Streams.Tests/Dsl/QueueSourceSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/ActorGraphInterpreterSpec.cs
- src/core/Akka.Streams/ActorMaterializer.cs
- src/core/Akka.Streams/Dsl/RunnableGraph.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
For instances where the `ActorSystem` can be used as the materializer, should use an `ActorSystem`-specific singleton.
> Use `ActorSystem` for `Materializer`

- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
close https://github.com/akkadotnet/akka.net/issues/6459
This was a very old (7-8 years old) workaround for a Mono bug - it's very likely no longer needed and that version of Mono probably doesn't exist much in the wild these days, now that .NET Core is x-plat.
> remove ancient Mono work-around in `ActorSystemImpl`

- src/core/Akka.Persistence.TCK/PluginSpec.cs
copy `Obsolete` attributes to Akka.Persistence.TCK - same changes as we made to the TestKit base classes for Xunit.
> copy `Obsolete` attributes to Akka.Persistence.TCK

- src/common.props
- src/core/Akka.TestKit/EventFilter/IEventFilterApplier.cs
- src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs
- src/core/Akka.TestKit/TestKitBase_AwaitConditions.cs
- src/core/Akka.TestKit/TestKitBase_Expect.cs
Fixing API issues reported in https://github.com/akkadotnet/akka.net/issues/6466
> fixed issues with `AwaitConditionAsync`

- RELEASE_NOTES.md
Version 1.5.0-beta3 contains **breaking API changes** and new API changes for Akka.NET.
* [Akka.Persistence.TCK: remove `IDisposable` from Akka.Persistence.TCK](https://github.com/akkadotnet/akka.net/pull/6465) - this hid methods from the `TestKit` base classes.
* [Akka.Remote: Make transport adapter messages public](https://github.com/akkadotnet/akka.net/pull/6469) - adds back public APIs from v1.4.
* [Akka.TestKit: fix accidental breaking changes in v1.5.0-beta3](https://github.com/akkadotnet/akka.net/issues/6466)
| 2 | 110 | 37 | Aaron Stannard |
| 1 | 253 | 7 | Gregorius Soedharmo |
> added v1.5.0-beta4 release notes

- src/core/Akka.Cluster/Cluster.cs
We used the `cluster.seed-node-timeout` property incorrectly in https://github.com/akkadotnet/akka.net/pull/6033 - that is a "how long did it take from me to hear back from a seed" setting, but we're using it like a "how much time do I have to join the cluster?" setting.
Added a function designed to give us at least 20s of leeway if the user does not provide a `CancellationToken` of their own.
If the user does provide their own `CancellationToken`, that should be the single source of truth for this operation - second-guessing it without own un-overridable timeout adds zero value.
> bug fix: timing regressions in `Cluster.JoinAsync` methods

- RELEASE_NOTES.md
Version 1.5.0-beta5 contains **breaking API changes** and new API changes for Akka.NET.
* [Akka.Cluster: Remove `JoinAsync` and `JoinSeedNodesAsync` default timeout values](https://github.com/akkadotnet/akka.net/pull/6473)
* [Akka.Event: expose `Args()` on `LogMessage`](https://github.com/akkadotnet/akka.net/pull/6472)
| 2 | 50 | 28 | Aaron Stannard |
| 1 | 22 | 32 | Gregorius Soedharmo |
> added v1.5.0-beta5 release notes

- docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
Upgrade documentation for Akka.Cluster.Sharding was incorrect and unnecessarily complicated. Corrected it.
> simplified Akka.Cluster.Sharding upgrade instructions for v1.5

- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
We were using the wrong state timeout value, which only gave us 2s to recover R-E data. We're now using the correct value.
Addresses part of #6478 but there's still an issue with shard backoff + recreation that isn't handled correctly.
> fix state update timeout for remember-entities

- docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
If you're not changing `state-store-mode` settings during the v1.5 upgrade, you have no downtime. Wanted to make that clear.
> Akka.Cluster.Sharding docs: clarifying migration details for unaffected users

- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka.Tests/Pattern/CircuitBreakerStressSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Util/Extensions/TaskExtensions.cs
- src/core/Akka/Util/Internal/AtomicState.cs
Might be related to #6106
The circuit breaker, in its current implementation, could give false positives (signal tasks as done when in reality they failed).
I ported the `CircuitBreakerStressSpec` and slightly modified it to make all tasks take longer than the CB's `CallTimeout`, so that all of them fail. Instead, by running the test you can see that they are all "marked" as succeeded (`DoneCount`).
Upon further inspection:
- The tasks indeed all failed with a `TimeException`, but the exception is swallowed by the `CallFail` method. This makes impossible to capture the `TimeException` outside the CB --as demonstrated by the `StressActor`.
- Because we are awaiting the task first, and only after it finishes we check whether it took longer than the `CallTimeout`, we could potentially be …
> Alternative implementation of `AtomicState` leveraging WaitAsync
