src/core/Akka.Tests/Actor/ActorProducerPipelineTests.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Actor/ActorCell.FaultHandling.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/ActorProducerPipeline.cs, src/core/Akka/Actor/ExtendedActorSystem.cs, src/core/Akka/Actor/Internals/ActorSystemImpl.cs, src/core/Akka/Actor/Stash/IActorStash.cs, src/core/Akka/Akka.csproj, src/core/Akka/Event/Logging.cs
cc #533
I've created `ActorProducerPipeline`, which accessible from `ExtendedActorSystem` (to be able to configure by plugins) and allows to inject custom hooks satisfying following interface:
```csharp
interface IActorProducerPlugin {
bool CanBeAppliedTo(ActorBase actor);
void AfterActorCreated(ActorBase actor, IActorContext context);
void BeforeActorTerminated(ActorBase actor, IActorContext context);
}
```
- **CanBeAppliedTo** determines if plugin can be applied to specific actor instance.
- **AfterActorCreated** is applied to actor after it has been instantiated by an `ActorCell` and before `InitializableActor.Init` method will (optionally) be invoked.
- **BeforeActorTerminated** is applied before actor terminates and before `IDisposable.Dispose` method will be invoked (for disposable …
=> Plugable actor creation pipeline + IDisposable action handling

src/core/Akka.FSharp/Akka.FSharp.fsproj, src/core/Akka.FSharp/FsApi.fs, src/core/Akka.FSharp/README.md, src/core/Akka/Actor/IActorContext.cs, src/core/Akka/Actor/Inbox.Actor.cs, src/core/Akka/Actor/Inbox.cs
I've exposed a `Watch/Unwatch` methods into separate `ICanWatch` interface. It's now implemented by `IActorContext`, `Inboxable` and F# actors. Since `Inboxable.Watch` had previously void as return type, now it returns actor reference (also have an `Unwatch` method, which was not present before). I've also removed a `watch` function from F# API (it has been replaced by `monitor`, mentioned below).
Also some of the F# modules (Configuration, Strategy) now require qualified access - calling their functions without module prefix was unclear and could result in enigmatic code i.e. `load` vs `Configuration.load`.
1. `Configuration.load()` - alias to `ConfigurationFactory.Load` method.
2. `monitor`/`demonitor` functions - similar to `Watch`/`Unwatch` (naming inspired by Erlang). Can operate …
=> F# API - README + more changes

src/core/Akka.Remote.Tests/RemoteRouterSpec.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Akka.csproj, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/Util/ISurrogate.cs
Made it possible to translate surrogate types back to the original type in the default json serializer.
This is a suggestion to solve the problems @Horusiath described in the gitter channel.
Any surrogate type implementing `ISurrogate` will be auto converted back after deserialization.
This could be useful for #556
=> Translate surrogate types back to original type after deserialization. prep for #556

src/Akka.Persistence.FSharp/Akka.Persistence.FSharp.fsproj, src/Akka.Persistence.FSharp/FsApi.fs, src/Akka.Persistence.FSharp/Script.fsx, src/Akka.sln, src/PersistenceExample.FsApi/App.config, src/PersistenceExample.FsApi/PersistenceExample.FsApi.fsproj, src/PersistenceExample.FsApi/Program.fs, src/PersistenceExample.FsApi/packages.config, src/core/Akka.FSharp/FsApi.fs, src/core/Akka.Persistence/Eventsourced.cs, src/core/Akka.Persistence/Persistence.cs, src/core/Akka.Persistence/PersistentView.cs, src/examples/FSharp.Api/packages.config, src/packages/repositories.config
I've just initialized a new F# plugin for Akka.Persistence. At the present moment it introduces basic concepts for persistent actors and views (guaranteed delivery still not covered). It's still a proof of concept - definitely not for releasing purposes. Sample project showing API features is available under `/Examples/Persistence/PersistenceExample.FsApi` path.
- `Persistence.DefaultConfig()` included as default fallback for plugin-related configuration (no need to call it explicitly on `ActorSystem.Create`).
- Changed encapsulation for particular fields to make them available for F# plugin perspective.
=> Akka.Persistence: minor changes + F# plugin init

src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
cc #553
This implementation uses new `ISurrogate` interface for object serialization with custom JsonConverter dedicated for the `ActorPath` class and it's derivatives. Unit test attached.
=> Serializable ActorPath using ISurrogate interface

src/core/Akka.Cluster.Tests/MultiNode/ConvergenceSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared.Tests/Akka.MultiNodeTestRunner.Shared.Tests.csproj, src/core/Akka.MultiNodeTestRunner.Shared.Tests/TestRunShutdownSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/ConsoleMessageSinkActor.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/FileSystemMessageSinkActor.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSinkActor.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/Messages.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/SinkCoordinator.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TestCoordinatorEnabledMessageSink.cs
Fixed both issues. Now we get reporting like this at the end of the test run:
[RUNNER][11:17 PM]: Test run completed in [00:09:05.5357386] with 3/6 specs passed.
[RUNNER][11:17 PM]: Results for Akka.Cluster.Tests.MultiNode.ClusterDeathWatchMultiNode.ConvergenceSpecTests
[RUNNER][11:17 PM]: Start time: 2/6/2015 11:08:33 PM
[RUNNER][11:17 PM]:  --> Node 1: PASS [00:00:23.6013804 elapsed]
[RUNNER][11:17 PM]:  --> Node 2: PASS [00:00:23.6613864 elapsed]
[RUNNER][11:17 PM]:  --> Node 3: PASS [00:00:23.6613864 elapsed]
[RUNNER][11:17 PM]:  --> Node 4: PASS [00:00:23.5403777 elapsed]
[RUNNER][11:17 PM]:  --> Node 5: PASS [00:00:23.6343846 elapsed]
[RUNNER][11:17 PM]: End time: 2/6/2015 11:09:00 PM
[RUNNER][11:17 PM]: FINAL RESULT: PASS after 00:00:26.5915572.
[RUNNER][11:17 PM]: Results for …
=> MultiNodeTestRunner fixes for #593 and #594

src/core/Akka.Cluster/ClusterSettings.cs, src/core/Akka.Remote/RemoteWatcher.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Deploy.cs, src/core/Akka/Actor/Props.cs, src/core/Akka/Actor/RemoteScope.cs, src/core/Akka/Actor/SupervisorStrategy.cs, src/core/Akka/Configuration/Config.cs, src/core/Akka/Configuration/Hocon/HoconObject.cs, src/core/Akka/Configuration/Hocon/HoconRoot.cs, src/core/Akka/Configuration/Hocon/HoconSubstitution.cs, src/core/Akka/Configuration/Hocon/HoconValue.cs, src/core/Akka/Routing/Broadcast.cs, src/core/Akka/Routing/ConsistentHash.cs, src/core/Akka/Routing/Resizer.cs, src/core/Akka/Routing/RoundRobin.cs, src/core/Akka/Routing/RouterConfig.cs, src/core/Akka/Routing/ScatterGatherFirstCompleted.cs, src/core/Akka/Routing/SmallestMailbox.cs, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/Util/ISurrogate.cs
This is for discussion and review and yakshaving for #547 and #573 and #569 
Added JsonSerializer support for private constructors and private setters
Added Equality members to Akka primitives
Added Serialization tests for Akka primitives
Added Serialization support for `Config`, seems to work, but need extensive testing,
Added Serialization support for `Props` , seems to work, but need extensive testing,
The currently largest issue is the implementation of `SupervisorStrategy`, we use a delegate to deal with exception evaluation, this does not serialize.
The only option I can think of is to replace this with a KVP -> exception type + directive and serialize that instead.
All tests pass, but we need more eyes and extensive testing,
cc @akkadotnet/developers.
=> Improving serialization support

src/core/Akka.Cluster.Tests/MultiNode/ClusterDeathWatchSpec.cs, src/core/Akka.Cluster.Tests/MultiNode/ConvergenceSpec.cs, src/core/Akka.Cluster.Tests/MultiNode/MultiNodeClusterSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/SinkCoordinator.cs, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
added muting capabilities for MultiNodeClusterSpec
able to capture exit code as signal for test pass
close #597 
Long story short, whenever `Controller.Exit` was called to simulate a node unexpectedly leaving a cluster during a `MultiNodeSpec` we never recorded an explicit PASS / FAIL value for that node and assumed silent failure.
Turns out that the `Controller` has been correctly setting the `Process.ExitCode` for each individual node in accordance with whether or not it passed its spec. The `SinkCoordinator` now captures this value inside the MultiNodeTestRunner and correctly reports failures / passes based on the exit code.
=> added asserts for MultiNodeSpec properties

src/core/Akka.Cluster.Tests/FailureDetectorPuppet.cs, src/core/Akka.Cluster.Tests/MultiNode/ClusterDeathWatchSpec.cs, src/core/Akka.Cluster.Tests/MultiNode/MultiNodeClusterSpec.cs, src/core/Akka.Cluster/ClusterActorRefProvider.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.NodeTestRunner/Program.cs, src/core/Akka.Remote.TestKit.Tests/Akka.Remote.TestKit.Tests.csproj, src/core/Akka.Remote.TestKit.Tests/packages.config, src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj, src/core/Akka.Remote.TestKit/Conductor.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote.TestKit/packages.config, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/RemoteWatcher.cs, src/core/Akka.Remote/Remoting.cs, src/core/Akka.Remote/packages.config, src/core/Akka.TestKit/TestLatch.cs, src/core/Akka/Actor/ActorPath.cs, src/examples/FSharp.Deploy.Local/App.config, src/examples/FSharp.Deploy.Remote/App.config, src/examples/TimeServer/TimeClient/TimeClient.csproj, src/examples/TimeServer/TimeClient/packages.config
close #602 
`ClusterRemoteWatcher` is now fully covered per the original `ClusterDeathWatchSpec`.
Unearthed some bugs as part of this unit test and fixed them accordingly:
* Found a race condition that resulted in unhandled errors within Helios during periods of rapid successive calls to `Disconnect`. Pushed a new version of Helios, v1.3.6, with fixes for this and referenced it throughout Akka.NET.
* `RemoteWatcher` was incorrectly deployed under the `/user/` actor hierarchy. It now lives happily under `/system/`
* `AddressTerminated` did not correctly fire within `RemoteWatcher`
* Fixed a couple sources of exceptions within `Conductor` inside the Akka.Remote.TestKit
* Added some equality members and implicit case operators to `ActorPath.Surrogate` so it can be used inside …
=> ClusterDeatchWatchSpecs now pass

RELEASE_NOTES.md, build.fsx, src/SharedAssemblyInfo.cs, src/contrib/dependencyInjection/Akka.DI.AutoFac/Akka.DI.AutoFac.csproj, src/contrib/dependencyInjection/Akka.DI.AutoFac/Akka.DI.AutoFac.nuspec, src/contrib/dependencyInjection/Akka.DI.AutoFac/Properties/AssemblyInfo.cs, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Akka.DI.CastleWindsor.csproj, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Akka.DI.CastleWindsor.nuspec, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Properties/AssemblyInfo.cs, src/contrib/dependencyInjection/Akka.DI.Core/Akka.DI.Core.csproj, src/contrib/dependencyInjection/Akka.DI.Core/Akka.DI.Core.nuspec, src/contrib/dependencyInjection/Akka.DI.Core/Properties/AssemblyInfo.cs, src/contrib/dependencyInjection/Akka.DI.Ninject/Akka.DI.Ninject.csproj, src/contrib/dependencyInjection/Akka.DI.Ninject/Akka.DI.Ninject.nuspec, src/contrib/dependencyInjection/Akka.DI.Ninject/Properties/AssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.Persistence.FSharp/Akka.Persistence.FSharp.fsproj, src/core/Akka.Persistence.FSharp/Akka.Persistence.FSharp.nuspec, src/core/Akka.Persistence.TestKit/Akka.Persistence.TestKit.csproj, src/core/Akka.Persistence.TestKit/Akka.Persistence.TestKit.nuspec, src/core/Akka.Persistence.TestKit/Properties/AssemblyInfo.cs, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Persistence/Akka.Persistence.nuspec, src/core/Akka.Persistence/Properties/AssemblyInfo.cs, src/core/Akka/Actor/Props.cs
__Dependency Injection support for Ninject, Castle Windsor, and AutoFac__. Thanks to some amazing effort from individual contributor (**[@jcwrequests](https://github.com/jcwrequests "@jcwrequests")**), Akka.NET now has direct dependency injection support for [Ninject](http://www.ninject.org/), [Castle Windsor](http://docs.castleproject.org/Default.aspx?Page=MainPage&NS=Windsor&AspxAutoDetectCookieSupport=1), and [AutoFac](https://github.com/autofac/Autofac).
Here's an example using Ninject, for instance:
// Create and build your container 
var container = new Ninject.StandardKernel(); 
container.Bind().To(typeof(TypedWorker)); 
container.Bind().To(typeof(WorkerService));
// Create the ActorSystem and Dependency Resolver 
var system = ActorSystem.Create("MySystem"); 
var propsResolver = …
=> Akka.NET v0.8 Stable Release (dev)

src/Akka.Persistence.FSharp/app.config, src/benchmark/PingPong/PingPong.csproj, src/benchmark/PingPong/packages.config, src/core/Akka.FSharp/app.config, src/core/Akka.MultiNodeTestRunner.Shared/Akka.MultiNodeTestRunner.Shared.csproj, src/core/Akka.MultiNodeTestRunner.Shared/packages.config, src/core/Akka.Persistence.FSharp/Akka.Persistence.FSharp.fsproj, src/core/Akka.Persistence.FSharp/app.config, src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj, src/core/Akka.Remote.TestKit/packages.config, src/core/Akka/Akka.csproj, src/core/Akka/packages.config, src/examples/FaultTolerance/FaultTolerance.csproj, src/examples/FaultTolerance/packages.config, src/packages/repositories.config
We are currently using two different versions of Json.NET.
This PR makes all projects use the same version.
There was also an unused nuget ref to DataFlow, which have been removed.
Resolves #622
=> Resolved Json.NET version issues

src/.nuget/packages.config, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs, src/core/Akka.Persistence/packages.config, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka.Tests/packages.config, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Futures.cs, src/core/Akka/Actor/Scheduler.cs, src/core/Akka/Akka.csproj, src/core/Akka/Dispatch/ConcurrentQueueMailbox.cs, src/core/Akka/Dispatch/Dispatchers.cs, src/core/Akka/Dispatch/GenericMailbox.cs, src/core/Akka/Dispatch/SysMsg/SystemMessage.cs, src/core/Akka/Dispatch/TaskDispatcher.cs
Finally got the testrunners and fixed some broken Nuget references.
This PR gives us the ability to use async await for both Ask and other async operations when using the `TaskDispatcher`
It is completely separate from all other infrastructure so it does not affect other usecases.
How it works.
If an actor is configured with `.WithDispatcher("akka.actor.task-dispatcher"),`
It will dispatch all messages through the task dispatcher, which in turn places all relevant continuation state into the `LogicalCallContext` which makes it possible for state to flow async.
It also executes the mailbox using Tasks and applies an `ActorTaskScheduler` to manage all task execution within the current context.
=> Working async await ftw

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Futures.cs, src/core/Akka/Actor/GracefulStopSupport.cs, src/core/Akka/Dispatch/FutureActor.cs, src/core/Akka/Dispatch/SysMsg/SystemMessage.cs
This PR fixes some hard coupling between `FutureActorRef` and the new Async Await support.
`CompleteFuture` have been removed in favor for completing `TaskCompletionSource`'s inline.
Ask support have also been cleaned up to utilize more idiomatic handling of tasks.
=> Fix coupling between async await support and the rest of the framework

.gitignore, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ReceiveActor.cs, src/core/Akka/Dispatch/TaskDispatcher.cs
Added Receive API for tasks, that is, the receive actor can handle async receive methods correctly now.
Added more tests to verify that async behavior is correct
This PR makes the async await support handle exceptions correctly, so any exception thrown in a continuation/await block will be propagated to the supervisor.
=> Added exception handling to async await support

src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs, src/core/Akka.Persistence.Tests/PersistentViewSpec.cs, src/core/Akka.Remote.Tests/RemoteRouterSpec.cs, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Remote.Tests/Transport/ThrottlerTransportAdapterSpec.cs, src/core/Akka.Remote/Routing/RemoteRouterConfig.cs, src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs, src/core/Akka.Tests/Actor/InboxSpec.cs, src/core/Akka.Tests/Routing/ResizerSpec.cs, src/core/Akka.Tests/Routing/RoutingSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Dispatch/ConcurrentQueueMailbox.cs, src/core/Akka/Routing/ResizablePoolActor.cs, src/core/Akka/Routing/ResizablePoolCell.cs, src/core/Akka/Routing/Resizer.cs, src/core/Akka/Routing/RoutedActorCell.cs, src/core/Akka/Routing/RouterActor.cs, src/core/Akka/Routing/RouterConfig.cs, src/core/Akka/Routing/RouterMsg.cs, src/core/Akka/Routing/RouterPoolActor.cs, src/core/Akka/Util/AtomicBoolean.cs, src/core/Akka/Util/Internal/AtomicCounterLong.cs
brought RoutingSpec up to code with canonical Akka
adjusting timeouts on regularly crashing specs
added some GC collect statements
cleaned up AtomicBool usages inside ResizablePoolCell
marked all PersistentViewSpecs as SKIP = FIXME
forced RemoteRouterSpec to load timeout data from config
decreased retry gate time for RemoteRouterSpec
brought resizers and pool routers up to code
fixing some issues with ResizerSpec
included sys messages in GetNumberOfMessages count inside ConcurrentQueueMailbox
adjusted values on ResizerSpec
=> Fixed a bunch of failing specs

documentation/wiki/What is Akka.md
Closes #653. Added both the Apache 2 and explainer link.
=> Add links to Apache license and explainer

src/core/Akka.Tests/Routing/ResizerSpec.cs, src/core/Akka/Routing/Resizer.cs
Figured out the fundamental issue with the ResizerSpecs - there's a tiny amount of mailbox pressure that happens at the very beginning of each actor being created: the mailboxes start with a status of busy. The Resizer detects this and increases capacity.
If you pause for a short amount of time (after all of the mailbox create / ActorCell wireup is done) the pressure values appear to return to normal.
Going to test this theory with a PR
=> added small pause for mailbox init overhead (ResizerSpec)

src/core/Akka/Actor/ReceiveActor.cs, src/core/Akka/Dispatch/TaskDispatcher.cs
Updated async await support to give correct exception stacktraces instead of throwing `AggregateException`
=> Async Await stacktraces fix

src/core/Akka.TestKit.Tests/TestActorRefTests/BossActor.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/SupervisorStrategy.cs
Added decider type that replaces the decider lambda
Added Decider serialization spec
Added SupervisorStrategy Serialization spec
Added Decider DSL
PR for #665 
Serializable Deciders can now be created like this:
```csharp
var decider = Decider.From(
Directive.Restart,
Directive.Stop.When<ArgumentException>(),
Directive.Stop.When<NullReferenceException>());
```
Old lambda support is still valid but not serializable.
=> Serializable supervisor

src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj, src/core/Akka.Cluster.Tests/MultiNode/JoinSeedNodeSpec.cs, src/core/Akka.Cluster.Tests/MultiNode/MultiNodeClusterSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared.Tests/ParsingSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunCoordinator.cs, src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunTree.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/SinkCoordinator.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TestCoordinatorEnabledMessageSink.cs, src/core/Akka.MultiNodeTestRunner/Program.cs
close #610
close #635
Also adds the `JoinSeedNodeSpec` to the Akka.Cluster MultiNodeSpecs.
=> Fixes ParseSpec for non-US cultures 

src/core/Akka.FSharp/FsApi.fs, src/core/Akka.FSharp/README.md
I've created a new method: `maiblox.Defer (unit -> unit)`, which takes a function and defers it's execution until actor's `PostStop` will be invoked. This way we may specify a set of operations, which have to be ensured to be executed no matter how actor will end it's lifecycle.
This is especially important when dealing with `IDisposable` resources.
cc #677
=> F# API: added mailbox.Defer

src/core/Akka/Actor/ActorSelection.cs, src/core/Akka/Actor/AutoReceivedMessage.cs, src/core/Akka/Dispatch/SysMsg/SystemMessage.cs, src/core/Akka/Dispatch/TaskDispatcher.cs
cc #72
Hope this will close the case.
=> Added meaningful ToString() to all system messages

src/core/Akka/Actor/ChildrenContainer/Internal/ChildStats.cs
Reverts akkadotnet/akka.net#689
PR #689 has altered the algorithm. Unfortunately it introduced several bugs, and needs to be reverted, as support for negative values have been completely removed. 
The values for `maxNrOfRetries` and `withinTimeMilliseconds` are specified when creating `AllForOneStrategy` and `OneForOneStrategy`. From the docs for these constructors:
-- `maxNrOfRetries`: the number of times a child actor is allowed to be restarted, negative value means no limit, if the limit is exceeded the child actor is stopped.
-- `withinTimeMilliseconds`: duration in milliseconds of the time window for maxNrOfRetries, negative values means no window.
#689 made these calls do the incorrect thing:
``` C#
RequestRestartPermission(-1,-1)
RequestRestartPermission(10,-1) …
```
=> Revert "Refactor childStats requestRestartPermission algorithm"

CONTRIBUTING.md
A PR should always be justified. 
As a few PR lately have slipped through without any description at all, except a title saying "Refactor Xyz" I thought it could be useful to have a paragraph we could point contributors to.
Maybe a native English speaker could have a look at what I've written. :)
=> Add info on Title and Description for a PR in CONTRIBUTING.md

src/core/Akka/Actor/ActorCell.Children.cs
This reverts parts of commit a43580322ec573e9e5259ef6e885e45fd601ad1e.
The previous version was optimized for the most common scenario, when `exceptFor == null`.
The LINQ expression introduced in #691 is creating a list every time and uses more enumerators. It also makes a call to `List<T>.Contains()` when we know it's not necessary.
Normally LINQ expression can make loops more readable, bu in this case, and it might come down to a matter of taste, I don't think the LINQ version was more readable.
=> Revert parts of #691 "refactor suspend children"

src/core/Akka/Actor/IActorContext.cs
Just adds some docs to `Watch` & `Unwatch`
=> Add documentation to Watch & Unwatch

src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote.Tests/Transport/GenericTransportSpec.cs
Hello,
please review this PR. It contains implementation of issue #624 "port GenericTransportSpec". Since GenericTransportSpec is an abstract class I've tested it on my local dev-box using following code:
```csharp
public class TestSpec : GenericTransportSpec
{
public TestSpec() : base(withAkkaProtocol: true) { }
protected override string SchemeIdentifier { get { return "akka"; } }
protected override Akka.Remote.Transport.Transport FreshTransport(TestTransport testTransport)
{
return testTransport;
}
}
```
=> #624 port GenericTransportSpec

src/core/Akka.Persistence/GuaranteedDelivery.cs, src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs, src/core/Akka.Remote.TestKit/Controller.cs, src/core/Akka.Remote/AckedDelivery.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/RemoteTransport.cs, src/core/Akka.Remote/Transport/AkkaPduCodec.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/FailureInjectorTransportAdapter.cs, src/core/Akka.Remote/Transport/Transport.cs, src/core/Akka/Actor/Exceptions.cs, src/core/Akka/Actor/Stash/StashOverflowException.cs, src/core/Akka/Configuration/ConfigurationException.cs, src/core/Akka/Pattern/IllegalStateException.cs
Hi, please review this pull request. 
Now exceptions derived from ```AkkaException``` have serialization constructor. This should resolve issue #701
=> #701 add serialization constructor to exceptions

build.fsx, src/core/Akka.Cluster/ClusterDaemon.cs
Fixed FAKE such that it passes arguments to NuGet.exe in the correct order now.
Also have a random fix that removes a debug statement I forgot to strip earlier when debugging my previous PR :\
=> close #619 (fixes FAKE NuGet publish)

src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/Util/ISurrogate.cs
This PR fixes a few issues with serialization:
Integers, Floats and Decimals serialized into fields of type Object, now works as expected.
This also applies to other surrogated types that are contained within Object containers.
=> Integer, Float and Decimal serialization fix

src/core/Akka/Actor/Stash/Internal/AbstractStash.cs, src/core/Akka/Dispatch/BoundedDequeBasedMailbox.cs, src/core/Akka/Dispatch/DequeBasedMailbox.cs, src/core/Akka/Dispatch/MessageQueues/DequeWrapperMessageQueue.cs, src/core/Akka/Dispatch/UnboundedDequeBasedMailbox.cs
Fixed the DequeWrapperMessageQueue so it correctly calls EnqueueFirst per issue #482
CC @HCanber @rogeralsing could you take a look at the changes I made to `AbstractStash` and `DequeWrapperMessageQueue` and verify that the behavior is correct?
I reverse the contents of the `Stack` when we call `UnstashAll` and as a result none of the Remoting or Clustering tests were affected. Ran the MultiNodeTest suite on my local machine and got the same results as  before, so I think we're set.
=> Fixed the DequeWrapperMessageQueue so it correctly calls EnqueueFirst (#482)

documentation/akkadoc.shfbproj
Going to close this one pretty much right away - @sean-gilliam fixed the issue with SandCastle and Akka.TestKit. This just adds those binaries to the SandCastle build file.
=> added all TestKit projects to SandCastle

src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/Util/ISurrogate.cs
After battling Json.net for a while.
The smallest size of integer/float surrogates that can be stored in both object properties and object arrays is:
`{$value:"F123.456"}`
=> Smaller integer surrogates

src/core/Akka.MultiNodeTestRunner.Shared/Reporting/SpecRunCoordinator.cs, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ReceiveActor.cs, src/core/Akka/Actor/UntypedActor.cs, src/core/Akka/Akka.csproj, src/core/Akka/Dispatch/ActorTaskScheduler.cs, src/core/Akka/Dispatch/ConcurrentQueueMailbox.cs, src/core/Akka/Dispatch/GenericMailbox.cs, src/core/Akka/Dispatch/Mailbox.cs, src/core/Akka/Dispatch/SysMsg/SystemMessage.cs, src/core/Akka/Dispatch/TaskDispatcher.cs
This PR removes the need to use the special "task-dispatcher" for async await inside ReceiveActor.
If the receive handler is an async method, it will apply the correct scheduling mechanics for that handler only.
This PR also introduces the `RunTask` method inside `UntypedActor` (possibly it should be in `ActorBase`)
This method lets you run tasks within the ActorTaskScheduler.
This does however not address "reentrancy", messages can still be processed during await periods (but never in parallell)
But this could easily be handled by extending how RunActor behaves, e.g. an argument for if reentrancy is allowed or not, and if not, suspend the mailbox.
The idea behind `RunTask` is that it allows you to run any task, or multiple tasks, within the safety of the ActorTaskScheduler. this means …
=> Async Await support w/o performance hit and TypedActor/UntypedActor support

src/core/Akka.Persistence.FSharp/FsApi.fs, src/core/Akka.Persistence.TestKit.Tests/Cleanup.cs, src/core/Akka.Persistence.TestKit.Tests/LocalSnapshotStoreSpec.cs, src/core/Akka.Persistence.TestKit/Journal/JournalSpec.cs, src/core/Akka.Persistence.TestKit/Snapshot/SnapshotStoreSpec.cs, src/core/Akka.Persistence.Tests/GuaranteedDeliveryCrashSpec.cs, src/core/Akka.Persistence.Tests/GuaranteedDeliverySpec.cs, src/core/Akka.Persistence.Tests/Journal/ChaosJournal.cs, src/core/Akka.Persistence.Tests/PersistenceSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.Actors.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Persistence.Tests/PersistentViewSpec.Actors.cs, src/core/Akka.Persistence.Tests/PersistentViewSpec.cs, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Persistence/Eventsourced.cs, src/core/Akka.Persistence/GuaranteedDelivery.cs, src/core/Akka.Persistence/Journal/SyncWriteJournal.cs, src/core/Akka.Persistence/Persistent.cs, src/core/Akka.Persistence/PersistentActor.cs, src/core/Akka.Persistence/PersistentView.Lifecycle.cs, src/core/Akka.Persistence/PersistentView.Recovery.cs, src/core/Akka.Persistence/PersistentView.cs, src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs, src/core/Akka.Persistence/persistence.conf, src/core/Akka.TestKit/TestKitBase_Expect.cs, src/examples/PersistenceExample.FsApi/Program.fs
Change log:
1. Minor changes in F# Persistence API:
- Added `Defer` method from core F# actors API
- Renamed `Persist`, `AsyncPersist` and `Defer` to `PersistEvent`, `AsyncPersistEvent` and `DeferEvent` due to `Defer` method naming conflict with core F# API for `Defer` method.
2. Altered state machine for `PersistentView` - these changes mirror latest updates of canonical akka-persistence API: 
- Removed *PrepareRestart* state (it's logic has been moved to *ReplayFailed* state). 
- Moved update scheduler initialization from *ReplayStarted* state to `PreStart` method. Also it now uses new `ScheduledUpdate` message instead of `Update`. This message has a dedicated behavior in *Idle* state.
3. Better support for `LocalSnapshotStore`:
- Asynchronous tasks are now activated using Akka …
=> Akka persistence bugfixes

src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.cs
This PR creates the behavior stack with capacity 1, i.e. `new Stack<Receive>(1)` instead of the initial size 0.
It also makes the stack private and renames it.
The behavior stack will _always_ contain at least 1 item, as all actors, the first thing they do, is to call Become, which pushes an item to the stack.
On first call to `Become`, as the stack has 0 capacity, a new array with size 4 is created.
As most actors do not use `Become`-stacked to push more items on the stack, this means we're wasting bytes, and allocating an empty array that's not used for long.
If we create the behavior stack with initial size 1, we avoid the creation of a new array on the first `Become`-call and for most common case the underlying array isn't larger than it has to be.
This is really a micro optimization. …
=> Small optimization in ActorCell: Create behavior stack with size 1

src/core/Akka/Dispatch/Dispatchers.cs
This is proposition of generic dispatcher `Schedule` variation returning TPL task used for tracking completion status. I've found it a pretty useful, because sometimes I want to delegate action through Akka dispatcher but still be able to wait/continue/pipe work from it. 
It works with any type of dispatcher, also one not using TPL internally. 
@akkadotnet/developers What do you think about this?
=> Extension method for dispatcher returning task

src/core/Akka.Persistence.Tests/PersistentActorSpec.Actors.cs, src/core/Akka.Persistence/PersistentActor.cs, src/core/Akka.Tests/Actor/ActorBecomeTests.cs, src/core/Akka.Tests/Actor/DeathWatchSpec.cs, src/core/Akka.Tests/Actor/ReceiveActorTests_Become.cs, src/core/Akka.Tests/Actor/ReceiveActorTests_LifeCycle.cs, src/core/Akka/Actor/ActorBase.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/Dsl/Act.cs, src/core/Akka/Actor/IActorContext.cs, src/core/Akka/Actor/IUntypedActorContext.cs, src/core/Akka/Actor/ReceiveActor.cs, src/core/Akka/Actor/UntypedActor.cs
This is sort of a discussion and PR at the same time. :)
The api for using `Become` and the options to store or not store the latest handler on the stack is very strange.
It's very hard to understand what differs between these calls:
``` C#
Become(newHandler);
Become(newHandler, false);
Become(newHandler, true);
```
In fact two of the calls are equivalent. Can you see which two? 
Which stores the handler on the stack so you can restore it later?
The `IActorDsl` used for inline actors has always had `Become(handler)`, `BecomeStacked(handler)` and `UnbecomeStacked()`. It's much better.
I suggest we do the same everywhere, i.e. 
- Obsolete `Become(handler,bool)` and add `Become(handler)` and `BecomeStacked(handler)`
- Obsolete `Unbecome()` and add `UnbecomeStacked()`
And incidentally, it's …
=> BecomeStacked instead of Become?

src/core/Akka.Remote/RemoteDaemon.cs, src/core/Akka.Tests/Actor/SystemGuardianTests.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/BuiltInActors.cs, src/core/Akka/Dispatch/SysMsg/SystemMessage.cs
All I've done really is uncomment @HCanber's original code and added some tests.
I have added this
```csharp
// guardian MUST NOT lose its children during restart
protected override void PreRestart(Exception reason, object message)
{
}
```
to GuardianActor.
It isn't necessary for this PR but seemed sensible so I've added it.
Perhaps I should add this as a separate PR?
=> TerminationHooks, Close #327

src/core/Akka.Tests/Actor/PropsSpec.cs, src/core/Akka/Actor/Props.cs
I believe I found a tiny bug with unused strategy argument passed to Props.Create in Props.cs.
Tests demonstrate expected (at least by me) functionality - on upstream `Props_created_with_strategy_must_have_it_set` would not pass.
After merge both tests should pass.
=> Bugfix - unused supervisorStrategy in props create is fixed

build.fsx
adjusted the FAKE script to suppress all prompts, which caused my last attempted build on the build server to fail.
=> fixed bug with AzCopy in FAKE

documentation/akkadoc.shfbproj
Changed the URLs produced by SandCastle to be hashed member names instead of Guids... This means that if we link to the /stable/{url for ActorSystem} it will always be the same and not differ between verisons.
Also added LearnAkka.NET link in footer, next to the one that links back to getakka.net.
=> API docs: changed URLs to hashed member names

build.fsx
Needed to a set a flag to enable the correct MIME types to be set based on file extension with AzCopy for API docs.
=> fixed AzCopy MIME type encoding

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs
Hotfix for async await suspend-resume mailbox mechanics.
=> Fix for async await suspend-resume mechanics

src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/WindsorDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Core/DIActorContextAdapter.cs, src/contrib/dependencyInjection/Akka.DI.Core/DIActorProducer.cs, src/contrib/dependencyInjection/Akka.DI.Core/DIExt.cs, src/contrib/dependencyInjection/Akka.DI.Core/IDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs, src/contrib/dependencyInjection/Examples/BasicAutoFacUses/Actors.cs, src/contrib/dependencyInjection/Examples/BasicAutoFacUses/Program.cs, src/contrib/dependencyInjection/Examples/BasicCastleWindsorUse/Program.cs, src/contrib/dependencyInjection/Examples/BasicNinjectUses/Program.cs, src/contrib/dependencyInjection/Examples/BasicUnityUses/Program.cs
Based @rogeralsing  suggestion I removed the using a string to produce the actor and am instead using the type. This should resolve the issues with 832 & 833. @nvivo @danthar could you please check this version to see if it resolves your issues.  Thanks
=> Patch for Issues 832 & 833

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs
Another hotfix for async await.
Turns out when using the `Suspend` behavior and awaiting tasks that complete on IO completion ports, e.g. `Task.Delay` or IO operations, the current context was lost.
This PR fixes this.
=> Hotfix async await when awaiting IO completion port based tasks

src/core/Akka.FSharp/Schedulers.fs
This should fix an #831 issue. New implementations of `ScheduleTellOnce` and `ScheduleTellRepeatedly` are now ripped off from optional parameters - they provide a minimal set of parameters required by their previous versions, while more parametrized ones are still available from akka core `ITellScheduler` implementation.
=> removed ITellScheduler extensions from F# API

src/core/Akka.Remote/SystemNanoTime.cs, src/core/Akka/Dispatch/ConcurrentQueueMailbox.cs, src/core/Akka/Dispatch/GenericMailbox.cs
Stopwatch ticks are not the same as TimeSpan or DateTime ticks.
The `Stopwatch.ElapsedTicks` property retrieves raw timer ticks, which are of varying size depending on the capabilities of the system.  They are typically around 16 nanoseconds per tick on modern systems that have high frequency performance counters.  To use them directly, you have to consider the value of `Stopwatch.Frequency`.
It's easier just to use `Stopwatch.Elapsed`, which takes the frequency into account.  Then you can get the `Ticks` property from the resulting timespan, which will indeed have a fixed size of 100 nanos-per-tick.
So - one period changes everything  `ElapsedTicks` => `Elapsed.Ticks`.
:)
See also: https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.elapsedticks.aspx
=> Fix stopwatch ticks evalution

src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs, src/core/Akka.Tests/Actor/InboxSpec.cs, src/core/Akka.Tests/Routing/ResizerSpec.cs, src/core/Akka.Tests/Routing/TailChoppingSpec.cs, src/core/Akka/Actor/Inbox.cs
Adding this as a PR already to start testing on Akka's CI.
=> 853 Fixing racy tests

src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/WindsorDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Core/Extensions.cs, src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs
All the DI assemblies had the same implementation of an extension.
Refactored the extension and moved it to Akka.DI.Core.
=> Refactored common extension

src/core/Akka.Tests/Routing/ConsistentHashingRouterSpec.cs, src/core/Akka/Actor/ActorCell.DeathWatch.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/ActorState.cs, src/core/Akka/Akka.csproj
This PR is much like @HCanber's #766
It's for review and memory footprint optimization.
In this PR, the state found in `ActorCell.DeathWatch.cs` + the `_behaviorStack` has been abstracted out to a state container that by default only holds a `WatchedBy`, that is, it's parent.
All other state is lazily allocated if the actor needs more than that initial state.
The actor size have now gone from **1334** bytes to **1144**, which is about 16% less memory per actor.
Thoughts on this?
=> State container

src/core/Akka.Tests/Dispatch/DispatchersSpec.cs, src/core/Akka/Actor/ActorCell.FaultHandling.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Akka.csproj, src/core/Akka/Dispatch/AbstractDispatcher.cs, src/core/Akka/Dispatch/Dispatchers.cs, src/core/Akka/Dispatch/ForkJoinDispatcher.cs, src/core/Akka/Dispatch/SingleThreadDispatcher.cs, src/core/Akka/Dispatch/ThreadPoolBuilder.cs
resolves #850
Also added the following methods to all `MessageDispatcher` instances:
```csharp
/// <summary>
/// Attaches the dispatcher to the <see cref="ActorCell"/>
/// 
/// <remarks>
/// Practically, doesn't do very much right now - dispatchers aren't responsible for creating
/// mailboxes in Akka.NET
/// </remarks>
/// </summary>
/// <param name="cell">The ActorCell belonging to the actor who's attaching to this dispatcher.</param>
public virtual void Attach(ActorCell cell)
{
}
/// <summary>
/// Detaches the dispatcher to the <see cref="ActorCell"/>
/// 
/// <remarks>
/// Only really used in dispatchers with 1:1 relationship with dispatcher.
/// </remarks>
/// </summary>
/// <param name="cell">The ActorCell belonging to the actor who's deatching from this dispatcher.</param>
public …
```
=> PinnedDispatcher fixes + dispatcher teardown capabilities across all dispatchers

src/core/Akka.Tests/Actor/SupervisorHierarchySpec.cs, src/core/Akka.Tests/Routing/ConsistentHashingRouterSpec.cs, src/core/Akka.Tests/Routing/TailChoppingSpec.cs, src/core/Akka/Routing/TailChoppingRoutingLogic.cs
* fixed the race condition in ConsistentHashingRouterSpec.ConsistentHashingRouterMustAdjustNodeRingWhenRouteeDies
* fixed some timeout logic in the TailChoppingSpec
* fixed the TailChoppingRouterLogic use timeouts on the asks to cancel the overall request instead of scheduling another task
* made the child name unique for SupervisorHierarchySpec.A_supervisor_hierarchy_must_handle_failure_in_creation_when_supervision_strategy_returns_Resume_and_Restart to fix test
=> #853 Fixed some racy tests

src/core/Akka.Tests/Routing/RoutingSpec.cs
test Router_in_general_must_evict_terminated_routees
=>  #853 fixed race condition in RoutingSpec

src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs, src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs, src/core/Akka.Cluster.Tests/ClusterHeartBeatSenderStateSpec.cs, src/core/Akka.Cluster.Tests/EWMASpec.cs, src/core/Akka.Cluster.Tests/MetricsCollectorSpec.cs, src/core/Akka.Cluster.Tests/MultiNode/ClusterDeathWatchSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.Actors.cs, src/core/Akka.Persistence/Eventsourced.Lifecycle.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs, src/core/Akka.Persistence/Journal/SyncWriteJournal.cs, src/core/Akka.Persistence/PersistentView.Lifecycle.cs, src/core/Akka.Persistence/PersistentView.Recovery.cs, src/core/Akka.Remote/Transport/FailureInjectorTransportAdapter.cs, src/core/Akka.Tests/Actor/ActorDslSpec.cs, src/core/Akka.Tests/Actor/LocalActorRefProviderSpec.cs, src/core/Akka.Tests/Actor/Stash/ActorWithStashSpec.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/ActorRefProvider.cs, src/core/Akka/Actor/Address.cs, src/core/Akka/Actor/Scheduler/TaskBasedScheduler.cs, src/core/Akka/Dispatch/CachingConfig.cs, src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs, src/examples/PersistenceExample/ExamplePersistentActor.cs, src/examples/PersistenceExample/ExamplePersistentFailingActor.cs, src/examples/PersistenceExample/ExampleView.cs, src/examples/PersistenceExample/GuaranteedDeliveryExampleActor.cs, src/examples/PersistenceExample/SnapshotedExampleActor.cs
The compiler warnings are getting out of control with at least 102 in
HEAD. Most of these can be ignored since they look to be Obsolete tags
throwing the warnings. This PR reduces the number of warnings to 60.
=> Fixed a number of compiler warnings

src/core/Akka/Dispatch/Dispatchers.cs
Hey guys,
As you asked i've made a pull request for the issue. The reason why default thread-pool dispatcher doesn't work in .NetFiddle is that you are using `ThreadPool.UnsafeQueueUserWorkItem(wc, null);` in `ThreadPoolDispatcher` instead of `ThreadPool.QueueUserWorkItem(wc, null);` 
The main difference between these two calls is that `UnsafeQueueUserWorkItem` call doesn't check for Code Access Security(CAS), so it works a bit faster without these checks, but it requires FullTrust permissions. In .NetFiddle we can't allow to use FullTrust permissions as code executes on server, so logic that requires FullTrust doesn't work here.
In this pull request i've added check that is based on `AppDomain.CurrentDomain.IsFullyTrusted`, so if current AppDomain is FullTrusted, then the code will use …
=> QueueUserWorkItem vs UnsafeQueueUserWorkItem issue in .NetFiddle

src/core/Akka.Cluster.Tests/EWMASpec.cs, src/core/Akka.Cluster.Tests/MetricsCollectorSpec.cs
#867 inadvertently included a commit that introduced some recursive disposal calls in these two specs.
This undoes those changes and leaves a comment explaining why they're there.
=> fixed `IDisposable` calls on EMWASpec and MetricsCollectorSpec

src/core/Akka.Tests/Dispatch/MailboxesSpec.cs
The existing tests don't catch the ordering issue reported on #881, fixed on #882.
This adds a test with ordering values spanning through the Int32 range in order to ensure ordering is maintained with many ordering values.
=> Adds test to the MailboxesSpec to catch the issue fixed in #882

src/core/Akka.Tests/Dispatch/DispatchersSpec.cs, src/core/Akka/Dispatch/CachingConfig.cs, src/core/Akka/Dispatch/DispatcherConfigurator.cs, src/core/Akka/Dispatch/Dispatchers.cs, src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
Some files had redundant copyright notices in them. I removed the ones
that didn't follow the <copyright> convention.
I'm not sure about Helios.Concurrency.DedicatedThreadPool.cs though. So
I concat'ed the two notices together. If I could get a second opinion on that.
=> Removed redundant copyright notices

src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka/Actor/RepointableActorRef.cs
Modified the `RemotingSpec` in Akka.Remote.Tests to reproduce #884 - confirms that the reply back to an actor underneath a router can't be received.
=> added spec to confirm that #884 is reproducible

src/core/Akka/Actor/ActorCell.DeathWatch.cs
=> Fixed to notification on DeathWatch watching.

src/core/Akka/Actor/Futures.cs, src/core/Akka/Akka.csproj, src/core/Akka/Util/Internal/TaskExtensions.cs
=> Proposed fix for #886 asp.net deadlock

src/core/Akka/Actor/Scheduler/DateTimeNowTimeProvider.cs, src/core/Akka/Actor/Scheduler/ITimeProvider.cs, src/core/Akka/Actor/Scheduler/SchedulerBase.cs, src/core/Akka/Actor/Scheduler/TaskBasedScheduler.cs, src/core/Akka/Akka.csproj, src/core/Akka/Util/MonotonicClock.cs
=> Monotonic clock for #846

src/core/Akka.Tests/Routing/RoundRobinSpec.cs, src/core/Akka.Tests/Routing/SmallestMailboxSpec.cs, src/core/Akka/Routing/RoundRobin.cs, src/core/Akka/Routing/SmallestMailbox.cs
Per the suggestion from @Aaronontheweb (#909) bitmask Interlocked.Increment(ref _next)
to ensure that it will always be a positive number.
Also, added unit tests that verify this behavior (#910).
=> Attempts to resolve issue #908

src/core/Akka.TestKit/ActorCellKeepingSynchronizationContext.cs, src/core/Akka.TestKit/Akka.TestKit.csproj, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Dispatch/XUnitAsyncTestsSanityCheck.cs
This should restore current actor cell before calling continuation
=> SynchronizationContext for #907

RELEASE_NOTES.md, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs
**Bugfix release for Akka.NET v1.0.**
Fixes:
* [v1.0 F# scheduling API not sending any scheduled messages](https://github.com/akkadotnet/akka.net/issues/831)
* [PinnedDispatcher - uses single thread for all actors instead of creating persanal thread for every actor](https://github.com/akkadotnet/akka.net/issues/850)
* [Hotfix async await when awaiting IO completion port based tasks](https://github.com/akkadotnet/akka.net/pull/843)
* [Fix for async await suspend-resume mechanics](https://github.com/akkadotnet/akka.net/pull/836)
* [Nested Ask async await causes null-pointer exception in ActorTaskScheduler](https://github.com/akkadotnet/akka.net/issues/855)
* [Akka.Remote: can't reply back remotely to child of Pool router](https://github.com/akkadotnet/akka.net/issues/884)
* …
=> v1.0.1 release notes

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ReceiveActor.cs, src/core/Akka/Actor/UntypedActor.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
Removing all traces of async reentrancy.
=> Removed Reentrancy behavior

src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/Remoting.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs
I'm in the process of documenting how all of the Akka.Remote internals work in an effort to make it easier for multiple contributors to get involved in Akka.NET v1.1 and Akka.Cluster.
This is my first pass at adding some additional XML-DOC comments. I also cleaned up a couple of small to-dos here and there.
=> added some more descriptive comments to the remoting components

src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs
Added a null argument check for supervisor strategy inside ClusterPoolRouters - saw this come up inside the WebCrawler demo.
Made it so heartbeat timeouts get logged to the error log.
=> added clearer logging and validation to Remote / Cluster

src/core/Akka.Cluster.Tests/Routing/ClusterRouterSupervisorSpec.cs, src/core/Akka/Routing/RouterConfig.cs
Fixed a bug that caused clustered pool routers to have a null `SupervisoryStrategy` by default when loaded from configuration. Big problem if one of your routees under a clustered router dies :p
=> All Pool routers from configuration now use DefaultSupervisorStrategy

src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs
changed the HeliosTcpHandler so it reports disassociations for reasons unknown, which causes the EndpointManager to apply a less severe policy to the failed node and should allow for reconnects. This is equivalent to what the NettyTcpHandler does in JVM Akka.
fixed termination issue inside AkkaProtocolTransport - had improperly nested `PatternMatch` was responsible for throwing a null exception when trying to set an exception.
Related to #918
=> changed the HeliosTcpHandle to report disassociations for "unknown" reasons

.editorconfig, build.cmd
When I ran build.cmd, I encountered the shell asking for my id and password to access the corporate nuget repo. It's sensitive information and you wound't want to type in your passwords if you don't trust the script 100%. 
It happened because NuGet.exe install used the default NuGet.Config in %appdata%\Nuget. By specifying the given nuget.config in \src.nuget, we can avoid this issue.
=> Specify Nuget config to avoid accessing private NuGet repo

src/core/Akka.Persistence/Persistence.cs
cc #926
This PR for Akka.Persistence will allow to resolve different snapshot stores and journals depending on `SnapshotPluginId` and `JournalPluginId` values provided by persistent actors or views. This way we could handle multiple peristence providers inside single actor system.
This change is backward compatible.
=> Dynamic resolution of snapshot stores and journals

src/contrib/dependencyInjection/Akka.DI.Core/DIActorProducer.cs
Now returns the proper ActorType instead of the Type of the
depencyResolver.
=> Fix for DIActorProducer #941

build.fsx, src/Akka.sln, src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj, src/contrib/persistence/Akka.Persistence.Sql.Common/InternalExtensions.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryMapper.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Properties/AssemblyInfo.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/DbSnapshotStore.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryMapper.cs, src/contrib/persistence/Akka.Persistence.SqlServer.Tests/Akka.Persistence.SqlServer.Tests.csproj, src/contrib/persistence/Akka.Persistence.SqlServer/Extension.cs, src/contrib/persistence/Akka.Persistence.SqlServer/InternalExtensions.cs, src/contrib/persistence/Akka.Persistence.SqlServer/Journal/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.SqlServer/Journal/SqlServerJournal.cs, src/contrib/persistence/Akka.Persistence.SqlServer/Snapshot/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.SqlServer/Snapshot/SqlServerSnapshotStore.cs, src/core/Akka.MultiNodeTests/Akka.MultiNodeTests.csproj, src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- I've changed Akka.Persistence.SqlServer to use asynchronous/non-blocking version of the ADO.NET where it's possible. 
- This PR also introduces `Akka.Persistence.Sql.Common` - project which may be used for faster development of SQL-based persistence plugins.
- Minor bugfix for `AsyncWriteJournal` - issuse with null EventStream reference in task continuation on delete messages.
These changes should not break existing API.
=> Changes in Akka.Persistence SQL backend

src/core/Akka.Cluster.Tests/ClusterDomainEventPublisherSpec.cs, src/core/Akka.Cluster.Tests/ClusterDomainEventSpec.cs, src/core/Akka.Cluster.Tests/GossipSpec.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterEvent.cs, src/core/Akka.Cluster/ClusterReadView.cs, src/core/Akka.Cluster/Gossip.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs
=> Fixing up cluster rejoin behavior

build.fsx, src/Akka.sln, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/Akka.Persistence.PostgreSql.Tests.csproj, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/DbUtils.cs, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/PostgreSqlJournalSpec.cs, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/PostgreSqlSnapshotStoreSpec.cs, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/Properties/AssemblyInfo.cs, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/app.config, src/contrib/persistence/Akka.Persistence.PostgreSql.Tests/packages.config, src/contrib/persistence/Akka.Persistence.PostgreSql/Akka.Persistence.PostgreSql.csproj, src/contrib/persistence/Akka.Persistence.PostgreSql/Akka.Persistence.PostgreSql.nuspec, src/contrib/persistence/Akka.Persistence.PostgreSql/Extension.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/InternalExtensions.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Journal/PostgreSqlJournal.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Journal/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Journal/QueryMapper.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/PostgreSqlInitializer.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Properties/AssemblyInfo.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/README.md, src/contrib/persistence/Akka.Persistence.PostgreSql/Snapshot/PostgreSqlSnapshotStore.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Snapshot/QueryBuilder.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/Snapshot/QueryMapper.cs, src/contrib/persistence/Akka.Persistence.PostgreSql/packages.config, src/contrib/persistence/Akka.Persistence.PostgreSql/postgresql.conf
See issue #944
-Largely ported from Akka.Persistence.SqlServer plugin
-Event journal and snapshot store specs passing
-Added separate build task for PostgreSql tests
-Added initial draft of readme and nuspec file
-There is still one potentially unresolved issue pertaining to passing in a connection string to the test runner inside build.fsx.  Right now, I put the connection string (with credentials) in the app.config of the test project.  There is currently no way to pass in a custom connection string or custom credentials using the test runner inside build.fsx.  I was talking to @Aaronontheweb last week, and one of his suggestions was to create a "PersistenceTestRunner" that would modify the app.config before the tests are run.  I wanted to double check before I wrote a test runner. …
=> PostgreSQL persistence plugin for both event journal and snapshot store

src/core/Akka/Actor/PipeToSupport.cs
This feels like something I want to do.  Let me know if this is a bad idea and I won't be doing in my own code.
=> Add PipeTo for non-generic Tasks for exception handling

src/core/Akka/Configuration/Pigeon.conf
Updated default throughput values to conform with JVM and promote fairness amongst actors and tasks.
This means that 3 times more events will get through between mailbox runs. instead of mailbox hogging threads for long periods of time
=> Updated Pigeon.conf throughput values

src/core/Akka/Actor/Internals/ActorSystemImpl.cs, src/core/Akka/Actor/Scheduler/DedicatedThreadScheduler.cs, src/core/Akka/Akka.csproj
This is a PoC to see what happens when the scheduler runs on a dedicated thread.
When running with the TaskBasedScheduler (the default) and the thread pool gets flooded, Akka.Remote can no longer push Heartbeats through and endpoints gets disassociated.
When using this scheduler, the disassociation no longer occur.
I have tested this by letting the chat application spin up 600 blocking actors on a special command.
That turned out to delay Heartbeats by almost 40 seconds.
When running the new scheduler, everything works fine in my test.
=> Dedicated thread Scheduler

src/core/Akka.Tests/Actor/SupervisorStrategySpecs.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Actor/SupervisorStrategy.cs
In chaining to other constructors, the constructors for the `AllForOne` and `OneForOne` strategies pull timeouts from `TimeSpan`s using the `Milliseconds` property. This is not the correct behavior for `TimeSpan` values greater than or equal to 1 second as it provides only the milliseconds portion of the timespan. Instead, use the `TotalMilliseconds` property and cast it to an `int`.
=> Supervisor strategy bad timeouts

src/contrib/loggers/Akka.Logger.NLog/NLogLogger.cs, src/contrib/loggers/Akka.Logger.Serilog/SerilogLogMessageFormatter.cs, src/contrib/loggers/Akka.Logger.Serilog/SerilogLogger.cs, src/contrib/loggers/Akka.Logger.slf4net/Akka.Logger.slf4net.csproj, src/contrib/loggers/Akka.Logger.slf4net/Slf4NetLogger.cs
- added missing xmldoc comments to the contrib loggers
- file rename Slf4jLogger => Slf4NetLogger to match the class name
=> Missing xmldoc comments and typo fix

src/core/Akka/Akka.csproj, src/core/Akka/Event/EventStreamExtensions.cs
EventStream is one of the few pieces that don't have generic counterparts.
This patch allows for:
```cs
EventStream.Subscribe<SomeMessage>(Self);
EventStream.Unsubscribe<SomeMessage>(Self);
```
instead of
```cs
EventStream.Subscribe(Self, typeof(SomeMessage));
EventStream.Unsubscribe(Self, typeof(SomeMessage));
```
I was going to add these methods directly to EventStream, but it seems these generic versions are usually extensions methods. One caveat with the extension method is that most code don't require an `using Akka.Event`, so people may miss it entirely.
Please let me know if they should be moved.
=> Added generic extensions to EventStream subscribe/unsubscribe.

README.md
The old url seems not exists anymore.
=> Fix the url for Building Akka docs

src/contrib/dependencyInjection/Akka.DI.Core/Akka.DI.Core.csproj, src/contrib/dependencyInjection/Akka.DI.Core/DIActorContextAdapter.cs, src/contrib/dependencyInjection/Akka.DI.Core/DIActorSystemAdapter.cs, src/contrib/dependencyInjection/Akka.DI.Core/Extensions.cs, src/contrib/dependencyInjection/Akka.DI.Core/Readme.md, src/contrib/dependencyInjection/Examples/BasicAutoFacUses/Program.cs, src/contrib/dependencyInjection/Examples/BasicCastleWindsorUse/Program.cs, src/contrib/dependencyInjection/Examples/BasicNinjectUses/Program.cs, src/contrib/dependencyInjection/Examples/BasicUnityUses/Program.cs
Issue #965
Added a new class `DIActorSystemAdapter.cs` containing methods to extend the `ActorSystem` with an `ActorOf` (return an `IActorRef` similar to the `DIActorContextApapter` method) and `Props` (returns a `Props` object that can be further configure) method that use DI to create the Actor dependencies. 
Added a `Props` method to `DIActorContextAdapter.cs` similar to the `DIActorSystemAdapter` class one. 
Added a `DI()` extension method for `ActorSystem` in `Extensions.cs` that uses the `DIActorSystemAdapter` class.  
With these changes it is now possible to create `Props` and `Actors` on the `ActorSystem` level without having to use a `IDependencyResolver` implementation available or through `system.GetExtensions<DIExt>().Props` call. 
// get an Actor through DI directly from the …
=> Added Extensions methods to ActorSystem and ActorContext to make DI more accessible

src/core/Akka.TestKit.Tests/NoImplicitSenderSpec.cs, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka/Actor/ActorRef.cs
This PR makes it possible to explicitly pass null as `sender` to `Tell` as it is a fairly common mistake and we have no real reason to throw on it.
This PR also fixes some context leakage in the testkit
=> Convert null to NoSender.

build.fsx, src/Akka.sln, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/Akka.Persistence.Cassandra.Tests.csproj, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/CassandraIntegrationSpec.cs, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/CassandraJournalSpec.cs, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/CassandraSnapshotStoreSpec.cs, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/Properties/AssemblyInfo.cs, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/TestSetupHelpers.cs, src/contrib/persistence/Akka.Persistence.Cassandra.Tests/packages.config, src/contrib/persistence/Akka.Persistence.Cassandra/Akka.Persistence.Cassandra.csproj, src/contrib/persistence/Akka.Persistence.Cassandra/Akka.Persistence.Cassandra.nuspec, src/contrib/persistence/Akka.Persistence.Cassandra/CassandraExtension.cs, src/contrib/persistence/Akka.Persistence.Cassandra/CassandraPersistence.cs, src/contrib/persistence/Akka.Persistence.Cassandra/CassandraSettings.cs, src/contrib/persistence/Akka.Persistence.Cassandra/ExtensionMethods.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Journal/CassandraJournal.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Journal/CassandraJournalSettings.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Journal/JournalStatements.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Properties/AssemblyInfo.cs, src/contrib/persistence/Akka.Persistence.Cassandra/README.md, src/contrib/persistence/Akka.Persistence.Cassandra/SessionManagement/CassandraSession.cs, src/contrib/persistence/Akka.Persistence.Cassandra/SessionManagement/DefaultSessionManager.cs, src/contrib/persistence/Akka.Persistence.Cassandra/SessionManagement/IManageSessions.cs, src/contrib/persistence/Akka.Persistence.Cassandra/SessionManagement/SessionSettings.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Snapshot/CassandraSnapshotStore.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Snapshot/CassandraSnapshotStoreSettings.cs, src/contrib/persistence/Akka.Persistence.Cassandra/Snapshot/SnapshotStoreStatements.cs, src/contrib/persistence/Akka.Persistence.Cassandra/packages.config, src/contrib/persistence/Akka.Persistence.Cassandra/reference.conf
- Based partially on the great Scala version by Martin Krasser (https://github.com/krasserm/akka-persistence-cassandra)
- Modified from Scala version:
* Different schema for the Journal to try and avoid reading tombstones if using permanent deletions
* Ensures batches of writes in the Journal will only go to one partition to ensure atomicity and isolation
* Share ISession instance from DataStax driver across journal and session by default
* Make ISession resolution pluggable (allows for more advanced creation options and possible DI integration)
- Implementations for both Journal and Snapshot Store passing specs
- Readme with instructions for setup
- Separate task in build script for running tests
=> Cassandra persistence plugin (issue #987)

src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj, src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardCoordinator.cs
Finished porting recovery and command behavior (not-tested yet) for `ShardCoordinator`).
**NOTEL**: current Akka.Cluster seems not to have `ClusterShuttingDown` event which is used in sharding.
=> Port of ShardCoordinator

src/core/Akka.Cluster/ClusterMetricsCollector.cs, src/core/Akka.Persistence/AtLeastOnceDelivery.cs, src/core/Akka.Persistence/Snapshot/SnapshotStore.cs, src/core/Akka.Remote/Deadline.cs, src/core/Akka.Tests/Actor/ActorSystemSpec.cs, src/core/Akka.Tests/Actor/InboxSpec.cs, src/core/Akka/Actor/ChildrenContainer/Internal/ChildStats.cs, src/core/Akka/Actor/Inbox.Actor.cs, src/core/Akka/Actor/Inbox.cs, src/core/Akka/Event/LogEvent.cs, src/examples/TimeServer/TimeServer/Program.cs
#846
In some cases (like Akka.Persistence) it seems that some long-term timestamp is needed, not ephemeral one (which monotonic clock is), so there I've replaced  `DateTime.Now` with `DateTime.UtcNow`, which should be safe but still improve things regarding daylight saving transitions.
I think that current time offset is irrelevant even for logging purposes, so I've replaced it there too.
=> Replaced DateTime.Now with DateTime.UtcNow/MonotonicClock

src/core/Akka/Event/ILoggingAdapter.cs, src/core/Akka/Event/LoggingAdapterBase.cs
I made a mistake on #947 - should not have approved the removal of the `ILoggingAdapter.Warn` method. Needs to stay in there until next major version upgrade per our change management rules around breaking changes.
=> Revert ILoggingAdapter Warn method removal

build.fsx
Reverting some earlier changes - not ready to release an Akka.Cluster or Akka.Persistence package without a -beta tag just yet.
=> added fix pre-release nuget package #s for Akka.Cluster, Akka.Persistence

src/core/Akka.Remote/RemoteActorRefProvider.cs
Replaces #1026 - includes some additional cleanup inside the RemoteActorRefProvider where the same error was made again (although that code was never used.)
=> close #1025

RELEASE_NOTES.md
**Bugfix release for Akka.NET v1.0.1.**
Fixes & Changes - Akka.NET Core
* [Routers seem ignore supervision strategy](https://github.com/akkadotnet/akka.net/issues/996)
* [Replaced DateTime.Now with DateTime.UtcNow/MonotonicClock](https://github.com/akkadotnet/akka.net/pull/1009)
* [DedicatedThreadScheduler](https://github.com/akkadotnet/akka.net/pull/1002)
* [Add ability to specify scheduler implementation in configuration](https://github.com/akkadotnet/akka.net/pull/994)
* [Added generic extensions to EventStream subscribe/unsubscribe.](https://github.com/akkadotnet/akka.net/pull/990)
* [Convert null to NoSender.](https://github.com/akkadotnet/akka.net/pull/993)
* [Supervisor strategy bad timeouts](https://github.com/akkadotnet/akka.net/pull/986)
* [Updated Pigeon.conf throughput …
=> added release notes for v1.0.2 release

src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka/Actor/ActorRef.cs
Fixes for `NoSender` actor serialization bugs described in #1036.
=> Fixes for NoSender serialization bugs

RELEASE_NOTES.md
This ensures that the nightly builds produced by the build server have a higher version number than the current stable release.
=> added version number for next release of Akka.NET to RELEASE_NOTES for nightly build support

src/contrib/loggers/Akka.Logger.NLog/NLogLogger.cs
Currently, NLogLogger simply logs exception messages as strings. This commit passes the exception to NLog as well. This allows clients to use ${exception:...} layout renderers to choose if they want to log exception details (including stack traces) or not.
=> pass exception to NLogLogger exception logging

src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.TestKit.Tests/NoImplicitSenderSpec.cs, src/core/Akka.TestKit/INoImplicitSender.cs, src/core/Akka.TestKit/RealMessageEnvelope.cs, src/core/Akka.TestKit/TestActorRefBase.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/ActorRef.Extensions.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Message.cs, src/core/Akka/Serialization/Serialization.cs
Fixes for `NoSender` actor reference serialization bugs described in #1036.
`NoSender` actor reference is changed to `null` as discussed in #1037.
=> NoSender is changed to null (Fixes for NoSender serialization bugs)

src/core/Akka.Persistence/Journal/SyncWriteJournal.cs
`HandleReplayMessages` sometimes lose `Context`
=> akka persistence context bug

src/contrib/persistence/Akka.Persistence.SqlServer/Snapshot/QueryBuilder.cs, src/core/Akka.Persistence.TestKit/PluginSpec.cs
1. Fix on Akka.Persistence.SqlServer snapshot store query builder (thx to @Silv3rcircl3 for pointing that out).
2. Fix for Akka.Peristence.TestKit plugin counter - it has been made static. This way it should handle parallel test runs.
=> Akka.Persistence - SqlServer and TestKit fixes

src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryFailureSpec.cs, src/core/Akka.Remote.TestKit/Conductor.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/FailureInjectorTransportAdapter.cs, src/core/Akka/Actor/FSM.cs, src/core/Akka/Serialization/Serialization.cs
There are a few places where the log message is pre-formatted using string.Format and some random  place where the order of the format arguments are non-ordered.
This PR cleans that up.
=> Logging message/template fixes

src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/IO/TcpConnectionSpec.cs, src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs, src/core/Akka.Tests/IO/UdpIntegrationSpec.cs, src/core/Akka/Akka.csproj, src/core/Akka/IO/DatagramChannel.cs, src/core/Akka/IO/DirectByteBufferPool.cs, src/core/Akka/IO/Inet.cs, src/core/Akka/IO/SocketChannel.cs, src/core/Akka/IO/Udp.cs, src/core/Akka/IO/UdpConnected.cs, src/core/Akka/IO/UdpConnectedManager.cs, src/core/Akka/IO/UdpConnection.cs, src/core/Akka/IO/UdpListener.cs, src/core/Akka/IO/UdpManager.cs, src/core/Akka/IO/UdpSender.cs, src/core/Akka/IO/WithUdpSend.cs
Added the Akka IO UDP driver, including all tests.  
The UDP driver also uses Socket.Select and therefore has the same allocation issue as described in #1023.
=> Akka IO UDP driver port

src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs, src/core/Akka.Persistence/persistence.conf
New config value **akka.persistence.journal.async-proxy-replay-timeout** that can be used to set receive timeout (it was fixed 5sec before) on `ReplayMediator` actor used by `AsyncWriteProxy` journals.
=> HOCON config key for replay receive timeout for AsyncWriteProxy

src/core/Akka/Util/ByteString.cs
ByteStrings should create a new ByteIterator every time.
=>  Akka IO: fixes #1070 - StackOverflowException

src/core/Akka.Persistence.TestKit/Snapshot/SnapshotStoreSpec.cs
Related issue: #1067 . Until this PR, if none snapshot store was attached to the `SnapshotStoreSpec`, tests were run against default snapshot store (using local file system). Now this won't be a case - spec by default loads non-existing snapshot store, allowing all tests to fails if no implementation was provided.
=> SnapshotStoreSpec not implementing default snapshot store by default

build.fsx, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.MultiNodeTests/Routing/ClusterConsistentHashingGroupSpec.cs, src/core/Akka.MultiNodeTests/Routing/ClusterConsistentHashingRouterSpec.cs
Minor change, but going forward all multinodetests will run on build.
This is a big step towards getting 1.1 out the door.
=> Set multinodetests to run on 'all' builds

documentation/akkadoc.shfbproj
Documented namespaces.
Note: I put a TBD on Akka.Pattern since it looks like the only class in
that namespace could be put into another.
Note2: As mentioned in gitter chat, it looks like Akka.Actor.Internal
and Akka.Actor.Internals is an oversight and should be merged.
=> [api-doc] Documentation of namespaces

src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/IO/TcpConnectionSpec.cs, src/core/Akka.Tests/IO/TcpIntegrationSpec.cs, src/core/Akka/Configuration/Pigeon.conf, src/core/Akka/IO/SelectionHandler.cs, src/core/Akka/IO/TcpConnection.cs, src/core/Akka/IO/TcpOutgoingConnection.cs
The only outstanding tests remaining for IO are for the 2 utility classes: ByteString and ByteIterator. Test coverage for the IO namespace is now at 68%.
Fixed 4 bugs found with new tests.
cc #788
=> Akka IO: Ported TcpIntegrationSpec and missing tests in TcpConnectionSpec

src/contrib/testkits/Akka.TestKit.NUnit.Tests/Akka.TestKit.NUnit.Tests.csproj, src/contrib/testkits/Akka.TestKit.NUnit.Tests/TestKitTestFixtureTest.cs, src/contrib/testkits/Akka.TestKit.NUnit/TestKit.cs, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka.TestKit/TestKitBase_AwaitConditions.cs, src/core/Akka.TestKit/TestKitBase_Expect.cs, src/core/Akka.TestKit/TestKitBase_Receive.cs, src/core/Akka.TestKit/TestKitBase_Within.cs
I've made changes as outlined in #1065 to allow NUnit's TestKit to work in the same way as xunit.
Unlike xunit (and I think mstest), NUnit does not create a new instance of the test class for each test run.  If the user provides an ```ActorSystem``` in the constructor, all tests will attempt to use the same system, however after each test the system is destroyed.  One possible fix would be to take a ```Func<ActorSystem>``` instead, however that would introduce a breaking change to the API for all TestKit implementations and I wasn't sure how you'd feel about that.  Another option is simply to throw a ```NotSupportedException``` in the NUnit TestKit if the user provides an instance of ```ActorSystem```.
The NUnit TestKit has ```AfterAll(), Dispose(), and Dispose(bool disposing)``` methods, …
=> Fix for issue #1065 NUnit to destroy ActorSystem after each test run inline with XUnit

build.sh
Minor change to `build.sh` - installs the XUnit 2.0.0 test runner instead of the XUnit 1.9.2 runner.
=> upgraded version of XUnit test runner to 2.0.0 for Mono builds

src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs, src/core/Akka/Akka.csproj, src/core/Akka/Pattern/BackoffSupervisor.cs
**Ported from Akka JVM**: This is implementation of the exponential backoff algorithm for actor supervisors. It's useful in cases, when for example persistent actor fails due to underlying persistence mechanism failures or unavailability. In that case it's quite probable that in this case immediate restart of an actor will fail again. Solution is to apply some delay before restart.
This implementation uses exponential back-off i.e. given minimal back-off 3 sec. and maximal back-off 30 sec. the following start attempts will be delayed with 3, 6, 12, 24, 30 seconds. In addition back-off uses random delay multiplier configured by `randomFactor` variable (example 0.2 &rArr; 20%). Reason for that is to avoid hitting the persistence backend by all restarting actors at the same time.
**Don't …
=> Implemented BackoffSupervisor

src/core/Akka/Util/ByteString.cs
=> Akka IO: Fixes #1113 - ByteString1C indexer always returns first element

src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs
From reading the original code, it seems the intention was to use the cache in the case that `GetTypeValue()` assembly scanned. Unfortunately, this was always being evaluated which made the use of the cache pretty pointless.   This PR changes the implementation to `GetOrAdd`.
=> NinjectDependencyResolver should use GetOrAdd not TryAdd

src/core/Akka.Remote/Serialization/DaemonMsgCreateSerializer.cs
This fixes a bug in the remotedaemonmsgserializer that incorrectly passes ByteString as the type to the Deserialize method instead of RouterConfig
This bug **is not observable using our json.net serializer as it ignores the Type argument** and relies on Type manifest embedded in the json itself.
But if we replace the json serializer, the bug presents itself. (as in my bson PoC)
=> RemoteDaemonMsgSerializer bug fix

.gitignore
New version of NCrunch gives new guidance files.
As the old ones are in the gitignore I included .ncrunchsolution and .ncrunchproject.
=> adding the latest ncrunch files to gitignore

src/core/Akka/Util/Either.cs
**Construction**
Before:
```csharp
static Either<int, string> Foo(bool left)
{
if (left)
return new Left<int, string>(123);
else
return new Right<int, string>("321");
}
```
After (first variant is still supported):
```csharp
static Either<int, string> Bar(bool left)
{
if (left)
return Either.Left(123);
else
return Either.Right("123");
}
```
**Transformations**
```csharp
var either = new Left<int, string>(123);
return either.
.MapLeft(x => x + 1)
.MapRight(s => s.Substring(1))
.Map(x => x + 2, s => s + "123")
.Fold(x => x/2, s => s.Length);
```
=> Either usability improvements

src/core/Akka.FSharp.Tests/ApiTests.fs, src/core/Akka.MultiNodeTestRunner.Shared/Akka.MultiNodeTestRunner.Shared.csproj, src/core/Akka.MultiNodeTestRunner.Shared/packages.config, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Persistence/packages.config, src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj, src/core/Akka.Remote.TestKit/packages.config, src/core/Akka/Akka.csproj, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/packages.config, src/examples/FSharp.Api/FSharp.Api.fsproj, src/examples/FSharp.Api/packages.config, src/examples/FaultTolerance/FaultTolerance.csproj, src/examples/FaultTolerance/packages.config, src/examples/PersistenceExample.FsApi/PersistenceExample.FsApi.fsproj, src/examples/PersistenceExample.FsApi/packages.config
This PR introduces Json.NET and removes the old DU hacks we had in the serializer.
This closes: #1127 #1126 #999 #827
=> Json net 7

src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingFailureSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingGracefulShutdownSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingLeavingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/CustomShardAllocationSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterDaemon.cs
These are complete specs for Akka.Cluster.Sharding, including:
- ClusterShardingCustomAllocationSpec
- ClusterShardingFailureSpec
- ClusterShardingGracefulShutdownSpec
- ClusterShardingLeavingSpec
These are not yet passing tests. 
Also some changes in pub/sub for cluster messages (included listeners on MemberRemoved).
=> Completed rewriting Akka.Cluster.Sharding.Tests

src/contrib/loggers/Akka.Logger.Serilog/SerilogLogger.cs
With the previous implementation, SourceContext always gets a value of "Akka.Logger.Serilog.SerilogLogger". This sets it to the actor's path.
=> SourceContext value reported as a path of the logging actor

src/core/Akka.Remote.Tests/RemoteWatcherSpec.cs, src/core/Akka.Remote/AddressUidExtension.cs
This fixes a major bug in Akka.Remote where the `AddressUIDExtension` was generating a brand new UID for the calling `ActorSystem` each time it was invoked, which means that invalid handshake information could be sent under otherwise normal circumstances. I'm not sure what the real-world impact of this error is, but it's resolved now.
=> fixed bug where new ActorSystem UID was generated on every call

src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs
This is a new key for `JournalSettings` and `SnapshotStoreSettings` for persistence plugin based on SQL-backends to give users ability to specify their connection strings not only inside HOCON configs, but as references to <connectionStrings> sections of Web.config/App.config files as well. 
This will also need a corresponding update in Akka.Persistence.SqlServer and Akka.Persistence.PostgreSql in order to work - this PR only adds new common key for settings classes.
/cc #1107
=> New config setting akka.persistence.xyz.connection-string-name

build.fsx
Makes it impossible for us to have public projects that do NuGet releases currently. Omitted the NuGet API key from log messages.
=> removed NuGet key from FAKE messages

src/core/Akka.Tests/IO/TcpConnectionSpec.cs
It is difficult to reproduce this test failure. The only place where it fails regularly is on the CI server. 
This bug fix might resolve the issue, but I will monitor the builds and re-open the issue if it happens again.
=> Akka IO: fixes #1153

CONTRIBUTING.md, README.md, src/contrib/dependencyInjection/Akka.DI.AutoFac/Readme.md, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Readme.md, src/contrib/dependencyInjection/Akka.DI.Core/Readme.md, src/contrib/dependencyInjection/Akka.DI.Ninject/Readme.md, src/contrib/dependencyInjection/Akka.DI.StructureMap/Readme.md, src/contrib/dependencyInjection/Akka.DI.Unity/Readme.md, src/core/Akka.FSharp/README.md
There were some old links to the getakka wiki which doesn't exist
anymore. This PR fixed those links.
Also fixed a typo (specifiy -> specify).
Note: It looks like Atom.io got a little carried away with some of the
EOL formatting. :(
Note2: I didn't change the links in older entries of
RELEASE_NOTES.md since that's basically a historical record
of the software.
=> [docs] Fixed documentation links

src/core/Akka.Tests/Actor/AskTimeoutSpec.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Actor/Futures.cs, src/core/Akka/Actor/Settings.cs, src/core/Akka/Configuration/Pigeon.conf
This is an attempt to resolve #1163. Instead of defaulting to `null`, I wasn't sure on how that should be represented, it defaults to `infinite`. This should provided the same effective result.
=> Adds support for a default Ask timeout in HOCON conf.

src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
This removes a line of code used for debugging when we fixed the F# DU serialization problems earlier.
It sets the Json default settings, thus mutating shared state, resulting in racy code if anything else uses JsonConvert in our code, in our tests or **in external code**.
=> Removed debug code from earlier F# DU serialization fix

src/core/Akka.Persistence.TestKit.Tests/Akka.Persistence.TestKit.Tests.csproj, src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka/Configuration/ConfigurationFactory.cs, src/core/Akka/Configuration/Hocon/HoconObject.cs, src/core/Akka/Configuration/Hocon/HoconParser.cs, src/core/Akka/Configuration/Hocon/HoconSubstitution.cs, src/core/Akka/Configuration/Hocon/HoconToken.cs, src/core/Akka/Configuration/Hocon/HoconTokenizer.cs
Related to #1164 
* Added Hocon Include support
* Added Hocon include resolver support
* Added Hocon Include substitution support
* Added more Hocon tests
* Added HoconObject.Merge support
* Added Config from Object support (.NET object to Hocon Config)
This allows us to use Hocon includes:
```javascript
a {
include "some resource"
}
```
The 'some resource' can then be resolved by an optional resolver callback. so the resource could be a file on disk, an url, or whatever you want that could result in a new hocon sub config.
**see inline comments for explanations of the code to help the review**
=> Hocon include support

README.md
Added Waffle.IO badges & more info/guidelines about contributing. Also added Readme logo for TeamCity build support / OSS license.
=> Issue badges & more contribution guidelines

src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/SinkCoordinator.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TestCoordinatorEnabledMessageSink.cs, src/core/Akka.Remote/Transport/FailureInjectorTransportAdapter.cs, src/core/Akka/Actor/Futures.cs
This PR cleans up some of the broken bitwise operations used in the `ContinueWith`.
The cases that have been fixed is ones that use  `&` instead of `|` to combine `TaskContinuationOptions`, which always result in `TaskContinuationOptions.None`
=> TaskContinuationOptions bitwise fix

src/Akka.sln, src/benchmark/PersistenceBenchmark/App.config, src/benchmark/PersistenceBenchmark/Messages.cs, src/benchmark/PersistenceBenchmark/PerformanceActors.cs, src/benchmark/PersistenceBenchmark/PersistenceBenchmark.csproj, src/benchmark/PersistenceBenchmark/Program.cs, src/benchmark/PersistenceBenchmark/Properties/AssemblyInfo.cs, src/benchmark/PersistenceBenchmark/packages.config
It's based on persistence performance spec tests form Akka on JVM. However here it's working as a separate console application.
NOTE: total performance may vary depending on how many persistent actors are running in parallel (difference should be less significant in case of commandsourced tests).
cc #754
=> Basic Akka.Persistence benchmark application

src/core/Akka.Remote.TestKit/Conductor.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/Remoting.cs, src/core/Akka.Remote/Transport/TestTransport.cs, src/core/Akka.TestKit/AutoPilots.cs, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka.TestKit/TestKitSettings.cs, src/core/Akka/Actor/Props.cs, src/core/Akka/Configuration/Config.cs, src/core/Akka/Configuration/Hocon/HoconParser.cs, src/core/Akka/Configuration/Hocon/HoconTokenizer.cs, src/core/Akka/Event/StandardOutLogger.cs, src/core/Akka/IO/ByteBuffer.cs, src/core/Akka/IO/Tcp.cs, src/core/Akka/IO/TcpConnection.cs, src/core/Akka/IO/TcpManager.cs, src/core/Akka/IO/UdpConnectedManager.cs, src/core/Akka/IO/UdpManager.cs, src/core/Akka/Util/ByteIterator.cs
Reference #1192
This PR replaces the generic exceptions with more specific ones. This
should help make debugging easier for apps that work with Akka.NET.
=> Replaced generic exceptions with more specific ones

src/core/Akka.FSharp/Akka.FSharp.fsproj, src/core/Akka.FSharp/FsApi.fs, src/core/Akka.FSharp/packages.config
Ref #1206
I am new to both Akka and F#, so please go easy on me!
Per the referenced issue, Akka.FSharp is using an old version of FsPickler, which I have updated in this PR. The key change in the FsPickler API was the removal of overloads for `Serialize`/`Deserialize` taking a type as a method parameter; instead it is a generic parameter on the method. I made the few minor changes to account for this, hopefully they are idiomatic/appropriate.
I ran the F# tests by hand and they passed. I was also able to use the updated Akka.FSharp.dll in conjunction with Vagabond in an FSI session, which I was unable to do with the existing FsPickler.0.9.11-based version.
=> Update FsPickler version used by Akka.FSharp

src/core/Akka.Tests/Actor/ActorRefSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs
Resolves #1212 - any messages for a `null` Sender now to go `Deadletters`.
Added a spec to verify.
=> Fix for null sender #1212

src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj, src/core/Akka.FSharp.Tests/ApiTests.fs, src/core/Akka.FSharp/FsApi.fs, src/core/Akka.Persistence.FSharp/FsApi.fs, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
This should fix #999 . The issue was that F# actor applied pattern matching on the generic type in case when message was not fully deserialized (it was an intermediate representation in form of json.net `JObject`). In result any try of pattern matching was failing. 
This PR solves that problem by adding additional step - in case when we have a `JObject` instance passed it tries a build in `ToObject(type)` conversion and if it succeeds, pass the result to the actor's receive function.
=> FSharp API: fixed problem with JObject deserialization

src/core/Akka.MultiNodeTestRunner.Shared/NodeTest.cs, src/core/Akka.MultiNodeTestRunner/Discovery.cs, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.MultiNodeTests/MultiNodeFact.cs
#1088 MultiNode tests can now be skipped by specifying a SkipReason
I have learned that XUnit works in two phases - discovery of tests and execution of tests. 
The tests that are to be skipped are skipped during execution and not discovery. I believe this is because you would want to show a message that a test was not executed but skipped for a particular reason. Since MultiNodeTestRunner has its own test execution logic, a change was needed in that logic to skip the tests.
=> #1088 MultiNode tests can now be skipped by specifying a SkipReason

src/Akka.sln, src/core/Akka.TestKit/Akka.TestKit.csproj, src/core/Akka.TestKit/TestBreaker.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs, src/core/Akka/Akka.csproj, src/core/Akka/Pattern/CircuitBreaker.cs, src/core/Akka/Pattern/CircuitBreakerState.cs, src/core/Akka/Pattern/IllegalStateException.cs, src/core/Akka/Pattern/OpenCircuitException.cs, src/core/Akka/Util/Internal/AtomicState.cs
#147 
- Add CircuitBreaker to codebase
- Add AtomicState, IAtomicState, OpenState, HalfOpenState, ClosedState, CircuitBreakerSpec
Ultimately I wound up ignoring the IScheduler and ExecutionContext / SynchronizationContext. I have implemented the tests from the Akka.io CircuitBreakerSpec tests and we can always come back later and add in the scheduler and execution context in a later commit and add suitable default values to a constructor.
=> 147 circuit breaker

src/core/Akka.Tests/IO/SimpleDnsCacheSpec.cs, src/core/Akka/IO/SimpleDnsCache.cs
Bugfix for the exception: itemwith the same key has already been added.
Make the Put on the SimpleDnsCache idempotent when a same host is
resolved.
=> Bugfix: Make the Put on the SimpleDnsCache idempotent

src/core/Akka/IO/Tcp.cs
Noticed these two messages do not inherit from Tcp.Event while playing with the new version
=> make Received and Connected inherit from Tcp.Event

src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Util/ByteStringSpec.cs, src/core/Akka.Tests/packages.config, src/core/Akka/Util/ByteIterator.cs, src/core/Akka/Util/ByteString.cs
I found a few issues with ByteString while using akka-io. This PR contains a few tests from the ByteStringSpec, as well as fixes to bugs identified with these tests.
ByteStringSpec uses FsCheck, a port of ScalaCheck.
=> akka-io: Ported a few tests in ByteStringSpec with bug fixes

src/core/Akka/IO/SelectionHandler.cs
TL;DR; This PR resolve issue #1225. 
The JVM socket selector will block until one socket is selected, or when wakeup is called. The behavior in JVM Akka is to block indefinitely until a socket is selected, or whenever a socket interest is added/removed  to wake-up the selector and then select again.
In .NET sockets there is unfortunately no way I'm aware of to wake-up the Socket.Select method. The high CPU usage here was caused because we never blocked on Select. 
I've changed the Select to block for 1 millisecond (the lowest timespan), which (in my testing at least) changed the idle CPU usage from 15% to 0%. The compromise is of course that some socket operation might wait a average of 0.5 ms, before they complete. I still have to do detailed measurement on the performance impact, but …
=> akka-io: fixed #1225 - High CPU load using the Akka.IO TCP server

src/core/Akka/IO/SimpleDnsCache.cs
Both Put() and CleanUp() methods in class SimpleDnsCache.Cache are now immutable.
It's my first pull request, so if you find any issues let me know and I'll fix them. Any ideas what unit test should I add?
=> Issue #1226 implemented

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs
This fixes the problems described in #1185 
If a receive timeout has been set after an `await` clause, the receive timeout message is never sent. 
This fix makes sure that the receive timeout is also triggered at the end of a async operation
=> Fix for 1185 receive timeout in async await actor

src/core/Akka/IO/SelectionHandler.cs
The PR fixes #1225. The select loop is now only started once sockets are registered for selection, and stopped when no sockets are interested anymore.
=> akka-io: Stop select loop on idle

.gitignore, build.cmd, src/.nuget/packages.config
Altered build command to install 4.1.0
Added .fake/ directory to .gitignore. Directory contains build artifacts.
Removed Fake 3.17.0 from packages.config as build.cmd dicates version.
Fixes #1241
=> Upgrade FAKE to version 4.1.0

src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.csproj, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs, src/core/Akka.Remote/Transport/TestTransport.cs, src/core/Akka.Remote/Transport/Transport.cs, src/core/Akka.Remote/Transport/TransportAdapters.cs
- Added property MaximumPayloadBytes to Transport. For HeliosTransport
this is the same as MaxFrameSize.
- If payload size > MaximumPayloadBytes, log OversizedPayloadException
and do not send message.
Corresponding Akka Scala code:
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Endpoint.scala#L745
https://github.com/akka/akka/blob/master/akka-remote/src/test/scala/akka/remote/RemotingSpec.scala#L527
https://github.com/akka/akka/search?utf8=%E2%9C%93&q=maximumpayloadbytes
=> Do not send if payload size > max allowed. Fixes #879

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryMapper.cs, src/core/Akka.Persistence.TestKit/Journal/JournalSpec.cs, src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj, src/core/Akka.Persistence.Tests/EndToEndEventAdapterSpec.cs, src/core/Akka.Persistence.Tests/MemoryEventAdapterSpec.cs, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Persistence/InternalExtensions.cs, src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs, src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs, src/core/Akka.Persistence/Journal/EventAdapters.cs, src/core/Akka.Persistence/Journal/EventSequences.cs, src/core/Akka.Persistence/Journal/MemoryJournal.cs, src/core/Akka.Persistence/Journal/SyncWriteJournal.cs, src/core/Akka.Persistence/Journal/WriteJournal.cs, src/core/Akka.Persistence/Persistence.cs, src/core/Akka.Persistence/Persistent.cs, src/core/Akka.Persistence/persistence.conf, src/examples/TcpEchoService.Server/Actors.cs
This is implementation of [Event Adapters](http://doc.akka.io/docs/akka/snapshot/scala/persistence.html#Event_Adapters) feature from canonical akka. They major role is ability to separate model stored by journal from domain model send by persistent actors through configurable mappers implementing `IEventAdapter` interface. Examples of use cases may be journal event versioning or addjusing domain model to specific schema expected by persistent backend.
Test suite is attached.
This feature should be documented.
cc #1223
=> implemented event adapters

build.fsx
By specifying 'spec-assembly' as part of the build it'll filter
out multinode tests assemblies that don't have the supplied word
in their name.
eg: build multinodetests spec-assembly=remote
Will run all multinode tests from all assemblies with 'remote' in
their name.
=> Added ability to filter multinode test assemblies

build.fsx
This is a documentation target for the MultiNodeTests target to explain
how to run the multiple node specs.
=> Added HelpMultiNodeTests target

build.fsx
`MultiNodeTests` target should have dependency on the following two targets in order to build the solution before running the tests
- BuildRelease
- CleanTests
=> Added BuildRelease and CleanTests targets as dependency for MultiNodeTests target

src/contrib/testkits/Akka.TestKit.NUnit.Tests/Akka.TestKit.NUnit.Tests.csproj, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryCrashSpec.cs, src/core/Akka.Remote.Tests/Serialization/DaemonMsgCreateSerializerSpec.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Actor/SupervisorStrategy.cs, src/core/Akka/Routing/RouterConfig.cs, src/core/Akka/packages.config, src/examples/FSharp.Api/Supervisioning.fs
Fixes #1275 
This PR replaces the default deciders in SupervisorStrategy and Pool with deployable deciders with the same semantics.
There is also a fix that prevents supervisorstrategies with local only deciders to be serialized, current code just ignores the local decider and sends an incomplete message
This could have some impact on user code, that is, if the user have used local only deciders in a remote deploy scenario, there will now be an exception thrown.
One could argue that this is a breaking change, but it is really a bug in user code if a local only decider is used in remote cases.
=> serialization fixes #1275 

src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj, src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs, src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs, src/core/Akka.Persistence.Tests/PersistenceSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs, src/core/Akka.Tests/Routing/BroadcastSpec.cs
This is an enhancement for TestKit using Xunit2, that allows you to see your logging data in output of xunit test runner. Even when you're running tests in parallel.
Xunit2 defines a dedicated interface `ITestOutputHelper`, that will be automatically injected to each test class constructor by the test runner itself. To allow this you must only expose it:
```csharp
class MyActorSpec : Akka.TestKit.Xunit2.TestKit 
{
public MyActorSpec(ITestOutputHelper output) : base(output: output) { }
}
```
`AkkaSpec` used for internal testing also has this *output* param exposed in it's constructor. I think we could expose it in all of internal test projects, but this should be done in separate PR. This will help with getting log info while executing specs.
=> Xunit2 output logger for parallel TestKit runs

src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj, src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs, src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs, src/core/Akka.Persistence.Tests/PersistenceSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Remote/Serialization/DaemonMsgCreateSerializer.cs, src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs, src/core/Akka.Tests/Actor/PropsSpec.cs, src/core/Akka.Tests/Routing/BroadcastSpec.cs, src/core/Akka/Actor/Props.cs
This addresses #1279. 
As suggested, I added checks to the `Props` constructors to handle cases where the `type` constructor parameter was `null`. I added a single test for the six methods changed (if preferred, I can split them out). Finally, I added the check to `DaemonMsgCreateSerializer` - when `GetType` returns `null` for the actor type name, an exception is thrown informing the user that the type should be referenced.
=> Better exception message when a remote actor deploy fails because of missing reference #1279

src/core/Akka/Routing/Resizer.cs
The `DefaultResizer` does not currently validate constructor arguments, it only validates values read from configuration.
Added missing Validate(); call in argument ctor.
=> Added missing validate call

src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryCrashSpec.cs, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryFailureSpec.cs, src/core/Akka.Remote.TestKit/MultiNodeSpec.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/Remoting.cs, src/core/Akka/Actor/ActorRefProvider.cs, src/core/Akka/Actor/Inbox.Actor.cs, src/core/Akka/IO/SimpleDnsManager.cs, src/core/Akka/IO/TcpOutgoingConnection.cs, src/core/Akka/Routing/ConsistentHashRouter.cs
These fixes relate to [this issue #1283](https://github.com/akkadotnet/akka.net/issues/1283).
Basically I corrected all the places that I've found. The main idea behind fixes is
to change log statements from this 
```c#
_log.Debug("Foo" + bar + "Baz" + yo)
```
to this
```c#
_log.Debug("Foo {0} Baz {1}",bar,yo);
```
I squashed all the commits into one.
=> Replaced string concatenation with format templates in log statements

src/core/Akka/Akka.csproj, src/core/Akka/Configuration/Pigeon.conf, src/core/Akka/Serialization/WireSerializer.cs, src/core/Akka/packages.config
This PR introduces the Wire serializer as an alternative serializer for Akka.NET.
The serializer is not set as the default serializer here, it is only included so users can activate it manually by changing what objects should use it in the config.
All tests pass when the serializer is enabled instead of the json.net serializer.
I would like users to evaluate this for some time and try it out in real world scenarios.
To enable the serializer:
```javascript
serialization-bindings {
"System.Byte[]" = bytes
"System.Object" = wire //instead of json
}
```
The main features this addresses
* Fully supports all F# types
* 27 times faster than our current Json.NET setup
=> Wire Serializer

src/core/Akka.TestKit/Internal/BlockingQueue.cs, src/core/Akka.Tests/Actor/Stash/ActorWithStashSpec.cs, src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
Fix for #1312
Our stashing support currently uses structural equality, which makes it impossible to stash two different objects with the same structural equality comparison.
e.g. this affects pretty much every F# type as they do structural comparisons.
In scala the comparison is done using `eq` which is the scala version of `ReferenceEquals`
I've updated our code to work the same way.
=> stashing reference equality

src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj, src/core/Akka.Remote.Tests.MultiNode/PiercingShouldKeepQuarantineSpec.cs, src/core/Akka.Remote/Properties/AssemblyInfo.cs
Ported spec from Akka, but with larger akka.remote.retry-gate-closed-for-timer.
How can akka spec actually pass ? If I set akka.remote.retry-gate-closed-for = 0.5s (as they have in their spec), then in a for part, then spec would not pass for some i > 0... as what I believe happens is, that after 0.5s quarantine is over and next assert ExpectNoMessage fails (since it waits for 2s)...
With increased retry-gate-closed-for it should pass...What am I not seeing ?
=> Issue #1246 - PiercingShouldKeepQuarantineSpec

src/core/Akka.FSharp.Tests/ApiTests.fs
This PR contains the F# tests that @raymens created in #1285
The failing test is commented out for now.
@Horusiath the actual problem is in here:
```fsharp
let private tryCast (t:Task<obj>) : 'Message =
match t.Result with
| :? 'Message as m -> m
| o ->                         //<------------- here, if the user Tells () to an actorref, the () will not be matched by the above line as it is not of that type. 
//instead the unit will be processed here, as a JObject, which it is not..
//my F#-fu is not strong enough to know how to deal with the F# type system :-/
let context = Akka.Actor.Internal.InternalCurrentActorCellKeeper.Current
if context = null 
then failwith "Cannot cast JObject outside the actor system context "
else
let serializer = …
```
=> Added tests for F# null bug

.gitignore, build.fsx, src/core/Akka.MultiNodeTestRunner.Shared/Persistence/FileNameGenerator.cs, src/core/Akka.MultiNodeTestRunner/Program.cs
Made minor changes to FAKE file and added a new flag to the multi-node test runner that will copy output to a new directory if specified.
```xml
<summary>
/// MultiNodeTestRunner takes the following <see cref="args"/>:
/// 
/// C:\> Akka.MultiNodeTestRunner.exe [assembly name] [-Dmultinode.enable-filesink=on] [-Dmultinode.output-directory={dir path}]
/// 
/// <list type="number">
/// <listheader>
///     <term>Argument</term>
///     <description>The name and possible value of a given Akka.MultiNodeTestRunner.exe argument.</description>
/// </listheader>
/// <item>
///     <term>AssemblyName</term>
///     <description>
///         The full path or name of an assembly containing as least one MultiNodeSpec in the current working directory.
/// 
///         i.e. …
```
=> Resolves #1314. Add unit test output as TeamCity artifacts.

src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/WindsorDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Core/IDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.StructureMap/StructureMapDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs
As discussed with Andrew Skotzko, when you dynamically want to resolve an actor, without an overload using System.Type, and only having generic types, you are forced to hard code large switch statements and also have the class know the entire universe.
This doesn't change the implementation, it just adds an overload.
=> Added an overload using non-generic System.Type

src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs, src/contrib/cluster/Akka.Cluster.Tools/PubSub/DistributedPubSubMediator.cs, src/contrib/cluster/Akka.Cluster.Tools/PubSub/DistributedPubSubSettings.cs, src/contrib/cluster/Akka.Cluster.Tools/PubSub/Internal/Messages.cs, src/contrib/cluster/Akka.Cluster.Tools/PubSub/Internal/Topics.cs
This PR contains:
- Structural equality for `DistributedPubSubMediator` messages.
- Setup mediator to schedule `Prune` and `GossipTick` signaling.
- `DistributedPubSubSettings` builder methods.
=> Distributed pub/sub messages structural equality with scheduler initialization

src/core/Akka/Actor/ActorPath.cs
I get a flurry of handled `UriFormatException`s whenever I run Akka.NET specs, and that's been by design. Rewrote that code to use `Uri.TryCreate` instead so it no longer throws period.
=> rewrote ActorPath.TryParseAddrss to now test Uris by use Uri.TryCreate instead of try / catch

src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj, src/core/Akka.Cluster.Tests/Routing/ClusterRouterAsk1343BugFixSpec.cs
Added some specs to verify if #1343 is an issue or not; was not able to reproduce the runtime error, but I want to keep these specs in the Akka.Cluster.Tests project anyway (they verify that Asks get forwarded to routees, which is helpful.)
=> Added specs for Ask clustered router timeout error (#1343)

src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterEvent.cs, src/core/Akka.Cluster/ClusterMetricsCollector.cs, src/core/Akka/Actor/ActorSystem.cs, src/core/Akka/Actor/Props.cs, src/core/Akka/IO/Tcp.cs, src/core/Akka/IO/TcpManager.cs, src/core/Akka/IO/UdpManager.cs, src/core/Akka/Routing/Resizer.cs
This PR replaces the scala documentation x-references with c# documentation x-references so that Sandcastle can pick these up when generating the api docs.
=> [xml-doc] replaced scala x-references with c# x-references

src/core/Akka.Remote.TestKit.Tests/BarrierSpec.cs, src/core/Akka.Remote.TestKit/BarrierCoordinator.cs, src/core/Akka.Remote.TestKit/Controller.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs
Closes #1192.
This PR renames various internal exceptions to follow the .NET standard
of suffixing exceptions with "Exception". Since these are internal and
not public it shouldn't break the public API.
=> Renamed internal exceptions to follow .NET standard

src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka/Configuration/Hocon/HoconValue.cs
Fix for `Hocon.Value.IsEmpty` bug
=> hocon-empty

src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.CastleWindsor/WindsorDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Core/DIActorProducer.cs, src/contrib/dependencyInjection/Akka.DI.Core/IDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Core/Readme.md, src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.StructureMap/StructureMapDependencyResolver.cs, src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs, src/core/Akka.Remote.TestKit/Conductor.cs, src/core/Akka.Remote.TestKit/Extension.cs, src/core/Akka.TestKit/EventFilter/IEventFilterApplier.cs, src/core/Akka.TestKit/INoImplicitSender.cs, src/core/Akka.TestKit/TestActorRef.cs, src/core/Akka.TestKit/TestActors/EchoActor.cs, src/core/Akka.TestKit/TestKitSettings.cs, src/core/Akka/Actor/Exceptions.cs, src/core/Akka/Dispatch/DequeBasedMailbox.cs, src/core/Akka/Dispatch/MessageQueues/DequeWrapperMessageQueue.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs, src/core/Akka/Util/MatchHandler/IPartialActionBuilder.cs, src/core/Akka/Util/MatchHandler/MatchBuilder.cs
This PR cleans up a bit of documentation.
- Fleshed out the api docs for the various Akka exceptions.
- Fixed a couple of x-references.
- Moved the link in the various dependency resolvers Release method to
the DI Core readme. That link didn't really relate to that method.
- Replaced some extraneous tags with self-closing tabs.
=> [api-docs] Documentation cleanup

src/core/Akka/Actor/PipeToSupport.cs
Added an optional success and failure handler to PipeTo, to simplify use of Tasks. PipeTo falls back to original behavior either handler isn't supplied.
Some examples:
```csharp
Context.ActorSelection("akka.tcp://remote@remote:1234/user/PingActor")
.ResolveOne(TimeSpan.FromSeconds(1))
.PipeTo(Self,
success: x => new PleasePing(x),
failure: e => new TryAgainLater(e.ToString()));
actorRef.Ask<Pong>(new Ping())
.PipeTo(Self,
failure: e => new TryAgainLater(e.ToString()));
```
=> Add optional PipeTo completion handlers

src/core/Akka.FSharp.Tests/ApiTests.fs, src/core/Akka.FSharp/FsApi.fs
This PR removes an JSON.NET hack hardcoded inside F# API. Also existing end2end discriminated union serialization test between remote nodes has been updated by replacing JSON.NET with Wire.
=> Removed F# hack over JSON.NET serializer

src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs
A fix for #1390 
- EndpointWriter now publishes actual messages instead of LinkedListNodes to
DeadLetters
- RemoteDeadLetterActorRef now handles submitted dead letters (behaves similarly to Scala version)
=> Publish not sent remote messages to DeadLetters (fix for #1390)

src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj, src/core/Akka.Persistence.Tests/ReceivePersistentActorTests.cs, src/core/Akka.Persistence.Tests/ReceivePersistentActorTests_Become.cs, src/core/Akka.Persistence.Tests/ReceivePersistentActorTests_LifeCycle.cs, src/core/Akka.Persistence/PersistentActor.cs, src/core/Akka/Actor/ActorBase.cs
See #1395
This part adds missing API parts to `ReceivePersistentActor` as well as the battery of tests to verify it's behavior:
- Two methods have been created -`Become` and `BecomeStacked`. They works with `Command`, `CommandAny`, `Recover` and `RecoverAny` handlers in the similar way as in case of `Receive` method in `ReceiveActor`.
- New method `UnbecomeStacked` reverts the behavior of `BecomeStacked` applied previously.
- `CommandAny` method matching any incoming command was missing and has been added.
NOTE: one of the test is skipped until some decisions will be made for issue described in #1400 .
=> Become and BecomeStacked for ReceivePersistentActor

src/core/Akka.Persistence/Eventsourced.Recovery.cs, src/core/Akka.Persistence/Eventsourced.cs, src/core/Akka.Persistence/Persistence.cs
This PR contains two changes:
1. It attaches `LazyThreadSafetyMode.ExecutionAndPublication` in order to make lazy journal/snapshot store creation more thread safe (see issue #1397).
2. It changes behavior of persistent actor in case of failure during recovery - now it causes actor to stop. This is desired behavior in sync with canonical akka-persistence from version 2.4 (see issue #1403). Also it changes singature of method `OnReplayFailure(Exception reason)` to `OnReplayFailure(Exception reason, object message = null)` - now it will not only pass an exception that caused an error but also responsible event. Another change is that default implementation will log this cause on Error level - therefore all persistent actors contain logging adapters by default.
=> Persistent actor stops on recovery failures

src/core/Akka/Util/ByteString.cs
Hi. I ran into this while working with Akka I/O (specifically, concatenated `ByteString`s can't be enumerated). I was going to add a couple of tests for this, but I see that the existing spec for `ByteString` doesn't currently cover IEnumerable at all. I'm wondering if this is because there's a separate "iterator" implemented on `ByteString` (a Scala artefact, perhaps?)...
Anyway, let me know if some tests would be helpful, I don't mind writing them.
=> Implement enumerator for Composite ByteString.

.gitignore, build.cmd, build.sh
Modifies just the `build.cmd` and `build.sh` files to download Nuget.exe to where it's expected for package publishing.
=> close #1399 - modified build script to download NuGet for package publishing

src/contrib/dependencyInjection/Akka.DI.TestKit/DiResolverSpec.cs
In an effort to eliminate racy behavior from some of the DI specs (#853), I have replaced all TPL and `async`/`await` calls with good, old fashioned `ExpectMsg<T>`.
=> removed async/await from all DI tests

src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/PipeToSupport.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
This pull request is a refactoring to fix the issues discussed in issue #1481. The major change with the old design is that each actor now have its own (lazy loaded) ActorTaskScheduler. CallContext is no longer required to flow the state so it should achieve better performance.
=> Actor task scheduler refactoring

src/benchmark/PingPong/ClientAsyncActor.cs, src/benchmark/PingPong/PingPong.csproj, src/benchmark/PingPong/Program.cs, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/PipeToSupport.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
This pull request is a refactoring to fix the issues discussed in issue #1481. The major change with the old design is that each actor now have its own (lazy loaded) ActorTaskScheduler. CallContext is no longer required to flow the state so it should achieve better performance.
For the full comment history see Pull Request #1482
=> ActorTaskScheduler refactoring with benchmark

src/Akka.sln, src/contrib/serializers/Akka.Serialization.TestKit/Akka.Serialization.TestKit.csproj, src/contrib/serializers/Akka.Serialization.TestKit/AkkaSerializationSpec.cs, src/contrib/serializers/Akka.Serialization.TestKit/ContainerMessage.cs, src/contrib/serializers/Akka.Serialization.TestKit/EmptyActor.cs, src/contrib/serializers/Akka.Serialization.TestKit/ImmutableMessage.cs, src/contrib/serializers/Akka.Serialization.TestKit/ImmutableMessageWithPrivateCtor.cs, src/contrib/serializers/Akka.Serialization.TestKit/Properties/AssemblyInfo.cs, src/contrib/serializers/Akka.Serialization.TestKit/SomeMessage.cs, src/contrib/serializers/Akka.Serialization.TestKit/UntypedContainerMessage.cs, src/contrib/serializers/Akka.Serialization.TestKit/packages.config, src/contrib/serializers/Akka.Serialization.Wire/Akka.Serialization.Wire.csproj, src/contrib/serializers/Akka.Serialization.Wire/Properties/AssemblyInfo.cs, src/contrib/serializers/Akka.Serialization.Wire/WireSerializer.cs, src/contrib/serializers/Akka.Serialization.Wire/packages.config, src/contrib/serializers/Akka.Serialization.WireTests/Akka.Serialization.WireTests.csproj, src/contrib/serializers/Akka.Serialization.WireTests/Properties/AssemblyInfo.cs, src/contrib/serializers/Akka.Serialization.WireTests/WireTests.cs, src/contrib/serializers/Akka.Serialization.WireTests/packages.config, src/core/Akka/Routing/RouterConfig.cs
Adding Wire back as a contrib package.
I've also added a Akka Serialization Testkit which can be inherited much like the Persistence spec.
The tests for the Wire serializer is implemented using the SerializationTestkit
=> Add wire back as contrib package + Serialization TestKit

src/core/Akka.Remote.Tests/RemoteConsistentHashingRouterSpec.cs, src/core/Akka.Tests/Actor/Stash/ActorWithStashSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
This is a suggestion on how to solve the stashing #1400 issue
The mechanics in this PR works by incrementing an envelopeId in the actorcell for each user message received.
Once you call `Stash` the stash plugin will check if it has already stashed this envelope Id.
This has minimal impact on performance and we can still keep our envelopes as structs.
The solution is also unaffected by async await features as the envelope ID is only touched when processing user messages.
Thoughts?
=> Stashing fix

src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/SqlSnapshotStore.cs
This is another approach of fixing problem solved by #1471 . Instead of working on making collection of cancellation tokens thread safe, we can remove it completely and use single shared cancellation token source between all async database calls.
=> Fixed racing conditions on sql-based snapshot stores

src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
Currently Akka.NET [uses `System.Text.Encoding.Default.GetBytes()`](https://github.com/akkadotnet/akka.net/blob/fcf07ec2ae02f00af8fd9fa7e87138f03044fd31/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L101) to obtain a "blob" representation of messages that need to be sent outside the local actor system. 
This is what the .NET [documentation has to say](https://msdn.microsoft.com/en-us/library/system.text.encoding.default.aspx#Anchor_1) regarding the use of `Encoding.Default:`
> Different computers can use different encodings as the default, and the default encoding can even change on a single computer. Therefore, data streamed from one computer to another or even retrieved at different times on the same computer might be translated incorrectly. In addition, the encoding returned …
=> Fix incorrect serialization of Unicode characters in NewtonSoftJsonSerializer

tools/contributors.sh
Call bash tools/contributors.sh to get contribs since last release. Thx @Horusiath for the formatting suggestions.
Example usage below.
```
>> bash tools/contributors.sh
```
6 contributors since release v1.0.5
| 4 | 83 | 24470 | Aaron Stannard |
| 2 | 24475 | 43 | Bartosz Sypytkowski |
| 2 | 1136 | 7 | rogeralsing |
| 1 | 364 | 113 | JeffCyr |
| 1 | 27 | 0 | Andrew Skotzko |
| 1 | 2 | 2 | easuter |
or:
```
>> bash tools/contributors.sh v1.0.4
```
32 contributors since release v1.0.4
| 18 | 5410 | 42582 | Aaron Stannard |
| 17 | 4637 | 1394 | maxim.salamatko |
| 12 | 1506 | 343 | rogeralsing |
| 11 | 40804 | 2541 | Bartosz Sypytkowski |
| 8 | 1667 | 320 | Graeme …
=> Print out contributors since release

build.cmd, build.sh
Reverts akkadotnet/akka.net#1511
Based on the discussion on the https://github.com/NuGet/Home/issues/1813, looks like this may have been an intermittent issue with symbolsource errors occurring silently. Suggestion is to upload symbol packages in a separate command from the main NuGet package upload, which should be easy to do.
=> Revert "prevent nuget from self-upgrading"

build.fsx, src/Akka.sln, src/contrib/loggers/Akka.Logger.log4net/Akka.Logger.log4net.csproj, src/contrib/loggers/Akka.Logger.log4net/Akka.Logger.log4net.nuspec, src/contrib/loggers/Akka.Logger.log4net/Log4NetLogger.cs, src/contrib/loggers/Akka.Logger.log4net/Properties/AssemblyInfo.cs, src/contrib/loggers/Akka.Logger.log4net/packages.config
Added support for log4net logging. :dart:
=> Add log4net logging adapter support

.gitignore, build.cmd, build.fsx, build.sh, src/Akka.sln, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Tests.Performance/Actor/ActorMemoryFootprintSpec.cs, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj, src/core/Akka.Tests.Performance/Dispatch/ConcurrentQueueMailboxThroughputSpec.cs, src/core/Akka.Tests.Performance/Dispatch/MailboxMemoryFootprintSpec.cs, src/core/Akka.Tests.Performance/Dispatch/MailboxThroughputSpecBase.cs, src/core/Akka.Tests.Performance/Properties/AssemblyInfo.cs, src/core/Akka.Tests.Performance/packages.config, src/core/Akka/Properties/AssemblyInfo.cs
Uses [NBench](https://github.com/petabridge/nbench) for performing some simple, but automated benchmarks on each build.
Adding this and actually uses it requires me to change the build process on the server, so I wanted to ship a minimal performance testing footprint immediately and expand it later - that way this commit can begin making it into every other contributor's dev branch going forward.
I'll link to some of the results this PR produces....
=> added initial performance specs using NBench

src/core/Akka.Tests/Actor/ActorSystemSpec.cs, src/core/Akka/Actor/ActorSystem.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs
closes #1519 
It also implements some of the tests for #60.
=> Implemented the RegisterOnTermination feature.

src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote.Tests/UntrustedSpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.TestKit/TestKitBase_ActorOf.cs, src/core/Akka/Actor/ActorRefFactoryShared.cs, src/core/Akka/Actor/ActorSystem.cs, src/core/Akka/Actor/IAutoReceivedMessage.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
fixed dropping inbound actor selection in the untrusted mode 
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Endpoint.scala#L79
fixed dropping inbound PossiblyHarmful message
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Endpoint.scala#L86
added path to remote daemon
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L167
added actor selection by given target
replaced type matching to `if else` , for doing complicated conditions
=> #1365 added untrustedspec

src/core/Akka.Remote/Endpoint.cs
Fixes #1539 
The log message is being formatted in the default pipeline, even if logging is not enabled. 
This PR moves the message formatting into the conditionals that logs.
=> Akka.Remote Performance - String.Format logging perf fix

src/core/Akka.Remote.TestKit/Player.cs
This PR fixes a non closed over Self reference in the Remote.TestKit Player.
`Self` is not safe to use in continuations as the `Self` property is pointing to the currently active context.
From ActorBase.cs
```csharp
protected IActorRef Self { get { return HasBeenCleared ? _clearedSelf : Context.Self; } }
protected static IActorContext Context
{
get
{
var context = InternalCurrentActorCellKeeper.Current;
if (context == null)
throw new NotSupportedException(
"There is no active ActorContext, this is most likely due to use of async operations from within this actor.");
return context.ActorHasBeenCleared ? null : context;
}
}
```
=> Player closure fix

documentation/akkadoc.shfbproj, src/contrib/dependencyInjection/Akka.DI.StructureMap/Akka.DI.StructureMap.csproj, src/contrib/dependencyInjection/Akka.DI.Unity/Akka.DI.Unity.csproj, src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj, src/contrib/persistence/Akka.Persistence.Sqlite/Akka.Persistence.Sqlite.csproj, src/contrib/serializers/Akka.Serialization.Wire/Akka.Serialization.Wire.csproj
Some of the newer assemblies forgot to enable this option when they were
merged in. This PR enables that option so that Sandcastle can generate
their respective documentation pages.
Also some of the newer namespaces were missing namespace documentation,
so this PR adds those docs as well.
=> [api-docs]Enabled missing xmldoc output option

src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj, src/core/Akka.Remote.Tests.Performance/ForkJoinDispatcherRemoteMessagingThroughputSpec.cs, src/core/Akka.Remote.Tests.Performance/ThreadPoolDispatcherRemoteMessagingThroughputSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/AssociationStressSpecBase.cs, src/core/Akka.Remote.Tests.Performance/Transports/HeliosRemoteMessagingThroughputSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/RemoteMessagingThroughputSpecBase.cs, src/core/Akka.Remote.Tests.Performance/Transports/TestTransportAssociationStressSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/TestTransportRemoteMessagingThroughputSpec.cs, src/core/Akka.Remote/Transport/TestTransport.cs, src/core/Akka.Tests.Performance/Actor/ActorThroughputSpecBase.cs
Modified Akka.Actor benchmarks to get more accurate reading
Added dispatcher-specific specs for Akka.Remote
close #1547 - fixed benchmarks that depend on `TestTransport`
close #1556 - memory leak caused by not clearing `TestTransport` logs
=> [Ready] Modified Akka.Remote.Transport benchmarks to get more accurate readings

src/core/Akka.Tests.Performance/Actor/AddressSpec.cs
Whoops - forgot to actually call the counter we use to instrument this spec.
=> fixed bug with AddressSpec that caused it not to actually measure Address.Parse operations

src/core/Akka.Persistence.Tests/AtLeastOnceDeliverySpec.cs
This PR fixes the AtLeastOnceDelivery_must_redeliver_many_lost_messages which was previously Skipped.
The old code reads as follows:
```csharp
var resA = new SortedSet<string>(probeA.ReceiveN(n, deliverWithin).Cast<Action>().Select(x => x.Payload));
var resB = new SortedSet<string>(probeB.ReceiveN(n, deliverWithin).Cast<Action>().Select(x => x.Payload));
var resC = new SortedSet<string>(probeC.ReceiveN(n, deliverWithin).Cast<Action>().Select(x => x.Payload));
resA.ShouldOnlyContainInOrder(a);
resB.ShouldOnlyContainInOrder(b);
resC.ShouldOnlyContainInOrder(c);
```
It is explicitly trying to compare the result **in order**.
The Scala code does not do this, it only checks that the sequences contains the same data:
```scala
probeA.receiveN(N, deliverWithin).map { case a: Action ⇒ a.payload …
```
=> Fixes AtLeastOnceDelivery_must_redeliver_many_lost_messages test

src/core/Akka.Persistence.Tests/PersistentViewSpec.Actors.cs, src/core/Akka.Persistence.Tests/PersistentViewSpec.cs
This PR fixes the previously skipped test PersistentView_should_run_updates_again_on_failure_during_an_update_cycle.
There was a message that wasnt handled in the view which caused the test to fail.
Adding the message handler from scala fixed the test.
cc @Horusiath
=> Fixes PersistentView_should_run_updates_again_on_failure_during_an_update_cycle test

src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryCrashSpec.cs
cc @Horusiath 
This test now passes. 
The description of the Skip message was only "Fix me"... was this disabled due to the test failing or due to racy-ness?
=> Enabling AtLeastOnceDelivery_should_not_send_when_actor_crashes

src/core/Akka.Tests/Actor/FSMTimingSpec.cs, src/core/Akka.Tests/Actor/RootGuardianActorRef_Tests.cs, src/core/Akka.Tests/Event/EventStreamSpec.cs
There are a few issues that have been fixed that makes it possible to re-enable these tests.
Not sure about the status of ManageLogLevels, it runs good on local machine. going to give it a few runs on the build server.
=> Enabling some tests where the problem have been solved.

src/contrib/serializers/Akka.Serialization.TestKit/AkkaSerializationSpec.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs
Some of the issues that made us skip a few serialization tests in the past have since been fixed.
This PR just enables the tests again.
=> Enabling skipped serialization tests

src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj, src/core/Akka.Remote.Tests.Performance/InboundMessageDispatcherSpec.cs, src/core/Akka.Remote.Tests.Performance/packages.config
Makes it possible to test performance improvements made to the read side of Akka.Remote independently from the rest of the message processing pipeline. Great for changes such as #1540.
=> added an independent performance spec for InboundMessageDispatcher

build.fsx, src/Akka.sln, src/contrib/loggers/Akka.Logger.CommonLogging/Akka.Logger.CommonLogging.csproj, src/contrib/loggers/Akka.Logger.CommonLogging/Akka.Logger.CommonLogging.nuspec, src/contrib/loggers/Akka.Logger.CommonLogging/CommonLoggingLogger.cs, src/contrib/loggers/Akka.Logger.CommonLogging/Properties/AssemblyInfo.cs, src/contrib/loggers/Akka.Logger.CommonLogging/packages.config
I know that it is not the most important thing in the world, but I am using Common Logging in my project and I wanted to share this adapter.
I hope I didn't miss anything.
=> Common.Logging logging support

src/core/Akka.Persistence/Persistence.cs
This PR should fix race problems with lazy-loaded persistent plugins (#1522). It turns out that lazy loading isn't actually needed. Also plugins cache has been refactored to work in safer manner.
[EDIT:30.12.2015] **More description**
Actual problem seemed to lay in the way the plugin handlers were registered in `Persistence` extension. Because of concurrent access, all parties (i.e. persistent actors) were trying to lazily initialize plugin handler and `AddOrUpdate` it to concurrent dictionary - this part was handled correctly. However when there are no entry in dictionary, new plugin was initialized and overriding concurrently updated entry, that may appeared in the meantime, as the default dictionary conflict resolution was to take latest plugin created. However one of the plugin …
=> Fix for race conditions in presistence plugins

src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj, src/core/Akka.Tests.Performance/Actor/ActorSelectionSpecs.cs, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
Still working on the Ask benchmarks and stress tests
=> added ActorSelection benchmarks per #1555

src/core/Akka.MultiNodeTestRunner.Shared/Akka.MultiNodeTestRunner.Shared.csproj, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/FileSystemAppenderActor.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/FileSystemMessageSinkActor.cs, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.NodeTestRunner/Akka.NodeTestRunner.csproj, src/core/Akka.NodeTestRunner/Program.cs, src/core/Akka.NodeTestRunner/Sink.cs, src/core/Akka.Remote.TestKit/CommandLine.cs
Builds on the work by @Silv3rcircl3 and uses a combination of STD OUT redirection and TCP logging to capture a complete picture of what actually happened inside a multi-node test.
=> Resolves 1475 - reliable error capture and logging system for MultiNodeTests

src/benchmark/PingPong/Program.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Extension.cs, src/core/Akka.Cluster.Tests.MultiNode/ClusterDeathWatchSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared/Sinks/SinkCoordinator.cs, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote.Tests.MultiNode/RemoteDeploymentDeathWatchSpec.cs, src/core/Akka.Remote.Tests.Performance/InboundMessageDispatcherSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/RemoteMessagingThroughputSpecBase.cs, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka.Tests.Performance/Actor/ActorMemoryFootprintSpec.cs, src/core/Akka.Tests.Performance/Actor/ActorSelectionSpecs.cs, src/core/Akka.Tests.Performance/Actor/ActorThroughputSpecBase.cs, src/core/Akka.Tests/Actor/ActorSystemSpec.cs, src/core/Akka/Actor/ActorSystem.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Actor/Scheduler/DedicatedThreadScheduler.cs, src/examples/FaultTolerance/Program.cs, src/examples/Stocks/SymbolLookup/MainForm.cs
I marked ```AwaitTermination```, ```Shutdown``` and ```TerminationTask``` as obsolete and replaced all internal calls with the new api.
closes #1532
=> Implemented WhenTerminated and Terminate

src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs
Previously, the fallback for PublicHostname was the Hostname from the
config, now it's the Hostname which has the IPAddress.Any fallback.
Also, added a test to cover this
=> PublicHostname defaults to IPAddress.Any when hostname is blank

src/core/Akka.Tests/Actor/ActorCellSpec.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Dispatch/ActorTaskScheduler.cs, src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
Fixes #1609
cc @JeffCyr please review that the current message on async `ActorTaskSchedulerMessage` messages looks OK.
=> Clear current message - fixes #1609

src/core/Akka.Remote.Tests.Performance/InboundMessageDispatcherSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/RemoteMessagingThroughputSpecBase.cs, src/core/Akka.Remote.Tests.Performance/Transports/TestTransportAssociationStressSpec.cs, src/core/Akka.Remote.Tests.Performance/Transports/TestTransportRemoteMessagingThroughputSpec.cs, src/core/Akka.Remote.Tests/EndpointRegistrySpec.cs, src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote.Tests/Transport/ThrottlerTransportAdapterSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/EndpointRegistry.cs, src/core/Akka.Remote/RemoteSettings.cs, src/core/Akka.Remote/Remoting.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.TestKit/Internal/TimeSpanExtensions.cs, src/core/Akka/Actor/ActorSelection.cs, src/core/Akka/Actor/Exceptions.cs, src/core/Akka/Pattern/IllegalStateException.cs, src/core/Akka/Util/Internal/Extensions.cs
Opening a streaming pull request for a set of changes I'm working on:
1. Converting all system remoting actors to `ReceiveActor` to make them easier to reason about, with exception of the `ProtocolStateActor` FSM.
2. Updating `RemotingSettings` and `Remote.conf` to support some new values.
3. Upgrading the `ReliableDeliverySupervisor` and fixing the backoff and buffering mechanism.
4. Updating the `EndpointManager`, `EndpointWriter`, and `EndpointReader` where needed.
=> Remoting system upgrade 

src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
*Issue #1538 Akka.Remote performance - ForkJoinDispatcher*
This PR contains a refactoring of the DedicatedThreadPool. The main improvement is to use a shared work queue for all workers. The work queue is implemented by a ConcurrentQueue and a custom semaphore highly optimized for the ThreadPool scenario. (I borrowed `UnfairSemaphore` from the coreclr repo, it's the one used for the real CLR ThreadPool) 
The new DedicatedThreadPool has ~3.5x more throughput and 32x less latency (for the worst-case).
Global ThreadPool : 00:00:01.2247981
HeliosThreadPool  : 00:00:03.8819794
Global ThreadPool : 00:00:00.4042989
HeliosThreadPool  : 00:00:07.2341554
Global ThreadPool : 00:00:01.2171287
HeliosThreadPool  : 00:00:01.0755531
Global ThreadPool : 00:00:00.5609632
HeliosThreadPool  : 00:00:00.2240666 …
=> Increased performance of DedicatedThreadPool

src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf
Resolves #1628 - the enhanced MNTR logs revealed that Helios delivering messages for a remotely deployed actor before the remotely deployed actor was created were the problem.
This will hurt throughput to some extent in Helios, but it's more important to be functionally correct. I would like to make this part of the v1.0.6 release as it fixes what is a critical issue in my opinion.
=> fixes issue with Helios message ordering

documentation/akkadoc.shfbproj, src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj, src/contrib/cluster/Akka.Cluster.Tools/Akka.Cluster.Tools.csproj
Some of the newer assemblies forgot to enable this option when they were merged in. This PR enables 
that option so that Sandcastle can generate their respective documentation pages.
Also some of the newer namespaces were missing namespace documentation, so this PR adds those 
docs as well.
=> [api-docs] Enabled missing xmldoc output option

CONTRIBUTING.md
This PR adds a section to the Contributing.md document instructing users
how to update git timestamps in order for the build server to pick up
updated PRs.
=> [docs] Added blurb about updated PRs and build server

src/core/Akka.Tests/Util/Internal/Collections/ImmutableAvlTreeTests.cs, src/core/Akka/Util/Internal/Collections/ImmutableAvlTreeBase.cs
This fixes #1202 which was caused by Remove sometimes returning an unbalanced tree. This happened in after the 'core' remove, node X became unbalanced, and either X.L.R was higher than X.L.L  or X.R.L was higher than X.R.R .
This has been reproduced in 2 unit tests.
Mostly this would not lead to a problem: a next remove or add would fix it, but in some cases (haven't been able to reproduce in a Unit Test, though) doing adds close to this tree (not to the tree itself!) would lead to a NullReferenceException when Rotating the now-unbalanced tree.
The fix is trivial: DoubleRotate should be done when the tree-after-remove is left (resp right) heavy - not only when it's left/right imbalanced. The helper functions were incorrectly named.
=> Issue1202 boekabart

src/core/Akka.Persistence/Persistence.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs
Use ConcurrentDictionary.GetOrAdd instead of TryGet + AddOrUpdate
=> Fix #1522 Ensure extensions and persistence plugins are only registered/created once

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ActorSystem.cs
The JVM version has this two properties which I need in the ActorSystemSpec.
=> Implemented StarTime and Uptime

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Cluster.Tests.MultiNode/FailureDetectorPuppet.cs, src/core/Akka.Tests/IO/SimpleDnsCacheSpec.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Util/AtomicReference.cs
Based on the gitter discussion I have rewritten the AtomicReference based on the DotNetty version.
- it is now restricted to reference types
- it uses Volatile Read/Write instead of Interlocked.MemoryBarrier for the Value property
- it has a new method to atomically get the current value and replace it with a new one
=> Rewrite of the AtomicReference

RELEASE_NOTES.md, contributor-output.md
**Maintenance release for Akka.NET v1.0.5**
This patch consists of many bug fixes, performance improvements, as well as the addition of two brand new alpha modules for Akka.Cluster users.
**Akka.Cluster.Tools** and **Akka.Cluster.Sharding**
The biggest part of this release is the addition of [Akka.Cluster.Tools](http://getakka.net/docs/clustering/cluster-tools) and [Akka.Cluster.Sharding](http://getakka.net/docs/clustering/cluster-sharding), both of which are available now as pre-release packages on NuGet.
```
PM> Install-Package Akka.Cluster.Tools -pre
```
and
```
PM> Install-Package Akka.Cluster.Sharding -pre
```
Respectively, these two packages extend Akka.Cluster to do the following:
1. Distributed pub/sub (Akka.Cluster.Tools)
2. `ClusterClient` - subscribe to changes in cluster …
=> Akka.NET v1.0.6 release (DEV)

build.cmd, build.fsx, src/Akka.sln, src/contrib/testkits/Akka.TestKit.NUnit/packages.config, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/Akka.TestKit.NUnit3.Tests.csproj, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/AssertionsTests.cs, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/Properties/AssemblyInfo.cs, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/TestKitTestFixtureTest.cs, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/TestKitTests.cs, src/contrib/testkits/Akka.TestKit.NUnit3.Tests/packages.config, src/contrib/testkits/Akka.TestKit.NUnit3/Akka.TestKit.NUnit3.csproj, src/contrib/testkits/Akka.TestKit.NUnit3/Akka.TestKit.NUnit3.nuspec, src/contrib/testkits/Akka.TestKit.NUnit3/NUnitAssertions.cs, src/contrib/testkits/Akka.TestKit.NUnit3/Properties/AssemblyInfo.cs, src/contrib/testkits/Akka.TestKit.NUnit3/TestKit.cs, src/contrib/testkits/Akka.TestKit.NUnit3/packages.config
=> Support for NUnit 3

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka/Routing/RouterConfig.cs
Added missing convenience method to `FromConfig` to comply with the Scala API.
```csharp
var router1 = ActorOf(FromConfig.Props(Props.Create<Worker>()));
//(same as)
//var router1 = ActorOf(Props.Create<Worker>().WithRouter(FromConfig.Instance));
```
Scala counterpart:
```scala
val router1: ActorRef = context.actorOf(FromConfig.props(Props[Worker]), "router1")
```
All other router configs do have the corresponding Props method, so it makes sense to be consistent with Scala and the rest of the .NET router configs IMO, even if it is just slight sugar of the existing API.
Also cleaned up the RouterConfig.cs file to comply with C#6 language features.
As all RouterConfig classes uses surrogates for serialization, no such language features affect the serializability of the types.
=> Added missing FromConfig.Props(props)

src/core/Akka/Util/ByteIterator.cs, src/core/Akka/Util/ByteString.cs
=> Akka IO: ByteIterator and ByteStringbuilder bug fixes

src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka/Configuration/Hocon/HoconTokenizer.cs
This PR fixes #1687
There was special handling for escape sequences in the code that pulls tripple quoted text which should not be there.
Now any characters inside a tripple quoted string are parsed verbatim.
=> Hocon Tripple quoted text - Fixes #1687

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs, src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs
This PR contains two changes:
- `JournalEntry.Payload` field from `Akka.Persistence.Sql.Common` has been made public. The reason behind it is that some database specific features (PostgreSQL JSON data type to be specific) expect from ADO.NET to pass column data in `string` format instead of `byte[]`.
- `AtLeastOnceDeliverySemantic` class has been made public, so it can be encapsulated by any other actor (not only persistent actors) to enhance them with at-least-once-delivery semantic.
None of these changes should break existing API.
=> Made JournalEntry.Payload an object and AtLeastOnceDeliverySemantic public

build.cmd, build.sh
The release of NBench v0.1.6 yesterday introduced a redesign of how tests are loaded (isolated AppDomains) and that broke compatibility between the runner and the test dll. This locks the runner version to the version we're using in our tests and is needed in order to get CI to pass.
=> [build system bug fix] locked the NBench runner version used to performance tests

src/core/Akka.Tests/Actor/InboxSpec.cs, src/core/Akka/Actor/Inbox.Actor.cs
The InboxActor could crash when scheduling a query timeout if that timeout was already expired.
I added a safety check to send a Kick to self immediately if the timeout is already expired.
=> #1694 Added safe check in InboxActor when receive timeout is already expired

src/core/Akka.Tests/Actor/ActorSystemSpec.cs
Some notes, 
1. I have changed the name of some test regarding to #1510 
2. ~~I need to update the ```Reliable_deny_creation_of_actors_while_shutting_down``` test as far as #1617 is merged, see the TODO~~ done
3. When reviewing this PR please also review my https://github.com/akkadotnet/akka.net/issues/60#issuecomment-161930959, especially the tests that couldn't be implemented 
4. Two tests are still missing in this PR because they are implemented in #1525, so when #1525 and this PR are merged, #60 can be closed
5. I'm not sure if the ```SlowDispatcher``` is implemented correctly, but I thought I create this PR anyway because it's easier to review than via Gitter messages.
=> [WIP] Implemented missing ActorSystem specs

src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj, src/contrib/cluster/Akka.Cluster.Sharding.Tests/packages.config, src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj, src/contrib/cluster/Akka.Cluster.Tools.Tests/packages.config, src/contrib/serializers/Akka.Serialization.TestKit/Akka.Serialization.TestKit.csproj, src/contrib/serializers/Akka.Serialization.TestKit/packages.config, src/contrib/serializers/Akka.Serialization.WireTests/Akka.Serialization.WireTests.csproj, src/contrib/serializers/Akka.Serialization.WireTests/packages.config
unifying all 2.0.0 and 2.1.0 xunit references to 2.0.0 strict to get MNTK cluster tests working
=> #1720 - changing xunit 2.1.0 references to 2.0.0

build.sh
The build failed, because of the outdated FAKE assembly:
```
> [Loading /home/juergen/akka.net/build.fsx]
/home/juergen/software/akka.net/build.fsx(223,11): error FS0039: The namespace 'Testing' is not defined
```
=> Sync Unix build script with Windows build script

src/core/Akka/IO/TcpListener.cs
This is to align with scala's AkkaIO:
https://github.com/akka/akka/blob/ddcfb5e4d07b07ab5221175264795235cbcd2492/akka-actor/src/main/scala/akka/io/TcpListener.scala
Origin of the problem:
When running in IIS, the app pool recycle event will likely cause another Bind command that might result in:
"Only one usage of each socket address (protocol/network address/port) is normally permitted". 
In that instance, as the Bind command runs in the ctor, the actor crashes without any notification to commander of the failure, so no easy way to detect the error.
=> Akka.IO bind failed must notify bindCommander of failure

src/core/Akka.MultiNodeTestRunner/Program.cs
While I was testing the RemoteGatePiercingSpec I found it annoying that I need to run all specs in the assembly and therefore I have created another argument ```-Dmultinode.spec``` which takes a string and only executes specs that contain the given name. 
It checks the method name that is marked with the ```MultiNodeFact``` attribute.
For example: 
>...Runner.exe "Akka.Remote.Tests.MultiNode.dll" -Dmultinode.spec=RemoteGatePiercing
=> Added a new argument to the MultiNodeTestRunner to filter specs

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/ActorSystemSpec.cs, src/core/Akka/Actor/ActorRefProvider.cs, src/core/Akka/Actor/SupervisorStrategy.cs, src/core/Akka/Configuration/Pigeon.conf
This PullRequest makes it possible to change the User Guardian supervision strategy with the guardian-supervisor-strategy` hocon setting.
=> Implemented `guardian-supervisor-strategy` hocon setting

src/core/Akka.Persistence.Tests/PersistentActorStashingSpec.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs, src/core/Akka.Persistence/Eventsourced.cs
See https://github.com/akka/akka/issues/19899
Fix in JVM is not yet merged in, but I thought I'd get this in before next week's release. I'll submit a subsequent if JVM team makes updates to the code.
=> Ensure internal stash is unstashed on writes after recovery

build.fsx, src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Used this to spot a problem in my repository that's similar to what's happening in #1730.
This will make it so a new XUnit process is spawned for each test assembly and all reporting / logging is done individually per-assembly now, rather than globbed together.
=> modified XUnit code to run each assembly individually

build.fsx, src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj, src/contrib/cluster/Akka.Cluster.Sharding/Properties/AssemblyInfo.cs, src/contrib/cluster/Akka.Cluster.Tools/Akka.Cluster.Tools.csproj, src/contrib/cluster/Akka.Cluster.Tools/Properties/AssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Proof from my local build log:
```
Creating nuget packages for D:\Repositories\olympus\akka.net\src\contrib\cluster\Akka.Cluster.Sharding\Akka.Cluster.Sharding.nuspec
Creating D:\Repositories\olympus\akka.net\bin\build
Creating D:\Repositories\olympus\akka.net\bin\build\src\
Deleting D:\Repositories\olympus\akka.net\bin\build\src\obj
D:\Repositories\olympus\akka.net\bin\build\src\bin does not exist.
Creating .nuspec file at D:\Repositories\olympus\akka.net\bin\build\Akka.Cluster.Sharding.1.0.7.0-beta.nuspec
Created nuspec file D:\Repositories\olympus\akka.net\bin\build\Akka.Cluster.Sharding.1.0.7.0-beta.nuspec
D:\Repositories\olympus\akka.net\src\.nuget\NuGet.exe pack -Symbols -Version 1.0.7.0-beta -OutputDirectory "D:\Repositories\olympus\akka.net\bin\nuget" …
```
=> close #1758 made Akka.Cluster.Tools and Akka.Cluster.Sharding use correct assembly version info and nuget dependencies

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Routing/ScatterGatherFirstCompletedSpec.cs, src/core/Akka/Routing/Router.cs, src/core/Akka/Routing/ScatterGatherFirstCompleted.cs, src/examples/Routing/Program.cs
Fixes #1718  The spec was using broadcast which never goes through the specific router routee logic
=> Fixed the ScatterGatherFirstCompleted router logic

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ChildrenContainer/Internal/ChildrenContainer.cs, src/core/Akka/Actor/ChildrenContainer/Internal/ChildrenContainerBase.cs, src/core/Akka/Actor/ChildrenContainer/Internal/EmptyChildrenContainer.cs
ChildrenContainer.Children was returning a copy of all its child. This PR change the Children and Stats property to return the lazy evaluated LINQ expression instead of a copy.
- This is safe because the underlying collection is immutable
- This is more efficient because:
- No memory is allocated
- Enumerating the children from the ImmutableDictionary is not expensive
- The returned IReadOnlyCollection is not iterated in most case
The performance problem of issue #1766 was caused by this line:
https://github.com/akkadotnet/akka.net/blob/d00159ee8be45babecc7d20b935559df1415f49f/src/core/Akka/Actor/ActorCell.FaultHandling.cs#L422
(Note that the implementation of HandleChildTerminated is not touching the children parameter)
With this PR, GetChildren is lazy evaluated, so calling this method …
=> Issue #1766 - Lazy evaluation of ChildrenContainer.Children and ChildrenContainer.Stats

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.csproj, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.Remote.TestKit/Conductor.cs, src/core/Akka.Remote.TestKit/Internals/Reference.conf, src/core/Akka.Remote.TestKit/MsgEncoder.cs, src/core/Akka.Remote.TestKit/MultiNodeSpec.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj, src/core/Akka.Remote.Tests.MultiNode/RemoteRandomSpec.cs, src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs, src/core/Akka.Remote.Tests.MultiNode/TestConductor/TestConductorSpec.cs, src/core/Akka.Remote.Tests/Transport/AkkaProtocolStressTest.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/RemoteWatcher.cs, src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs, src/core/Akka.Tests/Actor/FSMTransitionSpec.cs, src/core/Akka/Configuration/Config.cs, src/examples/Cluster/Roles/Samples.Cluster.Transformation/App.config, src/examples/Cluster/Samples.Cluster.Simple/App.config
Fresh version of #1360 - includes a major Akka.Remote fix already
=> Akka.Remote EndpointWriter backoff bugfix

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs, src/core/Akka.FSharp/FsApi.fs, src/core/Akka.Persistence.Tests/Journal/SteppingMemoryJournal.cs, src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs, src/core/Akka.Persistence/Snapshot/SnapshotStore.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs, src/core/Akka/Actor/Futures.cs
This flag could be harmful by making the outer task waits until the inner tasks complete.
=> Removed all usage of AttachedToParent

src/benchmark/PingPong/ClientAsyncActor.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunCoordinator.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Tests/Actor/ActorCellSpec.cs, src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs, src/core/Akka.Tests/Routing/TailChoppingSpec.cs, src/core/Akka/Actor/ReceiveActor.cs
Marked Receive(Func<T, Task> handler) as obsolete and replaced it by ReceiveAsync.
This prevents from calling the asynchronous Receive by mistake (e.g. EndpointManager)
=> Replaced Receive(Func<T, Task> handler) by ReceiveAsync(...)

src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs, src/core/Akka.Cluster.Tests/TestMember.cs, src/core/Akka.Cluster/Member.cs, src/core/Akka.Cluster/Proto/ClusterMessageSerializer.cs, src/core/Akka/Actor/ActorPath.cs
Fixes issue #1784.
Member.UpNumber is not being propagated across cluster
MemberAgeComparer is sorting in a reverse order then it should
=> Member.UpNumber fix

src/core/Akka.TestKit.Tests/Xunit2/TestEventListenerTests/AllTestForEventFilterBase.cs, src/core/Akka.TestKit.Tests/Xunit2/TestEventListenerTests/AllTestForEventFilterBase_Instances.cs, src/core/Akka.TestKit.Tests/Xunit2/TestEventListenerTests/CustomEventFilterTests.cs, src/core/Akka.TestKit.Tests/Xunit2/TestEventListenerTests/DeadLettersEventFilterTests.cs, src/core/Akka.TestKit/EventFilter/EventFilterFactory.cs, src/core/Akka.TestKit/EventFilter/EventFilterFactory_Generated.cs, src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs, src/core/Akka.TestKit/TestKitBase.cs
This commit resolves issue described in #1630. EventFilters now can be
created for user-defined actor systems, not only TestKit.Sys.
=> External ActorSystem for Testkit event filters.

src/core/Akka.Streams.Tests/Implementation/Fusing/ActorGraphInterpreterSpec.cs, src/core/Akka.Streams/CodeGen/Dsl/GraphApply.cs, src/core/Akka.Streams/Dsl/GraphDsl.cs, src/core/Akka.Streams/FanOutShape.cs, src/core/Akka.Streams/Graph.cs, src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs, src/core/Akka.Streams/Implementation/Fusing/GraphAssembly.cs, src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs, src/core/Akka.Streams/Implementation/StreamLayout.cs, src/core/Akka.Streams/Stage/GraphStage.cs
Included are:
* Update to Graph Dsl to use `combineMaterializers` func
* Bug fix in `GraphAssembly` contructor
* Bug fix `StreamLayout.MaterializeModule`
* Bug fix in `GraphStageLogic.PassAlong`
* Bug fix in `FanOutShape` constructor
=> Completed port of ActorGraphInterpreterSpec

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka/Actor/ActorRef.cs
ActorRefs.Nobody is now deserialized back to its singleton instance.
This PR fix issue #1828.
=> Issue #1828 Implemented NobodySurrogate

src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Configuration/Pigeon.conf
This PR includes information about obsoleting JSON.NET as the default serializer in Akka.NET version 1.5. (see #1695). Warning contains link to manual informing, how to change default serializer to Wire and info about how to suppress this warning message by setting `suppress-json-serializer-warning` config key to on.
=> Warning about JSON.NET obsolete in v1.5

src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs
Per #1628 - turning on some additional logging so I can get a clearer picture of what's going on inside the spec.
=> enabled additional debugging for troubleshooting RemoteRoundRobinSpec

src/Akka.sln, src/benchmark/RemoteBenchmark/App.config, src/benchmark/RemoteBenchmark/Program.cs, src/benchmark/RemoteBenchmark/Properties/AssemblyInfo.cs, src/benchmark/RemoteBenchmark/RemoteBenchmark.csproj, src/benchmark/RemoteBenchmark/packages.config, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/Streaming/AsyncQueue.cs, src/core/Akka.Remote/Transport/Streaming/NamedPipeTransport.cs, src/core/Akka.Remote/Transport/Streaming/NetworkStreamTransport.cs, src/core/Akka.Remote/Transport/Streaming/SslStreamTransport.cs, src/core/Akka.Remote/Transport/Streaming/StreamAssociationHandle.cs, src/core/Akka.Remote/Transport/Streaming/StreamTransport.cs
This pull request includes a new Remoting Transport based on a NetworkStream.
This Transport aims to get the lowest overhead possible on top of .Net Sockets.
A sub-goal is to be able to support easily any Transport based on System.IO.Stream. The PR include two other transports (SslStreamTransport and NamedPipeTransport), but it is still a work in progress.
Initial results are promising, the transport is able to achieve 120K msg/sec on a quad core workstation, compared to ~6K msg/sec with Helios.
The happy path is working, but the code remain largely untested. Other PRs will includes spec until there is 100% code & feature coverage.
(This PR does not include the ActorPath cache to achieve 120K msg/sec, without the patch it is doing ~70K msg/sec)
=> v1.5 - NetworkStreamTransport implementation

RELEASE_NOTES.md, src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs
**Maintenance release for Akka.NET v1.0.6**
The biggest changes in Akka.NET 1.0.7 have been made to Akka.Persistence, which is now designed to match the final stable release version in JVM Akka 2.4. Akka.Persistence is on-target to exit beta and become a fully mature module as of Akka.NET 1.5, due in May/June timeframe.
A quick note about 1.5 - JSON.NET will be replaced by Wire as the default serializer going forward, so if you want to be forward-compatible with 1.5 you will need to switch to using Wire today. [Learn how to switch to using Wire as the default Akka.NET serializer](http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer).
If you install 1.0.7 you may see the following warning appear:
> NewtonSoftJsonSerializer has been detected as a default serializer. …
=> updated release notes for Akka.NET 1.0.7

src/core/Akka.Streams.Tests/IO/InputStreamSinkSpec.cs, src/core/Akka.Streams.Tests/IO/OutputStreamSourceSpec.cs, src/core/Akka.Streams.Tests/IO/TcpHelper.cs, src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs, src/core/Akka.Streams/Implementation/FlowModule.cs, src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs, src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs, src/core/Akka.Streams/Implementation/IO/InputStreamSinkStage.cs, src/core/Akka.Streams/Implementation/IO/TcpStages.cs, src/core/Akka.Streams/Implementation/Modules.cs, src/core/Akka.Streams/Implementation/Sinks.cs, src/core/Akka.Streams/Implementation/StreamLayout.cs, src/core/Akka/Util/ByteString.cs
- Implemented AtomicModule and introduced it in inheriting classes.
- ByteString equality method (for spec asserts)
- Optimization step for compose working on two materialized values - now Keep.Left / Keep.Right check is made to minimize unnecessary steps.
=> AtomicModule, optimized StreamLayout.Compose and minor IO spec fixes

src/core/Akka.Tests/Configuration/HoconTests.cs
Added a testcase for the scenario i ran into as described towards the end in https://github.com/akkadotnet/akka.net/issues/1687
Im not sure this is a valid scenario for hocon. I haven't found anything explicit in the hocon docs about this.
The way i ran into this is by building a filepath to a sqllite db in code, using `Path.Combine` and putting it in hocon as is. 
So is it valid for the hocon parser to throw in this scenario, and should a user always supply escaped path strings? Or does hocon need to handle this transparently.
If its the former, ill update the testcase to verify it does. If its the latter, then the testcase is fine as is now, and we have a failing test for the hocon parser.
/cc @rogeralsing
=> added testcase for unescaped filepaths

src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryCrashSpec.cs, src/core/Akka.Persistence.Tests/AtLeastOnceDeliveryReceiveActorSpec.cs, src/core/Akka.Persistence.Tests/AtLeastOnceDeliverySpec.cs, src/core/Akka.Persistence.Tests/EndToEndEventAdapterSpec.cs, src/core/Akka.Persistence.Tests/Fsm/PersistentFSMSpec.cs, src/core/Akka.Persistence.Tests/LoadPluginSpec.cs, src/core/Akka.Persistence.Tests/MemoryEventAdapterSpec.cs, src/core/Akka.Persistence.Tests/OptionalSnapshotStoreSpec.cs, src/core/Akka.Persistence.Tests/PersistenceConfigSpec.cs, src/core/Akka.Persistence.Tests/PersistenceSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorDeleteFailureSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorFailureSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorStashingSpec.cs, src/core/Akka.Persistence.Tests/PersistentViewSpec.cs, src/core/Akka.Persistence.Tests/SnapshotDirectoryFailureSpec.cs, src/core/Akka.Persistence.Tests/SnapshotFailureRobustnessSpec.cs, src/core/Akka.Persistence.Tests/SnapshotRecoveryLocalStoreSpec.cs, src/core/Akka.Persistence.Tests/SnapshotSerializationSpec.cs, src/core/Akka.Persistence.Tests/SnapshotSpec.cs, src/core/Akka.Persistence/persistence.conf
See #1861
- Default config journal plugin id is restored to point at in-memory journal (was none, causing an error).
- Default config snapshot store plugin id is restored to point at local file system one (was none with warning log message, which didn't cause any explicit error, but was breaking change in API behavior).
EDIT:
- All persistence specs are now running on default config settings, making sure that default journal and snapshot store have been initialized.
=> Recovered default journal & snapshot store to default config

src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Remote.Tests/Transport/AkkaProtocolStressTest.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs, src/core/Akka.Remote/Transport/Streaming/AsyncQueue.cs, src/core/Akka.Remote/Transport/Streaming/NetworkStreamTransport.cs, src/core/Akka.Remote/Transport/Streaming/StreamTransport.cs
This PR makes the default helios config to use NetworkStreamTransport instead of HeliosTcpTransport.
This is to see how things goes with the unit tests.
We'll need to discuss the upgrade path from 1.0 to 1.5, like if we want to introduce a configuration breaking change (cleaner solution) or if we want to make things work with the same 1.0 config (better experience but ugly).
=> v1.5 - Replaced HeliosTcpTransport by NetworkStreamTransport

src/Akka.sln, src/core/Akka.Remote.Tests/EndpointRegistrySpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/EndpointRegistry.cs
Fixed numerous issues with the `EndpointRegistry` and added specs to cover - should resolve #1845 and others.
=> EndpointRegistry fixes

src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj, src/core/Akka.Tests.Performance/Util/StandardOutWriterMemoryBenchmark.cs, src/core/Akka.Tests.Performance/packages.config, src/core/Akka/Util/StandardOutWriter.cs
Found some memory leaks in Helios which revolve around the use of delegates with context closures - realized it might explain some of the memory leak reports we've had around logging in Akka.NET. Found some code inside the `StandardOutWriter` that uses delegates similarly and profiled it.
Added `NBench.PerformanceCounters` to get some more detailed metrics.
=> eliminated allocations with StandardOutWriter

src/core/Akka.Tests/Util/ByteStringSpec.cs, src/core/Akka/Util/ByteIterator.cs
Fixes issue #1852 where the method IndexOf(x) for a concatenated set
of byte strings would throw an index out of range exception when the
element doesn't exist in the either one of the strings.
Included two tests to confirm that existing and non-existing element situations work.
=> Fix IndexOf() method for concatenated byte strings

src/Akka.sln, src/core/Akka.Persistence.Query.Tests/Akka.Persistence.Query.Tests.csproj, src/core/Akka.Persistence.Query.Tests/DummyReadJournal.cs, src/core/Akka.Persistence.Query.Tests/PersistenceQuerySpec.cs, src/core/Akka.Persistence.Query.Tests/Properties/AssemblyInfo.cs, src/core/Akka.Persistence.Query.Tests/packages.config, src/core/Akka.Persistence.Query/Akka.Persistence.Query.csproj, src/core/Akka.Persistence.Query/EventEnvelope.cs, src/core/Akka.Persistence.Query/IReadJournalProvider.cs, src/core/Akka.Persistence.Query/Interfaces.cs, src/core/Akka.Persistence.Query/PersistenceQuery.cs, src/core/Akka.Persistence.Query/Properties/AssemblyInfo.cs
This PR contains core lib for Akka.Persistence.Query - persistent backend implementation must use it in order to support akka streams of their side.
Example usage:
```csharp
var journal = system.ReadJournalFor<SomeCoolReadJournal>(queryPluginConfigPath);
var events = journal.Query(new EventsByTag("mytag", 0L));
```
=> Akka.Persistence.Query core plugin

src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Dispatch/ActorMailboxSpec.cs
Added some basic specs for the mailbox/actor combinations in Akka.NET.
Bounded dispatcher and mailbox configurations haven't been added yet
as these are not supported right now.
Takes care of issue #1793
=> Implement spec for standard mailbox combinations in Akka.NET

RELEASE_NOTES.md
**Maintenance release for Akka.NET v1.0.7**
Fixes an issue with the 1.0.7 release where the default settings for Akka.Persistence changed and caused potential breaking changes for Akka.Persistence users. Those changes have been reverted back to the same values as previous versions.
General fixes:
* [Recovered default journal & snapshot store to default config](https://github.com/akkadotnet/akka.net/pull/1864)
* [EndpointRegistry fixes](https://github.com/akkadotnet/akka.net/pull/1862)
* [eliminated allocations with StandardOutWriter](https://github.com/akkadotnet/akka.net/pull/1881)
* [ClusterSingletonManager - settings update](https://github.com/akkadotnet/akka.net/pull/1878)
* [Implement spec for standard mailbox combinations in …
=> added Akka.NET v1.0.8 release notes

documentation/akkadoc.shfbproj
This PR removes the DI and logger entries from the Sandcastle build file
due to these plugins being re-homed recently.
=> [api-docs]Removed re-homed entries from Sandcastle

src/core/Akka.Persistence/Journal/EventSequences.cs
JVM version also uses a list, and a test in the cassandra plugins tests that duplicates are properly emitted
=> Store EventSequence events in list to permit duplicates

src/core/Akka.Streams/Actors/ActorPublisher.cs
For now this fixes the Cassandra plugin issues, will run the streams tests with serialize-messages=on shortly
=> Fixes to serialization errors for serialized-messages=on

build.fsx, src/core/Akka.Remote.Tests.Performance/Transports/HeliosRemoteMessagingThroughputSpec.cs, src/core/Akka.Tests.Performance/Util/StandardOutWriterMemoryBenchmark.cs
This PR does a couple of things:
1. Enables concurrency mode for NBench, which allows all cores to be utilized. You will notice a significant increase in performance for any multi-threaded NBench spec and an increase in standard deviation size for non-multi-threaded specs possibly.
2. Activates the benchmark for the current Helios Akka.Remote transport. This will be used to compare it to the Helios 2.0 implementation.
3. Disables and then restores Console.Out for the duration our `StandardOutWriter` specs, so we don't fill up the build log with garbage.
=> enabled concurrency mode for NBench; activated Helios 1.4 benchmarks

src/core/Akka.Persistence/Fsm/PersistentFSM.cs, src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
As I've described in https://github.com/akkadotnet/akka.net/issues/1952. With backward compatibility support.
=> Removed redundant type parameters from PersistentFSMBase.State

src/contrib/persistence/Akka.Persistence.Sqlite/Akka.Persistence.Sqlite.csproj, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Akka.csproj
Some files had the CopyAlways options, this marked the projects as dirty after each build preventing to skip unchanged projects when rebuilding.
Now when you build the solution twice you get a nice instantaneous:
`========== Build: 0 succeeded, 0 failed, 71 up-to-date, 0 skipped ==========`
=> Changed CopyAlways files to CopyIfNewer

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs, src/core/Akka/Actor/ActorCell.DefaultMessages.cs, src/core/Akka/Actor/ActorCell.ReceiveTimeout.cs
Messages marked with NotInfluenceReceiveTimeout will not reset the timer. This can be useful when ReceiveTimeout should be fired by external inactivity but not influenced by internal activity, e.g. scheduled tick messages.
=> Added NonInfluenceReceiveTimeout

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka.Tests/Event/LoggerSpec.cs, src/core/Akka/Actor/Settings.cs, src/core/Akka/Configuration/Pigeon.conf, src/core/Akka/Event/LoggingBus.cs
added configuration for default logger dispatcher (from Akka 2.4.3)
added configuration specs
implemented StopDefaultLoggers method
fixed default value for UnstartedPushTimeout
=> Configuration for default logger dispatcher

src/core/Akka.Tests.Performance/Actor/Pattern/AskSpec.cs, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
Testing the throughput and memory allocation of `ICanTell.Ask`.
Uses a simple blocking implementation to do it.
Going to be making some modifications to this in a subsequent PR. Wanted the data now as a baseline.
=> added Ask performance benchmark

src/benchmark/RemoteBenchmark/Program.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.Tests.Performance/InboundMessageDispatcherSpec.cs, src/core/Akka.Remote.Tests/ActorRefCacheSpec.cs, src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote/ActorRefCache.cs, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/Transport/AkkaPduCodec.cs, src/core/Akka.TestKit/TestScheduler.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Akka.csproj, src/core/Akka/Util/Internal/RefEqualityComparer.cs
This PR mitigates the current bottlenecks in Akka.Remote:
- ActorPath parsing
- ActorRef resolving
The cache is backed by a ConcurrentDictionary which maps the string path straight to the ActorRef. An actor is responsible for the handling of cache maximum size and expiration with an LRU list.
There is two modes of operation:
This mode handles the caching of local actor refs backed with an ActorCell. It is bounded by the number of live actors in the system. The cache entries are cleared with DeathWatch notifications.
This mode caches all the actor refs not backed with an ActorCell (e.g. RemoteActorRef). It is bounded by the `maximum-remote-cache-size` setting, the least recently used actor refs are removed first when the maximum capacity is reached.
The cache entries in this mode are also …
=> Implemented ActorRef caching in Akka.Remote

src/core/Akka.Persistence.Tests/PersistenceConfigSpec.cs
This PR introduces 2 persistence tests which checks if the same `Journal` / `SnapshotStore` class can be registered many times using different hocon paths, and if the config passed to each instance matches registered path.
=> Specs for checking register same journal/snapshot store under different config paths

src/core/Akka/Event/EventStream.cs
Moved the subscribe debug-log message in such a way that the message is
published after the subscribe completes.
=> Fix for #2053

src/core/Akka.Cluster.Tests.MultiNode/ConvergenceSpec.cs
Resolves issue with `ConvergenceSpec` cleanup per #2067
=> fixed Akka.Cluster.Tests.MultiNode.ConvergenceSpec

src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj, src/core/Akka.Streams.TestKit.Tests/Akka.Streams.TestKit.Tests.csproj
This PR removes duplicate target entries, ```Microsoft.CSharp.targets```, inside a couple of the csproj  files.
=> [build] Removed duplicate entries

src/core/Akka.Cluster/ClusterDaemon.cs
When a new incarnation of a node joins a Cluster, i.e. restarting after becoming `Unreachable`, the `Cluster` will automatically `Down` the previous incarnation of that node was `MemberStatus.Up`. 
This change relaxes that constraint so it doesn't matter what the previous `MemberStatus` was - so if a node ends up becoming unreachable and restarting during the middle of leaving the cluster, a new incarnation can still successfully join.
I've noticed this issue from time to time in our MNTR logs, but also saw that the JVM had an issue for it earlier this year: https://github.com/akka/akka/issues/19859
=> relaxed constraints for automatically downing previous incarnations of Cluster members

src/core/Akka.Cluster.Tests.MultiNode/AttemptSysMsgRedeliverySpec.cs
Compilation broke due to a sequencing in merging where I changed the namespace of the `Akka.Cluster.TestKit` base classes to reflect the name of the assembly. Going to merge this in right away so the `dev` branch can build.
=> fixes a compilation issue caused by a namespace change in the Akka.Cluster.TestKit

src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingFailureSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingLeavingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonConfigSpec.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Cluster.Tests/AutoDownSpec.cs, src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs, src/core/Akka.Cluster.Tests/ClusterDeployerSpec.cs, src/core/Akka.Cluster.Tests/ClusterDomainEventPublisherSpec.cs, src/core/Akka.Cluster.Tests/ClusterDomainEventSpec.cs, src/core/Akka.Cluster.Tests/ClusterSpec.cs, src/core/Akka.Cluster.Tests/GossipSpec.cs, src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs, src/core/Akka.Cluster.Tests/ReachabilitySpec.cs, src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterEvent.cs, src/core/Akka.Cluster/ClusterSettings.cs, src/core/Akka.Cluster/Configuration/Cluster.conf, src/core/Akka.Cluster/Gossip.cs, src/core/Akka.Cluster/Reachability.cs, src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs, src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka/Actor/Address.cs
Implemented these stories
- Exclude unreachable observations from downed node: https://github.com/akka/akka/issues/13875
- Investigate if expected-response-after can be removed: https://github.com/akka/akka/issues/17750
- Cluster: need to be able to perform self-join using local address: https://github.com/akkadotnet/akka.net/issues/1983
- logging selfRoles during node unreachable and quarantined: https://github.com/akka/akka/issues/20613
- Add a helper method to Cluster extension to get full ActorPath: https://github.com/akka/akka/issues/19086
- disable down-removal-margin by default https://github.com/akka/akka/issues/18337
- used FluentAssertions everywhere
Reviewed these cluster specs
- ClusterDomainEventSpec
- GossipSpec
- ReachabilitySpec
- AutoDownSpec
- ClusterConfigSpec
- …
=> Cluster specs update

src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Tests/Routing/ConsistentHashingRouterSpec.cs
Closes #2111.
Pretty sure the issue was our use of `RemainingOrDefault` and mixing of timespans - some calls may take longer than others due to scheduling. This encapsulates everything in a `Within` block to ensure the entire test completes as a unit within the allotted timeframe.
=> close #2111 - wrapped all RemotingSpec.Remoting_must_lookup_actors_across_node_boundaries waits in Within block

src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj, src/core/Akka.Cluster.Tests.MultiNode/NodeChurnSpec.cs, src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs, src/core/Akka.Cluster.Tests/VectorClockSpec.cs, src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterEvent.cs, src/core/Akka.Cluster/ClusterRemoteWatcher.cs, src/core/Akka.Cluster/Gossip.cs, src/core/Akka.Cluster/VectorClock.cs
- Prune vector clocks from removed member (https://github.com/akka/akka/pull/17624)
- Improve cluster downing (https://github.com/akka/akka/pull/17646)
- Require at least one subscribe class (https://github.com/akka/akka/pull/17882)
- Make cluster.joinSeedNodes equivalent to conf seed-nodes (https://github.com/akka/akka/issues/17362)
- Ported NodeChurnSpec
- Ported TransitionSpec (in a progress)
Reviewed:
- VectorClockSpec.cs
- Cluster.cs
- ClusterEvent.cs
- ClusterDaemon.cs
- ClusterRemoteWatcher.cs
- VectorClock.cs
In a progress:
- Gossip.cs
- Member.cs
- ClusterActorRefProvider.cs
- ClusterHeartbeat.cs
- ClusterReadView.cs
- Reachability.cs
=> [WIP] Cluster refactoring. Part 2

src/core/Akka.NodeTestRunner/Program.cs
Reason why NodeChurn spec was failing: it's a long running spec and can run longer than the 90 seconds currently used as the maximum timeout.
This spec increases the timeout to 5 minutes - a better solution would be to make this configurable per-spec but with the way we use XUnit2 I can't access any of those properties from the NodeTestRunner directly.
=> increased NodeTestRunner max wait timeout

src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj, src/core/Akka.Remote.Tests.MultiNode/RemoteNodeRestartGateSpec.cs
replaces https://github.com/akkadotnet/akka.net/pull/1666 - fixed some minor issues with the spec which allow it to pass.
=> 1252 remote node restart gate spec

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.TestKit/MultiNodeSpec.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj, src/core/Akka.Remote.Tests.MultiNode/RemoteReDeploymentSpec.cs, src/core/Akka/Actor/ActorCell.FaultHandling.cs, src/core/Akka/Actor/ExtendedActorSystem.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs
Fixed some bugs with the Akka.Remote.TestKit that caused this spec not to pass. Also implemented `ActorSystemImpl.Abort`.
=> #1255 Remote redeployment spec

build.fsx, src/contrib/persistence/Akka.Persistence.Query.Sql/Akka.Persistence.Query.Sql.csproj, src/contrib/persistence/Akka.Persistence.Query.Sql/Akka.Persistence.Query.Sql.nuspec
This will add `Akka.Persistence.Query.Sql` as a new NuGet package. 
Question: does `Akka.Persistence.Query.Sql.Tests` should be a nuget package too? (It will be necessary for 3rd party SQL plugins)
=> Added nuspec for Akka.Persistence.Query.Sql

src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj, src/core/Akka.Cluster.Tests.MultiNode/LeaderDowningAllOtherNodesSpec.cs, src/core/Akka.Cluster.Tests/ClusterHeartBeatSenderStateSpec.cs, src/core/Akka.Cluster.Tests/HeartbeatNodeRingSpec.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterHeartbeat.cs, src/core/Akka.Cluster/Gossip.cs
- Implemented LeaderDowningAllOtherNodesSpec (https://github.com/akkadotnet/akka.net/issues/2003)
- Expand the monitored nodes when unreachable (https://github.com/akka/akka/pull/16677)
- Partly implemented - Improve cluster startup thread usage (https://github.com/akka/akka/pull/18332)
Reviewed these cluster specs:
- ClusterHeartbeatSenderStateSpec
- HeartbeatNodeRingSpec
=> Implemented LeaderDowningAllOtherNodesSpec

RELEASE_NOTES.md
**Feature Release for Akka.NET**
In Akka.NET 1.1 we introduce the following major changes:
* Akka.Cluster is no longer in beta; it is released as a fully stable module with a frozen API that is ready for production use.
* Akka.Remote now has a new Helios 2.1 transport that is up to 5x faster than the previous implementation and with tremendously lower memory consumption.
* The actor mailbox system has been replaced with the `MailboxType` system, which standardizes all mailbox implementations on a common core and instead allows for pluggable `IMessageQueue` implementations. This will make it easier to develop user-defined mailboxes and also has the added benefit of reducing all actor memory footprints by 34%.
* The entire router system has been updated, including support for new …
=> Akka.NET 1.1 Stable Release (Dev)

src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Futures.cs
cancelling timeout CancellationToken in Ask in order to prevent memory leaks -- a reference to 'result' variable is stored in CancellationToken's callback which prevents it from garbage collection. it's a huge problem when your timeout value is more or less big and your actor returns big data:
```csharp
public sealed class LeakActor : ReceiveActor
{
public LeakActor()
{
Receive<GetDataMessage>(message => Sender.Tell(new byte[10000]));
}
public sealed class GetDataMessage { }
}
```
then call it somewhere:
```csharp
for (var index = 0; index < 10000; index += 1)
{
await greeter.Ask<byte[]>(new LeakActor.GetDataMessage(), TimeSpan.FromSeconds(10));
}
```
the next calls were rearranged because a future actor should set result before _unregister() cancels Token:
```csharp …
```
=> 'Ask' memory leak

documentation/akkadoc.shfbproj
This PR updates the Sandcastle build file to add the api docs of the newly added
projects (Akka.Persistence.Query, Akka.Streams and Akka.Streams.TestKit).
I also rearranged the entries in alphabetical order so that it would be
easier to find missing entries in the future.
=> [api-docs] Updated Sandcastle build file

src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Given the following setup:
- Node: client (cluster client using remoting)
- Node: lighthouse (seed node for cluster)
- Node: worker (cluster member)
where both `lighthouse` and `worker` start `ClusterClientReceptionist`
but only the `worker` node registers a service (`/user/worker`).
If the `client` node uses the `lighthouse` node as the only value in
`initial-contacts` and attempts to send a message to `/user/worker`, the
log on the `lighthouse` node indicates that it received the message, but
the `worker` node never does.
With this change, the `worker` node will now receive the message.
=> Fixes handling of messages intended for another node

src/core/Akka/Actor/BuiltInActors.cs
DeadLetterActorRef.TellInternal should process DeadLetter like [ActorRef.scala](https://github.com/akka/akka/blob/60fb163331aa2f9c22e27a9fc424f5975bc45d13/akka-actor/src/main/scala/akka/actor/ActorRef.scala#L582). Without this fix, `Watch` sent to already stopped actor will publish unncessary `DeadLetter` event.
=> Fix a bug that handled DeadLetters are published.

src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
=> DistributedPubSub: Use TypeQualifiedNameForManifest with Manifest required Serializers

src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteAllPersistenceIdsSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteEventsByPersistenceIdSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteEventsByTagSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteJournalQuerySpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteJournalSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs
The Persistence.Sql.Common code and sqlite.conf referred to a variable called metadata-table-name.  SqliteJournal.cs and many unit tests referred to meta-table-name.  
The unit tests passed before because the default value of metadata-table-name in sqllite.conf plus their manually configured meta-table-name variables defined in test worked out to cover both cases (and set them to the same name), but if you were to create a new project and assume the default name would cover all bases, you'd be wrong.  To get a sqlite persistence working in a new app I found I had to set both metadata-table-name and meta-table-name to the same value to get things to work.  Out of the box, following the sqlite modules directions, the sqlite persistence engine would not work right.
This PR standardizes all …
=> meta-table-name replaced with metadata-table-name

src/core/Akka.Streams.Tests.TCK/FilePublisherTest.cs
closes #2179 
Was able to reproduce it locally, run it several times without any issue after the fix.
=> Use a unique file for every FilePublisherTest

src/core/Akka.Remote.TestKit.Tests/Akka.Remote.TestKit.Tests.csproj, src/core/Akka.Remote.TestKit.Tests/packages.config, src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj, src/core/Akka.Remote.TestKit/packages.config, src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote.Tests/Transport/HeliosTransportDnsResolutionSpec.cs, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs, src/core/Akka.Remote/packages.config, src/examples/Cluster/ClusterSharding/ClusterSharding.Node/ClusterSharding.Node.csproj, src/examples/Cluster/ClusterSharding/ClusterSharding.Node/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/ClusterToolsExample.Node.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/ClusterToolsExample.Seed.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/ClusterToolsExample.Shared.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/packages.config, src/examples/TimeServer/TimeClient/App.config, src/examples/TimeServer/TimeClient/TimeClient.csproj, src/examples/TimeServer/TimeClient/packages.config, src/examples/TimeServer/TimeServer/TimeServer.csproj, src/examples/TimeServer/TimeServer/packages.config
Resolves #2161
upgraded to Helios 2.1.2; set default DNS resolution target to IPV4; made DNS resolution configurable via HOCON.
=> fix for DNS resolution issues

RELEASE_NOTES.md
**Maintenance release for Akka.NET v1.1**
Akka.NET 1.1.1 addresses a number of bugs and issues reported by end users who made the upgrade from Akka.NET 1.0.* to Akka.NET 1.1. 
**DNS improvements**
The biggest set of fixes included in Akka.NET 1.1.1 deal with how the Helios transport treats IPV6 addresses and performs DNS resolution. In Akka.NET 1.0.* Helios only supported IPV4 addresses and would use that as the default for DNS. In Akka.NET 1.1 we upgraded to using Helios 2.1, which supports both IPV6 and IPV4, but *changed the default DNS resolution strategy to use IPV6.* This caused some breakages for users who were using the `public-hostname` setting inside Helios in combination with a `hostname` value that used an IPV4 address.
This is now fixed - Akka.NET 1.1.1 uses Helios 2.1.2 …
=> added release notes for 1.1.1 [dev]

src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence/SnapshotProtocol.cs
Linked commit: https://github.com/akkadotnet/akka.net/commit/4a95a1e02da0041cbc9f89787328fa395c5c7d9c
Fixed that: https://github.com/akkadotnet/akka.net/issues/2203
=> Add lower bounds to SnapshotSelectionCriteria API Approval

src/core/Akka/Dispatch/MessageQueues/UnboundedMailboxQueue.cs
For queues that are longer than one segment (32 messages) this may reduce the check.
=> Using supported IsEmtpy for non-mono UnboundedMailboxQueue.

src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs, src/core/Akka.Streams/CodeGen/Dsl/GraphApply.cs
- New method: `Graph.CreateMaterialized` which allows to use GraphDsl.Builder with custom generic type parameter. This is necessary, because currently there is no way to use Graph API returning graphs with custom materializer type. 
- Changed signatures of internal `AtLeastOnceDeliverySemantic` messages to public. This is also necessary, since using this object as separate component (instead of internal field of `AtLeastOnceDeliveryActor`) causes problems when internal messages, such as `RedeliveryTick`, arrive to user actors.
=> Exposed API for for materialized graph builder and at-least-once-delivery semantic messages

src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote.Tests/Transport/HeliosTransportDnsResolutionSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs
Hi all. I've faced issue #2194 running Akka inside Azure WebApp. 
It is related to Ipv6 dns lookup not available in some cases.
To solve it we need to enforce ipv4 usage inside sockets used by Helious.
I've introduced new configuration variable for it, "enforce-ip-family".
According to #2194 it will be always need in Mono, so in Mono environment 
default value is true. 
Most of Akka.Net should not be affected by #2194 and will not care about new setting.
=> related to #2194

src/core/Akka/Configuration/Config.cs
This is related to issue #2274 
```Config.GetStringList``` returns an empty array instead of an empty list
=> Issue #2274

src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
We have this problem in PersistentFSM.
'''
return this.GoTo(newState).Applying(event1).Applying(event2).Applying(event3);
'''
In this case `event1` will be applied 3 times, `event2` 2 times and `event3` 1 time.
This PR fixes it.
=> PersistentFSM Removes events duplication on stacked Applying

src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/EventsByTagSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteConfigSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteQueryExecutor.cs, src/contrib/persistence/Akka.Persistence.Sqlite/README.md
This PR introduces new Ordering column to journal. It's used for ordering persistent queries operating on event tags. It fixed problem mentioned in #2257 . It should be followed by the PRs on the SqlServer and PostgreSQL implementations.
=> Fixed ordering issues for tagged persistence query (SQL)

src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Solution of https://github.com/akkadotnet/akka.net/issues/2226
Handles the midnight issue and I don't think that timestamp point of start is a problem.
=> Fix of #2226. DistributedPubSubMediator.NextVersion will use ticks

src/core/Akka.Tests/Routing/ResizerSpec.cs
We have these marked as skipped on TC right now. Given the relatively low priority of fixing these specs (they're designed to scale up and down dynamically anyway) I'm marking them as skipped in the source itself for now.
=> skip flaky Resizer specs

src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs, src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerStartupSpec.cs, src/core/Akka.MultiNodeTestRunner/Program.cs, src/core/Akka.Remote.TestKit/BarrierCoordinator.cs, src/core/Akka.Remote.TestKit/Extension.cs, src/core/Akka.Remote.TestKit/Player.cs
=> Fixed folder output, barrier spec failure handling issues in MNTR

build.fsx, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj, src/core/Akka.Cluster.Tests.MultiNode/Routing/ClusterBroadcastRouter2266BugfixSpec.cs, src/core/Akka.Cluster.Tests/ClusterDeployerSpec.cs, src/core/Akka.Cluster/ClusterActorRefProvider.cs, src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs, src/core/Akka/Actor/Deployer.cs, src/examples/Chat/ChatServer/Program.cs
=> Clustered routers now load correct default number of routees

RELEASE_NOTES.md, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs
**Maintenance release for Akka.NET v1.1**
Akka.NET 1.1.2 introduces some exciting developments for Akka.NET users.
**Mono Support and Improved IPV4/6 Configuration**
First, Akka.NET 1.1.2 is the first release of Akka.NET to be production-certified for Mono. We've made some changes to Akka.Remote, in particular, to design it to work within some of the confines of Mono 4.4.2. For instance, we now support the following HOCON configuration value for the default Helios TCP transport:
```
helios.tcp {
transport-protocol = tcp
port = 2552
hostname = ""
public-hostname = ""
dns-use-ipv6 = false
enforce-ip-family = false
}
```
`helios.tcp.enforce-ip-family` is a new setting added to the `helios.tcp` transport designed to allow Akka.Remote to function in environments that don't support IPV6. This …
=> 1.1.2 release notes

src/contrib/dependencyinjection/Akka.DI.TestKit/DiResolverSpec.cs
Added missing type registrations in DiResolverSpec to resolve an issue
where some DI libraries would fail tests because the actor being
resolved through the DI system was not registered (autofac to name one)
=> Fixed missing type registrations in DiResolverSpec

src/core/Akka/Serialization/Serialization.cs
A `KeyNotFoundException` can occur if the serializer dll is not present in the search paths for binaries. This can occur when there is a proj A that depends on B and B depends on Akka. There is no direct reference to any of the serializers in either A or B besides being referenced in HOCON. MSBuild likes to optimize dlls out of the output if they are not directly referenced in code.
=> Fix Serialization KeyNotFoundException when looking up serializers

src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt, src/core/Akka.Cluster.Tests/ClusterSpec.cs, src/core/Akka.Cluster/Cluster.cs
close #2280 
Also tried to implement the `leave-on-termination` feature in HOCON, but unfortunately the `TerminationHooks` implemented in `ActorSystem` don't support this - they always run *after* the actors have shut down. We'd need something that runs *before* the ActorSystem has shut down the actors to implement this correctly.
Therefore, I think the smartest thing to do is when developing an Akka.Cluster application, always call `Cluster.LeaveAsync` -> `ActorSystem.Terminate` in that order when you're ready to shut down.
=> added Cluster.LeaveAsync for graceful exit

src/core/Akka/Pattern/CircuitBreaker.cs
CircuitBreaker swallowing stack trace of exception cased it to become Open. 
It makes debug harder
=> Fix CircuitBreaker swallowing exceptions cased it to open

src/core/Akka.Tests/Actor/ActorSystemSpec.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs
It's a bit confusing seeing warning which prints akka configuration on staging machine .
I was confused and tried to figure out if there are any problems with this configuration, because it is WARNING.
In the original akka it logs it with INFO level instead. And it's fine.
http://doc.akka.io/docs/akka/2.4/scala/logging.html#Auxiliary_logging_options
> Log the complete configuration at INFO level when the actor system is started.
> This is useful when you are uncertain of what configuration is used.
> log-config-on-start = on
Here is the scala source code:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L572
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L662
Here is the net source code: …
=> The log-config-on-start option fixed to log with INFO level.

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs, src/core/Akka/Pattern/CircuitBreaker.cs
After Akka.Persistence upgrade to 1.1.2 sql journal started to fetch events with undetermined order, 
not caring about SequenceNr column. 
After we changed PK from (PersistenceId, SequenceNr) to (Ordering) raws in table no longer ordered by SequenceNr, so ordering should be declared explicitly
=> Get events from sql journal db in right sequence

src/contrib/cluster/Akka.DistributedData/WriteAggregator.cs, src/core/Akka.Remote.TestKit/DataTypes.cs, src/core/Akka.Remote.TestKit/Player.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka/Actor/ActorCell.FaultHandling.cs, src/core/Akka/Actor/Futures.cs
all high priority issues here https://gist.github.com/maxim-s/41ef6139bebe0e728594f5ded28f2b58
=> [WIP] fix static analized high priority issues

src/core/Akka.Tests/Actor/AskTimeoutSpec.cs, src/core/Akka/Actor/Futures.cs
Reverts akkadotnet/akka.net#2381
Have to revert this. Causes enormous, like hundreds of MBs worth of "unregister temp actor spam" in all of our logs. Can't ship it like this. Need to address that logging issue first.
=> Revert "Unregister temp actor if ask operation got canceled."

src/core/Akka/Actor/SupervisorStrategy.cs
Reference System.Threading.Timeout.InfiniteTimeSpan which is used by the internal code instead of Duration.Inf which appears to be a Java Akka specific constant.
=> Change doc comment references to Duration.Inf

src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
Singleton handover does not work because of matching messages against singleton instances instead of type
=> singleton handover message matching fix

src/core/Akka/Actor/SupervisorStrategy.cs
While working i noticed the XML comments for the OneForOne and AllForOne supervisorStrategies could be better. 
And the comments on the constructors where plain wrong. The OneForOne described the functionality of the AllForOne and vice versa. This fixes that.
=> Fix XML comments for SupervisorStrategies

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/ActorSystemTests.cs, src/core/Akka.Tests/Actor/DeployerSpec.cs, src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka/Configuration/Config.cs, src/core/Akka/Configuration/Hocon/HoconObject.cs, src/core/Akka/Configuration/Hocon/HoconValue.cs
Fix for [2404](https://github.com/akkadotnet/akka.net/issues/2404)
Note that configs logging on start producing more verbose output as a side effect of changes in implementation;
Also note that we may no more needing `public Config Fallback { get; private set; }`
I didn't removed it since its public, however its only used in Config.cs;
There is also room for optimisation [see here](https://github.com/akkadotnet/akka.net/issues/2404#issuecomment-266321385)
=> GetNode do not lookups fallback config; config produced by WithFallbck contains all values from provided fallback

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/AskSpec.cs, src/core/Akka/Actor/Futures.cs
This is taking Zetanova's commits from [PR #1632](https://github.com/akkadotnet/akka.net/pull/1632) in January, rebasing and doing all the merging to keep them current against the dev branch, and adding in the [changes](https://github.com/akkadotnet/akka.net/pull/1632#issuecomment-193860389) necessary to make the public API tests pass. [Additionally](https://github.com/akkadotnet/akka.net/pull/1632#issuecomment-253962723), one untested optimization was left out in the merge, and a test was renamed to follow adjustments to naming conventions.
The purpose is to allow the `Ask` extensions on `ICanTell` to be cancelled externally beyond just waiting for timeouts.
=> Updated Ask user cancellation rebase

src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj, src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMediatorSpec.cs
http://stackoverflow.com/questions/41249465/how-to-test-distributedpubsub-with-the-testkit-in-akka-net - just wanted to verify if this bug exists or not. My guess is that the end user needed to specify the `ClusterActorRefProvider` in their HOCON configuration
=> spec for verifying that DistributedPubSub mediator can be spawned from within child actor in testkit

src/core/Akka.Tests/Actor/AskSpec.cs, src/core/Akka.Tests/Actor/AskTimeoutSpec.cs, src/core/Akka/Actor/ActorRef.cs
This takes eisendle's idea of dealing with the temp actor unregistration issue on cancelled ask requests in #2380 and cherry-picks his test spec commit from PR #2381 , but handles it by calling the `unregister` action in a continuation inside of `FutureActorRef`. This should make the unregistration more consistent with `FutureActorRef` - ensuring that we clean up our resources once regardless of how the task turns out. I'm assuming there might be some back and forth in case it hits the same issue that caused the revert in #2399. Following up with this PR as a lot of people asked about #2381 when rebasing code in #2349.
It also adds two specs to make sure we clean up if we're basing the ask requests around cancellation requests or both timeouts and cancellation requests instead of just …
=> Make FutureActorRef call _unregister() in a task continuation.

src/core/Akka.Tests/Routing/RandomSpec.cs, src/core/Akka.Tests/Routing/RoundRobinSpec.cs, src/core/Akka/Routing/Random.cs
I was playing around with `RandomPool` and it turned out it works as thought it is `round robin`.
I checked the code and found the root of the problem :)
Looks like a simple copy-paste typo.
Here is a list of fixes and additional improvements:
- RandomLogic `Select Routee` upper bound fixed.
- RandomPool `CreateRouter` fixed to use proper random logic.
- RandomSpec improved to have additional check for stochasticity (some of all random values definitely should be different from `iterationCount`).
- RandomSpec additional tests added for `RandomGroup` and `RandomLogic`.
- RoundRobinSpec fixed to instantiate with proper round robin pools.
=> Fixed RandomLogic and RandomPool to work correctly.

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/BatchingSqliteJournal.cs
1. Now database exceptions for SQL batching journals are treated as write failures not rejections (as they should be).
2. Additional setting, `IsolationLevel`, that allows user to specify transaction isolation level used during query execution.
=> Updated batching journal behavior

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Dispatch/MessageQueues/UnboundedPriorityMailboxQueue.cs, src/core/Akka/Util/ListPriorityQueue.cs
close #2308 - realized that this was the result of a weird design choice on my part back when we were working on releasing 1.1. Should never change the priority generator function at runtime. Now it's set via a constructor and is immutable, which should eliminate the issue.
CC @ronnieoverby
=> fixed race condition with creating priority queue

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.Tests/RemotingTerminatorSpecs.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs, src/core/Akka/Actor/SupervisorStrategy.cs
1. Original ShutDownAssociation exception is not re-thrown, but rather escalated
2. EndpointManager's SupervisionStrategy default logging is turned off. Error logging will be done in the Decider itself in case of unexpected exceptions only
=> Akka.Remote - ShutDownAssociation exception logged during graceful stop

src/core/Akka.Tests/Actor/AskTimeoutSpec.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Futures.cs
=>  fixes race condition with AskTimeoutSpec

src/Akka.sln, src/contrib/serializers/Akka.Serialization.Wire/Akka.Serialization.Wire.csproj, src/contrib/serializers/Akka.Serialization.Wire/Properties/AssemblyInfo.cs, src/contrib/serializers/Akka.Serialization.Wire/WireSerializer.cs, src/contrib/serializers/Akka.Serialization.Wire/packages.config, src/contrib/serializers/Akka.Serialization.WireTests/Akka.Serialization.Wire.Tests.csproj, src/contrib/serializers/Akka.Serialization.WireTests/WireTests.cs, src/contrib/serializers/Akka.Serialization.WireTests/packages.config, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/examples/Cluster/ClusterSharding/ClusterSharding.Node/ClusterSharding.Node.csproj, src/examples/Cluster/ClusterSharding/ClusterSharding.Node/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/ClusterToolsExample.Node.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/ClusterToolsExample.Seed.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/packages.config, src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/ClusterToolsExample.Shared.csproj, src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/packages.config
This PR swaps out the underlying Wire dependencies for Hyperion, in order to stop our users from getting GPL'd by upgrading to a new version of Wire.
I propose doing this across two releases
1. Release the current Akka.Serailization.Wire, complete with Hyperion dependencies, to move net new users onto the latest Hyperion version.
2. Deprecate the Akka.Serialization.Wire package and replace it with a Akka.Serialization.Hyperion package and update the necessary documentation in a subsequent release.
Any thoughts on the above?
=> swapped out Wire references for Hyperion package

src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj, src/core/Akka.TestKit.Tests/TestActorRefTests/FsmActor.cs, src/core/Akka.TestKit.Tests/TestActorRefTests/TestActorRefSpec.cs, src/core/Akka.TestKit/TestKitBase_ActorOf.cs
close #1709 
Minor change, but it looks like #1709 is a non-issue. Will circle back with the user who reported it and see if I can get more information / verify that this spec actually addresses their issue.
=> verify that FSMs with constructor agruments can be instantiated

src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs
The old and new logs are in the issue #2452
=> Fixing Akka.Remote logging. We don't log the stack trace for known situations. (#2452)

src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaEqualException.cs, src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs, src/contrib/testkits/Akka.TestKit.Xunit/XunitAssertions.cs
=> [api-docs] Added TBD placeholders for Akka.TestKit.Xunit.csproj

src/contrib/persistence/Akka.Persistence.Sql.TestKit/AllPersistenceIdsSpec.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/EventsByPersistenceIdSpec.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/EventsByTagSpec.cs
As i have discovered before. XUnit in combination with the akka TestKit causes some wierd stuff sometimes.
One thing that happens is that state you expect to be reinitialized for each test is sometimes reused between tests.
Reference to where i encountered a similar case: http://stackoverflow.com/questions/40767924/testing-behavior-not-consistent-when-watching-actor-for-termination/40929659#40929659
What this PR does, is move the SqlReadJournal reference to the local scope. Thereby eliminating any chance there is concurrent access to that resource where its not expected.
The EventsByTagSpec might need more refactoring. But worked consistently locally on the SqlLite tests implementation whereas before are very racy.
=> Possible fix for racy sql testkit specs

src/core/Akka.Cluster.Tests.MultiNode/NodeChurnSpec.cs, src/core/Akka.Cluster.Tests/GossipSpec.cs, src/core/Akka.Cluster.Tests/ReachabilitySpec.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/Gossip.cs, src/core/Akka.Cluster/Reachability.cs, src/core/Akka.Remote.Tests/ActorsLeakSpec.cs
- [suppress deadletter for the cluster joining messages](https://github.com/akka/akka/pull/21156) [2.4.9]
- [harden NodeChurnSpec](https://github.com/akka/akka/pull/21141) [2.4.9]
- [Add a retry for a check for stopped actors](https://github.com/akka/akka/pull/21697) [2.4.12]
- [Reachability.remove didn't always remove all](https://github.com/akka/akka/pull/22016) [2.4.16]
- [don't use Down member as leader](https://github.com/akka/akka/pull/21990) [2.4.16]
=> Cluster updates to Akka JVM 2.4.16

build.fsx
Both https://github.com/akkadotnet/akka.net/pull/2509 and https://github.com/akkadotnet/akka.net/pull/2507 have run into issues where 15 minutes isn't long enough for them to complete their test suites for Akka.Tests.Performance. I've added 10 minutes to the timeout window to resolve this (and it will need to get longer the more specs we add to each assembly.)
=> increased FAKE nbench timeout from 15 to 25 minutes

src/core/Akka.Remote.Tests.MultiNode/RemoteGatePiercingSpec.cs
Stumbled upon this during search for examples of `NodeConfig` usages for docs.
Seems there was intention to assign different gating durations to each role.
Considering implementation of [NodeConfig](https://github.com/akkadotnet/akka.net/blob/fe2f30a9b7ccd6a3d406d5b47cd0cfc26b2d5e6e/src/core/Akka.Remote.TestKit/MultiNodeSpec.cs#L55) currently there is same config {gate-1d} with fallback {gate-1s} constructed for each node.
Spec is passing all this time but nevertheless it should be corrected.
=> Fixed NodeConfig usage in RemoteGatePiercingMultiNetSpec

src/contrib/serializers/Akka.Serialization.Hyperion.Tests/Akka.Serialization.Hyperion.Tests.csproj, src/contrib/serializers/Akka.Serialization.Hyperion.Tests/HyperionConfigTests.cs, src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj, src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializer.cs, src/contrib/serializers/Akka.Serialization.Hyperion/IKnownTypesProvider.cs, src/contrib/serializers/Akka.Serialization.Hyperion/reference.conf, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/Serialization/NewtonsoftJsonConfigSpec.cs, src/core/Akka.Tests/Serialization/SerializationSpec.cs, src/core/Akka/Configuration/Pigeon.conf, src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs, src/core/Akka/Serialization/Serialization.cs
Some of the users lack an ability to customize used serializers i.e. adding custom converters to json.net serializer. Another time some of them may want to harden serializer constraints on themselves in order to achieve better performance. This is especially a case with new Hyperion serializer, which uses things like preserving object references and version tolerance, which both increase the serialization time and a payload size, causing our default hyperion settings to be actually always a worst case scenario for that library.
This PR introduces an ability to add custom options to serializers through HOCON config. It can be used as a general purpose mechanism. From now, users may define their own serializer configuration within `akka.actor.serialization-settings` i.e.:
```hocon …
```
=> Customizable serializers

src/core/Akka.Cluster.Tests/ActorRefProvidersConfigSpec.cs, src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj, src/core/Akka/Actor/Settings.cs
This implements case mentioned in #2515 .
Instead of typing: 
- `akka.actor.provider = "Akka.Actor.LocalActorRefProvider"`
- `akka.actor.provider = "Akka.Remote.RemoteActorRefProvider, Akka.Remote"`
- `akka.actor.provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"`
we'll be able to just write:
- `akka.actor.provider = local`
- `akka.actor.provider = remote`
- `akka.actor.provider = cluster` 
Tests to ensure, that this actually happens are attached in this PR.
=> Added actor ref provider aliases

src/core/Akka.Streams.Tests/Dsl/FlowGroupedWithinSpec.cs, src/core/Akka.Streams/Implementation/Fusing/Ops.cs
This bug cost me several hours debugging and digging decompiled sources of completely unrelated assembly :suspect:
=> GroupedWithin no longer pushes empty IEnumerable when stopped immediately after start

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/SqlSnapshotStore.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/Akka.Persistence.Sql.TestKit.csproj, src/contrib/persistence/Akka.Persistence.Sql.TestKit/SqlJournalConnectionFailureSpec.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/SqlSnapshotConnectionFailureSpec.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/packages.config, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Akka.Persistence.Sqlite.Tests.csproj, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteConfigSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteJournalConnectionFailureSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteSnapshotStoreConnectionFailureSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs
Per Issue #2320, added try/catch to `SqlJournal.CreateDbConnection()` to catch and log failures in overridden calls to `CreateDbConnection(string connectionString)` by Akka.Persistence plugins.  Added new spec called `SqlJournalConnectionFailureSpec` that should be implemented by plugins to ensure that they don't swallow exceptions during establishing connection to Journal store.  Implemented said spec in Akka.Persistence.Sqlite.Tests as an example.  Also added missing xunit dependencies to Akka.Persistence.Sql.Testkit (i.e. xunit, xunit.core, etc)
=> Add logging behavior to Akka.Persistence SqlJournal to fail loudly when backend store connection cannot be established

build.fsx
Increase timeout for NBench task used in Performance Tests by TeamCity CI from 25 minutes to 45 minutes in build.fsx
=> Increase timeout for NBench target in build.fsx

build.fsx, src/contrib/transports/Akka.Remote.Transport.Helios/HeliosTcpTransport.cs, src/contrib/transports/Akka.Remote.Transport.Helios/HeliosTransport.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote.Tests/AsyncContext/AsyncContext.SynchronizationContext.cs, src/core/Akka.Remote.Tests/AsyncContext/AsyncContext.TaskQueue.cs, src/core/Akka.Remote.Tests/AsyncContext/AsyncContext.TaskScheduler.cs, src/core/Akka.Remote.Tests/AsyncContext/AsyncContext.cs, src/core/Akka.Remote.Tests/AsyncContext/AsyncEx.LICENSE, src/core/Akka.Remote.Tests/AsyncContext/BoundAction.cs, src/core/Akka.Remote.Tests/AsyncContext/Disposables.LICENSE, src/core/Akka.Remote.Tests/AsyncContext/ExceptionHelpers.cs, src/core/Akka.Remote.Tests/AsyncContext/SingleDisposable (of T).cs, src/core/Akka.Remote.Tests/AsyncContext/SynchronizationContextSwitcher.cs, src/core/Akka.Remote.Tests/AsyncContext/SynchronousTaskExtensions.cs.cs, src/core/Akka.Remote.Tests/AsyncContext/about.txt, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs, src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs, src/core/Akka.Remote/Transport/TransportAdapters.cs, src/core/Akka/Actor/ActorSelection.cs, src/core/Akka/Pattern/CircuitBreaker.cs, src/core/Akka/Pattern/CircuitBreakerState.cs, src/core/Akka/Routing/TailChopping.cs, src/core/Akka/Util/Internal/AtomicState.cs
The first test passes, the second test blocks indefinitely (even though I passed a timeout!).
This is probably an issue with a missing ``.ConfigureAwait(false)``.
``SynchronizationContextHelper`` was copied from here: http://stackoverflow.com/questions/14087257/how-to-add-synchronization-context-to-async-test-method
=> Fix deadlock when calling ActorSelection.ResolveOne from GUI context

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ActorCell.DeathWatch.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Actor/Deployer.cs, src/core/Akka/Util/FastLazy.cs, src/core/Akka/Util/Internal/Extensions.cs
Fix for #2539
Based on @alexvaluyskiy idea.
The trick is reusing `Parent`'s cached elements.
Can't compare two snapshots in dotMemory, hence two different screenshots.
Baseline:
Optimization:
=> ActorPath.Elements optimization

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs, src/core/Akka.Remote.TestKit/BarrierCoordinator.cs, src/core/Akka.Tests/Actor/FSMActorSpec.cs, src/core/Akka.Tests/Actor/FSMTimingSpec.cs, src/core/Akka.Tests/Actor/FSMTransitionSpec.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka/Actor/FSM.cs, src/core/Akka/Routing/Listeners.cs, src/core/Akka/Util/Internal/Extensions.cs
=> Akka Fsm Update

src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote.Tests/app.config, src/core/Akka.Remote.Tests/packages.config, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Remote/packages.config
Resolves issues we've had with DotNetty not allowing the main thread to exit without shutting down the `ActorSystem` first.
=> upgraded to DotNetty v0.4.3

src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence.Tests/Serialization/TestSerializers.cs, src/core/Akka.Persistence/Serialization/MessageSerializer.cs, src/core/Akka.Persistence/Serialization/SnapshotSerializer.cs, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj, src/core/Akka.Tests.Performance/Util/SerializationBenchmarks.cs, src/core/Akka/Serialization/Serialization.cs, src/core/Akka/Serialization/Serializer.cs
Related https://github.com/akkadotnet/akka.net/issues/2566
I've reused some parts of Scala implementation
**Before**: 1 400 243 ops/s
**After**: 4 551 167 ops/s
=> Make FindSerializerForType faster

src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs, src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientConfigSpec.cs, src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClient.cs, src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientSettings.cs, src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs, src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedMessages.cs, src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs, src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs, src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt, src/core/Akka.Cluster.Tests.MultiNode/SurviveNetworkInstabilitySpec.cs
- [stop ClusterClient ResponseTunnel after first reply when ask is used](https://github.com/akka/akka/pull/22123) [2.4.17]
- [minor cleanup of cluster.subscribe usage](https://github.com/akka/akka/pull/21813) [2.4.14] 
- the last public API changes
=> Stop ClusterClient ResponseTunnel after first reply when ask is used

src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams/CodeGen/Dsl/GraphApply.cs, src/core/Akka.Streams/Dsl/RunnableGraph.cs
It's a small improvement: a `GraphDSL.CreateMaterialized<TShape, TMat>` method. It's more flexible than `GraphDSL.Create<TShape>` method as it allows to construct from scratch a graph, than may have materialized value different than `NotUsed`. 
It's necessary, as there is no other way to build a generic `IGraph<TMat>` version - builder dsl constructors are internal. Personally I need this for building F# API for constructing graphs.
=> Added GraphDSL.CreateMaterialized method

src/contrib/persistence/Akka.Persistence.Sql.TestKit/EventsByPersistenceIdSpec.cs, src/contrib/persistence/Akka.Persistence.Sql.TestKit/TestActor.cs
PR in response to a set of tests deemed flaky by TeamCity CI.  Example here: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=21833&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaPersistenceImplementations_AkkaPersistenceSqlServer_PrBuilds#testNameId-488764090331667693
Test failures were due to the `DeleteCommand` being sent to the `TestActor` not completing the Journal cleanup before the assertions were being made against the cleaned-up Journal.
```
Failed: Expected a message of type Akka.Streams.TestKit.TestSubscriber+OnComplete, 
but received {TestSubscriber.OnNext(g1-1)} 
(type Akka.Streams.TestKit.TestSubscriber+OnNext`1[System.Object]) instead  
from [akka://test/user/StreamSupervisor-16/Flow-0-0-select#2080382836]
```
Revised `TestActor` to send acknowledgement to TestKit actor …
=> Revise TestActor used for EventsByPersistenceIdSpec to block until ack of Journal cleanup

src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs, src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs, src/contrib/dependencyinjection/Akka.DI.Core/DIActorContextAdapter.cs, src/contrib/dependencyinjection/Akka.DI.Core/DIActorProducer.cs, src/contrib/dependencyinjection/Akka.DI.Core/DIActorSystemAdapter.cs, src/contrib/dependencyinjection/Akka.DI.Core/DIExt.cs, src/contrib/dependencyinjection/Akka.DI.Core/Extensions.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs, src/contrib/persistence/Akka.Persistence.Sqlite/ConnectionContext.cs, src/core/Akka.Cluster.Tests/AutoDownSpec.cs, src/core/Akka.Cluster/ClusterActorRefProvider.cs, src/core/Akka.Cluster/Member.cs, src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs, src/core/Akka.MultiNodeTestRunner.Shared/Reporting/MultiNodeMessage.cs, src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs, src/core/Akka.Persistence/Journal/AsyncWriteProxy.cs, src/core/Akka.Persistence/Journal/ReplayFilter.cs, src/core/Akka.Persistence/JournalProtocol.cs, src/core/Akka.Persistence/Persistent.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/RemoteDeployer.cs, src/core/Akka.TestKit/EventFilter/Internal/ErrorFilter.cs, src/core/Akka/Actor/ActorBase.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/TypedActor.cs, src/core/Akka/Actor/UntypedActor.cs
This PR fleshes out more of the documentation labeled as TBD.
=> [api-docs] Even more documentation

src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs, src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubSettings.cs, src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxySettings.cs, src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Remote.Tests/RemotingSpec.cs, src/core/Akka.Streams.TestKit/TestGraphStage.cs, src/core/Akka.Streams/Actors/ActorPublisher.cs, src/core/Akka.Tests/Actor/PropsCreationSpec.cs, src/core/Akka.Tests/Akka.Tests.csproj, src/core/Akka.Tests/IO/UdpIntegrationSpec.cs, src/core/Akka/Actor/ActorCell.Children.cs, src/core/Akka/Actor/ActorCell.cs, src/core/Akka/Actor/IAutoReceivedMessage.cs, src/core/Akka/IO/TcpListener.cs, src/core/Akka/Routing/Router.cs
=> Added more messages which ignores the serialization

src/core/Akka.Remote/Configuration/Remote.conf
Update Remote.conf to show valid reference for enabling TLS for Akka.Remote using same configuration used in `DotNettySslSupportSpec`
=> Update Remote.conf reference HOCON with valid TLS settings for DotNettySslSupport

RELEASE_NOTES.md, build.fsx
**Feature Release for Akka.NET**
Akka.NET 1.2 is a major feature release that introduces the following major changes:
**Akka.Remote now uses [DotNetty](https://github.com/azure/dotnetty) for its transport layer**
The biggest change for 1.2 is the removal of Helios 2.0 as the default transport and the introduction of DotNetty. The new DotNetty transport is fully backwards compatible with the Helios 1.4 and 2.* transports, so you should be able to upgrade from any Akka.NET 1.* application to 1.2 without any downtime. All of the `helios.tcp` HOCON is also supported by the DotNetty transport, so none of that needs to updated for the DotNetty transport to work out of the box.
In addition, the DotNetty transport supports TLS, which can be enabled via the following HOCON:
```
akka {
loglevel = …
```
=> V1.2 release (dev)

build.fsx
Update dependency on Akka.Cluster.Tools for NuGet pack step in build.fsx to use release.NugetVersion instead of preReleaseVersion.
=> Switch Akka.Cluster.Sharding NuGet dependency for Akka.Cluster.Tools to NuGet release version

build.fsx
Update Akka.Streams.TestKit dependency for Akka.Persistence.Sql.TestKit to v1.2 stable release.
=> Update Akka.Streams.TestKit dependency for Akka.Persistence.Sql.TestKit to v1.2 stable

src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj, src/core/Akka.FSharp.Tests/app.config, src/core/Akka.FSharp.Tests/packages.config, src/core/Akka.FSharp/Akka.FSharp.fsproj, src/core/Akka.FSharp/packages.config, src/core/Akka.Persistence.FSharp/Akka.Persistence.FSharp.fsproj, src/core/Akka.Persistence.FSharp/packages.config, src/examples/FSharp.Api/FSharp.Api.fsproj, src/examples/FSharp.Deploy.Local/FSharp.Deploy.Local.fsproj, src/examples/FSharp.Deploy.Local/packages.config, src/examples/FSharp.Deploy.Remote/FSharp.Deploy.Remote.fsproj, src/examples/FSharp.Deploy.Remote/packages.config, src/examples/HelloWorld/FSharp.HelloAkka/FSharp.HelloAkka.fsproj, src/examples/HelloWorld/FSharp.HelloAkka/packages.config, src/examples/PersistenceExample.FsApi/PersistenceExample.FsApi.fsproj, src/examples/PersistenceExample.FsApi/packages.config
+ FSharp.Core dependency comes from nuget
+ Getting rid of <TargetFSharpCoreVersion>4.3.1.0</TargetFSharpCoreVersion> tag as it's not used inside the `fsproj` and it's making a confusion
`System.ValueTuple` is brought along with the latest FSharp.Core.dll
=> Update F# projects to the last FSharp.Core version (4.4.1.0)

build.fsx, src/core/Akka.Persistence.Tests/Properties/AssemblyInfo.cs
Disable test parallelization for Persistence.Tests to mitigate OutOfMemory exceptions in CI.  Should be applied to all test projects, but this is to see if there is an effect on the current CI test failures.
=> Disable test parallelization for Persistence.Tests

build.fsx, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/Akka.Cluster.Sharding.Tests.MultiNode.csproj, src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj, src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj, src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj, src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/Akka.DistributedData.Tests.MultiNode.csproj, src/contrib/cluster/Akka.DistributedData.Tests/Akka.DistributedData.Tests.csproj, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Akka.Persistence.Sqlite.Tests.csproj, src/contrib/serializers/Akka.Serialization.Hyperion.Tests/Akka.Serialization.Hyperion.Tests.csproj, src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.csproj, src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj, src/core/Akka.API.Tests/Akka.API.Tests.csproj, src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj, src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj, src/core/Akka.Cluster.Tests/ClusterSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared.Tests/Akka.MultiNodeTestRunner.Shared.Tests.csproj, src/core/Akka.Persistence.Query.Tests/Akka.Persistence.Query.Tests.csproj, src/core/Akka.Persistence.TestKit.Tests/Akka.Persistence.TestKit.Tests.csproj, src/core/Akka.Persistence.TestKit/Snapshot/SnapshotStoreSpec.cs, src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj, src/core/Akka.Remote.TestKit.Tests/Akka.Remote.TestKit.Tests.csproj, src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj, src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Streams.TestKit.Tests/Akka.Streams.TestKit.Tests.csproj, src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj, src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj, src/core/Akka.Tests/Akka.Tests.csproj
Try to use consistent xunit runner for Linux and Windows that will also run against `net452;netcoreapp1.1` test assemblies.  This was introduced in https://www.nuget.org/packages/dotnet-xunit/2.3.0-beta2-build3683.
It also allows us to pass xunit arguments to `dotnet xunit` the same way it was being done before, e.g. `-parallel none -teamcity`
=> [WIP] Replace dotnet test with dotnet xunit (v2.3.0)

build.fsx, build.ps1, src/core/Akka.Cluster.Tests.Performance/Akka.Cluster.Tests.Performance.csproj, src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj, src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj, src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
Adds build step NBench and upgrades NBench to v1.0.1 to enable performance testing on v1.3 branch.
=> Enable performance tests on Windows/.NET Framework

docs/articles/actors/dependency-injection.md, docs/articles/concepts/addressing.md, docs/articles/concepts/message-delivery-reliability.md, docs/articles/remoting/index.md, docs/articles/streams/basics.md, docs/articles/streams/buffersandworkingwithrate.md, docs/articles/streams/builtinstages.md, docs/articles/streams/cookbook.md, docs/articles/streams/customstreamprocessing.md, docs/articles/streams/designprinciples.md, docs/articles/streams/error-handling.md, docs/articles/streams/introduction.md, docs/articles/streams/modularitycomposition.md, docs/articles/streams/pipeliningandparallelism.md, docs/articles/streams/quickstart.md, docs/articles/streams/reactivetweets.md, docs/articles/streams/stream-dynamic.md, docs/articles/streams/testingstreams.md, docs/articles/streams/workingwithgraphs.md, docs/articles/streams/workingwithstreamingio.md
Add a space after # in all doc files.
=> Documentation titles clean-up.

src/core/Akka/Dispatch/MessageQueues/UnboundedMessageQueue.cs, src/core/Akka/Dispatch/MessageQueues/UnboundedPriorityMessageQueue.cs
_( This is for issue #2696. )_
Two of the MessageQueue classes had file names that did not match the classes they contained.
* UnboundedMailboxQueue.cs -> UnboundedMessageQueue.cs
* UnboundedPriorityMailboxQueue.cs -> UnboundedPriorityMessageQueue.cs
=> renaming the unbounded mailbox queue files

src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs, src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
port of
https://github.com/akka/akka/issues/21725
https://github.com/akka/akka/issues/22916
=> sharding snapshot & journal cleanup

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.TestKit/Internal/Reference.conf, src/core/Akka/Actor/TypedActor.cs
We already encouraged users away from using `TypedActor` and were talking about removing it from the API but no steps were made. This PR adds obsoletes a `TypedActor` class.
Additional feature - it sets up an `akka.suppress-json-serializer-warning = on` in all tests. I think that having JSON serializer warning is useless in case of tests and only adds an unnecessary noise for test output (as it will be printed at least once per each test).
=> Obsoleted TypedActor

src/core/Akka.Cluster.Tests/ActorRefProvidersConfigSpec.cs, src/core/Akka.Cluster.Tests/ClusterSpec.cs, src/core/Akka.Cluster.Tests/DowningProviderSpec.cs, src/core/Akka.Tests/Routing/TailChoppingSpec.cs, src/core/Akka/Actor/ActorSystem.cs
I've looked through some of these and the reasons for the raciness in most of these specs are due to issues where sockets aren't being cleaned up quickly enough or the timeouts are too narrowly defined. There might be some legitimate bugs with the specs here too, so I'm going to go through each one and submit some patches for each in the name of making our build process run more smoothly.
Current list:
The common thread with most of these issues is that they use the real socket system underneath Akka.Remote, so I suspect it's a problem with how that's being used / not giving it enough time.
I'm also going to see if these failures might be related to https://github.com/akkadotnet/akka.net/issues/2575 - which I was planning on fixing anyway. Stay tuned.
=> Cleaning up racy specs part1

src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
fixes https://github.com/akkadotnet/akka.net/issues/2713
=> read Environment.ProcessorCount once into a static

build.fsx, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Akka.Persistence.Sqlite.Tests.csproj, src/contrib/persistence/Akka.Persistence.Sqlite/Akka.Persistence.Sqlite.csproj, src/core/Akka.Persistence.TestKit.Tests/LocalSnapshotStoreSpec.cs, src/core/Akka.Persistence.TestKit/Snapshot/SnapshotStoreSpec.cs
Partially fixes https://github.com/akkadotnet/akka.net/issues/2659
=> Enable Sqlite tests, uncommented snapshot tests in Persistence.Testkit

src/core/Akka/Routing/Broadcast.cs, src/core/Akka/Routing/ConsistentHash.cs, src/core/Akka/Routing/ConsistentHashRouter.cs, src/core/Akka/Routing/Listeners.cs, src/core/Akka/Routing/Random.cs, src/core/Akka/Routing/ResizablePoolActor.cs, src/core/Akka/Routing/Resizer.cs, src/core/Akka/Routing/RoundRobin.cs, src/core/Akka/Routing/RoutedActorCell.cs, src/core/Akka/Routing/RoutedActorRef.cs, src/core/Akka/Routing/Router.cs, src/core/Akka/Routing/RouterActor.cs, src/core/Akka/Routing/RouterConfig.cs, src/core/Akka/Routing/RouterPoolActor.cs, src/core/Akka/Routing/ScatterGatherFirstCompleted.cs, src/core/Akka/Routing/SmallestMailbox.cs, src/core/Akka/Routing/TailChopping.cs
This PR refactors the classes in the Akka.Routing namespace to take
advantage of newer C# features.  It also simplifies some of the logic in
the various routers.
=> [routing] Akka.Routing refactoring

src/core/Akka.Streams/Akka.Streams.csproj, src/core/Akka.TestKit/Akka.TestKit.csproj, src/core/Akka/Akka.csproj
In older versions of VS, the template was the parent of the .cs file.
The current layout doesn't reflect this making both the T4 template and
the code live side by side. This clutters up the Solution Explorer
slightly.
This PR fixes the visual issue with those templates.
=> [misc] Fix T4 templates in projects

docs/articles/remoting/transports.md
Updated the docs to illustrate the use of dot-netty instead of helios. I updated alot of links as well. Made them relative where i can, so the should point to the right document. But i can't be sure untill the site is updated.
Furthermore there is a section in there about how to configure multiple transports. That uses the TCP and UDP transport as an example. However how its written now suggest we actually have an UDP transport available for use. 
As far as i know, this isn't true. But i could be missing something. @Aaronontheweb  ?
Eitherway i'd like to change that part abit, to avoid confusion.
=> Bringing Remote transports docs up to date. #2670

build.fsx
Using the new `dotnet xunit` tooling seems to cause different exit codes upon test failures:
```
[12:43:57][Test collection for Akka.Persistence.Tests.PersistentActorStashingSpec (1)] Akka.Persistence.Tests.PersistentActorStashingSpec.PersistentActor_should_support_user_stash_operations_under_failures
[12:43:58][RunTests] [ERROR][6/20/2017 12:43:58 PM][Thread 0003][akka://AkkaSpec/user/$a] boom
[12:43:58][RunTests] Cause: Akka.Persistence.Tests.TestException: boom
[12:43:58][RunTests]    at Akka.Persistence.Tests.PersistentActorStashingSpec.UserStashFailureActor.ReceiveCommand(Object message) in D:\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\PersistentActorStashingSpec.cs:line 208
[12:43:58][RunTests]    at Akka.Persistence.PersistentActor.Receive(Object message) in …
```
=> Allow test failures to happen without failing build w/dotnet-xunit

src/core/Akka.FSharp.Tests/ApiTests.fs, src/core/Akka.FSharp.Tests/InfrastructureTests.fs
Two tests in the Akka.FSharp.Tests suite fail due to upgraded version of F# Compiler on our newest Mono Docker image (F# 4.1).  Until we figure out a way to downgrade F# on the Mono 5.0.1 Docker image, skipping these failing tests.
=> Skip failing Akka.FSharp.Tests on Mono

src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/EventSourceSpec.cs, src/core/Akka.Streams/Dsl/Source.cs, src/core/Akka.Streams/Implementation/Sources.cs
This PR brings 2 extra methods (versions of `FromEvent`, similar to another approach that can be seen in Rx.NET Observables). 
It's not ported from the JVM, however I think we should add it nonetheless: events are pretty essential part of the .NET ecosystem. They exist in many libraries, therefore to make it easier to integrate, we should add native support for them in Akka.Streams.
=> Added integration source stage for .NET events

RELEASE_NOTES.md
Resolves issues related to Akka.Cluster nodes not being able to cleanly leave or join a cluster after a period of network instability.
[See the full set of Akka.NET 1.2.1 fixes here](https://github.com/akkadotnet/akka.net/milestone/15).
| 15 | 1362 | 753 | alexvaluyskiy |
| 7 | 635 | 1487 | ravengerUA |
| 7 | 1966 | 764 | Nick Chamberlain |
| 4 | 420 | 345 | Aaron Stannard |
| 3 | 18715 | 999 | Alex Valuyskiy |
| 2 | 1943 | 3492 | Sean Gilliam |
| 2 | 104 | 24 | Jaskula Tomasz |
| 1 | 6 | 10 | Szer |
| 1 | 20 | 25 | Lealand Vettleson |
=> final v1.2.1 release notes [dev]

src/core/Akka.Cluster.Tests.MultiNode/Routing/UseRoleIgnoredSpec.cs, src/core/Akka/Routing/RoutedActorCell.cs
=> no longer deploy local routees when clustered pool router is on wrong role type

.gitignore, build.cmd, build.sh
Change NuGet download URL to specific v4.1.0 distribution and remove `update -self` from build scripts.
=> Lock NuGet version to v4.1.0

RELEASE_NOTES.md, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Finally, fully resolves issues related to Akka.Cluster nodes not being able to cleanly leave or join a cluster after a period of network instability. Also includes some minor fixes for clustered routers and Akka.Persistence.
[See the full set of Akka.NET 1.2.2 fixes here](https://github.com/akkadotnet/akka.net/milestone/16).
| 13 | 589 | 52 | Aaron Stannard |
=> Akka v1.2.2 release notes [dev]

.gitignore, RELEASE_NOTES.md, build.cmd, build.sh, src/SharedAssemblyInfo.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt, src/core/Akka.Cluster.Tests.MultiNode/LeaderLeavingSpec.cs, src/core/Akka.Cluster.Tests.MultiNode/Routing/UseRoleIgnoredSpec.cs, src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj, src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs, src/core/Akka.Cluster.Tests/ClusterGenerators.cs, src/core/Akka.Cluster.Tests/MemberOrderingModelBasedTests.cs, src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs, src/core/Akka.Cluster.Tests/TestMember.cs, src/core/Akka.Cluster.Tests/app.config, src/core/Akka.Cluster.Tests/packages.config, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterSettings.cs, src/core/Akka.Cluster/Configuration/Cluster.conf, src/core/Akka.Cluster/Member.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj, src/core/Akka.Persistence.Tests/PersistenceConfigAutoStartSpec.cs, src/core/Akka.Persistence/Persistence.cs, src/core/Akka.TestKit/TestKitBase.cs, src/core/Akka/Event/Logging.cs, src/core/Akka/Routing/RoutedActorCell.cs
Finally, fully resolves issues related to Akka.Cluster nodes not being able to cleanly leave or join a cluster after a period of network instability. Also includes some minor fixes for clustered routers and Akka.Persistence.
[See the full set of Akka.NET 1.2.2 fixes here](https://github.com/akkadotnet/akka.net/milestone/16).
| 13 | 589 | 52 | Aaron Stannard |
=> Akka.NET v1.2.2 Production Release

src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj, src/contrib/cluster/Akka.Cluster.Tools/Akka.Cluster.Tools.csproj, src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj, src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj, src/core/Akka.Cluster/Akka.Cluster.csproj, src/core/Akka.Persistence.Query/Akka.Persistence.Query.csproj, src/core/Akka.Persistence.TCK/Akka.Persistence.TCK.csproj, src/core/Akka.Persistence/Akka.Persistence.csproj, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Streams.TestKit/Akka.Streams.TestKit.csproj, src/core/Akka.Streams/Akka.Streams.csproj, src/core/Akka.TestKit/Akka.TestKit.csproj, src/core/Akka.Tests.Shared.Internals/Akka.Tests.Shared.Internals.csproj, src/core/Akka/Akka.csproj
Tests were failing because of code optimization done by the compiler.
This hot fix turns off code optimization on all netstandard1.6 framework targets so that those tests can pass.
NOTE: Need to turn code optimization on again when net core 2.0 is out to test and see if the problem persists or not.
=> Hotfix for #2800

build.fsx, buildIncremental.fsx
In incremental testing, when a build script was altered it should run all tests, but the way it was done scanned all projects and dependencies.  This changes the fallback to just list all projects based on `testMode`
=> Fix performance issue with Incremental Tests for running All Tests

src/core/Akka.Remote.TestKit.Tests/RemoteConnectionSpecs.cs
Skip Akka.Remote.TestKit.Tests test that causes deadlocking: `RemoteConnection_should_send_and_decode_Done_message`
=> Skip Akka.Remote.TestKit.Tests test that causes deadlock

buildIncremental.fsx
As it stands, incremental testing will search for test projects that have a dependency or indirect dependency on a changed project.  It didn't account for if the only project that was changed was a test project, e.g. if the PR was only a change to `Akka.Tests.csproj`.  This will force incremental testing to run test projects if they were the only project changed.
=> Incremental tests - account for sole change to test project

buildIncremental.fsx
Since TeamCity only clones the feature branch of the PR, this leaves the incremental testing code with no way to compare changed files with `git merge-base --fork-point v1.3` on the TeamCity build agent.  Adding a check for the existence of `v1.3` branch locally and if it doesn't exist, run `git checkout -b v1.3 origin/v1.3` to get that branch onto the build agent
=> Incremental testing - fetch default branch in TeamCity

src/core/Akka.TestKit/Internal/BlockingCollectionTestActorQueue.cs, src/core/Akka.TestKit/Internal/BlockingQueue.cs, src/core/Akka.TestKit/Internal/ITestActorQueue.cs, src/core/Akka.TestKit/Internal/InternalTestActor.cs
Not actually a race condition. 
TestProbe empties its message queue at PostStop when it sends its queue to the dead letter mailbox. 
This behavior is different than the Java implementation, where messages are retained in the queue.
The bug happens when the test is delayed in such a way that the probe message is asserted after it is stopped and its message queue already emptied.
=> Fix for ClusterSpec terminate ActorSystem via leave CoordinatedShutdown (#2728)

RELEASE_NOTES.md, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Resolves a bug introduced in Akka.NET 1.2.2 that caused Akka.Remote to not terminate properly under some conditions during `ActorSystem.Terminate`.
[See the full set of Akka.NET 1.2.3 fixes here](https://github.com/akkadotnet/akka.net/milestone/18).
| 3 | 46 | 63 | Aaron Stannard |
=> Added v1.2.3 release notes

RELEASE_NOTES.md, src/SharedAssemblyInfo.cs, src/core/Akka.FSharp/Properties/AssemblyInfo.fs, src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj, src/core/Akka.Remote.Tests/Transport/DotNettyTransportShutdownSpec.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/Transport/DotNetty/AkkaLoggingHandler.cs, src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs, src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs, src/core/Akka/Event/Logging.cs, src/core/Akka/Util/ConcurrentSet.cs, src/examples/Chat/ChatClient/Program.cs
Resolves a bug introduced in Akka.NET 1.2.2 that caused Akka.Remote to not terminate properly under some conditions during `ActorSystem.Terminate`.
[See the full set of Akka.NET 1.2.3 fixes here](https://github.com/akkadotnet/akka.net/milestone/18).
| 3 | 46 | 63 | Aaron Stannard |
=> Akka.NET v1.2.3 Production Release

src/core/Akka.Tests/Actor/Dispatch/Bug2751Spec.cs
=> verify that SysMsg is always delivered ahead of user messages

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/DeathWatchSpec.cs, src/core/Akka/Actor/ActorCell.DeathWatch.cs, src/core/Akka/Actor/IActorContext.cs, src/core/Akka/Actor/Inbox.Actor.cs, src/core/Akka/Actor/Inbox.cs, src/core/Akka/ActorState.cs
I ported [PR #22794](https://github.com/akka/akka/pull/22794) from Akka that allows custom termination messages. The old deathwatch tests all pass and I added an additional one testing the custom message.
I think this is a really nice feature and worthwhile having, because this allows giving termination messages some more meaning and integrate them better in the message protocol of an actor.
=> Port JVM Akka's watchWith for custom termination messages

build.fsx, src/core/Akka.Tests/Actor/Dispatch/Bug2751Spec.cs
Adds a FinalTarget called "KillCreatedProcesses" that should run regardless of failure or success of build script steps "RunTests" "RunTestsNetCore" "MultiNodeTests" and "NBench".
Attempt to resolve #2848
=> Add FinalTarget to kill running processes on TeamCity build agent

build.fsx
Already addressed in #2825, but isolated so we can continue with #2855.
=> Fix source folder for nuget publish

build.fsx
Switch command for running tests for .NET Core to force Release mode with `-c Release`
=> Run .NET Core tests in Release config

buildIncremental.fsx
`git merge-base --fork-point` proved unreliable when commits could be fast forwarded.  Replacing with `git merge-base <branch> v1.3` and added failure detection.
=> Incremental-tests: fix bug with not being able to find --fork-point for fast-forwards

build.fsx
Initially had applied the FAKE FinalTarget "KillCreatedProcesses" to test runs, but had a failed build and saw the symptom occur at a similar time so adding the activation of this target to the "Clean" step to cover BuildRelease and others that use a Clean step
=> Add KillCreatedProcesses activation to Clean step to cover BuildRelease runs

buildIncremental.fsx
Originally was using `merge-base --fork-point <branchName>` to get the commit hash to compare file changes between the tip of the feature branch and the point that it diverged from `v1.3`, however this has shown to only work on branches that haven't been rebased yet (also attempted to just use `merge-base` without `--fork-point` in case it was `--fork-point` being trashed upon rebase.  
Once a feature branch is rebased, the merge-base is altered to be just behind the merge-commit and therefore show that there are no revisions between the merge-base commit and HEAD.
Instead of using `merge-base` at all, this PR simply compares the feature branch changes against the default branch, regardless of commit hashes.  This way we don't have to worry about merge-commits or rebases.  Needs to be …
=> Incrmntl. Tests: remove call to merge-base, replace with branch diff

build.fsx
The `dotnet xunit` process has a timeout set to 30 minutes.  If the test run were to reach that 30 minute timeout, the build would fail but due to a bug in dotnet-xunit detailed in #2848 - the xunit.console.exe process would not be shut down.  This causes subsequent builds on the agent to be unable to clean files and start a new build, as they were locked.
This adds to the `KillCreatedProcesses` build target to always run a cleanup of both `dotnet` and `xunit.console` processes regardless of failure/success.
=> Fix locked files issue: kill dotnet and xunit.console processes left behind

build.fsx
For nightlies, an environment variable is set by TeamCity `BUILD_NUMBER` that should then be passed into the Assembly Version in `common.props` so that the assembly version is `1.3.0.*`.  Nightly builds pass `nugetprerelease=dev` to enable this.
=> Increment build number with TeamCity number for -beta releases

build.fsx
For nightly builds, assembly version suffix was being set for the name of the nupkg but not for the .dll itself.  This changes the number scheme from `1.3.0.1234-beta` to `1.3.0-beta-1234` and uses the `VersionSuffix` flag passed into MSBuild to name the package correctly.
=> Number nightly assemblies correctly and update nightly build formatting

ISSUE_TEMPLATE.md
Lately there are numerous issues being created where people don't
specify which Akka.Net version they are using, and other basic stuff.
This template uses the github issue template feature to make people
aware of these things. And will hopefully lead to a better quality of
issue reporting.
=> Added an issue template to the repos

docs/examples/DocsExamples/Networking/IO/EchoConnection.cs
Fixes `DocsExamples.Networking.IO` example having issues after #2683.
=> Fix docs example with new Akka.IO

build.fsx, build.ps1, docs/docfx.json
Per #2891.  Test setting maxParallelism to 1 on the build agent to mitigate the early success and completion of `docfx.exe build`.  Also upgrade DocFx to latest version.  WIP for testing on build server since docs build locally fine.
=> [WIP] Upgrade DocFx to v2.21.1 and set maxParallelism to 1

build.fsx, src/common.props
On later releases, this PR ensures that we only need to update RELEASE_NOTES.md to change the VersionPrefix and include PackageReleaseNotes for the NuGet packages created on `dotnet pack` step.
=> Parse VersionPrefix and PackageReleaseNotes from RELEASE_NOTES.md into common.props

build.fsx
Fixes timeout when building DocFx docs in TeamCity.
=> Increase DocFx build step timeout to 30 min

src/contrib/cluster/Akka.DistributedData/DistributedData.cs, src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
This PR changes 2 things:
1. It fixes critical error related to delta state merges during deltas propagation in DistributedData plugin. **Without it DData will be unusable**.
2. It changes behavior of `DistributedData.GetAsync` - previously it was throwing a `KeyNotFoundException` if a CRDT with provided key was not found. I think this was wrong, as it's not an exceptional scenario. Actually it's pretty common when we deal with masterless distributed data. Instead I've changed generic constraint to class (all current CRDTs are classes) and return null on key not found.
=> Fixed broken delta propagation merge

src/NuGet.Config, src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj
Updates NuGet.config to point to nightlies that are live and pushed daily to MyGet feed.
=> Update NuGet.config to use live nightlies

buildIncremental.fsx
Adds remote `upstream` being akka.net repository, fetches, and runs file-changes diff against `upstream/v1.3`.  Was previously comparing against `origin/v1.3` as per #2914.
=> Incremental tests: compare against upstream/v1.3 isntead of origin/v1.3

src/core/Akka.Remote/MessageSerializer.cs
Slightly reduced allocations for serializers with Includemanifest=true
|                                         Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
|----------------------------------------------- |----------:|----------:|----------:|-------:|----------:|
|          MessageSerializer_Serialize_Primitive | 47.544 us | 0.3309 us | 0.2583 us | 0.1261 |    6577 B |
| MessageSerializer_SerializeOptimized_Primitive | 48.715 us | 0.3919 us | 0.3474 us | 0.1221 |    6289 B |
|            MessageSerializer_Serialize_Complex | 63.856 us | 1.2648 us | 1.3533 us | 0.2360 |   10601 B |
|   MessageSerializer_SerializeOptimized_Complex | 64.427 us | 1.2760 us | 1.2532 us | 0.2360 |   10601 B |
=> Reduced allocations for serializers with IncludeManifest

src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/Akka.Cluster.Sharding.Tests.MultiNode.csproj, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxy.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingCustomShardAllocationSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingFailureSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStateSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStatsSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGracefulShutdownSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingLeavingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingMinMembersSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesNewExtractorSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/MemoryJournalShared.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingConfigSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingMessageSerializerSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ConstantRateEntityRecoveryStrategySpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/LeastShardAllocationStrategySpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.Messages.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs, src/contrib/cluster/Akka.Cluster.Sharding/Serialization/ClusterShardingMessageSerializer.cs, src/contrib/cluster/Akka.Cluster.Sharding/Serialization/Proto/ClusterShardingMessages.g.cs, src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardAllocationStrategy.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs, src/protobuf/ClusterShardingMessages.proto
This PR updates sharding to version 2.5.2, including tests and multi-node tests.
All tests are passing on my end.
This also brings support for sharding entities without remembering feature, in the future DData support could be done in a similar way.
FYI:
**This update includes one breaking change**, which was introduced in akka 2.5.2:
If you are using Cluster Sharding with “remembering entities” there is one important change that requires that you make a change to your code when updating to 2.5.2. To solve a critical issue https://github.com/akka/akka/issues/22289 that could result in duplicate entities when the extractShardId function is changed (e.g. between deployments) there is now a new message Shard.StartEntity(entityId) that the extractShardId must understand.
close #1578
close …
=> Sharding updated to v2.5.2

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Remote.Tests/Transport/AkkaProtocolSpec.cs, src/core/Akka.Remote.Tests/Transport/GenericTransportSpec.cs, src/core/Akka.Remote/Endpoint.cs, src/core/Akka.Remote/EndpointManager.cs, src/core/Akka.Remote/RemoteActorRefProvider.cs, src/core/Akka.Remote/Serialization/ActorPathCache.cs, src/core/Akka.Remote/Serialization/AddressCache.cs, src/core/Akka.Remote/Transport/AkkaPduCodec.cs, src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs, src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs, src/core/Akka.Tests.Performance/Actor/ActorPathEqualitySpec.cs, src/core/Akka.Tests.Performance/Actor/ActorPathSpec.cs, src/core/Akka.Tests/Actor/ActorPathSpec.cs, src/core/Akka/Actor/ActorCell.Children.cs, src/core/Akka/Actor/ActorPath.cs, src/core/Akka/Actor/ActorRef.cs, src/core/Akka/Actor/Address.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Actor/LocalActorRef.cs
Also going to try to address this race condition that keeps coming up on Linux....
```
[22:14:14]	[docker] [ERROR][07/17/2017 22:14:15][Thread 0150][LocalActorRefProvider(akka://AkkaSpec)] guardian [akka://AkkaSpec/] failed, shutting down!
[22:14:14]	[docker] Cause: System.NullReferenceException: Object reference not set to an instance of an object.
[22:14:14]	[docker]    at Akka.Actor.ActorPath.FillElements(ActorPath actorPath) in /checkout/src/core/Akka/Actor/ActorPath.cs:line 207
[22:14:14]	[docker]    at Akka.Actor.ActorPath.<>c.<.cctor>b__56_0(ActorPath actorPath) in /checkout/src/core/Akka/Actor/ActorPath.cs:line 156
[22:14:14]	[docker]    at Akka.Util.FastLazy`2.get_Value() in /checkout/src/core/Akka/Util/FastLazy.cs:line 149
[22:14:14]	[docker]    at …
```
=> Actorpath performance improvements

src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
this removes some unhandled events warnings
=> ClusterSingletonManager remove ClusterEvent.MemberExited events

src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence.Tests/PersistentActorSpecAsyncAwait.Actors.cs, src/core/Akka.Persistence.Tests/PersistentActorSpecAsyncAwait.cs, src/core/Akka.Persistence.Tests/ReceivePersistentActorAsyncAwaitSpec.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs, src/core/Akka.Persistence/Eventsourced.cs, src/core/Akka.Persistence/PersistentActor.cs
Here is another try on CommandAsync topic.
I's introducing similar support for async/await as in ReceiveAsync.
Remarks:
- As with ReceiveAsync, all other commands to actor are blocked until the command handler task finishes processing the current command, including the Persist and PersistAll callbacks.
- It does NOT introduce async support for Persist callbacks, they work the same way as before
=> CommandAsync for persistent actors

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
`AsyncWriteJournal` (which is a base class to `SqlJournal`) converts events before writing them to DB in a `PreparePersistentBatch` method:
https://github.com/akkadotnet/akka.net/blob/fa34c230adf0ed4823aa22fd0672e3ee17cc98ef/src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs#L337
which internally calls `AdaptToJournal`
https://github.com/akkadotnet/akka.net/blob/cd33195b5aad34895f0fb69893bd2074d539201f/src/core/Akka.Persistence/Journal/WriteJournal.cs#L41
Now, those parsed messages are NOT used when reporting events that were saved back to the actor. The original events are used instead (`message.Messages`):
https://github.com/akkadotnet/akka.net/blob/fa34c230adf0ed4823aa22fd0672e3ee17cc98ef/src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs#L359
`BatchSqlJournal` behaves …
=> Use unadapted event in replies in BatchSqlJournal

src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/Akka.Cluster.Sharding.Tests.MultiNode.csproj, src/core/Akka.NodeTestRunner/Akka.NodeTestRunner.csproj, src/core/Akka.NodeTestRunner/Program.cs
Enables Akka.Cluster.Sharding.Tests.MultiNode to be run under `MultiNodeTestsNetCore` step in CI.  Fixes bug in NodeTestRunner related to loading dependent assemblies into context on .NET Core.
=> Enable Akka.Cluster.Sharding.Tests.MultiNode specs on .NET Core

src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka/Configuration/Hocon/HoconTokenizer.cs
Partial fix to #2950
This fix the infinite loop, not the substitution
=> Fix unquoted string value in HOCON would cause infinite loop crash.

src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingCustomShardAllocationSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingFailureSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStateSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStatsSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGracefulShutdownSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingLeavingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingMinMembersSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesNewExtractorSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
This PR renames some items to align with akka naming. This is a continuation of #2767
`idExtractor` rename to `extractEntityId`
`shardResolver` renamed to `extractShardId`
=> [Sharding] - Align naming with akka

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Actor/Settings.cs
Serializers configurations from extension default config are not correctly loaded.
At the time extension tries to inject it's default config with InjectTopLevelFallback, serializer configuration was already loaded and it's not reloaded afterwards. Currently only workaround I know about is providing all fallback configurations when creating ActorSystem itself. This pr tries to improve this.
=> Serialization reload on settings change

src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj, src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
Use production Hyperion v0.9.5 instead of nightly for Akka.Serialization.Hyperion and Akka.DistributedData
=> Use production Hyperion v0.9.5 instead of nightly

build.fsx
We don't pass `--symbol-source` when releasing to production.  This accounts for that by allowing us not to include that flag.
=> Account for not publishing symbols to NuGet

docs/index.md
Fixes "Get Started Now" and "Read the documentation" links in the hero section of the Documentation home page.
=> Fix hero links in Documentation

build.fsx, src/common.props
Hotfix for NuGet publish code and update NuGet logo link.  Also revise build numbering once more to not have an extra dash.
=> Hotfix for NuGet publish code and update NuGet logo link

src/core/Akka/Configuration/Hocon/HoconObject.cs, src/core/Akka/Configuration/Hocon/HoconValue.cs
|                               Method |           Mean |  Gen 0 | Allocated |
|------------------------------------- |---------------:|-------:|----------:|
|                    Config_GetBoolean |    534.1718 ns | 0.0100 |     344 B |
|                        Config_GetInt |    612.6211 ns | 0.0100 |     344 B |
|                       Config_GetLong |    632.0545 ns | 0.0097 |     344 B |
|                     Config_GetString |    519.4849 ns | 0.0102 |     352 B |
|                      Config_GetFloat |    684.5236 ns | 0.0101 |     352 B |
|                     Config_GetDouble |    657.3743 ns | 0.0099 |     352 B |
|                    Config_GetDecimal |    764.9903 ns | 0.0108 |     352 B |
|                   Config_GetTimeSpan |  2,962.0917 ns | 0.0542 |    1976 B |
| …
=> Improved Config performance

src/core/Akka.Tests/IO/TcpIntegrationSpec.cs, src/core/Akka/IO/TcpConnection.cs
TL;DR;, the design of this class as it currently stands is a port of the JVM and all of its semantics around queueing pending writes, backpressure, etc, all depend on synchronous socket sends. We still use async socket reads - those work fine. But all writes are performed synchronously as of this PR.
This resolves the issue I outlined in #3021 and makes it possible to queue writes with Akka.IO.Tcp again.
=> fix 3021 - returned Akka.IO.Tcp semantics to use synchronous write

build.fsx, build.sh, src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj, src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj, src/contrib/dependencyinjection/Akka.DI.Core/Akka.DI.Core.csproj, src/core/Akka.Remote/Akka.Remote.csproj, src/core/Akka.Streams/Akka.Streams.csproj
* Rider/OSX appears to be less forgiving around the csproj format and requires that the nuget dependencies use Version and not version.
* Updated the build.sh script to only install dotnet once and also to pull down protoc from nuget.
* The FAKE build has been updated to support building the Protobuf target on OSX & Linux
=> Improving Support for OSX & Rider

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Serialization/SqliteJournalSerializationSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Serialization/SqliteSnapshotStoreSerializationSpec.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/BatchingSqliteJournal.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteQueryExecutor.cs, src/contrib/persistence/Akka.Persistence.Sqlite/Snapshot/SqliteSnapshotStore.cs
This addresses #3019
* Added a serializer id to the sql columns
* Updated how the manifest is set to support SerializerWithStringManifest
* ReadEvent should be backwards compatible
=> Added support for SerializerWithStringManifest to Akka.Persistence.Sql.Common

docs/articles/actors/testing-actor-systems.md
Alot of the code references where line ranges are used, where off by a few lines. 
Also there was a non-closing code block, causing issues.
Not sure why the code line indexes where wrong. Perhaps reformatting of the files as part of someone's PR ?
=> Formatting fixes for the testplan doc

src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs, src/core/Akka.Cluster/Member.cs, src/core/Akka/Actor/Address.cs
This PR introduces an `IComparable<>`/`IComparable` interface implementations for both `Address`/`UniqueAddress`, which should help to fix #3010 and allow us to keep our implementations in line with Akka JVM code.
**WARNING: There is a difference in `UniqueAddress.CompareTo(UniqueAddress)` implementation!** Previously to compare address parts, a `Member.AddressOrdering` was used. This was different from JVM implementation, which by default uses `Address.addressOrdering`. The difference between the two is that the first one ignores the protocol and system name part of the address during comparison.
=> Address & UniqueAddres -> IComparable interface

src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt, src/core/Akka.Persistence.Tests/Serialization/MessageSerializerRemotingSpec.cs, src/core/Akka.Persistence/Fsm/PersistentFSM.cs, src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs, src/core/Akka.Persistence/Serialization/Proto/Persistence.g.cs, src/protobuf/Persistence.proto
To bring the Akka.Persistence module more in line with the JVM Akka implementation protobuf serialization of PersistentFSMSnapshot and StateChangeEvent classes.  As PersistentFSMSnapshot uses generics, reflection is needed to properly serialize and deserialize the class.
=> Protobuf serialization support for FSM types

src/contrib/persistence/Akka.Persistence.Sqlite/README.md
Adds note to README that users need to run 2 ALTER statements for backwards compatibility with existing 1.2.* databases.  Also turns the schema table into a table because it became too wide and started to wrap lines in the rendered html.
=> Update Akka.Persistence.Sqlite README to include ALTER statements for backwards compatibility

build.fsx, src/common.props
Fixes issue where our NuGet packages were published with the releaseNotes being "Placeholder" instead of  the actual release notes.
Verified in the .nuspec file:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
<metadata>
<id>Akka</id>
<version>1.3.0</version>
<authors>Akka.NET Team</authors>
<owners>Akka.NET Team</owners>
<requireLicenseAcceptance>false</requireLicenseAcceptance>
<licenseUrl>https://github.com/akkadotnet/akka.net/blob/master/LICENSE</licenseUrl>
<projectUrl>https://github.com/akkadotnet/akka.net</projectUrl>
<iconUrl>http://getakka.net/images/akkalogo.png</iconUrl>
<description>Akka.NET is a port of the popular Java/Scala framework Akka to .NET</description>
<releaseNotes>Feature Release for Akka.NET** …
```
=> Fix issue with not publishing release notes to NuGet

src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams/Dsl/BidiFlow.cs
The generic type parameters of the flow returned from the current implementation of Bidiflow's JoinMat method are incorrect as discussed in issue #3055.
This patch corrects the type, an equivalent PR is also being raised with Lightbend for the Akka Scala project for consistency.
=> Fix the materialised value of the Flow returned by Bidiflow JoinMat() #3055

docs/articles/streams/error-handling.md, docs/articles/streams/integration.md, docs/articles/streams/workingwithgraphs.md
Scala JVM has `RestartSource`, `RestartSink` and `RestartFlow`, which is not implemented in Akka.NET at the moment
Fixed https://github.com/akkadotnet/akka.net/issues/3086
=> Improved Streams Error-Handling docs

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ActorProducerPipeline.cs, src/core/Akka/Actor/ExtendedActorSystem.cs
As proposed in #3050 and #3057 , if we're going to modernize the way how we do create actors (including native support for dependency injection) an existing actor producer pipeline API will need to be removed - this isn't actually a great pain, as AFAIK it's not a very popular or well-known part of the API.
This PR obsoletes relevant types and fields with *Actor producer pipeline API will be removed in v1.5.* message, so that eventual users will be informed about this beforehand.
=> Obsoleted actor producer pipeline extensions

docs/articles/streams/error-handling.md, docs/examples/DocsExamples/Streams/RestartDocTests.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/RestartSpec.cs, src/core/Akka.Streams/Dsl/Restart.cs, src/core/Akka.Streams/Dsl/Sink.cs
Implemented https://github.com/akkadotnet/akka.net/issues/3090
=> Added RestartSource/Flow/Sink

src/core/Akka.Streams.TestKit/TestSubscriber.cs
This PR fixes the problem of unreadable assert messages in Akka.Streams `TestSubscriber`.
***Before**
> Got a message of the expected type <Akka.Streams.TestKit.TestSubscriber+OnNext1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]>. Also expected the predicate to return true but the message {TestSubscriber.OnNext(a)} of type <Akka.Streams.TestKit.TestSubscriber+OnNext1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]> did not match
**After**
> Expected 'a' but got 'c'
=> Human-friendly streams assertions

docs/articles/toc.yml
Serilog docs page is accessible (http://getakka.net/articles/utilities/serilog.html) but not visible in the table of contents.
=> Add Serilog docs page to the table of contents

src/core/Akka.Cluster.TestKit/Akka.Cluster.TestKit.csproj, src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
Removed Akka.Cluster.TestKit's dependency on Akka.Test.Shared.Internals which is not on nuget (and according to it's readme not intended to be public).
Replaced the usages of "Should" extension assertions with ITestKitAssertions as they were used elsewhere in the file, and the Shared.Internals extensions weren't really providing that much value.
=> Fixed Akka.Cluster.TestKit nuget package (Fixes #3131)

docs/articles/clustering/distributed-publish-subscribe.md, src/Akka.sln, src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubConfigSpec.cs
The docs at http://getakka.net/articles/clustering/distributed-publish-subscribe.html currently contain an error in the section that explains how to configure `DistributedPubSub` to launch at startup. I've corrected this and added a spec to verify that my configuration is valid.
=> fixed bug with DistributedPubSub automatic extension loading docs

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Serialization/CustomSerializerSpec.cs, src/core/Akka/Serialization/Serialization.cs
Serializer id is now only determined once, upon initialisation. And its
the serializer implementation which dictates where that id comes from.
We no longer assume it always comes from the hocon config.
=> Fix in resolving serializer id

build.fsx, buildIncremental.fsx, src/common.props
Resolves #3150 by simply copying 100% of nuget dependencies to the output directory for .NET Core. This is more of a work-around than a fix.
IMHO, we probably need to rewrite the multi-node testrunner to take advantage of the runtime.deps files and such for finding the locations of assemblies that are shared by multiple apps on a given .NET Core runtime.
Either way, this should allow specs to pass again.
=> close #3150 - resolved issue with missing runtime assembly loaded dependencies

src/core/Akka.Tests/Util/ByteStringSpec.cs, src/core/Akka/Util/ByteString.cs
Fixes akkadotnet/akka.net#3147.
=> Ensure ByteStrings are compact when calling ToString.

docs/articles/utilities/serilog.md
As of the merged PR in `Akka.Logger.Serilog` project https://github.com/akkadotnet/Akka.Logger.Serilog/pull/33 the documentation for Serilog needed an update.
These changes explain how to use the `ForContext()` extension method. It also provides an example.
=> Updates Serilog documentation about using ForContext() extension method

src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka/Actor/Internal/ActorSystemImpl.cs, src/core/Akka/Configuration/Pigeon.conf
We've had this warning in the codebase for a year and we've not set a timeframe for the Hyperion switch.
Urging users to switch from something stable (JSON.NET) to something that is still in beta (Hyperion) isn't the right call at the moment considering that we're not directing a lot of resources into Hyperion right now due to other priorities (i.e. such as integrating with all of the new standard APIs for configuration, dependency injection, Unity3D, Xamarin support, etc... - stuff that wasn't on anyone's radar a year ago.)
Beyond that the most urgent issues solved by Hyperion, related to Cluster.Sharding, were solved via dedicated Protobuf serializers in 1.3. The ultimate plan is still the same: to switch from JSON.NET to Hyperion in the 1.5 release. But the timeframe for that is …
=> disabled Hyperion warning

RELEASE_NOTES.md, src/common.props
**Updates and bugfixes**:
- Bugfix: Akka incorrectly schedules continuations after .Ask, causing deadlocks and/or delays
- Bugfix: ByteString.ToString is sometimes broken for Unicode encoding
- Bugfix: ClusterShardingMessageSerializer Exception after upgrade from 1.2.0 to 1.3.1
- Bugfix: Fix an inconstant ToString on ConsistentRoutee when the node is remote vs. local
- Various documentation fixes
- Akka.Streams: Implement MergePrioritized
- Akka.Streams: Implement Restart Flow/Source/Sink
- Akka.TestKit.Xunit: updated `xunit` dependency to 2.3.0 stable.
- Akka.Cluster.TestKit: removed dependency on Akka.Tests.Shared.Internals
| 9 | 137 | 59 | Aaron Stannard |
| 8 | 2713 | 997 | Alex …
=> V1.3.2 release notes [dev]

src/core/Akka/Configuration/Pigeon.conf
Increased direct-buffer-pool.buffer-size from 256B to 512B, for both UDP and TCP. Additionally removed redundant config sections. Related issue #3116 - reason is that 256 is often too small, and (specifically in case of UDP) it establishes an upper size limit of a payload. UDP-based protocols like TFTP and DNS have maximum frame size of 512B, so I think we should stick to it. DHCP has 548B, but this could slice up page caches in weird ways.
=> Changed Akka.IO configured buffer-size to 512B

src/contrib/cluster/Akka.Cluster.Sharding.Tests/LeastShardAllocationStrategySpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardAllocationStrategy.cs
Having maxSimultaneousRebalance > rebalanceThreshold in LeastShardAllocationStrategy caused shards "flapping" (deallocation of excessive shards followed by their immediate allocation on the same node)
Migrated from https://github.com/akka/akka/issues/23830
=> Fix excessive rebalance in LeastShardAllocationStrategy

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka/Configuration/Hocon/HoconTokenizer.cs
The problem with current HOCON parser is that it doesn't give any meaningful support, when a user has specified a malformed HOCON string. No position of issued token or anything else.
This PR introduces a human-friendly error messages. Example:
```hocon
akka {
ask-timeout = $10s
}
```
will produce following error message:
```
Unknown token at position 26:
ask-timeout = $10s
^
```
=> Added human-friendly error message for malformed HOCON

src/core/Akka.Persistence.Tests/RecoveryPermitterSpec.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs
When exception was thrown from RecoveryCompleted the
permit was returned twice, resulting in negative balance
migrated from https://github.com/akka/akka/pull/24006
=> Persistence - fix double return of recovery permit

src/core/Akka/IO/TcpConnection.cs
This PR fixes 2 bugs:
- One is #3203 - a write request was made as part of recursive function call. This could result with StackOverflowException when ratio of written bytes to TCP buffer chunk size was to big (either the bigger the payload or the smaller the direct byte buffer pool could cause this).
- Another isssue is #3188 - when using non-blocking IO, occasionally we could run into non-fatal `SocketError.WouldBlock`. According to winsock docs, in this case we should try to make a send later. However we could also switch flag to `Socket.Blocking = true` and fallback to blocking send. This is not ideal, but for sure it's better than the current state.
=> Akka.IO bug fixes

src/core/Akka/IO/SocketEventArgsPool.cs, src/core/Akka/IO/TcpConnection.cs, src/core/Akka/IO/TcpOutgoingConnection.cs
TcpOutgoingConnection saves reference to SocketAsyncEventArgs it acquires during connection in a protected field on base TcpConnection class. This field is then being disposed when closing connection.
Also PreallocatedSocketEventAgrsPool forces dispose of SocketAsyncEventArgs during release even if InvalidOperationException is caught. This also lead to some memory leak because this exception gets raised quite often when system is under load.
=> Fix TcpOutgoingConnection memory leak (#3211)

src/core/Akka.Tests/IO/UdpIntegrationSpec.cs, src/core/Akka/IO/UdpListener.cs
This fixes a bug reported by @blackclavus in #3210 . Also contains new test case for verification.
=> Fixed problem with byte buffer overridden inside UDP listener 

src/core/Akka/Event/DefaultLogger.cs, src/core/Akka/Event/LogEvent.cs, src/core/Akka/Event/StandardOutLogger.cs
The performance optimization is simple: don't dynamically create a new "ERROR", "INFO" string every time. Just cache one for each log level and re-use it.
The main thing here is a bug I've run into in my own code and in some end-user code I've reviewed: `FormatException`s thrown when the logging string itself isn't formatted correctly. When this error occurs here's the stack trace you get:
```
Cause: System.FormatException: Input string was not in a correct format.
at System.Text.StringBuilder.FormatError()
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.Format(String format, Object[] args)
at …
```
=> Logging performance optimization + ease of use fix

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/Futures.cs
Deadlock comes as an edge case from ContinueWith, await and TaskCompletionSource.
One TaskCompletionSource was covered, but there is another one in CastTask
=> Ask deadlock - proof of concept

src/core/Akka.Cluster/SplitBrainResolver.cs
* Fix exception that can occur when remaining and unreachable variables both have zero elements
* tidy up if else logic as per Refactor recommendations
This fixes a bug which has been experienced in production where remaining and unreachable have zero elements which causes an exception when trying to call .First() to get the oldest in the else (which obviously does not exist).
Unfortunately I do not have the time right now to write a test for this due to work constraints, do with this as you will.
=> Update KeepMajority SplitBrainResolver strategy to avoid exception

src/contrib/cluster/Akka.Cluster.Sharding/DDataShardCoordinator.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardCoordinator.cs
Port of https://github.com/akka/akka/pull/24209
1. Previously if `GetShardHome` request was received while shard was rebalancing, request was ignored. It was not a problem, as retry was send later. Now, requests senders are collected, and once rebalance is done, they are being replied reactivelly (potentially before request retry).
2. Additionally while `DDataShardCoordinator` in the middle of the update, and `GetShardHome` is incoming for shard of known localization, we can reply right away instead of awaiting for update phase to complete. This is change done in one of the previous PRs on Akka JVM side.
=> Handle GetShardHome after rebalance

src/core/Akka.Cluster/SplitBrainResolver.cs
I have found another issue when attempting to use KeepOldest strategy when sometimes the remaining and unreachable lists can be empty with an exception being generated due to the use of .First().
I have also removed some else statements Resharper pointed out were unnecessary.
=> Fix potential exception in KeepOldest split brain strategy

src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/Member.cs
Was able to re-apply the fix from #2584 here and modified some of the specs to test for `WeaklyUp` transitions specifically. Should close #3274.
=> Fixed weaklyup nodes stuck at joining

RELEASE_NOTES.md, src/common.props
The largest changes featured in Akka.NET v1.3.3 are the introduction of [Splint brain resolvers](http://getakka.net/articles/clustering/split-brain-resolver.html) and `WeaklyUp` members in Akka.Cluster.
**Akka.Cluster Split Brain Resolvers**
Split brain resolvers are specialized [`IDowningProvider`](http://getakka.net/api/Akka.Cluster.IDowningProvider.html) implementations that give Akka.Cluster users the ability to automatically down `Unreachable` cluster nodes in accordance with well-defined partition resolution strategies, namely:
* Static quorums;
* Keep majority;
* Keep oldest; and 
* Keep-referee.
You can learn more about why you may want to use these and which strategy is right for you by reading our [Splint brain resolver …
=> added Akka.NET v1.3.3 release notes [dev]

docs/articles/streams/stream-dynamic.md, docs/articles/utilities/may-change.md, docs/examples/DocsExamples/Streams/HubsDocTests.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/HubSpec.cs, src/core/Akka.Streams/Dsl/Hub.cs
=> Implement PartitonHub

src/core/Akka.Remote/Transport/AkkaPduCodec.cs
Noticed some low-hanging fruit for performance in the `AkkaPduCodec` fixes while I was working on implementing a custom serializer for Akka.Remote today.
This is the class responsible for serializing 100% of message traffic that passes over each Akka.Remote connection.
=> AkkaPduCodec performance fixes [remoting]

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ActorCell.DefaultMessages.cs
API change and that may also have some performance impact (`virtual` methods can't be inlined by the compiler). 
Rationale for this change is that it allows developers who are working on aspect-oriented add-ons for Akka.NET, such as yours truly, to be able to decorate 100% of actors with instrumentation and other goodies without having to have the user consume a custom actor base class or anything else that makes "infrastructure" a foreground concern. Also makes it possible to instrument built-in `/system` actors, which is part of my goal.
Using a custom `ActorCell` allows me to keep most of this stuff out of end-user code. However, at the moment there isn't a way for me to inject instrumentation at the time of processing a message, aside from doing it inside a custom `IMessageQueue` …
=> changed ActorCell.ReceiveMessage method to be protected and virtual

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.4 is a minor patch mostly focused on bugfixes.
**Updates and Bugfixes**
1. [Akka: Ask interface should be clean](https://github.com/akkadotnet/akka.net/pull/3220)
1. [Akka.Cluster.Sharding: DData replicator is always assigned](https://github.com/akkadotnet/akka.net/issues/3297)
2. [Akka.Cluster: Akka.Cluster Group Routers don't respect role setting when running with allow-local-routees](https://github.com/akkadotnet/akka.net/issues/3294)
3. [Akka.Streams: Implement PartitionHub](https://github.com/akkadotnet/akka.net/pull/3287)
4. [Akka.Remote AkkaPduCodec performance fixes](https://github.com/akkadotnet/akka.net/pull/3299)
5. [Akka.Serialization.Hyperion updated](https://github.com/akkadotnet/akka.net/pull/3306) to [Hyperion …
=> Akka.NET v1.3.4 release notes

src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
The DistributedPubSubMediator wasn't checking if the TopicActor was actually terminated before pruning it from the bucket.  This can cause problems if a TopicActor is re-suscribed to before being stopped.  The Subscribe message only checks Context.Child, but does not check if the bucket is still valid.  So it was possible to get in a state where subscribes/unsubscribes were succeeding, but any publishes to the topic where being dropped on the floor.
I've also switched from null to ActorRefs.Nobody.  Previously, if a Topic actor had terminated and a publish for that topic was received before the DistributedPubSubMediator did a prune, the publish would throw an exception.
=> Fixing premature pruning of Topics

src/core/Akka.Remote/Transport/TransportAdapters.cs
An oversight from some of the work I did leading up to 1.3.4. Being able to use the `TransportAdapter` system as an injection point for doing things like slapping a byte / s monitor in front of an Akka.Remote transport is pretty handy. But, needed to change the cast in the constructor to target the `IRemoteActorRefProvider` interface rather than the concrete class. Also added some more comments to some of the public parts of this code while I was there.
=> fixed API call inside TransportAdapters exentsion to support third-party RemoteActorRefProviders

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.5 is a minor patch containing only bugfixes.
**Updates and Bugfixes**
1. [Akka.Cluster.Tools: DistributedPubSub Fix premature pruning of topics](https://github.com/akkadotnet/akka.net/pull/3322)
You can see [the full set of changes for Akka.NET v1.3.4 here](https://github.com/akkadotnet/akka.net/milestone/23).
| 4 | 4405 | 4284 | Aaron Stannard |
| 1 | 4 | 4 | Joshua Garnett |
=> Akka.NET v1.3.5 Release Notes

src/core/Akka.Tests.Shared.Internals/AsyncContext/AsyncContext.SynchronizationContext.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/AsyncContext.TaskQueue.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/AsyncContext.TaskScheduler.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/AsyncContext.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/BoundAction.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/ExceptionHelpers.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/SingleDisposable (of T).cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/SynchronizationContextSwitcher.cs, src/core/Akka.Tests.Shared.Internals/AsyncContext/SynchronousTaskExtensions.cs.cs
Tagged these when we did the mass copyright update yesterday. That was unintentional. Removed the headers from these files.
=> removed copyright from Nito.AsyncEx files

src/core/Akka/Configuration/Pigeon.conf
It was not possible to use tail-chopping routers from config.
- added "tail-chopping-*" routers to Pigeon.conf
- removed non-existing "balancing-pool" router.
=> tail-chopping routers could not be selected from config

src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs
Fixes #3352 
Looks like a copy-paste error from the real shard startup. The replicator is only used when a shard is created, and this does not happen on a Proxy.
The Akka source code also does not pass the replicator in. See https://github.com/manonthegithub/akka/blob/232b4d0d7a38cb84f8a87c43322f50314cd6650e/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala#L681
=> A replicator is not needed for a Shard Proxy

src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs, src/contrib/cluster/Akka.DistributedData/Replicator.cs
Inspired by #3361
I have gone through the rest of the distributed / cluster codebase and replaced all `GetHashCode` calls on string instances that I could find.
I am raising this as a separate PR because these changes might not be needed. I do not know the codebase very well and in case these are private methods that do not rely on the same bucketing on remote nodes then it is fine to use `GetHashCode` and this PR might potentialy only slow Akka down (assuming `GetHashCode` is faster than the `MurmurHash`).
Submitting this for review and let me know if you want me to remove something but keep the rest.
=> Removing string.GetHashCode usage from distributed classes

src/core/Akka.Streams/Implementation/Fusing/Ops.cs
Using List allocation on batch size eliminates buffer reallocations.
=> Fix GroupedWithin allocation of new buffer after emit.

src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/AccumulateWhileUnchangedSpec.cs, src/core/Akka.Streams.Tests/Dsl/LastElementSpec.cs, src/core/Akka.Streams.Tests/Dsl/PartitionWithSpec.cs, src/core/Akka.Streams.Tests/Dsl/SampleSpec.cs, src/core/Akka.Streams/Dsl/AccumulateWhileUnchanged.cs, src/core/Akka.Streams/Dsl/LastElement.cs, src/core/Akka.Streams/Dsl/PartitionWith.cs, src/core/Akka.Streams/Dsl/Sample.cs
Hello, please review my attempt to port 4 following "streams contrib" stages:
- AccumulateWhileUnchanged
- LastElement
- PartitionWith
- Sample
This is for issue #3234
=> Port 4 "streams contrib" stages

src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs, src/core/Akka/Actor/FSM.cs
Fixes "... a small bug in FSM timers, which could result in that a timer from a previous incarnation was let through to new incarnation after restart".
Original PR: [#22873](https://github.com/akka/akka/pull/22873)
=> Discard timers from a previous (FSM) incarnation after restart

docs/community/online-resources.md
Noticed when I was working on #3388 that the links to Akka.NET Bootcamp were still pointed to some old handlebars syntax from the previous Akka.NET website design. Fixed those and replaced with a real URL.
=> fixed online resources link in docs

src/core/Akka.Remote.Tests/Transport/Bug3370DotNettyLinuxBufferPoolSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs, src/core/Akka.Remote/Transport/DotNetty/DotNettyTransportSettings.cs
close #3370 
When DotNetty v0.5.0 comes out this should no longer be necessary.
=> workaround DotNetty v0.4.6 issues on .NET Core Linux by disabling buffer pooling via HOCON

src/core/Akka.Remote.Tests/RemoteConfigSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf
Added this to make sure this data shows up on the website when #3388 is merged, so people don't have to go "guessing" for this option.
=> added descriptive hocon for the akka.remote.dot-netty.tcp.public-port option

docs/articles/configuration/akka.cluster.md, docs/articles/configuration/akka.md, docs/articles/configuration/akka.persistence.md, docs/articles/configuration/akka.remote.md, docs/articles/configuration/akka.streams.md, docs/articles/configuration/akka.testkit.md, docs/articles/configuration/toc.yml, docs/articles/toc.yml, serve-docs.cmd, serve-docs.ps1, src/common.props
We should probably expand what I've started here and add support for `Cluster.Sharding` and the `/src/contrib` projects, but this is a good start. One of the most frequently requested areas where users ask for help is "how do I configure X/Y/Z?" I usually steer them to the right place in the source code, but I think putting this up on the website and exposing it that way is much more easily discoverable.
Also copied over some scripts I use to make it easier to preview DocFx websites locally for proofing: `serve-docs.ps1` and `serve-docs.cmd`.
=> added serve-docs.cmd and pages with default HOCON configurations for website

RELEASE_NOTES.md, build.fsx, src/common.props
Akka.NET v1.3.6 is a minor patch consisting mostly of bug fixes.
**Akka.FSharp on .NET Standard**
The biggest change in this release is [the availability of Akka.FSharp on .NET Standard and .NET Core](https://github.com/akkadotnet/akka.net/issues/2826)!
Akka.FSharp runs on .NET Standard 2.0 as of 1.3.6 (it doesn't support .NET Standard 1.6 like the rest of Akka.NET due to FSharp-specific, downstream dependencies.)
**Updates and Additions**
1. [Akka.Streams: Port 4 "streams contrib" stages - AccumulateWhileUnchanged, LastElement, PartitionWith, Sample](https://github.com/akkadotnet/akka.net/pull/3375)
2. [Akka.Remote: Add `public-port` setting to allow for port aliasing inside environments like Docker, …
=> Akka.NET v1.3.6 Release Notes [Dev]

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Actor/AskSpec.cs, src/core/Akka/Actor/Futures.cs
Change the inner `Ask` implementation to accept a message factory instead of a message, so the message can optionally encapsulate the sending `IActorRef` - the address of the light actor inside `Ask`. Only the most complex version of the public `Ask` extension (with Timeout and Cancellation params) also exposes this Factory option. Existing `Ask` extension methods proxy through this new one.
The reasoning behind this:
In the support framework of our application we sometimes need to encapsulate the 'requester' of a message explicitly into the payload, rather than rely on 'Sender'. Two cases stand out: Forwarding (where the generic-ness of the helper prevents us from using `ref.Forward` rather than `ref.Tell`, and the other case is merging/grouping requests -> multiple intended recipients …
=> Add an Ask 'overload' that allows message generation with `IActorRef` inside

src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
close #3430 
So this was a bug I introduced in https://github.com/akkadotnet/akka.net/pull/3395
When manually configuring the allocator for use inside the `DotNettyTransport`, I was `new`-ing up an allocator each time. Instead going forward we'll use the singleton default built into DotNetty.
I'm not 100% sure this eliminates any possibility of buffers leaking on all platforms, since it seems like there's some major runtime differences that could affect this on .NET Core vs. .NET and on Linux / Windows, but this is definitely one possible source of the problem.
=> Akka.Remote memory leak fix: use singleton allocators for DotNetty channels.

build.fsx
Hello, please review this PR 
it fixes https://github.com/akkadotnet/akka.net/issues/3268 - now build process runs all NBench test assemblies, even if some of them are failed.
In case of error it produces following sample output -
here we have 2 fails: 
- one when runner exited with -1
- another when runner timed-out:
```
Running build failed.
Error:
System.Exception: NBench.Runner failed for 2 run(s):
1: "System.Exception: D:\GitHub\alex-bogomaz\akka.net\tools\NBench.Runner\lib\net45\NBench.Runner.exe "D:\GitHub\alex-bogomaz\akka.net
\src\core\Akka.Cluster.Tests.Performance\bin\Release\net452\Akka.Cluster.Tests.Performance.dll" "output-directory="D:\GitHub\alex-bogo
maz\akka.net\PerfResults"" "concurrent="true"" "trace="true"" "teamcity="false""
exited with code -1
at …
```
=> run NBench test despite previous failed

src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj, src/core/Akka.FSharp/Akka.FSharp.fsproj
These csharp warnings are currently imported through the common.props file but are not understood by the fsharp compiler. This is now fixed by overriding the NoWarn property in the FSharp projects.
=> Override suppressed csharp warnings in FSharp projects

docs/articles/persistence/persistence-query.md
Currently the code returns NULL which is not only not allowed but will silently fail if the faulted Task is not dealt with --and will probably confuse people, not just me :)
Let's instead return the actual event to keep the flow going.
=> Minor fix to the Persistence Query sample code

src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj, src/core/Akka.FSharp.Tests/InfrastructureTests.fs, src/core/Akka.FSharp.Tests/Tests.fs
Add a unit test to demonstrate a bug with Akka.FSharp.System.create when creating with a configuration that has akka.extensions specified.
=> Unit test Akka.FSharp.System.create with extensions

src/core/Akka.Tests/Actor/ActorSelectionSpec.cs
close #3420 
No actual bug here. Checked my reproduction in our external app too and... apparently it's fixed there as well.
=> verified that wildcard ActorSelections actually do get delivered to deadletters when there's no matching recipient

src/core/Akka.Cluster/SplitBrainResolver.cs
close #3450 
Purely cosmetic fix. Keep seeing these messages during normal cluster startup and it caused a room full of Akka.NET developers, including me, to freak out every time we saw it. Figured changing it to only log this message only when there were unreachable nodes detected by the time the cluster stabilized would be a good idea.
@Horusiath do you have any opinions on this?
=> Akka.Cluster: don't let SplitBrainResolver log 'partition detected' messages when there are no unreachable nodes

src/core/Akka/Dispatch/MessageQueues/BlockingMessageQueue.cs
close #3459 
I don't see a point in waiting for the timeout - what are we supposed to do? Not deliver the message? Just block indefinitely until the lock is available.
=> just block until lock is available inside BlockingQueue

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.7 is a minor patch consisting mostly of bug fixes as well as an upgrade to DotNetty v0.4.8.
**DotNetty v0.4.8 Upgrade**
You can [read the release notes for DotNetty v0.4.8 here](https://github.com/Azure/DotNetty/blob/5eee925b7597c6b07689f25f328966e330ff58f9/RELEASE_NOTES.md) - but here are the major improvements as they pertain to Akka.NET:
1. DotNetty length-frame decoding is now fully-supported on .NET Core on Linux and
2. Socket shutdown code has been improved, which fixes a potential "port exhaustion" issue reported by Akka.Remote users.
If you've been affected by either of these issues, we strongly encourage that you upgrade your applications to Akka.NET v1.3.8 as soon as possible.
**Updates and Additions**
1. [Akka.Streams: add …
=> Akka.NET v1.3.8 release notes

src/core/Akka.Streams/Implementation/IO/TcpStages.cs, src/core/Akka/Actor/Futures.cs, src/core/Akka/Util/Internal/TaskEx.cs
Fixes #3498 but we need to find a better way to address those issues. Potentially moving to netstandard 2+ compatibility (where async task completion source flags are available by default).
=> Non-blocking task completion source helpers

src/core/Akka/Pattern/CircuitBreaker.cs
Fixes concurrency issue in CircuitBreaker
Migrated from: https://github.com/akka/akka/issues/17415
Didn't include the CircuitBreakerStressSpec, because I was not able to reproduce the issue with it
=> fix concurrency bug in CircuitBreaker

src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
there is a possibility that the `ShardRegion.RestartShard` message escapes into userspace. This can cause issues in custom `ExtractEntityId` implementations.
This can happen, when the `RestartShard` message gets into ShardBuffers here: https://github.com/akkadotnet/akka.net/blob/d732274b0fa9cb6863fabbdf9d1d2c447d61d6f3/src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs#L560
and later is send to `Shard`
=> Sharding - RestartShard escapes into userspace

src/contrib/cluster/Akka.Cluster.Sharding/ShardCoordinator.cs
`RebalanceInProgress` removal is handled in `ClearRebalanceInProgress`, should not be here.
Also checked against akka, also doesn't have it
=> sharding rebalance small fix

src/core/Akka/Actor/ActorCell.Children.cs, src/core/Akka/Actor/ChildrenContainer/Internal/TerminatedChildrenContainer.cs
This PR updated ActorCell methods related with children container modifications to the related code in core JVM version of akka. Most of the changes oscilate around removing usage of lambdas and class tuples in favor of direct interlocked exchange methods.
=> Updated ActorCell children container updates

src/core/Akka.Remote/RemoteWatcher.cs
There is a race condition in the `RemoteWatcher` when `Unwatch`ing shortly before receiving `Terminated`
resulting in:
```
System.Collections.Generic.KeyNotFoundException: The given key '[akka.tcp://engine@10.0.0.5:30002/system/XXXXXXXXXX#399075042]' was not present in the dictionary.
at TValue System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey key)
at void Akka.Remote.RemoteWatcher.ProcessTerminated(IInternalActorRef watchee, bool existenceConfirmed, bool addressTerminated)
at void Akka.Cluster.ClusterRemoteWatcher.OnReceive(object message)
at bool Akka.Actor.UntypedActor.Receive(object message)
at bool Akka.Actor.ActorBase.AroundReceive(Receive receive, object message)
at void Akka.Actor.ActorCell.ReceiveMessage(object message)
at void …
```
=> RemoteWatcher race-condition fix

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Event/LoggingAdapterBase.cs
Designed to help fix https://github.com/akkadotnet/Akka.Logger.Serilog/issues/51 by making LoggingAdapterBase methods `virtual` so they can be overridden at the point in time where the formatting arguments are supplied to the `LogEvent`.
I have a reproduction spec which demonstrates how not having this created some issues in the 1.3.6 version of Akka.Logger.Serilog: https://github.com/akkadotnet/Akka.Logger.Serilog/pull/52 - this PR along with a subsequent update to Akka.Logger.Serilog should fix that.
=> Mark public LoggingAdapterBase methods as virtual

src/core/Akka.Persistence.Tests/PersistentActorSpec.Actors.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs, src/core/Akka.Persistence/Eventsourced.cs
~~**DO NOT MERGE** before #3372~~
> This PR adds support for persisting when recovery is completed, before any commands are received. It's still not possible to persist new events when replaying events. Replaying events should typically be free of external side effects so it doesn't make much sense to support persisting during the actual replay, but there might be some use cases for doing it right afterwards.
Original issues: [#21736](https://github.com/akka/akka/issues/21736) and [#22609](https://github.com/akka/akka/issues/22609)
Original PR: [#21893](https://github.com/akka/akka/pull/21893)
=> Allow persisting events when recovery has completed

docs/articles/clustering/cluster-sharding.md, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingFailureSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingInternalsSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/GetShardTypeNamesSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/ProxyShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs, src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
Contains following changes:
- Provide access to known shard types
https://github.com/akka/akka/issues/23912
- Separate sharding regions and proxies
https://github.com/akka/akka/issues/23472
Fix lookup of coordinator for sharding proxies
https://github.com/akka/akka/pull/23995
- Fix race in ClusterShardingFailureSpec
AFAICT there was nothing ensuring the order of messages when sent to the
shard and the region so first checkthat the passivation has happened
before sending another add in the test
https://github.com/akka/akka/issues/24013
- Better warning message on cluster sharding registration
https://github.com/akka/akka/pull/24906
- entityId => Behavior in ClusterSharding API
mixture of
https://github.com/akka/akka/issues/24053
https://github.com/akka/akka/issues/21809 …
=> Sharding update

src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingConfigSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding.Tests/DDataClusterShardingConfigSpec.cs, src/contrib/cluster/Akka.DistributedData/Properties/AssemblyInfo.cs
close #3529 
Validates that the DData serialization system gets correctly loaded by the `Cluster.Sharding` runtime when `akka.cluster.sharding.state-store-mode=ddata`. In other words, the current behavior is correct and this spec validates it.
=> added DDataClusterShardingConfigSpec

src/core/Akka.Streams.Tests/IO/FileSourceSpec.cs, src/core/Akka.Streams/Implementation/IO/FilePublisher.cs
As discussed in Gitter: Fixes bug in `FileIO.FromFile` that the same file can be opened multiple times at the same time
=> File publisher allows opening the same file for reading multiple times

src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Event/LoggerSpec.cs, src/core/Akka/Event/BusLogging.cs, src/core/Akka/Event/Debug.cs, src/core/Akka/Event/Error.cs, src/core/Akka/Event/ILoggingAdapter.cs, src/core/Akka/Event/Info.cs, src/core/Akka/Event/LogEvent.cs, src/core/Akka/Event/LoggingAdapterBase.cs, src/core/Akka/Event/Warning.cs
Implements #3424 
Introduces a bunch of API changes to the surface area of `ILoggingAdapter` - it's a backwards compatible change, but not a binary compatible change since we've added new methods to the interface. Users will need to recompile any logging plugins in order to consume these changes.
=> [v1.4] Add exception overloads to all logging methods

docs/articles/intro/tutorial-1.md
Added sentence about how an actor system must be created before an actor can be spawned.
Also reformatted the markdown file to 80 columns for readability and fixed a spelling error.
=> Edits to "Part 1: Top-level Architecture" #3433

src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs, src/core/Akka/Actor/ActorCell.ReceiveTimeout.cs
Port [#24927](https://github.com/akka/akka/pull/24927)
=> Fixed ReceiveTimeout not triggered in some case when combined with NotInfluenceReceiveTimeout messages

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
This fixes a memory leak with SqlCommands being referenced indefinitely in the SqlJournal's long living CancellationToken.
=> Create a new linked CancellationToken for each database operation(#3471)

src/contrib/cluster/Akka.Cluster.Sharding.Tests/CoordinatedShutdownShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs, src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs, src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Cluster.Tests/ClusterSpec.cs, src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/Member.cs, src/core/Akka.Tests/Actor/CoordinatedShutdownSpec.cs, src/core/Akka/Actor/CoordinatedShutdown.cs
contains 
https://github.com/akkadotnet/akka.net/pull/3263
- ClusterSingletonManager should ignore FSM events during shutdown
https://github.com/akka/akka/issues/24048
- Run all CoordinatedShutdown phases also when downing
- add Reason to CoordinatedShutdown
https://github.com/akka/akka/issues/24140
- Allow member to leave a cluster via CoordinatedShutdown.run when MemberStatus is Joining/WeaklyUp/Up.
https://github.com/akka/akka/issues/23449
- ClusterSpec, race between MemberRemoved and MemberExited
=> Coordinated downing improvements

docs/examples/DocsExamples/DocsExamples.csproj
This issue with the XUnit version downgrade has rendered our website un-deployable, so this fix is somewhat urgently needed.
Really we should refactor these DocSpecs back into the main solution but that's a bigger bite than I have time for right now.
=> fixed documentation example project build

docs/examples/Tutorials/Tutorial2/DeviceInProgress.cs
private readonly double? _lastTemperatureReading = null;
on line 61 would make this field not editable because of the red only modifier
=> _lastTemperatureReading should be updatable

src/core/Akka.Persistence.Tests/SnapshotSpec.cs, src/core/Akka.Persistence/Eventsourced.Recovery.cs
> The Eventsourced trait does update the sequence number to the snapshoted even if the snapshot is not handled by the actor and then continues recovering from there.
> 
> This may lead to only partially recovered actors. If the snapshot is not handled the actor should recover from scratch to prevent such corrupted states.
Port [#23469](https://github.com/akka/akka/pull/23469)
=> Sequence number should not be set if snapshot is unhandled

docs/articles/streams/stream-dynamic.md, src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/FlowKillSwitchSpec.cs, src/core/Akka.Streams/KillSwitch.cs
This PR introduces an extension method, that allows to produce a stage (similar in design to `SharedKillSwitch`) from `CancellationToken`:
```csharp
var cts = new CancellationTokenSource();
source
.Via(cts.Token.AsFlow<string>(cancelGracefully: true))
.RunForEach(Console.WriteLine, materializer)
```
`cancelGracefully` parameter defines if calling Cancel on token should cause stream shutdown in graceful way (via Complete) or as a failure (via OperationCanceledException).
=> KillSwitches: flow stage from CancellationToken

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.9 features some major changes to Akka.Cluster.Sharding, additional Akka.Streams stages, and some general bug fixes across the board.
**Akka.Cluster.Sharding Improvements**
The [Akka.Cluster.Sharding documentation](http://getakka.net/articles/clustering/cluster-sharding.html#quickstart) already describes some of the major changes in Akka.NET v1.3.9, but we figured it would be worth calling special attention to those changes here.
**Props Factory for Entity Actors**
> In some cases, the actor may need to know the `entityId` associated with it. This can be achieved using the `entityPropsFactory` parameter to `ClusterSharding.Start` or `ClusterSharding.StartAsync`. The entity ID will be passed to the factory as a parameter, which can then …
=> Akka.NET v1.3.9 Release Notes

src/core/Akka.TestKit/TestProbe.cs
This minimal change adds a `ToString` `override` to `TestProbe` to be able to use it in debug logging of tests.
=> Add ToString override to TestProbe.

build.fsx
resolves issue with production beta packages like Cluster.Sharding depending on the wrong version, i.e.:
All of those packages, except for DData, should be references to the stable version. Not beta packages. This PR resolves that issue for all beta packages we still publish.
=> [build system] fix NuGet package dependency version overrides

docs/docfx.json, docs/web.config
This PR adds the `application/json` mimetype for `.json` files to the IIS configuration and enables the `ExtractSearchIndex` postrpocessor, in order to re-enable the search bar functionality , which was reported broken in #3423.
=> #3423 SearchBar fix

src/core/Akka.Cluster.Tests.MultiNode/SurviveNetworkInstabilitySpec.cs, src/core/Akka.Cluster/ClusterDaemon.cs
Currently, a quarantined node will be automatically downed and removed from the cluster without the downing provider being aware of the situation.
Port [#25678](https://github.com/akka/akka/pull/25678)
=> Don't automatically down quarantined nodes

src/core/Akka.Tests/Actor/ActorSelectionSpec.cs, src/core/Akka/Util/StringLike.cs
Addressing [up for grabs #3128](https://github.com/akkadotnet/akka.net/issues/3128)
Stops the following from matching the selection:
```var sys = ActorSystem.Create("sys");
var worker = sys.ActorOf<Worker>("worker");
sys.ActorSelection("akka://sys/user/ker*").Tell(42);```
=> Actor selection #3128

src/examples/Chat/ChatClient/Program.cs, src/examples/Chat/ChatMessages/Messages.cs, src/examples/Chat/ChatServer/Program.cs
This has bothered me for years. Removed all instances of `TypedActor` and replaced them with `ReceiveActor` in this sample. Also removed some unused message types and used the HOCON shorthand for `RemoteActorRefProvider`.
=> Sample Cleanup: Modernize Akka.Remote Chat Sample

src/core/Akka.Persistence/Eventsourced.cs
Fix small typo: "its handler", not "it's handler"
=> Fixo typo in documentation

src/core/Akka.Streams.Tests/Dsl/GraphMergeSortedSpec.cs, src/core/Akka.Streams/Dsl/Graph.cs
Hi - this should fix https://github.com/akkadotnet/akka.net/issues/3604
=> Correctly compare values in MergeSorted

docs/articles/utilities/serilog.md
The [`ColoredConsole`](https://github.com/serilog/serilog-sinks-coloredconsole/) sink has been replaced by the [`Console`](https://github.com/serilog/serilog-sinks-console/) sink, which now implements the same functionality. This PR updates the docs to reflect that.
More info:
* https://github.com/serilog/serilog-sinks-coloredconsole/
* https://www.nuget.org/packages/Serilog.Sinks.ColoredConsole/
---
[![image](https://user-images.githubusercontent.com/177608/46994488-0d125f80-d0eb-11e8-9ed2-b41af9940591.png)](https://github.com/serilog/serilog-sinks-coloredconsole/)
[![image](https://user-images.githubusercontent.com/177608/46994474-f966f900-d0ea-11e8-99fb-625ebea79e01.png)](https://www.nuget.org/packages/Serilog.Sinks.ColoredConsole/)
=> Update Serilog docs to use `Console` instead of `ColoredConsole`

docs/articles/intro/use-case-and-deployment-scenarios.md
Update the [Azure PaaS Worker Role example](https://getakka.net/articles/intro/use-case-and-deployment-scenarios.html#azure-paas-worker-role) to use the provided `CancellationToken` when _awaiting_.
=> Update Azure PaaS Worker Role example to use the provided `CancellationToken`

src/core/Akka/IO/TcpConnection.cs
=> Fix too many open files issue (#3630)

src/core/Akka.Remote.Tests/Transport/DotNettySslSupportSpec.cs, src/core/Akka.Remote/Configuration/Remote.conf, src/core/Akka.Remote/Transport/DotNetty/DotNettyTransportSettings.cs
In certain environments, it is preferred to have certificates installed on the local machine by system administrators, and having applications use said certificates via thumbprint.
This pull request contains changes to allow thumbprints to be used by dotnetty,, via a new set of configuration options; backwards compatibility is maintained by this being 'opt in' behavior.
=> Added Capability for Dotnetty to use Thumbprint for SSL

src/contrib/dependencyinjection/Akka.DI.Core/DIActorContextAdapter.cs, src/contrib/dependencyinjection/Akka.DI.Core/DIActorSystemAdapter.cs
When using the `DI()` extension methods on `ActorSystem` or `IActorContext` without having properly configured an `IDependencyResolver` we currently get a `NullReferenceException` (e.g. [1](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/dependencyinjection/Akka.DI.Core/DIActorSystemAdapter.cs#L43), [2](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/dependencyinjection/Akka.DI.Core/DIActorContextAdapter.cs#L55)).
```csharp
using (var system = ActorSystem.Create("mySystem"))
{
var actorRef = system.DI().Props<MyActor>(); // Throws NullReferenceException
// ...
}
```
This PR adds a check on the constructors of `DIActorSystemAdapter` and `DIActorContextAdapter` to verify if a dependency resolver exists, and throws an `InvalidOperationException` with a clear message …
=> Check if Dependency Resolver is configured to avoid a `NullReferenceException`

src/common.props, src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteConfigSpec.cs, src/contrib/serializers/Akka.Serialization.Hyperion.Tests/HyperionConfigTests.cs, src/contrib/serializers/Akka.Serialization.TestKit/AkkaSerializationSpec.cs, src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoverySpec.cs, src/core/Akka.Remote.Tests/AccrualFailureDetectorSpec.cs, src/core/Akka.Remote.Tests/EndpointRegistrySpec.cs, src/core/Akka.Remote.Tests/RemoteMessageLocalDeliverySpec.cs, src/core/Akka.TestKit.Tests/TestActorRefTests/TestActorRefSpec.cs, src/core/Akka.Tests/Actor/ActorPathSpec.cs, src/core/Akka.Tests/Actor/SupervisorStrategySpecs.cs, src/core/Akka.Tests/Configuration/ConfigurationSpec.cs, src/core/Akka.Tests/Configuration/HoconTests.cs, src/core/Akka.Tests/MatchHandler/MatchExpressionBuilder_BuildLambdaExpression_Tests.cs, src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs, src/core/Akka.Tests/Serialization/NewtonsoftJsonConfigSpec.cs
This PR fixes a number of issues caught by the xunit analyzer.
* xunit1013 - these were false positives due to how we run the MNTK tests
* xunit1014 - basically changing hardcoded string references to nameof
* xunit2000 - basically changing the order so that expected value is first
* xunit2003 - use the xunit Null() check instead of Equals()
* xunit2004 - use the xunit True()/False() check instead of Equal()
* xunit2009 - use the xunit Contains()/StartsWith() check instead of Equals() + string methods
* xunit2012 - use the xunit Contains() check instead of Equals() + Any()
Anecdotal data, but I was able to shave off a minute from the build time and the build log was a bit nicer to look at.
=> Fix xunit warnings

docs/articles/actors/dependency-injection.md
Update docs on Autofac wiring to use the new extension method, now that https://github.com/akkadotnet/Akka.DI.AutoFac/pull/16 has been merged.
=> Update docs on Autofac wiring to use new extension method

src/core/Akka.Cluster/Cluster.cs, src/core/Akka.Cluster/ClusterDaemon.cs, src/core/Akka.Cluster/ClusterSettings.cs
Resolves #3635 and implements a bunch of more helpful, useful log messages inside the cluster which properly attribute the NODE ADDRESS to each logged message. Should be a nice usability improvement to what we have already.
=> [Akka.Cluster] cleanup and fix event logging

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.10 consists mostly of bug fixes and patches to various parts of Akka.NET:
* [Akka.Remote: add support for using installed certificates with thumbprints](https://github.com/akkadotnet/akka.net/issues/3632)
* [Akka.IO: fix TCP sockets leak](https://github.com/akkadotnet/akka.net/issues/3630)
* [Akka.DI.Core: Check if Dependency Resolver is configured to avoid a `NullReferenceException`](https://github.com/akkadotnet/akka.net/pull/3619)
* [Akka.Streams: Interop between Akka.Streams and IObservable](https://github.com/akkadotnet/akka.net/pull/3112)
* [HOCON: Parse size in bytes format. Parse microseconds and nanoseconds.](https://github.com/akkadotnet/akka.net/pull/3600)
* [Akka.Cluster: Don't automatically down quarantined …
=> added v1.3.10 release notes

build.fsx
If TeamCity isn't available to pass in a build number environment variable, beta NuGet packages will now be named using the following convention:
```
[PackageName].[VerisonInReleaseNotes]-beta[DateTime.UtcNow.Ticks]
```
If the `BUILD_NUMBER` environment variable is available, NuGet packages will be built the same way they are now:
```
[PackageName].[VerisonInReleaseNotes]-beta[BUILD_NUMBER]
```
Ported the strategy over from NBench and Hyperion: https://github.com/akkadotnet/Hyperion/pull/103
=> made it easier to generate local beta packages of Akka.NET

docs/articles/persistence/snapshots.md, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
Port [#25590](https://github.com/akka/akka/pull/25590)
=> Provide minSequenceNr for snapshot deletion

src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj, src/core/Akka.FSharp.Tests/ApiTests.fs, src/core/Akka.FSharp/Akka.FSharp.fsproj, src/core/Akka.FSharp/FsApi.fs
This fixes the exception when spawning from an expression using the FSharp api. This did require bumping the FSharp version to 4.5 to get it work though.
=> Fix for #3402. Allows spawning an actor via expression.

docs/examples/DocsExamples/DocsExamples.csproj
`DocsExamples.csproj` referenced its own version of System.Collections.Immutable. Removed that NuGet reference so now it just uses whatever `Akka.csproj` depends on. The upgrade to System.Collections.Immutable 1.5 in #3633 caused our docs to not compile due to the NuGet downgrade errors this caused.
=> fixed NuGet issue with DocsExamples

RELEASE_NOTES.md, src/common.props
Akka.NET v1.3.11 is a bugfix patch primarily aimed at solving the following issue: [DotNetty Remote Transport Issues with .NET Core 2.1](https://github.com/akkadotnet/akka.net/issues/3506).
.NET Core 2.1 exposed some issues with the DotNetty connection methods in DotNetty v0.4.8 that have since been fixed in subsequent releases. In Akka.NET v1.3.11 we've resolved this issue by upgrading to DotNetty v0.6.0.
In addition to the above, we've introduced some additional fixes and changes in Akka.NET v1.3.11:
* [Akka.FSharp: Akka.Fsharp spawning an actor results in Exception](https://github.com/akkadotnet/akka.net/issues/3402)
* [Akka.Remote: tcp-reuse-addr = off-for-windows prevents actorsystem from …
=> added v1.3.11 release notes

docs/articles/streams/error-handling.md, src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt, src/core/Akka.Streams.Tests/Dsl/RestartSpec.cs, src/core/Akka.Streams/Dsl/Restart.cs
Adds a new method signature to both RestartSource and RestartFlow to control if they should restart wrapped Source in only failures, or also in completions.
=> Allow RestartSource/RestartFlow to restart only on failures

src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka/Actor/ActorRef.Extensions.cs
So we can now do something like this:
```
var child = Context.Child(actorName).GetOrElse(() => Context.ActorOf(...));
```
In the JVM this method is part of the OptionVal object, but I thought it made sense to it put along with the IsNobody extension method.
=> Syntactic sugar to make the "create if not exist" pattern more idiomatic

src/core/Akka.Streams/Implementation/Sources.cs
When we `Source.Queue<>` method, it can be materialized into queue with `OfferAsync` method. Problem is that, awaiting for it may cause a deadlock - it's a classical problem with awaiting on the `TaskCompletionSource<>.Task` and using `SetResult` on that task in the same execution context. We already met it before.
This issue is easy to fix in .NET Standard 2.0 by using special option when creating `TaskCompletionSource<>`. For .NET Standard < 1.6 we already provided a hack around it (which uses `Task.Run` to escape from execution context): it's suboptimal, but it's used only for older framework versions.
This PR uses our fixer method set to overcome this deadlock issue.
Example, I've used to recreate this issue, was a Akka.Streams TCP server:
```csharp
// Server
var connectionHandler = …
```
=> Using nonblocking task completion source hack for Source.Queue

docs/articles/streams/quickstart.md
The Getting Started guide lacks crucial knowledge that is necessary to actually get started, which is the nuget package.  So above the ```using Akka```s paragraph, I've added the ```Install-Package Akka.Streams``` instruction.
=> Add "Install-Package" instruction for Akka.Streams

src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs, src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Pattern/BackoffOnRestartSupervisorSpec.cs, src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs, src/core/Akka/Actor/SupervisorStrategy.cs, src/core/Akka/Pattern/BackoffOnRestartSupervisor.cs, src/core/Akka/Pattern/BackoffOptions.cs, src/core/Akka/Pattern/BackoffSupervisor.cs, src/core/Akka/Pattern/BackoffSupervisorBase.cs
Updated BackoffSupervisor to Akka JVM 2.5.18
* BackoffSupervisor notifies sender when child stop
* Fixed BackoffSupervisor.CalculateDelay (and try to settle #3318)
* Added maximum restart attempts to BackoffSupervisor
=> Updated BackoffSupervisor to Akka JVM 2.5.18

src/contrib/cluster/Akka.Cluster.Sharding.Tests/SupervisionSpec.cs, src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt, src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs, src/core/Akka/Pattern/BackoffOnRestartSupervisor.cs, src/core/Akka/Pattern/BackoffOptions.cs, src/core/Akka/Pattern/BackoffSupervisor.cs, src/core/Akka/Pattern/BackoffSupervisorBase.cs
> Can be used to allow cluster sharding to work with a back off on stop supervisor which is typically what you want for sharded persistent actors
[#25933](https://github.com/akka/akka/pull/25933)
[#26142](https://github.com/akka/akka/pull/26142)
=> Support ClusterSharding passivation in BackoffSupervisor

src/core/Akka/Serialization/Serialization.cs
Got one of this exceptions early today when switching to a very old branch. Figured out we were missing something [#26225](https://github.com/akka/akka/pull/26225)
=> Include manifest or class in missing serializer failure if possible

docs/docfx.json
Allows other websites that use DocFx to refer directly to our API documentation [using the built-in DocFx XREF support](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-map-file).
Validated this locally.
=> added ability to publish xrefmap to Akka.NET docs website

src/core/Akka/Dispatch/Mailboxes.cs
Change to exception message in relation to open issue #3292. 
The exception message seems to be taking in the incorrect input at the end of the message. The if statement is making sure `mqType.Value` is a subclass of `actorRequirement.Value` and as such the exception error message should state 
`$"Must be a subclass of [{actorRequirement.Value}]");`
rather than
`$"Must be a subclass of [{mqType.Value}]");`
if this condition is not met.
=> Change input type for error message relating to open issue 

src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs, src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs, src/core/Akka.Persistence.TCK/Query/CurrentEventsByTagSpec.cs
#3697 
Looking at the Scala LevelDb implementation, it looks like they have a special "$$$tag" persistence-id that stores the highest sequence number.
Most SQL database are fairly good at getting highest value of an indexed column, so it's done as a separate query.
=> Fixed logic on how to get current events by tag in batches

RELEASE_NOTES.md, src/common.props
This will be the final bugfix release for Akka.NET v1.3.* - going forward we will be working on releasing Akka.NET v1.4.
This patch contains many important bug fixes and improvements:
* [Akka.Cluster.Sharding: Automatic passivation for sharding](https://github.com/akkadotnet/akka.net/pull/3718)
* [Akka.Persistence: Optimize AtLeastOnceDelivery by not scheduling ticks when not needed](https://github.com/akkadotnet/akka.net/pull/3704)
* [Akka.Persistence.Sql.Common: Bugfix CurrentEventsByTag does not return more than a 100 events](https://github.com/akkadotnet/akka.net/issues/3697)
* [Akka.Persistence.Sql.Common: DeleteMessages when journal is empty causes duplicate key SQL exception](https://github.com/akkadotnet/akka.net/issues/3721)
* …
=> Akka.NET v1.3.12 release notes

docs/articles/actors/di-core.md, docs/articles/actors/fault-tolerance.md, docs/articles/concepts/actors.md, docs/articles/intro/what-problems-does-actor-model-solve.md, docs/articles/persistence/event-sourcing.md, docs/articles/streams/pipeliningandparallelism.md, docs/articles/toc.yml, docs/index.md
This PR fixes several broken links on the website.
These were mainly due to incomplete ports from the old site, markdown
errors, or items being shuffled around.
=> [docs] fix broken links on website

RELEASE_NOTES.md, src/common.props, src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt, src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs
Brings our API in-line with JVM Akka, but more importantly - makes the `ThrottleTransportAdapter` usable outside of internal Akka.NET tests and tools.
=> made ThrottleTransportAdapter messages public

src/core/Akka.Persistence/Eventsourced.cs
As an user I want the complete stacktrace when persistence of an event is rejected. Plus IMO any issue wih persistence is a serious enough to log an error instead. I checked, and the JVM is logging an error too.
=> OnPersistRejected now logs an error with the complete stacktrace

src/core/Akka.Streams/Dsl/Restart.cs
> That seems reasonable, failing streams do not necessarily require operator attention.
Port [#25023](https://github.com/akka/akka/pull/25023)
=> Reducing log level of restarting to WARN

src/core/Akka/Actor/Props.cs
While running some unit tests using a PersistentActor a `NullReferenceException` was encountered. The culprit seems to be that when `producer.Produce()` throws an exception, the creation of the `TypeLoadException` throws a `NullReferenceException` when `Arguments` is `null`. The relevant excerpt from `Props` lines 568-577
```csharp
public virtual ActorBase NewActor()
{
var type = Type;
var arguments = Arguments;
try {
return producer.Produce();
} catch (Exception e) {
throw new TypeLoadException($"Error while creating actor instance of type {type} with {arguments.Length} args: ({StringFormat.SafeJoin(",", arguments)})", e);
}
}
```
This fix ensures that no matter how the  `Props`  is constructed, `Arguments` will not be `null` fixing the above issue. This problem might be related to issue …
=> Ensure Arguments are never null

RELEASE_NOTES.md, src/common.props
Well, we thought 1.3.12 would be the final release for Akka.NET v1.3.* - but then we found some nasty bugs prior to merging any of the v1.4 features into our development branch. But finally, for real this time - this is really the last v1.3.13 release.
This patch contains some critical bug fixes and improvements to Akka.NET:
* [Akka.Persistence: OnPersistRejected now logs an error with the complete stacktrace](https://github.com/akkadotnet/akka.net/pull/3763)
* [Akka.Persistence.Sql: Ensure that BatchingSqlJournal will propagate sql connection opening failure](https://github.com/akkadotnet/akka.net/pull/3754)
* [Akka: Add UnboundedStablePriorityMailbox](https://github.com/akkadotnet/akka.net/issues/2652)
* [Akka.Remote and Akka.Cluster: Port …
=> added v1.3.13 release notes

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
Currently, you have to capture Sender before calling Persist() when you use the BatchingSqlJournal, otherwise you end up with the wrong Sender in the PersistCallback.
=> BatchingSqlJournal now preserves Sender in PersistCallback

build.fsx
If there are no "compilable" changes, skip packing the MultiNodeTestRunner (which currently errors out)
=> Skip MNTRNuGet pack when skipping builds

build-system/azure-pipeline.template.yaml
=> Azure DevOps: moved 'fail' stage after artifact copy stage

build-system/azure-pipeline.template.yaml
=> Azure DevOps: glob all artifact subfolders

src/core/Akka.Remote.TestKit.Tests/RemoteConnectionSpecs.cs, src/core/Akka.Remote.TestKit/RemoteConnection.cs
=> [SpecFix] made RemoteConnection_should_send_and_decode_messages async

src/core/Akka.Persistence.Tests/PersistenceSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorRecoveryTimeoutSpec.cs, src/core/Akka.Persistence.Tests/PersistentActorSpec.cs, src/core/Akka.Remote.TestKit.Tests/RemoteConnectionSpecs.cs
#3786 - fix PersistentActor_should_be_able_to_persist_events_that_happen_during_recovery by porting https://github.com/akka/akka/pull/22232
=> fix PersistentActor_should_be_able_to_persist_events_that_happen_during_recovery

src/core/Akka.Cluster.Tests/ClusterSpec.cs
Part #3786 - these two specs are racy and they don't actually test anything meaningful. Invoking the `CancellationTokenSource` we pass into the `Cluster.JoinAsync` or `Cluster.JoinSeedNodesAsync` methods doesn't actually cancel the `Join` operation from executing, they only cancel the `Task` returned by these methods. They're just bloat in the test suite - thought it best to remove them.
=> [SpecFix] removed two Cluster must cancel join prematurely specs

src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs, src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
PassivateIdleTask was not cancelled for persistent shards on stop leading to deadletters
=> sharding PassivateIdle fix

src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
#3822 I think any actor state accessed in WriteMessagesAsync is at risk, namely _tagSubscribers and _persistenceIdSubscribers. Both changed to ImmutableDictionary of ImmutableSet.
=> Changed subscriber lists to immutable collections

src/core/Akka/Actor/CoordinatedShutdown.cs
Fixes #3815 
I've removed the return statement in front of force exit task, which was making code responsible for actual terminating of actor system unreachable when both terminate-actor-system and exit-clr are enabled.
Sorry for not writing any tests but I didn't figure out how to write unit test for code containing ```Environment.Exit(0)``` (which causes whole test suite to exit).
=> Remove return of force exit task in coordinated shutdown

src/core/Akka.Remote.Tests/RemoteConsistentHashingRouterSpec.cs, src/core/Akka.Remote.Tests/Transport/AkkaProtocolSpec.cs, src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs
=> fixed issue with multiple specs all trying to use same Akka.Remote port at the same time
