akkadotnet/akka.net

- src/core/Akka.Tests/Actor/ActorProducerPipelineTests.cs
- src/core/Akka/Actor/ActorCell.FaultHandling.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/ActorProducerPipeline.cs
- src/core/Akka/Actor/ExtendedActorSystem.cs
- src/core/Akka/Actor/Internals/ActorSystemImpl.cs
- src/core/Akka/Actor/Stash/IActorStash.cs
> API changes: pipeline caching based on actor type + renaming plugins methods

- documentation/wiki/What-is-Akka.md
- Remove JVM Akka references
- Add commercial support section
- Comment out TODO items so not visible to end user
- Little edits for easier reading flow
> Beginning to update documentation

- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterEvent.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/ClusterMetricsCollector.cs
- src/core/Akka.Remote.TestKit/BarrierCoordinator.cs
- src/core/Akka.Remote.TestKit/Conductor.cs
- src/core/Akka.Remote.TestKit/Player.cs
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/RemoteWatcher.cs
- src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs
- src/core/Akka/Actor/ActorBase.cs
- src/core/Akka/Actor/FSM.cs
- src/core/Akka/Actor/Inbox.Actor.cs
- src/examples/TimeServer/TimeServer/Program.cs
Deprecating IActorLogging interface and removing its implementations.
> Removing all implementations of IActorLogging #515

- src/core/Akka/Actor/ActorRef.cs
Hi. Please review this pull request. It contains fix for issue #540 "Remove ReservedActorRef"
> Remove ReservedActorRef

- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/Journal/SyncWriteJournal.cs
- src/core/Akka.Persistence/Snapshot/SnapshotStore.cs
- src/core/Akka.Remote.TestKit/Player.cs
- src/core/Akka.Remote.Tests/AckedDeliverySpec.cs
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/Transport/AkkaProtocolTransport.cs
- src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs
- src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
- src/core/Akka/Actor/ActorProducerPipeline.cs
- src/core/Akka/Util/MonoConcurrentQueue.cs
> Fixed a few typos

- src/core/Akka.Remote.TestKit/Conductor.cs
- src/core/Akka.Remote/AckedDelivery.cs
A couple of xmldoc tags weren't closed properly.
> Fixed a couple of xmldoc errors.

- src/contrib/dependencyInjection/Akka.DI.Core/Extensions.cs
- src/core/Akka.Remote.TestKit/Controller.cs
- src/core/Akka.Remote/Routing/RemoteRouterConfig.cs
- src/core/Akka.Tests.Shared.Internals/AkkaSpecExtensions.cs
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/Extensions.cs
- src/core/Akka/Util/Internal/StringBuilderExtensions.cs
Redundant casts are redundant.
> Removed redundant casts

- src/core/Akka.FSharp/FsApi.fs
> [#645] Fix typo in function name

- src/core/Akka.Persistence.Tests/PersistentViewSpec.cs
- src/core/Akka.Tests/Actor/ActorRefSpec.cs
- src/core/Akka/Actor/ActorBase.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
> ActorRefSpec missing specs + actor cell sys msg optimizations

- src/core/Akka/Actor/ActorSystem.cs
> Documentation update to reflect how the Actor System should be named

- src/core/Akka.Tests/App.config
- src/core/Akka/Configuration/ConfigurationFactory.cs
- src/examples/TimeServer/TimeClient/App.config
- src/examples/TimeServer/TimeClient/Program.cs
- src/examples/TimeServer/TimeServer/App.config
- src/examples/TimeServer/TimeServer/Program.cs
Changed ConfigurationFactory to load App.Config automatically from disk
Modified TimeServer example to use auto-loading config
> Automatic App / Web.config loading #671

- documentation/wiki/Contributing to Akka.NET.md
> Fixed link

- RELEASE_NOTES.md
- src/SharedAssemblyInfo.cs
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Bumping the version numbers for local builds for the time being. Nothing gets auto-published to NuGet without going through the master branch ATM.
> added 1.0 version numbers

- src/core/Akka/Actor/IActorContext.cs
Documented most of `IActorContext` #647
> documented IActorContext

- src/core/Akka.TestKit/TestFSMRef.cs
- src/core/Akka.TestKit/TestKitBase_AwaitConditions.cs
- src/core/Akka.TestKit/TestProbe.cs
> xmldoc fixes

- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparerAdapter.cs
- src/core/Akka.FSharp/FsApi.fs
- src/core/Akka.TestKit/EventFilter/TestEventListener.cs
- src/core/Akka.TestKit/NoImplicitSender.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka.TestKit/TestKitBase_ActorOf.cs
- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.Tests.Shared.Internals/TestReceiveActor.cs
- src/core/Akka/Actor/Inbox.cs
- src/core/Akka/Actor/Stash/WithBoundedStash.cs
- src/core/Akka/Actor/Stash/WithUnboundedStash.cs
- src/core/Akka/Routing/ConsistentHash.cs
- src/core/Akka/Routing/Listeners.cs
- fixed various xmldoc errors namely references and a malformed tag
- closes #720
n.b. sandcastle will error when it encounters a pre tag within a code
tag
> xmldoc and sandcastle fix

- src/core/Akka.FSharp/FsApi.fs
The F# API currently doesn't expose stash capabilities.
This is a basic implementation for the unbounded stash.
Usage example:
```fsharp
(fun (mailbox: Actor<_>) -> 
let rec runningChartActor () =
actor {
let! message = mailbox.Receive ()
match message with
| TogglePause -> return! pausedChartActor ()
| _ -> return! runningChartActor ()
}
and pausedChartActor () =
actor {
let! message = mailbox.Receive ()
match message with
| TogglePause -> 
mailbox.UnstashAll ()
return! runningChartActor ()
| m -> 
let ps = m
|> pausedHandler mailbox
|> Option.map (fun _ -> mailbox.Stash ())
return! pausedChartActor ()
}
runningChartActor ())
```
Features to add in the future (discussed with @Horusiath):
1. Create the stash lazily when Stash() is called for the first time.
2. Provide a way to choose …
> Added stash support for F#

- README.md
Think I have a fix for #734, but I need a fresh PR to find out :p
> added logo to README (testing 734)

- src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs
- src/core/Akka.Remote.Tests/RemoteRouterSpec.cs
- src/core/Akka.Remote.Tests/Transport/GenericTransportSpec.cs
- src/core/Akka.Remote/Transport/FailureInjectorTransportAdapter.cs
- src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs
- src/core/Akka.Remote/Transport/TransportAdapters.cs
- src/core/Akka.Tests/Actor/ActorPathSpec.cs
- src/core/Akka.Tests/Actor/AddressSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Actor/Address.cs
- src/core/Akka/Actor/RemoteScope.cs
Fix for #750 and give Address a general tidy up, including adding the WithXXX mutation methods as discussed with @rogeralsing
> Remoting and hostnames case sensitivity bug

- documentation/wiki/ActorProducerPipeline.md
> Created docs for ActorProducerPipeline

- src/examples/Chat/ChatClient/Program.cs
This fixes a problem introduced in the latest merge and makes the code compilable again. I'm going to pull this in myself as it's trivial.
> Add missing using

- src/core/Akka/Actor/SupervisorStrategy.cs
The final step in making primitives immutable using surrogates.
`SupervisorStrategy` is now back to its original form
> Immutable SupervisorStrategy 

- documentation/wiki/Examples of use cases for Akka.md
Removed stray heading that appeared at the and of the page.
> Update Examples of use cases for Akka.md

- src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Persistence/JsonPersistentTestRunStore.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunCoordinator.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
- src/core/Akka.Remote/DeadlineFailureDetector.cs
- src/core/Akka/Routing/ConsistentHash.cs
- src/core/Akka/Routing/ResizablePoolCell.cs
- src/core/Akka/Util/Internal/ImmutabilityUtils.cs
In first commit I removed Guard which would never throw.
In second commit I removed guards and changed them to manual exception throwing.
Should I also remove Guard class since it's now no longer in use ?
> Issue #765

- src/contrib/testkits/Akka.TestKit.VsTest/VsTestAssertions.cs
- src/contrib/testkits/Akka.TestKit.Xunit/XunitAssertions.cs
- src/core/Akka.Cluster.Tests/MultiNode/MultiNodeClusterSpec.cs
- src/core/Akka.FSharp/FsApi.fs
- src/core/Akka.Persistence.FSharp/FsApi.fs
- src/core/Akka.TestKit/Akka.TestKit.csproj
- src/core/Akka.TestKit/ITestKitAssertions.cs
- src/core/Akka.TestKit/TestKitAssertionsExtension.cs
- src/core/Akka.TestKit/TestKitAssertionsProvider.cs
- src/core/Akka.TestKit/TestKitBase.cs
- src/core/Akka.TestKit/TestProbe.cs
- src/core/Akka/Actor/ActorRefFactoryExtensions.cs
- src/core/Akka/Actor/ActorRefFactoryShared.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/Dsl/Act.cs
- src/core/Akka/Actor/IActorContext.cs
- src/core/Akka/Actor/IActorRefFactory.cs
- src/core/Akka/Akka.csproj
In support of #802, the last of the interfaces.
> Actually the last interface renames. :)

- src/Akka.sln
- src/contrib/dependencyInjection/Akka.DI.Unity/Akka.DI.Unity.csproj
- src/contrib/dependencyInjection/Akka.DI.Unity/Akka.DI.Unity.nuspec
- src/contrib/dependencyInjection/Akka.DI.Unity/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Akka.DI.Unity/Readme.md
- src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs
- src/contrib/dependencyInjection/Akka.DI.Unity/packages.config
- src/contrib/dependencyInjection/Examples/BasicUnityUses/Actors.cs
- src/contrib/dependencyInjection/Examples/BasicUnityUses/App.config
- src/contrib/dependencyInjection/Examples/BasicUnityUses/BasicUnityUses.csproj
- src/contrib/dependencyInjection/Examples/BasicUnityUses/Program.cs
- src/contrib/dependencyInjection/Examples/BasicUnityUses/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Examples/BasicUnityUses/packages.config
- src/packages/repositories.config
Ive recreated this as i made a mess of the previous one :S
> UnityDependencyResolver and example project

- src/core/Akka.FSharp.Tests/ApiTests.fs
- src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
> Updated PR for fixing F# discriminated unions

- src/contrib/dependencyInjection/Akka.DI.Core/Readme.md
Updated Readme file to match Patch for issues 832 & 833
> Updated Readme to match Patch for Issues 832, 833

- src/examples/PersistenceExample/GuaranteedDeliveryExampleActor.cs
- src/examples/PersistenceExample/PersistenceExample.csproj
- src/examples/PersistenceExample/Program.cs
Guaranteed delivery with default journal. I didn't use snapshotting as there are some discussions in progress #789 and akka/akka#17139
> Guaranteed delivery sample

- src/core/Akka.Cluster/ClusterMetricsCollector.cs
> Proposed fix for #812

- src/contrib/dependencyInjection/Akka.DI.AutoFac/Akka.DI.AutoFac.nuspec
- src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Akka.DI.CastleWindsor.nuspec
- src/contrib/dependencyInjection/Akka.DI.Core/Akka.DI.Core.nuspec
- src/contrib/dependencyInjection/Akka.DI.Ninject/Akka.DI.Ninject.nuspec
- src/contrib/dependencyInjection/Akka.DI.Unity/Akka.DI.Unity.nuspec
- src/contrib/loggers/Akka.Logger.NLog/Akka.Logger.NLog.nuspec
- src/contrib/loggers/Akka.Logger.Serilog/Akka.Logger.Serilog.nuspec
- src/contrib/loggers/Akka.Logger.slf4net/Akka.Logger.slf4net.nuspec
- src/contrib/testkits/Akka.TestKit.VsTest/Akka.TestKit.VsTest.nuspec
- src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.nuspec
- src/core/Akka.Cluster/Akka.Cluster.nuspec
- src/core/Akka.FSharp/Akka.FSharp.nuspec
- src/core/Akka.Persistence.FSharp/Akka.Persistence.FSharp.nuspec
- src/core/Akka.Persistence.TestKit/Akka.Persistence.TestKit.nuspec
- src/core/Akka.Persistence/Akka.Persistence.nuspec
- src/core/Akka.Remote/Akka.Remote.nuspec
- src/core/Akka.TestKit/Akka.TestKit.nuspec
- src/core/Akka/Akka.nuspec
The NuGet packages were missing icons, this changes the nuspec files to point to the new icon location
> Update nuspecs to point to new icon location

- src/contrib/dependencyInjection/Akka.DI.AutoFac/AutoFacDependencyResolver.cs
- src/contrib/dependencyInjection/Akka.DI.Core/DIActorContextAdapter.cs
- src/contrib/dependencyInjection/Akka.DI.Ninject/NinjectDependencyResolver.cs
- src/contrib/dependencyInjection/Akka.DI.Unity/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs
- src/contrib/dependencyInjection/Examples/BasicAutoFacUses/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Examples/BasicCastleWindsorUse/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Examples/BasicNinjectUses/Properties/AssemblyInfo.cs
- src/contrib/dependencyInjection/Examples/BasicUnityUses/Program.cs
- src/contrib/dependencyInjection/Examples/BasicUnityUses/Properties/AssemblyInfo.cs
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster/ClusterEvent.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Persistence/JsonPersistentTestRunStore.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunCoordinator.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs
- src/core/Akka.Persistence.TestKit/Journal/JournalSpec.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpec.cs
- src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
- src/core/Akka.Remote/DeadlineFailureDetector.cs
- src/core/Akka.Tests/Actor/RootGuardianActorRef_Tests.cs
- src/core/Akka.Tests/Actor/SystemGuardianTests.cs
- src/core/Akka.Tests/Dispatch/DispatchersSpec.cs
- src/core/Akka.Tests/Routing/RoutingSpec.cs
- src/core/Akka.Tests/Routing/TailChoppingSpec.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
- src/core/Akka/Dispatch/DequeBasedMailbox.cs
- src/core/Akka/Routing/RoundRobin.cs
- src/core/Akka/Routing/ScatterGatherFirstCompleted.cs
- src/examples/Chat/ChatServer/Program.cs
- src/examples/PersistenceExample/GuaranteedDeliveryExampleActor.cs
These using clauses don't appear to be used.
> Removed unused usings

- src/contrib/persistence/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.csproj
- src/contrib/persistence/Akka.Persistence.SqlServer/Akka.Persistence.SqlServer.nuspec
> Added nuspec to Akka.Persistence.SqlServer

- src/contrib/dependencyInjection/Akka.DI.AutoFac/Readme.md
- src/contrib/dependencyInjection/Akka.DI.CastleWindsor/Readme.md
- src/contrib/dependencyInjection/Akka.DI.Core/Readme.md
- src/contrib/dependencyInjection/Akka.DI.Ninject/Readme.md
- src/contrib/dependencyInjection/Akka.DI.Unity/Readme.md
- added code fences
- fixed some stilted wording to flow better
- rearranged sections to flow better
- added relevant links to the wiki
- added final example to each segment that ties the document together
> Documentation fixes for Dependency Injection

- src/core/Akka/Akka.csproj
- src/core/Akka/Serialization/JavaSerializer.cs
- src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs
- src/core/Akka/Serialization/NullSerializer.cs
- src/core/Akka/Serialization/Serializer.cs
- moved regular comments into xmldoc
- added class cross-references
- fleshed out auto-generated xmldoc
- split JavaSerializer into its own file
> Updated xmldocs in Akka.Serialization

- src/core/Akka/Event/Logging.cs
> "virtual" log level for OFF #940

- RELEASE_NOTES.md
- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj
- src/core/Akka.Remote.TestKit/MsgEncoder.cs
- src/core/Akka.Remote.TestKit/MultiNodeFact.cs
- src/core/Akka.Remote.TestKit/Player.cs
- src/core/Akka.Remote.TestKit/packages.config
- src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj
- src/core/Akka.Remote.Tests/MultiNode/RemoteNodeShutdownAndComeBackSpec.cs
- src/core/Akka.Remote.Tests/packages.config
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka.Remote/RemoteDaemon.cs
> Implement RemotingTerminator and add RemoteNodeShutdownAndComeBackSpec

- src/Akka.sln
- src/contrib/clustersingleton/Akka.ClusterSingleton/Akka.ClusterSingleton.csproj
- src/contrib/clustersingleton/Akka.ClusterSingleton/ClusterSingletonManager.cs
- src/contrib/clustersingleton/Akka.ClusterSingleton/ClusterSingletonProxy.cs
- src/contrib/clustersingleton/Akka.ClusterSingleton/MemberAgeOrdering.cs
- src/contrib/clustersingleton/Akka.ClusterSingleton/Properties/AssemblyInfo.cs
- src/contrib/clustersingleton/Akka.ClusterSingleton/packages.config
- src/packages/repositories.config
This is a WIP to add initial cluster singleton port as to allow for progress to be made on cluster sharding. Tests and code comments still to come.
> [WIP] clustersingleton

- build.fsx
> Fix for the nightly build beta tagging

- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/TestRunCoordinatorSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Reporting/TestRunCoordinator.cs
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/RemoteSettings.cs
- src/core/Akka.Tests/Dispatch/MailboxesSpec.cs
- src/core/Akka/Actor/Scheduler/TaskBasedScheduler.cs
- src/core/Akka/Configuration/Pigeon.conf
- src/core/Akka/Dispatch/ForkJoinDispatcher.cs
- src/core/Akka/Dispatch/SingleThreadDispatcher.cs
- src/core/Akka/Dispatch/ThreadPoolBuilder.cs
- src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
- src/examples/Cluster/Samples.Cluster.Simple/App.config
- src/examples/Cluster/Samples.Cluster.Simple/Program.cs
Cluster and dispatcher had a few actors on the default dispatcher this PR corrects that. Also some boyscout cleanup and the dedicated threads will now have names.
> Added dispatcher fixes for remote and cluster

- src/contrib/clustersharding/Akka.ClusterSharding/ClusterSharding.cs
Checking in my latest sharding updates
> small sharding progress

- src/core/Akka.Tests/Routing/RoutingSpec.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Routing/RouterPoolActor.cs
This fixes #996 
It also contais @kaju's tests for verification
> Pool router supervisor strategy fix

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
This is part of the overall work to be done for cluster sharding.
> ported message types, some workers and shard region receive recovery

- src/core/Akka/Routing/ScatterGatherFirstCompleted.cs
Added constructor overload for  ScatterGatherFirstCompletedPool
> Added constructor overload

- src/core/Akka/Configuration/Hocon/AkkaConfigurationSection.cs
- src/core/Akka/Configuration/Hocon/CDataConfigurationElement.cs
- src/core/Akka/Configuration/Hocon/HoconArray.cs
- src/core/Akka/Configuration/Hocon/HoconConfigurationElement.cs
- src/core/Akka/Configuration/Hocon/HoconLiteral.cs
- src/core/Akka/Configuration/Hocon/HoconObject.cs
- src/core/Akka/Configuration/Hocon/HoconParser.cs
- src/core/Akka/Configuration/Hocon/HoconRoot.cs
- src/core/Akka/Configuration/Hocon/HoconSubstitution.cs
- src/core/Akka/Configuration/Hocon/HoconToken.cs
- src/core/Akka/Configuration/Hocon/HoconTokenizer.cs
- src/core/Akka/Configuration/Hocon/HoconValue.cs
- src/core/Akka/Configuration/Hocon/IHoconElement.cs
Fixed missing/boilerplate xmldoc comments to the
Akka.Configuration.HOCON classes
> Fixed missing/boilerplate xmldoc comments

- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka/Actor/ActorRef.cs
Reverts akkadotnet/akka.net#1037
> Revert "Fixes for NoSender serialization bugs"

- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka.Tests/IO/TcpConnectionSpec.cs
- src/core/Akka.Tests/IO/TcpListenerSpec.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
- src/core/Akka/Akka.csproj
- src/core/Akka/IO/ByteBuffer.cs
- src/core/Akka/IO/DirectByteBufferPool.cs
- src/core/Akka/IO/IO.cs
- src/core/Akka/IO/Inet.cs
- src/core/Akka/IO/SelectionHandler.cs
- src/core/Akka/IO/SocketAsyncEventArgsPool.cs
- src/core/Akka/IO/SocketChannel.cs
- src/core/Akka/IO/Tcp.cs
- src/core/Akka/IO/TcpConnection.cs
- src/core/Akka/IO/TcpIncomingConnection.cs
- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/IO/TcpManager.cs
- src/core/Akka/IO/TcpOutgoingConnection.cs
- src/core/Akka/Util/ByteIterator.cs
- src/core/Akka/Util/ByteString.cs
- src/core/Akka/Util/Internal/Extensions.cs
This is a port of the Akka IO TCP driver. I've initially created PR #1023 on the dev branch. This is the same PR on the akka-io branch.
@Horusiath - Thanks for the feedback in that PR - I will include it in my next contribution to Akka IO
> Initial Akka IO port with TCP driver

- RELEASE_NOTES.md
- build.fsx
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.nuspec
- src/core/Akka.Cluster/Member.cs
Fixed issues with Akka.Persistence.Sql.Common packages (#1044.) Doing a quick release and a bump to Akka.NET v1.0.3 so we can solve this issue for all Akka.Persistence.SqlServer and Akka.Persistence.PostgreSql users.
None of the other changes from dev are included in this release.
> close #1044 (PRODUCTION RELEASE)

- RELEASE_NOTES.md
- build.fsx
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.nuspec
- src/core/Akka.Cluster/Member.cs
Bringing over the build system changes from v1.0.3 into `dev`.
> bringing in latest changes from master to dev

- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka.Tests/IO/SimpleDnsCacheSpec.cs
- src/core/Akka.Tests/IO/TcpConnectionSpec.cs
- src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs
- src/core/Akka/Akka.csproj
- src/core/Akka/IO/DatagramChannel.cs
- src/core/Akka/IO/DirectByteBufferPool.cs
- src/core/Akka/IO/Dns.cs
- src/core/Akka/IO/DnsProvider.cs
- src/core/Akka/IO/InetAddressDnsProvider.cs
- src/core/Akka/IO/InetAddressDnsResolver.cs
- src/core/Akka/IO/SimpleDnsCache.cs
- src/core/Akka/IO/SimpleDnsManager.cs
- src/core/Akka/IO/SocketChannel.cs
- src/core/Akka/IO/Tcp.cs
- src/core/Akka/IO/TcpConnection.cs
- src/core/Akka/IO/TcpListener.cs
- src/core/Akka/IO/TcpOutgoingConnection.cs
- src/core/Akka/IO/Udp.cs
- src/core/Akka/IO/UdpConnected.cs
- src/core/Akka/IO/UdpConnectedManager.cs
- src/core/Akka/IO/UdpConnection.cs
- src/core/Akka/IO/UdpListener.cs
- src/core/Akka/IO/UdpManager.cs
- src/core/Akka/IO/UdpSender.cs
- src/core/Akka/IO/WithUdpSend.cs
- src/core/Akka/Util/ByteIterator.cs
- src/core/Akka/Util/ByteString.cs
This is a port of the IO DNS cache. With this PR most of the IO extension have been ported. I will create a list of outstanding issues.
> Akka IO - DNS Port

- src/core/Akka.FSharp/FsApi.fs
Two little changes:
1. Overload for `ICanTell.Ask` method. As discussed in #1042 up to this moment there was no elegant way to use Ask with timeout specified using F# API. To be compatible, ask had to look like this: `actorRef.Ask(message, Nullable(timeout)) |> Async.AwaitTask`. After this change it's equivalent would be: `actorRef.Ask(message, timeout)`.
2. Until now F# Actor tried direct casting message to input type expected by behavior function. It means, that if message of wrong type was sent, invalid cast exception would be thrown and actor would crash and restart. Now it will check if message is of expected type and if not, it will become unhandled, which is actually an expected and akka idiomatic behavior.
Review first ;)
> F# API - ask wrapper + making messages of wrong types unhandled

- src/core/Akka.Remote/RemoteSystemDaemon.cs
- src/examples/RemoteDeploy/System1/Program.cs
This PR enables remote watching from the RemoteSystemDaemon
(and also removes some old debug code from the remote deploy example)
> Enable remote watching from RemoteSystemDaemon

- build.fsx
- build.sh
Updated our build scripts to work around https://github.com/fsharp/fsharp/issues/427 and resolve https://github.com/fsharp/FAKE/issues/839
> Fixed build scripts to work around known issues with Mono 4.0

- src/core/Akka.Remote/RemoteWatcher.cs
fixing #1090
there was a condition that always evaluated true that is now fixed to be in line with the scala code
> fixing repeated remote rewatch

- src/core/Akka.Tests/IO/TcpConnectionSpec.cs
This PR resolves the test failures in #1117.
This happened when Socket.BeginConnect completed synchronously. See comments in diff.
> Akka IO: Fixed intermittent test failures

- tools/CheckSourceFilesForCopyrightHeader.ps1
A Powershell script to check source files for copyright banner.
> [tools] Script to check source files for copyright banner

- src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj
- src/core/Akka.TestKit.Tests/TestSchedulerTests.cs
- src/core/Akka.TestKit/Akka.TestKit.csproj
- src/core/Akka.TestKit/Internal/TestScheduler.conf
- src/core/Akka.TestKit/TestScheduler.cs
- src/core/Akka/Properties/AssemblyInfo.cs
Needed for testing actors that use the scheduler. Included unit tests demonstrate usage.
> A virtual time TestScheduler

- src/contrib/persistence/Akka.Persistence.Sql.Common/InternalExtensions.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryBuilder.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryMapper.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/DbSnapshotStore.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryBuilder.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryMapper.cs
- src/contrib/testkits/Akka.TestKit.NUnit.Tests/Properties/AssemblyInfo.cs
- src/contrib/testkits/Akka.TestKit.NUnit/Properties/AssemblyInfo.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Properties/AssemblyInfo.cs
- src/core/Akka.NodeTestRunner/Discovery.cs
- src/core/Akka.TestKit.Tests/TestSchedulerTests.cs
- src/core/Akka.TestKit/ActorCellKeepingSynchronizationContext.cs
- src/core/Akka.TestKit/TestScheduler.cs
- src/core/Akka.Tests/Actor/SupervisorStrategySpecs.cs
- src/core/Akka.Tests/Dispatch/XUnitAsyncTestsSanityCheck.cs
- src/core/Akka.Tests/Pattern/BackoffSupervisorSpec.cs
- src/core/Akka.Tests/Util/Internal/Collections/IteratorTests.cs
- src/core/Akka/Actor/Scheduler/DedicatedThreadScheduler.cs
- src/core/Akka/ActorState.cs
- src/core/Akka/Event/EventStreamExtensions.cs
- src/core/Akka/Pattern/BackoffSupervisor.cs
- src/core/Akka/Util/Internal/Collections/EnumeratorExtensions.cs
- src/core/Akka/Util/Internal/Collections/Iterator.cs
- src/core/Akka/Util/Internal/TaskExtensions.cs
- src/core/Akka/Util/MonotonicClock.cs
- src/core/Akka/Util/Vector.cs
- src/examples/PersistenceExample/AtLeastOnceDeliveryExampleActor.cs
Some newer files were missing the copyright banner.
> [misc] Added copyright banner to files

- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerChaosSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerLeaveSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonManagerStartupSpec.cs
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
This PR contains ported code of:
- `ClusterSingletonManagerSpec` 
- `ClusterSingletonManagerLeaveSpec`
Also skipped multi node facts about `Akka.Cluster.Tools` that where not verified yet.
> Cluster singleton manager specs

- src/core/Akka.Persistence.TestKit.Tests/LocalSnapshotStoreSpec.cs
- src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs
cc #1149 
This should fix the issue, using URI escaping on PersistenceId. Test attached.
> Fix for bug #1149: LocalSnapshotStore failing on pid using forbidden path characters

- build.fsx
Added Akka.TestKit.XUnit2 as a NuGet dependency for Akka.Persistence.TestKit
closes #1101
> Added Akka.TestKit.XUnit2 as a NuGet dependency for Akka.Persistence.TestKit

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs
- src/contrib/transports/Akka.Remote.AkkaIOTransport/TransportManager.cs
- src/core/Akka.Remote.Tests/RemoteRouterSpec.cs
- src/core/Akka.Tests/Actor/Scheduler/TaskBasedScheduler_TellScheduler_Schedule_Tests.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/Scheduler/DedicatedThreadScheduler.cs
- src/core/Akka/Actor/Scheduler/DeprecatedSchedulerExtensions.cs
- src/core/Akka/Configuration/Hocon/AkkaConfigurationSection.cs
- src/core/Akka/Configuration/Hocon/CDataConfigurationElement.cs
- src/core/Akka/Configuration/Hocon/HoconConfigurationElement.cs
- src/core/Akka/Configuration/Hocon/HoconValue.cs
- src/core/Akka/Dispatch/AbstractDispatcher.cs
- src/core/Akka/IO/SocketChannel.cs
- src/core/Akka/Util/ByteString.cs
> [api-doc][misc] fixed various typos

- RELEASE_NOTES.md
Release notes before we ship Akka.NET v1.0.4 (#1193).
Anything crucial I need to add before we release?
> added release notes for Akka.NET v1.0.4

- RELEASE_NOTES.md
Used for versioning nightly builds to distinguish them from latest stable.
> placeholder for next maintenance release

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/LookupRemoteActorMultiNetSpec.cs
> Implement LookupRemoteActorSpec

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteDeliverySpec.cs
> Remote Delivery Spec

- src/core/Akka.Persistence/Serialization/MessageSerializer.cs
...and appears to adhere to the practice of including an address with the serialized binary.
> Fixes the NullReferenceException in #1235 

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs
I found myself with bit of free time and thought about giving a try to #1258. There are 2 TODOs which I could use some help with.
I have not done C# in a long time, so please give it a good thorough look :-)
> add remote round robin spec #1258

- src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs
- src/core/Akka/Routing/ResizablePoolCell.cs
Should fix #1301 
If build server agrees then #1302 does should not be merged.
> Fix for Issue 1301

- src/core/Akka.Tests/Pattern/CircuitBreakerSpec.cs
- src/core/Akka/Pattern/CircuitBreaker.cs
- src/core/Akka/Pattern/CircuitBreakerState.cs
- src/core/Akka/Util/Internal/AtomicState.cs
> fix circuit breaker as per #1309

- src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs
> Ignore one test as per #1301

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteRandomSpec.cs
> Add remote random spec

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxy.cs
- src/examples/Cluster/Singleton/SingletonExample.Client/App.config
- src/examples/Cluster/Singleton/SingletonExample.Host/App.config
- src/examples/Cluster/Singleton/SingletonExample.Shared/WorkerManager.cs
I've managed to finish missing parts in ClusterSingletonProxy implementation an make it working with cluster singleton example projects.
> Cluster singleton proxy finished

- src/core/Akka.Tests/Actor/RelativeActorPathSpec.cs
- src/core/Akka/Actor/Address.cs
New PR with 1 commit. See issue for more details
> Fix for  #1332 Akka.Cluster.Routing.ClusterRouterGroupSettings Linux issue

- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.FSharp.Tests/InfrastructureTests.fs
- src/core/Akka.TestKit/TestActorRefBase.cs
- src/core/Akka.TestKit/TestProbe.cs
- src/core/Akka/Actor/ActorRef.cs
fix https://github.com/akkadotnet/akka.net/issues/1325
> implemented IComparable  genericless variant

- src/contrib/transports/Akka.Remote.AkkaIOTransport/AddressConverters.cs
- src/contrib/transports/Akka.Remote.AkkaIOTransport/AkkaIOTransport.cs
- src/contrib/transports/Akka.Remote.AkkaIOTransport/ConnectionAssociation.cs
- src/contrib/transports/Akka.Remote.AkkaIOTransport/TransportManager.cs
Fixes #1357: AkkaIOTransport broken
> Akka IO Transport: framing support

- src/core/Akka.Tests/Event/EventStreamSpec.cs
- src/core/Akka/Event/EventBusUnsubscriber.cs
- src/core/Akka/Event/EventStream.cs
> fix #1376 EventStreamUnsubscriber is created under user space

- src/core/Akka/Actor/PipeToSupport.cs
Reverts akkadotnet/akka.net#1381
> Revert "Add optional PipeTo completion handlers"

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/JournalDbEngine.cs
This PR fixes racing conditions caused by concurrent access to `JournalDbEngine.PendingOperations` list (see #1398). 
Instead of using list, we now have a single CancellationTokenSource per engine instance, that is shared by all tasks created by it. Once journal gets closed (by default when sql journal calls post stop), all pending tasks are cancelled from there.
> Fixed: data races inside sql journal engine

- src/contrib/loggers/Akka.Logger.Serilog/SerilogLogger.cs
> Makes Akka context props available to Serilog templates

- src/core/Akka.Tests/Dispatch/AsyncAwaitSpec.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/PipeToSupport.cs
- src/core/Akka/Dispatch/ActorTaskScheduler.cs
- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
Reverts akkadotnet/akka.net#1482
> Revert "Actor task scheduler refactoring"

- build.fsx
The retry feature mentioned in #838 was already implemented. 
closes #838
> Continue with the next nuget/symbol upload if one failed

- src/contrib/persistence/Akka.Persistence.Sqlite/README.md
- src/contrib/persistence/Akka.Persistence.Sqlite/sqlite.conf
> Fixed the sqlite.conf as well as the readme

- RELEASE_NOTES.md
**Maintenance release for Akka.NET v1.0.4**
This release is a collection of bug fixes, performance enhancements, and general improvements contributed by 29 individual contributors.
**Fixes & Changes - Akka.NET Core**
* [Bugfix: Make the Put on the SimpleDnsCache idempotent](https://github.com/akkadotnet/akka.net/commit/2ed1d574f76491707deac236db3fd7c1e5af5757)
* [Add CircuitBreaker Initial based on akka 2.0.5](https://github.com/akkadotnet/akka.net/commit/7e16834ef0ff8551cdd3530eacb1016d40cb1cb8)
* [Fix for receive timeout in async await actor](https://github.com/akkadotnet/akka.net/commit/6474bd7dc3d27756e255d12ef21f331108d9922d)
* [akka-io: fixed High CPU load using the Akka.IO TCP server](https://github.com/akkadotnet/akka.net/commit/4af2cfbcaafa33ea04a1a8b1aa6486e78bd6f821)
* …
> updated release notes for Akka.NET v1.0.5

- src/core/Akka/Routing/Broadcast.cs
- src/core/Akka/Routing/ConsistentHashRouter.cs
- src/core/Akka/Routing/Random.cs
- src/core/Akka/Routing/RoundRobin.cs
- src/core/Akka/Routing/Router.cs
- src/core/Akka/Routing/RouterConfig.cs
- src/core/Akka/Routing/ScatterGatherFirstCompleted.cs
- src/core/Akka/Routing/TailChoppingRoutingLogic.cs
This PR replaces boilerplate or expands upon documentation regarding
routers.
> [api-docs] Added missing router documentation

- src/core/Akka.Persistence/AtLeastOnceDelivery.cs
- src/core/Akka.Persistence/AtLeastOnceDeliveryReceiveActor.cs
> fixed the deliver comment

- src/core/Akka/Routing/ConsistentHashRouter.cs
- src/core/Akka/Routing/Listeners.cs
- src/core/Akka/Routing/RouterMsg.cs
- src/core/Akka/Routing/SmallestMailbox.cs
This PR adds more Akka.Routing documentation in the form of listeners,
routers and router messages.
> [api-docs] Added more routing documentation

- src/core/Akka.TestKit.Tests/TestActorRefTests/TestActorRefSpec.cs
- src/core/Akka.Tests/Actor/StashMailboxSpec.cs
- src/core/Akka/Actor/ActorCell.ReceiveTimeout.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/IActorContext.cs
Enabling some tests that previously have been set to Skip due to broken or not implemented code.
> Enabling bounded dequeue stash and receive timeout test

- src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs
Old line left over from 6551d44
> Removing old line. Don't know why it didn't pick up the removal

- src/core/Akka.Remote/RemoteActorRefProvider.cs
Fix for #1646
In the `RemoteDeadletterActorRef` there is some missing code to propagate deadletters to the base implementation:
```
.With<DeadLetter>(
deadLetter =>
{
// else ignore: it is a reliably delivered message that might be retried later, and it has not yet deserved
// the dead letter status
var deadSend = deadLetter.Message as EndpointManager.Send;
if (deadSend != null && deadSend.Seq == null)
{
base.TellInternal(deadSend.Message, deadSend.SenderOption ?? ActorRefs.NoSender);
}
//##############
// the issue here was that the With<DeadLetter> consumed _all_ dead letters, 
// when this clause was just intended to consume those containing EndpointManager.Send
})
```
> Remote ActorRef Provider Fix for #1646

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
> Add the default cluster singleton config as a top-level fallback.

- src/contrib/dependencyInjection/Akka.DI.Ninject/Readme.md
just fixed typo Akka.DI.Ninject project README.md
> fix typo Akka.DI.Ninject README

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
This solves the snapshotting issues with #1663
> Take snapshots when configured

- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
This solves the serialization issues with #1663
> Change ShardState to a class

- src/contrib/dependencyInjection/Akka.DI.Core/DIActorContextAdapter.cs
- src/contrib/dependencyInjection/Akka.DI.Core/DIActorProducer.cs
- src/contrib/dependencyInjection/Akka.DI.Core/DIActorSystemAdapter.cs
- src/contrib/dependencyInjection/Akka.DI.Core/DIExt.cs
- src/contrib/dependencyInjection/Akka.DI.Core/DIExtension.cs
- src/contrib/dependencyInjection/Akka.DI.Core/Extensions.cs
- src/contrib/dependencyInjection/Akka.DI.StructureMap/StructureMapDependencyResolver.cs
- src/contrib/dependencyInjection/Akka.DI.Unity/UnityDependencyResolver.cs
- src/core/Akka/Actor/Extensions.cs
This PR fixes missing or boilerplate documentation related to dependency
injection.
> [api-docs] Added more DI documentation

- src/core/Akka.API.Tests/App_Packages/ApiApprover.3.0.1/PublicApiGenerator.cs
Fixed localization issue which causes problems when building on a system
with non US locale. Fixes issue #1723
> Manually patch for ApiApprover

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteGatePiercingSpec.cs
> Added RemoteGatePiercingSpec

- src/core/Akka.Tests/Actor/ActorSelectionSpec.cs
> ActorSelectionSpec: added ActorSelection_must_send_ActorSelection_targeted_to_missing_actor_to_DeadLetters

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeShutdownAndComesBackSpec.cs
> Added RemoteNodeShutdownAndComesBackSpec

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeDeathWatchSpec.cs
> Added RemoteNodeDeathWatchSpec

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
Fixed global ActorContext in SqlJournal
#1750
> Fixed global ActorContext in SqlJournal

- src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs
> Fixes initialization of LocalSnapshotStore directory

- src/core/Akka.Streams.TestKit.Tests/Utils.cs
- src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
Fixes a number of issues with materialization and subscription
> Work to get TestPublisherSubscriberSpec to pass

- src/core/Akka.Streams.TestKit.Tests/Utils.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs
- src/core/Akka.Streams/Implementation/Fusing/Fusing.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
It temporarily includes commits from https://github.com/akkadotnet/akka.net/pull/1775.
> [WIP] Work to make StreamTestKitSpec pass

- src/core/Akka.Streams/Attributes.cs
- src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphAssembly.cs
- src/core/Akka.Streams/Stage/AbstractStage.cs
- src/core/Akka.Streams/Stage/Context.cs
- src/core/Akka.Streams/Stage/GraphStage.cs
- src/core/Akka.Streams/Stage/Stage.cs
Changes:
- `Attributes` and `ActorAttributes` have human-friendly ToString() methods. Improved readability and debugging experience.
- Implemented empty method bodies in `PushPullGraphLogic`.
- Modified `PushPullGraphLogic` to work on `AbstractStage<TIn, TOut, ISyncDirective, ISyncDirective, IContext<TOut>, ILifecycleContext>` instead of `AbstractStage<TIn, TOut, IDirective, IDirective, IContext<TOut>, ILifecycleContext>` - due to C# generic constraint rules previous cast inside `CreateLogicAndMaterializedValue` method was throwing an error. This may need further investigation.
/cc @Silv3rcircl3 @cconstantin
> Implemented PushPullGraphLogic

- src/core/Akka/Configuration/Pigeon.conf
The timeout was set to 5 milliseconds but should be 5 seconds
> Fixed within timeout for routers in default configuration

- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpecKit.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/InterpreterSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/EnumeratorInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphAssembly.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
- src/core/Akka.Streams/Shape.cs
- src/core/Akka.Streams/Stage/AbstractStage.cs
- src/core/Akka.Streams/Stage/GraphStage.cs
It also includes updates to GraphInterpreter and GraphAssembly to be in line with akka jvm 2.4.2
> Port GraphInterpreterSpecKit and part of InterpreterSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Configuration/Config.cs
Make HOCON config ToString() method more readable
added enhancement #1703 
@Silv3rcircl3 
Made a new pull request as per conversation on pull #1785
> #1703 ToString overloaded to make HOCON config ToString more readable by including fallback

- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClient.cs
ClusterClient messages should be the same as in ClusterReceptionist
> ClusterClient messages namespace fix

- src/core/Akka.Streams.Tests/Implementation/StreamLayoutSpec.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
> StreamLayoutSpec

- src/core/Akka.Streams.Tests/Implementation/StreamLayoutSpec.cs
- src/core/Akka.Streams/ActorMaterializer.cs
- src/core/Akka.Streams/Implementation/Fusing/Fusing.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
- src/core/Akka.Streams/Stage/GraphStage.cs
This PR contains remaining parts of `StreamLayoutSpec` - all are passing now.
/cc @cconstantin @Silv3rcircl3
> StreamLayoutSpec - ported remaining tests

- src/core/Akka.Streams.TestKit.Tests/ScriptedTest.cs
- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpecKit.cs
- src/core/Akka.Streams/CodeGen/Dsl/ZipWith.cs
- src/core/Akka.Streams/CodeGen/Dsl/ZipWith.tt
- src/core/Akka.Streams/CodeGen/FanInShape.cs
- src/core/Akka.Streams/CodeGen/FanInShape.tt
- src/core/Akka.Streams/Dsl/FlowOperations.cs
- src/core/Akka.Streams/Dsl/Graph.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/FanInShape.cs
- src/core/Akka.Streams/FanOutShape.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
- src/core/Akka.Streams/Stage/AbstractStage.cs
- src/core/Akka.Streams/Stage/Context.cs
- src/core/Akka.Streams/Stage/GraphStage.cs
- src/core/Akka.Streams/Stage/Stage.cs
All but one tests pass, will investigate the failing test tomorrow
> Port GraphInterpreterSpec

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteScatterGatherSpec.cs
> Added RemoteScatterGatherSpec

- CONTRIBUTING.md
@Silv3rcircl3 I think some information on branch deletion after pull request merge and close would be useful in the Contributing.md document. I have added it. Please advise if its required or I need to improve it.Thanks.
> added branch deletion documentation to Contributing.md

- src/core/Akka.Streams.TestKit.Tests/Akka.Streams.TestKit.Tests.csproj
- src/core/Akka.Streams.TestKit.Tests/AkkaSpec.cs
- src/core/Akka.Streams.TestKit.Tests/StreamTestKitSpec.cs
- src/core/Akka.Streams.TestKit.Tests/TestException.cs
- src/core/Akka.Streams.TestKit.Tests/Utils.cs
- src/core/Akka.Streams.TestKit/TestSubscriber.cs
- src/core/Akka.Streams.Tests/Actor/ActorPublisherSpec.cs
- src/core/Akka.Streams.Tests/ActorMaterializerSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/ActorGraphInterpreterSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterFailureModesSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterPortsSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpecKit.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/InterpreterSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/InterpreterSupervisionSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/KeepGoingStageSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/LifecycleInterpreterSpec.cs
- src/core/Akka.Streams.Tests/Implementation/TimeoutsSpec.cs
- src/core/Akka.Streams/ActorMaterializer.cs
- src/core/Akka.Streams/Actors/ActorPublisher.cs
- src/core/Akka.Streams/Dsl/Sink.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ActorMaterializerImpl.cs
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Stages/Stages.cs
- src/core/Akka.Streams/Implementation/StreamLayout.cs
- src/core/Akka.Streams/Shape.cs
* StreamTestKitSpec
* ActorPublisherSpec (all but one passing)
> A few more bug fixes and a lot more tests passing

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorRefProvider.cs
- src/core/Akka/Akka.csproj
- src/core/Akka/Dispatch/Mailboxes.cs
- src/core/Akka/Util/Reflection/TypeCache.cs
- Cached the default mailbox type
- Removed an unused GetMailboxType in ActorRefProvider
> Default MailboxType optimization

- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/RestartNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/UnreachableNodeJoinsAgainSpec.cs
- src/core/Akka.MultiNodeTestRunner/Program.cs
- src/core/Akka.Remote.TestKit/BarrierCoordinator.cs
- src/core/Akka.Remote.TestKit/Internals/Reference.conf
- src/core/Akka.Remote.TestKit/Player.cs
close #1821 - Akka.Cluster.Tests.MultiNode.RestartNodeSpec added and passes
close #1830 - Akka.Cluster.Tests.MultiNode.UnreachableNodeJoinsAgainSpec added and passes
> Akka.Cluster MultiNode specs for node restarts, downing, and rejoining

- build.cmd
- build.sh
- src/Akka.sln
- src/SharedAssemblyInfo.cs
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Remote.Tests.Performance/packages.config
- src/core/Akka.Tests.Performance/Actor/ActorSystemShutdownSpec.cs
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/packages.config
Designed to time how long it takes to shutdown various-sized `ActorSystem`s - going to use this to benchmark the results of #1792
> upgraded to NBench v0.2.1 - added ActorSystemShutdownSpec

- src/core/Akka.Tests/Actor/ActorBecomeTests.cs
Extra testcase for issue: https://github.com/akkadotnet/akka.net/issues/1849
> Added testcase for Become in Become scenario

- src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs
- src/core/Akka.Persistence/Eventsourced.cs
- src/core/Akka.Remote/Transport/TestTransport.cs
- src/core/Akka/Actor/Exceptions.cs
- src/core/Akka/Actor/Inbox.cs
This PR fixes some incorrect xmldoc tags.
> [api-docs] fixed incorrect xmldoc tags

- src/core/Akka.Cluster.TestKit/Properties/AssemblyInfo.cs
- src/core/Akka.Cluster.Tests.MultiNode/RestartNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/UnreachableNodeJoinsAgainSpec.cs
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
- src/core/Akka.Persistence.Tests/Journal/MemoryEventAdaptersSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteGatePiercingSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeDeathWatchSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeRestartDeathWatchSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeShutdownAndComesBackSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteScatterGatherSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/TestConductor/TestConductorSpec.cs
- src/core/Akka.Remote.Tests/RemoteMetricsSpec.cs
- src/core/Akka.Remote/RemoteMetricsExtension.cs
- src/core/Akka.Tests/Event/LoggerMailboxSpec.cs
- src/core/Akka/Util/Reflection/TypeCache.cs
- src/examples/Cluster/ClusterSharding/ClusterSharding.Node/Customers.cs
This PR fixes incorrect or missing copyright headers on newly
added/edited files.
> [misc] fixed copyright headers

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs
ClusterSingletonManager 
- RemovalMargin
- min-number-of-hand-over-retries
settings updated
> ClusterSingletonManager - settings update

- src/core/Akka.Tests/Actor/HotSwapSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
Ported more specs from the JVM to verify https://github.com/akkadotnet/akka.net/issues/1849
> Added HotSwapSpecs

- src/core/Akka.Streams/Attributes.cs
- src/core/Akka.Streams/Dsl/Sink.cs
- src/core/Akka.Streams/Implementation/Fusing/Fusing.cs
> Fixed FusingSpec

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteRestartedQuarantinedSpec.cs
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/RemotingLifecycleEvent.cs
> Added RemoteRestartedQuarantinedSpec

- build.fsx
- src/System.Reactive.Streams/Properties/AssemblyInfo.cs
- src/System.Reactive.Streams/System.Reactive.Streams.csproj
- src/System.Reactive.Streams/System.Reactive.Streams.nuspec
- src/core/Akka.Persistence.Query/Akka.Persistence.Query.csproj
- src/core/Akka.Persistence.Query/Akka.Persistence.Query.nuspec
- src/core/Akka.Persistence.Query/Properties/AssemblyInfo.cs
- src/core/Akka.Streams/Akka.Streams.csproj
- src/core/Akka.Streams/Akka.Streams.nuspec
- src/core/Akka.Streams/Properties/AssemblyInfo.cs
Temporarily includes System.Reactive.Streams
> Updates build to package Akka.Streams, Akka.Persistence.Query

- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
```hocon
debug {
verbose-heartbeat-logging = off
}
```
> Added heartbeat verbose mode

- src/core/Akka.Persistence/Akka.Persistence.csproj
- src/core/Akka.Persistence/Journal/Tagged.cs
This PR adds `Tagged` class used for tagged persistent queries.
> Added Tagged class for persistent journals

- src/contrib/serializers/Akka.Serialization.Wire/WireSerializer.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster/ClusterActorRefProvider.cs
- src/core/Akka/Actor/Deploy.cs
- src/core/Akka/Actor/LocalScope.cs
- src/core/Akka/Actor/Props.cs
- src/core/Akka/Actor/RemoteScope.cs
- src/core/Akka/Actor/Scope.cs
- src/core/Akka/Configuration/Config.cs
- src/core/Akka/Configuration/Hocon/HoconObject.cs
- src/core/Akka/Configuration/Hocon/HoconParser.cs
- src/core/Akka/Configuration/Hocon/HoconToken.cs
- src/core/Akka/Configuration/Hocon/HoconValue.cs
This PR contains misc api-doc updates.
> [api-docs] misc updates

- src/benchmark/RemoteBenchmark/Program.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj
- src/core/Akka.Remote.Tests/Transport/TransportSpec.cs
- src/core/Akka.Remote.Tests/Transport/TransportSpecBase.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Transport/Streaming/AsyncQueue.cs
- src/core/Akka.Remote/Transport/Streaming/NamedPipeTransport.cs
- src/core/Akka.Remote/Transport/Streaming/NetworkStreamTransport.cs
- src/core/Akka.Remote/Transport/Streaming/SslStreamTransport.cs
- src/core/Akka.Remote/Transport/Streaming/StreamAssociationHandle.cs
- src/core/Akka.Remote/Transport/Streaming/StreamTransport.cs
- src/core/Akka/Util/Internal/TaskExtensions.cs
This PR contains the TestKit for StreamTransport.
> StreamTransport TestKit + misc fixes

- build.cmd
- src/Akka.sln
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Remote.Tests.Performance/packages.config
- src/core/Akka.Streams.TestKit.Tests/BaseTwoStreamsSetup.cs
- src/core/Akka.Streams.TestKit.Tests/StreamTestDefaultMailbox.cs
- src/core/Akka.Streams.TestKit.Tests/StreamTestKitSpec.cs
- src/core/Akka.Streams.TestKit.Tests/TestPublisherSubscriberSpec.cs
- src/core/Akka.Streams.TestKit.Tests/TwoStreamsSetup.cs
- src/core/Akka.Streams.TestKit/TestUtils.cs
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/FlowSelectBenchmark.cs
- src/core/Akka.Streams.Tests.Performance/GraphBuilderBenchmark .cs
- src/core/Akka.Streams.Tests.Performance/IO/FileSourcesBenchmark .cs
- src/core/Akka.Streams.Tests.Performance/InterpreterBenchmark.cs
- src/core/Akka.Streams.Tests.Performance/MaterializationBenchmark.cs
- src/core/Akka.Streams.Tests.Performance/MergeManyBenchmark.cs
- src/core/Akka.Streams.Tests.Performance/Properties/AssemblyInfo.cs
- src/core/Akka.Streams.Tests.Performance/packages.config
- src/core/Akka.Streams.Tests/IO/InputStreamSourceSpec.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphStages.cs
- src/core/Akka.Streams/Implementation/IO/InputStreamPublisher.cs
- src/core/Akka.Streams/Implementation/IO/InputStreamSinkStage.cs
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/packages.config
Note: I also updated NBench to the latest version.
> Ported stream benchmarks

- src/core/Akka.Remote/Transport/Transport.cs
- src/core/Akka.Remote/Transport/TransportAdapters.cs
Intended to fix #1554 and #1696
> Added missing INoSerializationVerification markers in Akka.Remote

- src/core/Akka/Actor/ActorCell.cs
DeadLetter with a Message property marked with INoSerializationVerificationNeeded should be excluded from serialization verification
> Fix serialization verification for DeadLetters

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxySettings.cs
Cluster Tools and Sharding doesn't have any default configuration. So, I've added it and have written unit tests for default configuration
> Added default config fallback to cluster tools

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote/Transport/Streaming/NetworkStreamTransport.cs
- src/core/Akka.Remote/Transport/Streaming/StreamAssociationHandle.cs
- src/core/Akka.Remote/Transport/Streaming/StreamTransport.cs
- src/core/Akka/Util/Internal/TaskExtensions.cs
Fixed error handling for outbound connections + proper socket cleanup in case of Socket.Accept errors.
> NetworkStreamTransport - Fixed error handling for outbound connections

- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Cluster.Tests/StartupWithOneThreadSpec.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
> adds proper lazy initialization to avoid cluster startup deadlock

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/RestartFirstSeedNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/packages.config
Issue: https://github.com/akkadotnet/akka.net/issues/1996
> Implemented RestartFirstSeedNodeSpec

- src/Akka.sln
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Properties/AssemblyInfo.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerChaosSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeaveSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerStartupSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/packages.config
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools/Properties/AssemblyInfo.cs
I've created Akka.Cluster.Tools.Tests.MultiNode and moved all MNTK tests there.
Fixed: https://github.com/akkadotnet/akka.net/issues/1573
I'm planning to fix another ClusterTools MNTK specs soon
> Implemented ClusterSingletonManagerStartupSpec

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerChaos2Spec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/1575
I could not run these two specs inside one MultiNodeSpec class. Remote TestKit has some problems with the state of cluster between different tests
> fixed ClusterSingletonManagerChaosSpec

- src/core/Akka.Cluster.Tests/ClusterSpec.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
close #1946
Note: does not call leave on ActorSystem shutdown - merely terminates the underlying clustering system. The end user should still shut down the cluster using the following sequence of commands:
`Cluster.RegisterOnMemberRemoved(myActorSystem.Terminate())` --> `Cluster.Leave`
> added cluster termination hooks and added RegisterOnMemberRemoved

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/DisallowJoinOfTwoClustersSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/1995
> Implemented DisallowJoinOfTwoClusterSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/NodeMembershipSpec.cs
- src/core/Akka/Properties/AssemblyInfo.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2020
Fixed AssertMembers method in MultiNodeClusterSpec
> Implemented NodeMembershipSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/MinMembersBeforeUpSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2001
> Implemented MinMembersBeforeUpSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/LeaderElectionSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/MinMembersBeforeUpSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/NodeMembershipSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/RestartFirstSeedNodeSpec.cs
https://github.com/akkadotnet/akka.net/issues/2005
> Implemented LeaderElectionSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/NodeUpSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2019
> Implemented NodeUpSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/SplitBrainSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2017
> Implemented SplitBrainSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Persistence/Serialization/SnapshotSerializer.cs
- src/core/Akka.Remote/MessageSerializer.cs
- src/core/Akka.Remote/Serialization/MessageContainerSerializer.cs
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/EmptyLocalActorRef.cs
Ported the code from this PR https://github.com/akkadotnet/akka.net/pull/2032
Enabled SerializerWithStringManifest in Akka-Actor and Akka.Remote
Implemented SerializeAllCreators
Also have added Obsoleted to IInternalActorRef.IsTerminated and made small code formatting
> Implemented SerializeAllCreators and SerializerWithStringManifest

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerChaos2Spec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeaveSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerStartupSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxy.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/Serialization/ClusterSingletonMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/reference.conf
Ported ClusterSingleton code from here https://github.com/akkadotnet/akka.net/pull/2032
This version was aligned with Akka 2.4.7
Two ClusterManager MNTK specs still have racy conditions, so I've commented them, and wait for cluster stabilization.
> Enabled ClusterSingleton specs

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/SingletonClusterSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2018
> Implemented SingletonClusterSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/DeployerSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka.Tests/Configuration/HoconTests.cs
- src/core/Akka.Tests/Util/Internal/ExtensionsTests.cs
- src/core/Akka/Actor/Deployer.cs
- src/core/Akka/Configuration/Config.cs
- src/core/Akka/Util/Internal/Extensions.cs
> Added support for akka.actor.deployment with actorPaths/wildcards w/ dots

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMediatorRouterSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSub.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/TopicMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/reference.conf
Ported DistributedPubSub code from here https://github.com/akkadotnet/akka.net/pull/2032
This version was aligned with Akka 2.4.1
Also, I've created two stories related with DistributedPubSub
- DistributedPubSub: race condition regarding children/topic actor liveness (https://github.com/akkadotnet/akka.net/issues/2055)
- DistributedPubSub: put messages without route into the dead letters (https://github.com/akkadotnet/akka.net/issues/2056)
> Enabled all DistributedPubSub specs

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/SunnyWeatherSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2016
> Implemented SunnyWeatherSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/NodeDowningAndBeingRemovedSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2009
> Implemented NodeDowningAndBeingRemovedSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/NodeLeavingAndExitingAndBeingRemovedSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2010
> Implemented NodeLeavingAndExitingAndBeingRemovedSpec

- src/core/Akka.Cluster.Tests.MultiNode/ConvergenceSpec.cs
- src/core/Akka.Cluster.Tests/ClusterDomainEventPublisherSpec.cs
- src/core/Akka.Cluster.Tests/ClusterDomainEventSpec.cs
- src/core/Akka.Cluster/ClusterEvent.cs
https://github.com/akka/akka/issues/18575
> Cluster: Implemented MemberJoined and MemberLeft events

- src/core/Akka.Cluster.Tests.MultiNode/ClusterAccrualFailureDetectorSpec.cs
Needed to combine all of the three spec methods into one `MultiNodeFact`
> fixed ClusterAccrualFailureDetector MNTR spec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/LeaderDowningNodeThatIsUnreachableSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2004
> Implemented LeaderDowningNodeThatIsUnreachableSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/RestartNode2Spec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/1990
> Implemented RestartNode2Spec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/NodeLeavingAndExitingSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2011
> Implemented NodeLeavingAndExitingSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/MembershipChangeListenerExitingSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2006
> Implemented MembershipChangeListenerExitingSpec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/RestartNode3Spec.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
Fixed https://github.com/akkadotnet/akka.net/issues/1991
Implemented this PR https://github.com/akka/akka/issues/19274
> Implemented RestartNode3Spec

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/MembershipChangeListenerUpSpec.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2007
> Implemented MembershipChangeListenerUpMultiNode

- src/core/Akka.Streams.Tests/Dsl/FlowIntersperseSpec.cs
> Fix racy spec for flow interleave

- src/core/Akka.Persistence.FSharp/FsApi.fs
- src/core/Akka.Persistence/PersistentView.cs
Done. 
Ready for review.
Unit tests are passing.
> #1606 - It should be possible to check if a PersistentView is in a recovery mode

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/AttemptSysMsgRedeliverySpec.cs
The same spec as https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote.Tests.MultiNode/AttemptSysMsgRedeliverySpec.cs but for Cluster
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/AttemptSysMsgRedeliverySpec.scala
> Implemented AttemptSysMsgRedeliverySpec

- src/core/Akka.Cluster.Tests.MultiNode/Routing/ClusterConsistentHashingRouterSpec.cs
- src/core/Akka.Cluster.Tests/ClusterDeployerSpec.cs
- src/core/Akka.Cluster/ClusterActorRefProvider.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs
Implemented https://github.com/akka/akka/issues/13802
> Implemented max-total-nr-of-instances

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerChaos2Spec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerChaosSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeaveSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerStartupSpec.cs
Cluster Singleton is currently passes all Multi Node Specs
> Stable Cluster Singleton

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/QuickRestartSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs
- src/core/Akka.Remote.Tests.MultiNode/RemoteNodeRestartDeathWatchSpec.cs
- src/core/Akka.Remote.Tests/ActorsLeakSpec.cs
- src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj
- src/core/Akka.Remote.Tests/RemoteDeathWatchSpec.cs
- src/core/Akka.Remote.Tests/RemotingSpec.cs
- src/core/Akka.Remote.Tests/packages.config
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/EndpointRegistry.cs
- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka.Remote/RemoteSystemDaemon.cs
- src/core/Akka.Remote/RemoteWatcher.cs
- src/core/Akka.TestKit/TestKitBase_Expect.cs
- src/core/Akka.Tests/Actor/ActorLookupSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Actor/ActorCell.Children.cs
- src/core/Akka/Actor/ActorCell.DeathWatch.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/ActorPath.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Cell.cs
- src/core/Akka/Actor/ExtendedActorSystem.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Actor/RepointableActorRef.cs
added ActorsLeakSpec
resolved two EndpointManager bugs that would have prevented reconnects
> ported QuickRestartSpec; fixed EndpointManager errors

- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.MultiNode/RemoteQuarantinePiercingSpec.cs
- src/core/Akka.Remote.Tests.MultiNode/packages.config
Fixed https://github.com/akkadotnet/akka.net/issues/1254
> Implemented RemoteQuarantinePiercingSpec

- src/core/Akka.Remote.Tests/EndpointRegistrySpec.cs
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/EndpointRegistry.cs
Implements https://github.com/akka/akka/pull/20594
> Gating should not overrwite quarantine

- src/core/Akka/Event/ActorEventBus.cs
- src/core/Akka/Event/AddressTerminatedTopic.cs
- src/core/Akka/Event/BusLogging.cs
- src/core/Akka/Event/DeadLetter.cs
- src/core/Akka/Event/DeadLetterListener.cs
- src/core/Akka/Event/Debug.cs
- src/core/Akka/Event/DefaultLogMessageFormatter.cs
- src/core/Akka/Event/Error.cs
- src/core/Akka/Event/EventBus.cs
- src/core/Akka/Event/EventStream.cs
- src/core/Akka/Event/ILogMessageFormatter.cs
- src/core/Akka/Event/ILoggingAdapter.cs
- src/core/Akka/Event/Info.cs
- src/core/Akka/Event/InitializeLogger.cs
- src/core/Akka/Event/LogEvent.cs
- src/core/Akka/Event/LoggerInitialized.cs
- src/core/Akka/Event/Logging.cs
- src/core/Akka/Event/LoggingAdapterBase.cs
- src/core/Akka/Event/LoggingBus.cs
- src/core/Akka/Event/StandardOutLogger.cs
- src/core/Akka/Event/TraceLogger.cs
- src/core/Akka/Event/UnhandledMessage.cs
- src/core/Akka/Event/Warning.cs
- src/core/Akka/Util/StandardOutWriter.cs
This PR fixes missing or boilerplate documentation related to Akka.Event
> [api-docs] added more Akka.Event documentation

- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs
- src/core/Akka.Persistence/Eventsourced.cs
- src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
- src/core/Akka.Persistence/Journal/AsyncRecovery.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/PersistentActor.cs
- src/core/Akka.Persistence/PersistentView.Recovery.cs
- src/core/Akka.Persistence/Snapshot/NoSnapshotStore.cs
- src/core/Akka/Actor/ActorRefProvider.cs
- src/core/Akka/Actor/IUntypedActorContext.cs
- src/core/Akka/Actor/UntypedActor.cs
- src/core/Akka/Dispatch/Mailboxes.cs
- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
- src/core/Akka/Routing/RoundRobin.cs
- src/core/Akka/Routing/SmallestMailbox.cs
- src/core/Akka/Util/Index.cs
This PR fixes several x-references that Sandcastle was having trouble
resolving (namely inherited methods) and a few tag errors as well.
> [api-docs] Fixes several x-reference errors

- src/core/Akka.API.Tests/Akka.API.Tests.csproj
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.cs
These packages is going to be stable in the near future, so we need to check api changes in PRs
> Added API approval tests for Remote/Cluster/Persistence/Cluster.Tools

- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/DeterministicOldestWhenJoiningSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterEvent.cs
- src/core/Akka.Cluster/Member.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2082
Should go after these two: https://github.com/akkadotnet/akka.net/pull/2098 and https://github.com/akkadotnet/akka.net/pull/2099
> Implemented DeterministicOldestWhenJoiningSpec

- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/Transport/Helios/HeliosTransport.cs
Just some logging cleanup before we push 1.1
> disabled Helios STDOUT logging; eliminated ERROR logs for shutdown associations

- src/contrib/persistence/Akka.Persistence.Query.Sql/Akka.Persistence.Query.Sql.csproj
- src/contrib/persistence/Akka.Persistence.Query.Sql/packages.config
- src/contrib/persistence/Akka.Persistence.Sql.TestKit/Akka.Persistence.Sql.TestKit.csproj
- src/contrib/persistence/Akka.Persistence.Sql.TestKit/packages.config
- src/core/Akka.Persistence.Query.Tests/Akka.Persistence.Query.Tests.csproj
- src/core/Akka.Persistence.Query.Tests/packages.config
- src/core/Akka.Persistence.Query/Akka.Persistence.Query.csproj
- src/core/Akka.Persistence.Query/packages.config
- src/core/Akka.Streams.TestKit.Tests/Akka.Streams.TestKit.Tests.csproj
- src/core/Akka.Streams.TestKit.Tests/packages.config
- src/core/Akka.Streams.TestKit/Akka.Streams.TestKit.csproj
- src/core/Akka.Streams.TestKit/packages.config
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/packages.config
- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams.Tests/packages.config
- src/core/Akka.Streams/Akka.Streams.csproj
- src/core/Akka.Streams/packages.config
- src/examples/Streams/StreamsExamples/StreamsExamples.csproj
- src/examples/Streams/StreamsExamples/packages.config
Changed Reactive.Streams package to 1.0.0-RC1
Removed all redundant NetCore dependencies
> Fixed Akka.Streams dependencies

- src/SharedAssemblyInfo.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/Properties/AssemblyInfo.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sql.TestKit/DefaultConfigSpec.cs
- src/contrib/persistence/Akka.Persistence.Sql.TestKit/Properties/AssemblyInfo.cs
- src/core/Akka.Cluster.Tests.MultiNode/JoinWithOfflineSeedNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/LeaderDowningAllOtherNodesSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/QuickRestartSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/Routing/UseRoleIgnoredSpec.cs
- src/core/Akka.Cluster/Proto/Msg/ClusterMessages.cs
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
- src/core/Akka.Remote.Tests/ActorsLeakSpec.cs
- src/core/Akka.Remote.Tests/RemoteDeathWatchSpec.cs
- src/core/Akka.Tests.Performance/Dispatch/CallingThreadExecutor.cs
- src/core/Akka.Tests.Performance/Dispatch/MailboxBenchmarks.cs
- src/core/Akka.Tests.Performance/Dispatch/MessageDispatchAndReceiveBenchmark.cs
- src/core/Akka.Tests.Performance/Dispatch/ReceiveOnlyBenchmark.cs
- src/core/Akka.Tests/Actor/ActorLookupSpec.cs
- src/core/Akka.Tests/Actor/Dispatch/ActorModelSpec.cs
- src/core/Akka.Tests/Dispatch/SysMsg/SystemMessageListSpec.cs
- src/core/Akka.Tests/Util/IndexSpec.cs
- src/core/Akka.Tests/Util/Internal/ExtensionsTests.cs
- src/core/Akka/Dispatch/Dispatcher.cs
- src/core/Akka/Dispatch/ExecutorService.cs
- src/core/Akka/Dispatch/IRunnable.cs
- src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs
- src/core/Akka/Util/FastLazy.cs
- src/core/Akka/Util/Index.cs
- src/core/Akka/Util/Result.cs
- tools/AddCopyrightHeaderToSourceFiles.ps1
Also removed some unused `using` statements.
> fixed lightbend url

- src/core/Akka.Remote.Tests/RemoteMessageLocalDeliverySpec.cs
- src/core/Akka.Tests/Actor/ActorPathSpec.cs
- src/core/Akka/Actor/ActorPath.cs
Pretty nasty bug - not sure how it occurs in the wild exactly but I observed it happening inside Lighthouse. Have more tests to cover it and a small fix.
> close #2151 - fixes NRE on ActorPath.ElementsWithUid

- src/core/Akka.Tests/Actor/PatternSpec.cs
- src/core/Akka/Actor/GracefulStopSupport.cs
> Remove an unnecessary DeadLetter at GracefulStop. #2157

- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMediatorRouterSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2056
> Put messages without route into the dead letters

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2149
> Remove distributed pubsub nodes on leave

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/PublishSubscribe/DistributedPubSubRestartSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/TopicMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/Proto/DistributedPubSubMessages.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt
- src/core/protobuf/DistributedPubSubMessages.proto
Fixed https://github.com/akkadotnet/akka.net/issues/2140
> DistributedPubSub may gossip with old cluster

- src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj
- src/core/Akka.TestKit.Tests/TestKitBaseTests/WithinTests.cs
- src/core/Akka.TestKit/TestKitBase_Within.cs
> Added epsilon value to the Within assertion.

- src/core/Akka.Tests/Actor/RepointableActorRefSpecs.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Actor/RepointableActorRef.cs
Props to @kantora for finding, reporting, and providing an initial fix for this issue.
> changed data structure in UnstartedCell to avoid multiple enumeration

- src/contrib/dependencyInjection/Akka.DI.TestKit/DiResolverSpec.cs
> close #2188 - perform correct check on DI types now

- src/core/Akka.Tests/Configuration/HoconTests.cs
Added tests for #2187 for clarity so we dont get confused over why things are the way they are
> Added ip tests for clarity

- src/contrib/serializers/Akka.Serialization.TestKit/AkkaSerializationSpec.cs
This PR adds some new serializer tests to allow us to pin down potential future issues.
They were used to fix the latest Wire compatibility problems
> More serializer tests

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote.Tests/RemotingSpec.cs
- src/core/Akka.Remote/RemoteSystemDaemon.cs
- src/core/Akka.Tests/Actor/ActorSelectionSpec.cs
- src/core/Akka/Actor/ActorSelection.cs
> Update ActorSelection and specs

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.FSharp.Tests/ApiTests.fs
- src/core/Akka.Persistence/InternalExtensions.cs
- src/core/Akka.TestKit/Internal/InternalTestActorRef.cs
- src/core/Akka.Tests.Performance/Dispatch/MailboxBenchmarks.cs
- src/core/Akka.Tests.Performance/Dispatch/ReceiveOnlyBenchmark.cs
- src/core/Akka.Tests/Actor/DeathWatchSpec.cs
- src/core/Akka.Tests/Event/LoggerMailboxSpec.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/DeadLetterMailbox.cs
- src/core/Akka/Actor/Message.cs
- src/core/Akka/Actor/RepointableActorRef.cs
- src/core/Akka/Actor/Stash/Internal/AbstractStash.cs
- src/core/Akka/Routing/ResizablePoolCell.cs
- src/core/Akka/Routing/RoutedActorCell.cs
- src/core/Akka/Util/TypeExtensions.cs
I've also removed all getters in the properties
> Check for empty message in Envelope class

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote.TestKit/Controller.cs
- src/core/Akka.Remote/Transport/Transport.cs
- src/core/Akka.Remote/Transport/TransportAdapters.cs
- src/core/Akka.Tests/Actor/DeadLetterSupressionSpec.cs
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Actor/EmptyLocalActorRef.cs
- src/core/Akka/Actor/IAutoReceivedMessage.cs
- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
- src/core/Akka/Event/DeadLetter.cs
- src/core/Akka/Pattern/BackoffSupervisor.cs
Implemented DeadLetterSupression
http://doc.akka.io/docs/akka/2.4.3/scala/event-bus.html#Dead_Letters
> Implemented DeadLetterSupression

- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs
While working on a persistent driver for Oracle, I found the need to override some of the methods in the Snapshot/QueryExecutor class. This change is consistent with what the Journal/QueryExecutor already does.
> Replaces fields and methods signatures to allow overriding the Snapshot/QueryExecutor class

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/DeathWatchSpec.cs
- src/core/Akka/Actor/ActorCell.FaultHandling.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
- added an abstract IDecider property to an abstract SupervisorStrategy class
- added "child" parameter to ProcessFailure method
> Align SupervisorStrategy with scala version

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Fixed the error in DistributedPubSubMediator.HandlePrune (https://github.com/akkadotnet/akka.net/issues/2221)
> Fixed #2221 (DistributedPubSubMediator - an error in HandlePrune)

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Sorry, I've replaced one bug with another. This should help.
> DistributedPubSubMediator - an error in HandlePrune, Fix of fix in #2222 (removed multiple enumeration)

- src/contrib/cluster/Akka.Cluster.Tools/Akka.Cluster.Tools.csproj
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/TopicMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/Topics.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/PerGroupingBuffer.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2055
@jordansjones could you help me to debug this change? I missed somethings and specs are failing
You can find an original scala code in the linked issue
> DistributedPubSub: Fixed race-condition issue when handling Topic/Group actors

- src/contrib/serializers/Akka.Serialization.Wire/Akka.Serialization.Wire.csproj
- src/contrib/serializers/Akka.Serialization.Wire/packages.config
- src/contrib/serializers/Akka.Serialization.WireTests/Akka.Serialization.WireTests.csproj
- src/contrib/serializers/Akka.Serialization.WireTests/WireTests.cs
- src/contrib/serializers/Akka.Serialization.WireTests/packages.config
- src/examples/Cluster/ClusterSharding/ClusterSharding.Node/ClusterSharding.Node.csproj
- src/examples/Cluster/ClusterSharding/ClusterSharding.Node/packages.config
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/ClusterToolsExample.Node.csproj
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Node/packages.config
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/ClusterToolsExample.Seed.csproj
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Seed/packages.config
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/ClusterToolsExample.Shared.csproj
- src/examples/Cluster/ClusterTools/ClusterToolsExample.Shared/packages.config
fixed https://github.com/akkadotnet/akka.net/issues/2201
@rogeralsing are we ready for this PR?
> Updated Wire to 0.7.1

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
Fixed this bug: https://github.com/akkadotnet/akka.net/issues/2226
> Fix pruning in Distributed PubSub

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Akka.Cluster.Tools.Tests.MultiNode.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientStopSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClient.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientReceptionist.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionistSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/Serialization/ClusterClientMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/Serialization/Proto/ClusterClientMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/reference.conf
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterTools.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Remote.Tests/DeadlineFailureDetectorSpec.cs
- src/core/Akka.Remote/DeadlineFailureDetector.cs
- src/core/Akka/Properties/AssemblyInfo.cs
- src/core/Akka/Util/Internal/ArrayExtensions.cs
- src/core/protobuf/ClusterClientMessages.proto
- Code and specs was aligned with Cluster Client 2.4.8 (Jvm)
- Implemented https://github.com/akkadotnet/akka.net/issues/1980 and https://github.com/akkadotnet/akka.net/issues/1981
> Updated ClusterTools.Client to 2.4.8

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/packages.config
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.Messages.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Serialization/ClusterShardingMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
Fixed ClusterShardingMessageSerializer and added ClusterShardingMessageSerializerSpec
> Fixed ClusterShardingMessageSerializer

- src/core/Akka.Tests/Actor/SupervisorHierarchySpec.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
> Supervision Strategy fix for ReceiveAsync

- src/core/Akka/Dispatch/Mailbox.cs
Copied bits from the docs on
http://getakka.net/docs/working-with-actors/Mailbox into the XML doc for
UnboundedPriorityMailbox
> Better doc for UnboundedPriorityMailbox

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs
- src/core/Akka/Actor/IAutoReceivedMessage.cs
Fixed https://github.com/akka/akka/issues/20998
> Identify does not reset idle state of actors under ReceiveTimeout

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
These changes are related to the Pull Request #2213
> Marked some methods as virtual in Journal/QueryExecutor

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Cluster.Tests/DowningProviderSpec.cs
- src/core/Akka.Cluster/Akka.Cluster.csproj
- src/core/Akka.Cluster/AutoDown.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Cluster/DowningProvider.cs
This PR includes downing providers feature described in #1982 . This change is backward compatible with existing API (only part is obsoleting one of the cluster settings).
> Implemented downing providers

- src/core/Akka/Actor/Scheduler/HashedWheelTimerScheduler.cs
I detailed the cause of the issue on #2314 - the fix is simple.
> close #2314 - fixes shutdown race condition with HashedWheelTimer

- src/core/Akka.TestKit/TestScheduler.cs
> TestScheduler should use ConcurrentQueue for work items

- src/core/Akka.Persistence/PersistentView.cs
Added a missing string.format parameter
https://github.com/akkadotnet/akka.net/issues/2342
> Fix for #2342

- src/core/Akka.Remote.Tests/RemoteConfigSpec.cs
1) Added checking of Adapters dictionary of RemoteSettings.
2) Remove redundant TODO
> Add check for remote settings adapter

- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams.Tests/Dsl/FlowDelaySpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/ChasingEventsSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterPortsSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/GraphInterpreterSpecKit.cs
- src/core/Akka.Streams/Dsl/Hub.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/Ops.cs
<details>
<summary>
2.4.3 done</summary>
</details>
<details>
<summary>
2.4.4 done</summary>
</details>
<details>
<summary>
2.4.5 done</summary>
</details>
<details>
<summary>
2.4.6 & 2.4.7 done</summary>
</details>
<details>
<summary>
2.4.8 done</summary>
</details>
<details>
<summary>
2.4.9 done</summary>
</details>
<details>
<summary>
2.4.10 done</summary>
</details>
<details>
<summary>
2.4.11 done</summary>
</details>
> Streams update to 2.4.11

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs
> RedeliveryTick marked with INotInfluenceReceiveTimeout

- build.cmd
- build.fsx
- build.sh
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Remote.Tests.Performance/packages.config
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/packages.config
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/packages.config
Should help with https://github.com/akkadotnet/akka.net/pull/2398
> upgraded to NBench v0.3.2 for TeamCity formatting

- documentation/akkadoc.shfbproj
- src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj
- src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj
- src/core/Akka.Cluster.TestKit/Akka.Cluster.TestKit.csproj
- src/core/Akka.Persistence.Query/Akka.Persistence.Query.csproj
This PR updates the Sandcastle build file to include newer namespaces.
Also updated the various project files to output xml declaration file.
> [api-docs] Updated Sandcastle build/projects

- src/contrib/cluster/Akka.Cluster.Tools/Client/Serialization/ClusterClientMessageSerializer.cs
- src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs
- src/core/Akka.Streams.Tests/Dsl/UnfoldResourceAsyncSourceSpec.cs
- src/core/Akka.Streams.Tests/Dsl/UnfoldResourceSourceSpec.cs
Need this for https://github.com/akkadotnet/akka.net/issues/2153
> Replace Stream.Close to Stream.Dispose

- src/core/Akka.Cluster/AutoDown.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterActorRefProvider.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterEvent.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/ClusterReadView.cs
- src/core/Akka.Cluster/ClusterRemoteWatcher.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/DowningProvider.cs
- src/core/Akka.Cluster/Gossip.cs
- src/core/Akka.Cluster/Member.cs
- src/core/Akka.Cluster/Reachability.cs
- src/core/Akka.Cluster/Routing/ClusterRoutingConfig.cs
- src/core/Akka.Cluster/Util.cs
- src/core/Akka.Cluster/VectorClock.cs
This PR is part of an ongoing commit for #2407. It adds placeholders
for missing/incomplete xmldoc comments.
[2/23]
> [api-docs] Added TBD placeholders for Akka.Cluster.csproj

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/ActorDslSpec.cs
- src/core/Akka/Actor/Dsl/Act.cs
> Added ReceiveAsync and ReceiveAnyAsync support to Akka.Actor.Dsl.Act

- src/core/Akka.Cluster.Tests/ClusterSpec.cs
> verified that RegisterOnMemberUp still fires if the node is already up

- src/contrib/cluster/Akka.DistributedData.Tests/Akka.DistributedData.Tests.csproj
- src/contrib/cluster/Akka.DistributedData.Tests/Serialization/ReplicatedDataSerializerSpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/Serialization/ReplicatorMessageSerializerSpec.cs
- src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj
- src/contrib/cluster/Akka.DistributedData/DistributedData.cs
- src/contrib/cluster/Akka.DistributedData/GCounter.cs
- src/contrib/cluster/Akka.DistributedData/GSet.cs
- src/contrib/cluster/Akka.DistributedData/LWWDictionary.cs
- src/contrib/cluster/Akka.DistributedData/ORDictionary.cs
- src/contrib/cluster/Akka.DistributedData/ORMultiDictionary.cs
- src/contrib/cluster/Akka.DistributedData/ORSet.cs
- src/contrib/cluster/Akka.DistributedData/PNCounter.cs
- src/contrib/cluster/Akka.DistributedData/PNCounterDictionary.cs
- src/contrib/cluster/Akka.DistributedData/ReadAggregator.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatorMessageSerializer.cs
- src/contrib/cluster/Akka.DistributedData/packages.config
- src/contrib/cluster/Akka.DistributedData/reference.conf
- src/core/Akka/Util/Internal/StringBuilderExtensions.cs
This PR brings few bug fixes, more API methods for distributed data collections and optimized, Hyperion-based serializers for ddata module (original Akka uses Protobuf).
> Continued work over Distributed Data

- src/contrib/cluster/Akka.DistributedData/DistributedData.cs
- src/contrib/cluster/Akka.DistributedData/Dsl.cs
- src/contrib/cluster/Akka.DistributedData/FastMerge.cs
- src/contrib/cluster/Akka.DistributedData/Flag.cs
- src/contrib/cluster/Akka.DistributedData/GCounter.cs
- src/contrib/cluster/Akka.DistributedData/GSet.cs
- src/contrib/cluster/Akka.DistributedData/IReplicatedDataSerialization.cs
- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
- src/contrib/cluster/Akka.DistributedData/Key.cs
- src/contrib/cluster/Akka.DistributedData/LWWDictionary.cs
- src/contrib/cluster/Akka.DistributedData/LWWRegister.cs
- src/contrib/cluster/Akka.DistributedData/Local/ClusterReplicatedDataExtensions.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalGCounter.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalLWWDictionary.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalLWWRegister.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalORDictionary.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalORMultiDictionary.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalORSet.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalPNCounter.cs
- src/contrib/cluster/Akka.DistributedData/Local/LocalPNCounterDictionary.cs
> [api-docs] Added TBD placeholders for Akka.DistributedData.csproj

- src/core/Akka.Remote/Transport/Helios/HeliosTcpTransport.cs
A bit more logging for the known cases
> Akka.Remote - Handling the case when remote node abruptly goes down (#2460)

- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/AkkaEqualException.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/XunitAssertions.cs
> [api-docs] Added TBD placeholders for Akka.TestKit.Xunit2.csproj

- RELEASE_NOTES.md
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
**Maintenance release for Akka.NET v1.1**
Akka.NET v1.1.3 features some new libraries and an enormous number of bug fixes.
**Akka.DistributedData Beta**
First, we've introduced an alpha of a new module intended for use with Akka.Cluster: Akka.DistributedData. The goal of this library is to make it possible to concurrently read and write replicated copies of the same entity across different nodes in the cluster using conflict-free replicated data types, often referred to as "CRDTs." These replicas can eventually be merged together in a fully consistent manner and are excellent choices for applications that require a high level of availability and partition tolerance.
The library is still a bit of a work in progress at the moment, but you are free to use it via the following command:
``` …
```
> Akka.NET V1.1.3 release notes (dev)

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.Messages.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Serialization/ClusterShardingMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardAllocationStrategy.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs
> [api-docs] Added TBD placeholders for Akka.Cluster.Sharding.csproj

- documentation/akkadoc.shfbproj
- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
This PR updates the Sandcastle build file to include the Hyperion
serializer.
> [api-docs] Added Hyperion serializer

- src/core/Akka.Tests/Actor/AskSpec.cs
> close #2463 - used AwaitAssert to avoid race condition with temp actors deregistering

- src/contrib/persistence/Akka.Persistence.Sql.Common/InternalExtensions.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/ITimestampProvider.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/Messages.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/MultiValueDictionaryExtensions.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryApi.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Queries/Hints.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Queries/Query.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Settings.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/SqlSnapshotStore.cs
> [api-docs] Added TBD placeholders for Akka.Persistence.Sql.Common.csproj

- README.md
Example: https://gist.github.com/alexvaluyskiy/aa351ae40c100b67729797084a948b9e
> Added build statuses from TeamCity

- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClient.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientReceptionist.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionist.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterReceptionistSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/Serialization/ClusterClientMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSub.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/TopicMessages.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Internal/Topics.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/PerGroupingBuffer.cs
- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/Serialization/DistributedPubSubMessageSerializer.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxy.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonProxySettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/MemberAgeOrdering.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/Serialization/ClusterSingletonMessageSerializer.cs
> [api-docs] Added TBD placeholders for Akka.Cluster.Tools.csproj

- src/contrib/persistence/Akka.Persistence.Sqlite/ConnectionContext.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Extension.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Journal/BatchingSqliteJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteQueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Snapshot/SqliteSnapshotStore.cs
> [api-docs] Added TBD placeholders for Akka.Persistence.Sqlite.csproj

- src/core/Akka.MultiNodeTestRunner.Shared.Tests/ParsingSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/ConsoleMessageSinkActor.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/IMessageSink.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSink.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/MessageSinkActor.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/Messages.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TestCoordinatorEnabledMessageSink.cs
As @Aaronontheweb stated during review for #2502 there left some loging parts that no more used during specs run. This PR is clean-up for such dead code. Have traced all possible execution paths (hard task in actor-model) and runned several debug sessions with breakpoints on candidates to be removed. But anyway I'm asking for scrupulous review whoever will decide to merge.
> Tech debt for 2502 - got rid of unused code

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
This is basically #2244 all over again, but for the new BatchingSqlJournal.
> Changed signature for methods in BatchingSqlJournal

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeaveSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonRestartSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
Implemented https://github.com/akka/akka/issues/20942 and https://github.com/akka/akka/issues/21236
The parts of this changes were implemented here https://github.com/akkadotnet/akka.net/pull/2495
> Implemented ClusterSingletonRestartSpec

- src/core/Akka.API.Tests/CoreAPISpec.ApproveRemote.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.MultiNode/SurviveNetworkInstabilitySpec.cs
- src/core/Akka.Remote/Properties/AssemblyInfo.cs
Fixed https://github.com/akkadotnet/akka.net/issues/2015
The first 4 tests looks good. The another 3 tests have racy conditions
> [WIP] Implemented SurviveNetworkInstability

- src/core/Akka.API.Tests/App_Packages/ApiApprover.3.0.1/PublicApiGenerator.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Util/Internal/ExtensionsTests.cs
- src/core/Akka/Util/Internal/Extensions.cs
Fix for #2544
Should reduce allocations.
Can run benchmarks for exact numbers a bit later.
> Rewrited SplitDottedPathHonouringQuotes using indexof and substr

- src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.csproj
- src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.nuspec
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparer.cs
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaEqualException.cs
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/Loggers.cs
- src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs
- src/contrib/testkits/Akka.TestKit.Xunit/XunitAssertions.cs
- src/contrib/testkits/Akka.TestKit.Xunit/packages.config
- src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj
- src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.nuspec
XUnit1 teskit project now have the same content as XUnit 2 testkit
> Deprecate XUnit1 project

- src/examples/Streams/StreamsExamples/StreamsExamples.csproj
- src/examples/Streams/StreamsExamples/packages.config
> added NuGet package reference to System.Collections.Immutable for StreamsExamples.csproj

- build.fsx
- src/SharedAssemblyInfo.cs
- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj
- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.nuspec
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
We'll release this beta as soon as it's merged in, along with the package fix to Akka.Cluster.Sharding
> Add LightningDB nuspec

- build.fsx
- src/SharedAssemblyInfo.cs
- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj
- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.nuspec
- src/core/Akka.FSharp/Properties/AssemblyInfo.fs
Won't affect any of the production packages, but will push updates to the beta packages.
> Deploy Akka.Cluster.Sharding and LightningDB package fixes

- build.fsx
Updates NuGet pack dependency for Akka.Persistence.Query to stable release of Akka.Streams
> Update NuGet dependency Akka.Persistcence.Query => Akka.Streams to latest stable v1.2 release

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/core/Akka.Persistence/Fsm/PersistentFSMBase.cs
> fixed possible NRE and flawed Reverse() call described in issue #2588

- src/core/Akka.FSharp/Akka.FSharp.fsproj
- src/core/Akka.FSharp/FsApi.fs
- src/core/Akka.FSharp/packages.config
Updated to the lasr FsPickler. Issue #2644
> Update FsPickler nuget package to v3.2.0

- docs/articles/streams/integration.md
The parts between //NOT DONE still aludes me because I couldn't find the exact implementation in akka.net (line 84-100)
> [WIP] Akka.Stream 2.4.12 documentation mirror

- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/EndpointManager.cs
- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka.Remote/RemoteWatcher.cs
- src/core/Akka.Remote/Transport/ThrottleTransportAdapter.cs
Should help reduce allocations
> replaced inline delegates with local functions in perf-sensitive parts of Akka.Remote

- src/core/Akka.Tests.Performance/Dispatch/DispatcherThroughputSpecBase.cs
Should help provide a more accurate reading for the relative performance of different `Dispatcher` implementations.
> significantly increased number of scheduled operations for dispatcher throughput specs

- docs/articles/utilities/scheduler.md
> Updated the scheduler docs

- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparer.cs
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparerAdapter.cs
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaEqualException.cs
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/Loggers.cs
- src/contrib/testkits/Akka.TestKit.Xunit/TestKit.cs
- src/contrib/testkits/Akka.TestKit.Xunit/XunitAssertions.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/AkkaAssertEqualityComparer.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/AkkaAssertEqualityComparerAdapter.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/AkkaEqualException.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/Internals/Loggers.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs
- src/contrib/testkits/Akka.TestKit.Xunit2/XunitAssertions.cs
- src/core/Akka.TestKit/ITestKitAssertions.cs
This PR contains th following modifications to the Akka.TesstKit.Xunit
and Akka.TestKit.Xunit2 projects:
* refactors classes to take advantage of newer C# features
* made class variables explicit instead of implicit
* fills in various TBD placeholders
> [api-docs][xunit]Xunit TestKit docs/refactoring

- .gitignore
- build.fsx
Output MultiNode Test Runner results to TestResults/multinode so they show up as artifacts in CI.  Also ignore launchSettings.json in .gitignore
> Place MNTR spec results into correct artifacts folder

- build.fsx
- src/benchmark/PersistenceBenchmark/PersistenceBenchmark.csproj
- src/benchmark/PingPong/PingPong.csproj
For performance, build by solution instead of by project.
> dotnet-build on solution file instead of project file

- build.sh
Update FAKE for dev branch to v4.61.3 (latest)
> Update dev branch FAKE to v4.61.3

- src/core/Akka.Cluster.Tests.MultiNode/InitialHeartbeatSpec.cs
Trying to resolve this one https://github.com/akkadotnet/akka.net/issues/2780
> Enabled InitialHeartbeat Spec

- RELEASE_NOTES.md
Not the full notes, but just enough to ship a nightly for users affected by #2773
> v1.2.1 initial release notes

- build.fsx
Add `RunTestsNetCore  DoNothing` to dev branch build.fsx per #2786
> Add RunTestsNetCore to dev branch build.fsx

- src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs
> Fixed node transition spec

- build.fsx
> Enable Remote.TestKit.Tests

- src/core/Akka/Event/Logging.cs
closes #2368 
Staging this just in case I have to do more Akka.Cluster debugging over the weekend ;) cc @nvivo
> log actors by absolute path when using Akka.Remote or Cluster

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/LeaderLeavingSpec.cs
- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Cluster.Tests/ClusterGenerators.cs
- src/core/Akka.Cluster.Tests/MemberOrderingModelBasedTests.cs
- src/core/Akka.Cluster.Tests/MemberOrderingSpec.cs
- src/core/Akka.Cluster.Tests/TestMember.cs
- src/core/Akka.Cluster.Tests/app.config
- src/core/Akka.Cluster.Tests/packages.config
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/Member.cs
- src/core/Akka.TestKit/TestKitBase.cs
Adding some model-based tests and other tools to try to reproduce #2584 
Currently exploring:
> Fix cluster node stuck joining

- src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj
- src/core/Akka.Persistence.Tests/PersistenceConfigAutoStartSpec.cs
- src/core/Akka.Persistence/Persistence.cs
> Akka.Persistence: automatically start snapshot store correctly

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
> add debug logging for gossip received result

- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka/Event/Logging.cs
> fix logging issue with system actor race upon startup

- docs/community/online-resources.md
[Introducing Petabridge.Cmd - a Command-line Management Tool for Akka.NET Applications](https://petabridge.com/blog/petabridgecmd-release/) (Aaron Stannard on June 7, 2017)
[Monitoring Akka.NET Systems with Datadog](https://gregshackles.com/monitoring-akka-net-systems-with-datadog/) (Creg Shackles on May 25th, 2017)
[Actor model and using of Akka.NET](https://rubikscode.net/2017/05/28/actor-model-and-using-of-akka-net/) (Nikola Živković on May 28th, 2017)
[Akka.NET: The Future of Distributed Programming in .NET](https://www.youtube.com/watch?v=ozelpjr9SXE) (Aaron Stannard on August 31, 2016)
[Life with actors: experience report](https://www.youtube.com/watch?v=KQwskUjsSi8) (Vagif Abilov and Erlend Wiig on February 16th, 2017)
[Akka.NET: The Future of Distributed Programming in …
> Added new articles and videos to Online Resources

- src/core/Akka.Remote.Tests/Akka.Remote.Tests.csproj
- src/core/Akka.Remote.Tests/Transport/DotNettyTransportShutdownSpec.cs
- src/core/Akka.Remote/RemoteActorRefProvider.cs
- src/core/Akka.Remote/Transport/DotNetty/AkkaLoggingHandler.cs
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
- src/core/Akka/Util/ConcurrentSet.cs
- src/examples/Chat/ChatClient/Program.cs
Related to #2575 - verifying the all manner of Akka.Remote association disposals "do the right thing"
> investigate DotNetty clean shutdown

- build.fsx
For now, to be consistent with CI - pass `nugetprerelease=dev` for nightly builds so `versionSuffix` is set to `-beta` for the published package names.
> Change flag versionsuffix to nugetprerelease for consistency with dev branch

- src/NuGet.Config
Upgrade NuGet.config to use v3 NuGet feed instead of v2.  Try to mitigate #2864 and also just for maintenance.
> Upgrade NuGet feed to v3

- docs/articles/streams/basics.md
form --> from.
A follow-up based on @sean-gilliam's comment on the old docs: 
https://github.com/akkadotnet/getakka.net/pull/245#issuecomment-315142577
> Fix tiny typo in basics.md

- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByPersistenceIdPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/SqlReadJournal.cs
- src/core/Akka.API.Tests/Akka.API.Tests.csproj
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceQuery.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.cs
- src/core/Akka.Persistence.Query/EventEnvelope.cs
- src/core/Akka.Persistence.Query/Interfaces.cs
- src/core/Akka.Persistence.Query/Offset.cs
- src/core/Akka.Persistence.TCK/Query/CurrentEventsByTagSpec.cs
- src/core/Akka.Persistence.TCK/Query/EventsByTagSpec.cs
- Add support for Time-based UUID offset into EventsByTag query
- Make an offset as exclusive
- Added PersistenceQuery to API.Tests
> Add pluggable offset strategies to EventsByTag query

- src/core/Akka.Tests.Performance/Dispatch/DispatcherThroughputSpecBase.cs
increased dispatcher message count, reduced # of runs, added GC profiling
> Tweak MessageDispatcherThroughput specs

- src/core/Akka.MultiNodeTestRunner.Shared.Tests/Akka.MultiNodeTestRunner.Shared.Tests.csproj
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoverySpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/NodeMessageHelpers.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/ParsingSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/TestRunShutdownSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Akka.MultiNodeTestRunner.Shared.csproj
- src/core/Akka.MultiNodeTestRunner.Shared/Discovery.cs
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/Spec.cs
- src/core/Akka.NodeTestRunner/Akka.NodeTestRunner.csproj
- src/core/Akka.NodeTestRunner/Program.cs
- src/core/Akka.NodeTestRunner/Sink.cs
> Fix Xunit runner transparent proxy error problem on net452 target

- src/core/Akka/Actor/ActorSelection.cs
This PR refactors ActorSelection to take advantage of newer C# features.
Breaking apart #2854 for easier review.
> ActorSelection refactor

- docs/articles/clustering/cluster-overview.md
Based on a gitter chat with @Aaronontheweb, there are several aspects of cluster default behavior as shown in akka cluster sample that aren't documented for what happens when a node crushes and is being restarted.
> Docs update to capture important aspects of node recovery

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams/Implementation/Fusing/ActorGraphInterpreter.cs
- src/core/Akka.Streams/Implementation/Fusing/GraphInterpreter.cs
Small micro optimizations around `GraphInterpreter` and `ActorGraphInterpreter`.
> GraphInterpreter: C# 7 style + const IsDebug

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/Inbox.Actor.cs
- src/core/Akka/Actor/Inbox.cs
This PR refactors Inbox to take adavantage of newer C# features.
Breaking apart #2854 for easier review.
> Inbox refactor

- src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.csproj
- src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj
Make Akka.TestKit.Xunit beta `<VersionSuffix>` since we're using `xunit-beta2-*` and also fix hard-coded xunit version in .csproj to use common.props.
> Make TestKits "beta" VersionSuffix

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/ActorRef.Extensions.cs
- src/core/Akka/Actor/ActorRefFactoryExtensions.cs
- src/core/Akka/Actor/Address.cs
- src/core/Akka/Actor/ChildrenContainer/Internal/ChildStats.cs
- src/core/Akka/Actor/Dsl/Act.cs
- src/core/Akka/Actor/IActorRefFactory.cs
- src/core/Akka/Actor/Scheduler/IActionScheduler.cs
- src/core/Akka/Actor/Scheduler/ITellScheduler.cs
- src/core/Akka/Actor/Scheduler/SchedulerException.cs
- src/core/Akka/Actor/Scheduler/SchedulerExtensions.cs
- src/core/Akka/Actor/Scope.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
This PR fills in various TBD placeholders in the Akka.Actor namespace.
Breaking apart #2854 for easier review.
> [api-docs]  Further document Akka.Actor namespace

- src/core/Akka.Remote/Akka.Remote.csproj
Upgrades DotNetty.Handlers to v0.4.6
> Upgrade DotNetty.Handlers to v0.4.6

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
this fixes missing sender on RememberEntityStarter._requestor
> RememberEntityStarter missing sender fix

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingCustomShardAllocationSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingFailureSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStateSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGetStatsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingGracefulShutdownSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingLeavingSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingMinMembersSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesNewExtractorSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesSpec.cs
this forces usage of ClusterShardingMessageSerializer for serialization
> default sharding configs added to tests

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Dispatch/MailboxesSpec.cs
- src/core/Akka/Dispatch/Mailboxes.cs
- src/core/Akka/Dispatch/MessageQueues/UnboundedPriorityMessageQueue.cs
close #2649 
Fix for stashing support in priority mailbox.
> Issue 2649

- docs/articles/actors/mailboxes.md
Adds a note about the combination with Stashing
> Updated priority mailbox docs

- src/core/Akka.Remote.Tests/Serialization/MiscMessageSerializerSpec.cs
- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Serialization/ExceptionSupport.cs
- src/core/Akka.Remote/Serialization/MiscMessageSerializer.cs
- src/core/Akka.Remote/Serialization/Proto/WireFormats.g.cs
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka/Configuration/Hocon/HoconValue.cs
- src/protobuf/ContainerFormats.proto
- src/protobuf/WireFormats.proto
- src/protobuf/common/duration.proto
- Improved Exception serializer on NetCore
- Added serializer for ConsistentHashingPool
- Added serializer for Config
TODO:
- Use protobuf's `Duration` type instead of a custom `TimeSpan`
> Protobuf serialization improvements

- build.fsx
Point NuGet publish step to correct folder
> Point NuGet publish step to correct folder

- build.fsx
Fixed: https://github.com/akkadotnet/akka.net/issues/2972
> Fixed nuget for Persistence.TCK

- docs/articles/clustering/cluster-client.md
Fixes incorrect setting and uses file inclusion for reference.conf
> Updated cluster-client article

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/IO/UdpConnectedIntegrationSpec.cs
- src/core/Akka.Tests/IO/UdpIntegrationSpec.cs
- src/core/Akka/IO/SocketEventArgsPool.cs
- src/core/Akka/IO/TcpConnection.cs
- src/core/Akka/IO/Udp.cs
- src/core/Akka/IO/UdpConnected.cs
- src/core/Akka/IO/UdpConnectedManager.cs
- src/core/Akka/IO/UdpConnection.cs
- src/core/Akka/IO/WithUdpSend.cs
- src/core/Akka/Util/ByteString.cs
This should fix the issue reported in #2995 (PR contains tests which reproduced the issue). It also upgrades the codebase to C# 7.
> Updates and fixes for Akka.IO UDP support

- docs/articles/utilities/logging.md
- docs/articles/utilities/serilog.md
close https://github.com/akkadotnet/akka.net/issues/2997
> Added serilog instructions

- docs/articles/clustering/cluster-client.md
> Better config display for cluster client page

- src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj
- src/core/Akka.TestKit.Tests/TestKitBaseTests/IgnoreMessagesTests.cs
- src/core/Akka.TestKit/TestKitBase.cs
Just thought this would be convenient.
Also filled in some tests for non-generic IgnoreMessages().
> Add TestKitBase.IgnoreMessages<TMsg>

- docs/articles/clustering/cluster-client.md
- docs/articles/clustering/cluster-configuration.md
- docs/articles/clustering/cluster-overview.md
- docs/articles/clustering/cluster-routing.md
- docs/articles/remoting/deployment.md
- docs/articles/remoting/security.md
- docs/articles/remoting/transports.md
close https://github.com/akkadotnet/akka.net/issues/2983
> Shorthand notation fixes

- src/common.props
https://xunit.github.io/releases/2.3-beta3
https://xunit.github.io/releases/2.3-beta4
https://xunit.github.io/releases/2.3-beta5
> Update Xunit to 2.3.0-beta5

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence.Tests/Serialization/MessageSerializerRemotingSpec.cs
- src/core/Akka.Persistence.Tests/Serialization/PersistenceMessageSerializerSpec.cs
- src/core/Akka.Persistence/Fsm/PersistentFSM.cs
- src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs
Fix https://github.com/akkadotnet/akka.net/issues/3067
> Updated PersistenceMessageSerializer

- RELEASE_NOTES.md
- src/common.props
> v1.3.1 Release Notes

- src/core/Akka.Streams.TestKit/TestSubscriber.cs
Fixed https://github.com/akkadotnet/akka.net/issues/3122
> Added timeout parameter to Probe.RequestNext and ManualProbe.ExpectNext

- docs/examples/Tutorials/Tutorial3/Device.cs
- docs/examples/Tutorials/Tutorial3/DeviceGroup.cs
- docs/examples/Tutorials/Tutorial3/DeviceGroupInProgress.cs
- docs/examples/Tutorials/Tutorial4/Device.cs
- docs/examples/Tutorials/Tutorial4/DeviceGroup.cs
"groupId" -> GroupId
"deviceId" -> DeviceId
> Fixed tutorials

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Remote.Tests/RemotingSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
https://github.com/akkadotnet/akka.net/pull/2548
> Fix Ask deadlock #2

- docs/articles/clustering/distributed-publish-subscribe.md
> Remove subscription by the publisher

- src/core/Akka.Tests/Dispatch/MailboxesSpec.cs
> close #3061 - fixed Unbounded_Priority_Mailbox_Supports_Unbounded_Stashing

- build.fsx
- src/contrib/testkits/Akka.TestKit.Xunit/Akka.TestKit.Xunit.csproj
- src/contrib/testkits/Akka.TestKit.Xunit2/Akka.TestKit.Xunit2.csproj
> Fix xunit publish

- RELEASE_NOTES.md
Getting the nightlies onto the next version #
> version bump for v1.3.3

- src/core/Akka.MultiNodeTestRunner/Discovery.cs
One of the not so obvious requirements for writing MultiNode TestKit test classes is that, this class must not only inherit from `MultiNodeSpec`, but somewhere in its inheritance chain it also must specify a constructor, which first parameter is a class inheriting from `MultiNodeConfig`.
Up to this point, if this requirement was not fulfilled, we simply crashed with NRE - since we tried to go down the test class inheritance chain until we reached System.Object, which BaseType is null.
This PR replaces recursive check with loop. When the loop ends and no correct config class was found, we throw a meaningful message informing user what has gone wrong. Example:
> [MyNodeSpec] or one of its base classes must specify constructor, which first parameter is a subclass of MultiNodeConfig.
> Added human-friendly error for failed MNTK discovery

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
> Avoid NullReferenceException in DistributedPubSubMediator.PublishMessage

- docs/articles/streams/quickstart.md
Fixes a small error I noticed while reading the Streams documentation
> Fix unicode error

- src/Akka.sln
- src/core/Akka.Remote.TestKit/Akka.Remote.TestKit.csproj
- src/core/Akka.Streams.Tests.TCK/Akka.Streams.Tests.TCK.csproj
- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.Streams/Akka.Streams.csproj
- src/core/Akka.Tests.Shared.Internals/Akka.Tests.Shared.Internals.csproj
- src/core/Akka.Tests/Akka.Tests.csproj
> Solution cleaning (#3216)

- src/Akka.sln
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/Akka.MultiNodeTestRunner.Shared.Tests.csproj
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoveryCases.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoverySpec.cs
- src/core/Akka.MultiNodeTestRunner/Discovery.cs
> Fixed issue with MNTR not discovering configuration on base classes

- docs/articles/clustering/cluster-sharding.md
This PR only updated documentation up to changes made previously around DData mode + section about remember entities. No code was changed.
> Updated documentation on cluster sharding

- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
Last major to-do before we move forward with the Akka.NET v1.3.3 release.
> upgraded to Hyperion v0.9.7

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs
> sharding StartProxy replicator used based on configuration

- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
Using the latest Hyperion release on NuGet
> upgraded Akka.Serialization.Hyperion to Hyperion 0.9.8

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FlowScanSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowSplitWhenSpec.cs
- src/core/Akka.Streams.Tests/Dsl/GraphStageTimersSpec.cs
- src/core/Akka.Streams.Tests/Dsl/HubSpec.cs
- src/core/Akka.Streams.Tests/Dsl/SourceSpec.cs
- src/core/Akka.Streams.Tests/IO/TcpSpec.cs
- src/core/Akka.Streams.Tests/Implementation/Fusing/KeepGoingStageSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/CompletedPublishers.cs
- src/core/Akka.Streams/Implementation/Modules.cs
This is a fix for #3286 
Hello, i tried to found any reference to `MaybePublisher` and fix it. 
The API Tests pass but i would like to know if there is any unit test that i must create or alter for that.
Thanks.
> Fixing Issue 3286

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
> ShardId needs to be consistent across nodes (GetHashCode might not be)

- src/core/Akka.Persistence/Eventsourced.Recovery.cs
@Aaronontheweb  I think this should be merged ASAP
Original PR: [#24439](https://github.com/akka/akka/pull/24439)
> Add missing ReturnRecoveryPermit

- src/core/Akka.Remote/Akka.Remote.csproj
This fixes https://github.com/akkadotnet/akka.net/issues/3409
> Pin DotNetty version to 0.4.6

- src/core/Akka/Actor/IAutoReceivedMessage.cs
> Doc Typo Fix: Sending a PoisonPill to an * will stop

- build.sh
- src/core/Akka.Cluster.Tests/ClusterSpec.cs
Trying to solve the same problem as #3391, but from a different angle.
> changed version of .NET Core SDK being used on Linux

- src/core/Akka.Tests/Event/EventStreamSpec.cs
- src/core/Akka/Event/LoggingBus.cs
close #3267
Added reproduction spec to verify
> fix NullReferenceException when logging UnhandledMessage from ActorRefs.NoSender

- src/core/Akka.Remote/Akka.Remote.csproj
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
> upgraded to DotNetty v0.4.8

- docs/articles/streams/basics.md
- docs/examples/DocsExamples/Streams/FlowDocTests.cs
- docs/examples/Tutorials/Tutorials.csproj
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/SourceSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
Port of https://github.com/akka/akka/pull/24497
> Akka.Streams: add PreMaterialize support for Sources

- docs/articles/streams/builtinstages.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.cs
- src/core/Akka.Streams.Tests/Dsl/SinkSpec.cs
- src/core/Akka.Streams/Dsl/Sink.cs
Port of https://github.com/akka/akka/pull/24657
> Akka.Streams: add PreMaterialize support for Sinks

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/SourceSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
> Add CombineMaterialized method to Source

- src/core/Akka.Cluster.TestKit/MultiNodeClusterSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/ClusterDeathWatchSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/InitialHeartbeatSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/RestartNodeSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/Routing/ClusterConsistentHashingRouterSpec.cs
- src/core/Akka.Cluster.Tests.MultiNode/UnreachableNodeJoinsAgainSpec.cs
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/TestRunCoordinatorSpec.cs
- src/core/Akka.Remote.Tests/RemoteConfigSpec.cs
- src/core/Akka.Remote.Tests/Transport/GenericTransportSpec.cs
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka.Tests/Actor/ActorSystemTests.cs
- src/core/Akka.Tests/MatchHandler/MatchExpressionBuilder_CreateArgumentValuesArray_Tests.cs
This PR fixes a number of issues caught by the xunit analyzer regarding collection assertions.
> [xunit] Fix xunit warnings wrt collections

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.DistributedData/Dsl.cs
- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
- src/contrib/cluster/Akka.DistributedData/ORDictionary.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Streams/Attributes.cs
- src/core/Akka.Streams/Dsl/Internal/InternalFlowOperations.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Dsl/SourceOperations.cs
- src/core/Akka.Streams/Dsl/SubFlowOperations.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
- src/core/Akka/Pattern/BackoffOptions.cs
This PR fixes some xrefs issues wrt to referencing base class
fields/methods. It also adds some missing method parameter tags.
> [api-docs] fix a few xref/parameter issues

- RELEASE_NOTES.md
- src/common.props
Just so the nightlies start making some sense for this branch.
Nightlies for v1.4 available here:
https://www.myget.org/F/akkadotnet-v14/api/v3/index.json
> bumped v1.4 branch to v1.4 versions

- src/contrib/cluster/Akka.Cluster.Tools.Tests/ClusterClient/ClusterClientConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Client/ClusterClientSettings.cs
mentioned in #3417 
Added spec to reproduce and verify fix as well.
> fixed NRE issue with ClusterClientSettings.Copy

- .gitignore
Ignore [CodeRush](https://www.devexpress.com/products/coderush/) files
Ignore [GhostDoc](https://submain.com/products/ghostdoc.aspx) files
Ignore [NDepend](https://www.ndepend.com/) files
Ignore [Visual Studio Code](https://code.visualstudio.com/) files
> Ignore CodeRush, GhostDoc, NDepend, VS Code files

- docs/articles/persistence/persistence-query.md
> [docs] Remove Akka.Persistence.Query warning

- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
Messages that come through for an entity before StartEntity
has been processed for that entity caused redundant persistence
of the entity.
Migrated from:
https://github.com/akka/akka/issues/25261
> Sharding - Check remembered entities before remembering entity

- src/core/Akka.Persistence.Tests/OptimizedRecoverySpec.cs
- src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
- src/core/Akka.Persistence/PersistentActor.cs
- src/core/Akka.Persistence/Snapshot/SnapshotStore.cs
Port [#25132](https://github.com/akka/akka/issues/25132)
> Optimized recovery

- docs/articles/actors/dependency-injection.md
- docs/articles/actors/dispatchers.md
- docs/articles/actors/mailboxes.md
- docs/articles/actors/routers.md
- docs/articles/actors/testing-actor-systems.md
- docs/articles/clustering/cluster-configuration.md
- docs/articles/clustering/cluster-extension.md
- docs/articles/clustering/cluster-sharding.md
- docs/articles/clustering/distributed-data.md
- docs/articles/clustering/split-brain-resolver.md
- docs/articles/concepts/actor-systems.md
- docs/articles/intro/tutorial-3.md
- docs/articles/networking/io.md
- docs/articles/networking/multi-node-test-kit.md
- docs/articles/persistence/event-sourcing.md
- docs/articles/persistence/persistent-fsm.md
- docs/articles/remoting/messaging.md
- docs/articles/remoting/transports.md
- docs/articles/streams/basics.md
- docs/articles/streams/builtinstages.md
- docs/articles/streams/cookbook.md
- docs/articles/streams/custom-stream-processing.md
- docs/articles/streams/workingwithgraphs.md
- docs/articles/utilities/scheduler.md
- docs/articles/utilities/serilog.md
This PR fixes various issues w.r.t. the documentation site.
- fix various typos
- fix several links
- fix styling issues
> [docs] Fix various issues

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
part of https://github.com/akka/akka/pull/23596
> Singleton - confirm TakeOverFromMe when singleton already in oldest state

- docs/articles/streams/reactivetweets.md
I don't believe `Selet` is a valid method
> Fix small typo

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/IntervalBasedRateLimiterSpec.cs
- src/core/Akka.Streams.Tests/Dsl/PagedSourceSpec.cs
- src/core/Akka.Streams/Dsl/IntervalBasedRateLimiter.cs
- src/core/Akka.Streams/Dsl/PagedSource.cs
Hi 
please review port of these streams stages:
https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/PagedSource.scala
and
https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/IntervalBasedRateLimiter.scala
This is for issue #3234
> Port PagedSource & IntervalBasedRateLimiter

- .github/stale.yml
- docs/articles/streams/configuration.md
https://github.com/akkadotnet/akka.net/issues/3537
> Deleting file, reason issue 3537

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster/ClusterReadView.cs
- src/core/Akka.Remote.TestKit/BarrierCoordinator.cs
- src/core/Akka/Serialization/Serialization.cs
- src/core/Akka/Util/Internal/Extensions.cs
> GetOrElse null handling fix

- src/core/Akka/Event/LoggingBus.cs
Fixes https://github.com/akkadotnet/akka.net/issues/3571
> Handle AskTimeoutException when initializing a logger.

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams/Dsl/BidiFlow.cs
#3563 seems like a low hanging fruit, can anyone review it please?.
Changed AtopMat's return type to TMat3
> #3563 AtopMat's return type changed TMat -> TMat3

- docs/examples/Tutorials/Tutorial4/DeviceGroupSpec.cs
I created a new fork, added the fix on a new branch (as has been mentioned in https://github.com/akkadotnet/akka.net/pull/3589) 
Removed Todo from DeviceGroup_actor_must_be_able_to_collect_temperatures_from_all_active_devices and added approp. assert
> Fix for issue #3588, second try

- src/core/Akka.Persistence.Tests/AtLeastOnceDeliverySpec.cs
- src/core/Akka.Persistence/AtLeastOnceDelivery.cs
- src/core/Akka.Persistence/AtLeastOnceDeliveryReceiveActor.cs
This PR introduces possible solution of https://github.com/akkadotnet/akka.net/issues/3500 by combining Anchor Path and PathString
> Can not parse an ActorPath #3500

- docs/examples/Tutorials/Tutorial4/DeviceGroupQuerySpec.cs
Run dotnet test failed when using Tutorials.Tutorial4 on main Program.cs
> fix failed when run test on Tutorials.Tutorial4

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/StreamRefsSpec.cs
- src/core/Akka.Streams/Dsl/StreamRefs.cs
- src/core/Akka.Streams/Serialization/StreamRefSerializer.cs
- src/core/Akka.Streams/StreamRefs.cs
- src/core/Akka.Streams/reference.conf
> Stream ref fixes

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/RestartSpec.cs
- src/core/Akka.Streams/Dsl/Restart.cs
Port [#24328](https://github.com/akka/akka/pull/24328)
> Add MaxRestarts to RestartWithBackoff

- docs/community/contributor-guidelines.md
Made capitalization and punctuation consistent.
> Minor formatting tweaks

- docs/articles/clustering/cluster-sharding.md
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/InactiveEntityPassivationSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
Port [#25765](https://github.com/akka/akka/pull/25765)
> Automatic passivation for sharding

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.Persistence/AtLeastOnceDeliverySemantic.cs
Port [#26248](https://github.com/akka/akka/pull/26248)
> Optimize AtLeastOnceDelivery by not scheduling ticks when not needed

- docs/articles/actors/di-core.md
- docs/articles/networking/serialization.md
- docs/articles/toc.yml
This adds di-core.md to the Actor directory and adds it to the TOC.
Once I know this is the correct home and name for the file, I will fix the link to it mentioned in #3378
> Port di-core.md

- src/core/Akka.Tests/Actor/Dispatch/Bug2640Spec.cs
- src/core/Akka.Tests/Dispatch/DispatchersSpec.cs
- src/core/Akka/Actor/Scheduler/HashedWheelTimerScheduler.cs
Have a reproduction spec for #2640 in here, but not a fix yet.
> Fix ForkJoinExecutor / Dispatcher Leak

- build.fsx
> fixed NRE with build.fsx when not running incrementally

- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMediatorSpec.cs
- src/contrib/cluster/Akka.Cluster.Tools.Tests/PublishSubscribe/DistributedPubSubMessageSerializerSpec.cs
Part of #3786 - ran into this issue while testing https://github.com/akkadotnet/akka.net/pull/3744
> fix racy bind on port 0 error with DistributedPubSub specs

- src/core/Akka.Remote/RemoteSystemDaemon.cs
> reduce allocations in RemoteSystemDaemon ActorPath resolution

- src/common.props
> added SourceLink support

- docs/articles/remoting/transports.md
it seems should be akka.http protocol, not udp
> fix typo in transports.md

- build-system/windows-release.yaml
Need this for v1.3.14 and future releases
> added updated Windows Release pipeline YAML file

- build.ps1
- build.sh
Need this to solve some more complex Roslyn diff detection issues involving multi-targeting, per https://github.com/petabridge/Incrementalist/issues/63
> upgrade to Incrementalist v0.1.7

- build.fsx
- src/core/Akka.MultiNodeTestRunner/Akka.MultiNodeTestRunner.nuspec
resolves https://github.com/akkadotnet/akka.net/pull/3861
> added ability to support custom beta builds from commandline

- src/core/Akka.Persistence.TCK/Query/TestActor.cs
> Akka.Persistence.TCK.Query.TestActor now waits for delete confirmation before replying

- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceQuery.approved.txt
- src/core/Akka.Persistence.Query.Tests/OffsetCompareSpecs.cs
- src/core/Akka.Persistence.Query/Offset.cs
> Akka.Persistence.Query: made Offset IComparable to itself

- build-system/nightly-builds.yaml
Nightly builds are not running. This PR aims to fix that.
> Fix nightly-build template

- src/common.props
- src/contrib/cluster/Akka.DistributedData/Akka.DistributedData.csproj
- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
close https://github.com/akkadotnet/akka.net/issues/3959
> Upgrade to Hyperion v0.9.9

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingInternalsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingSettingsSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingSettings.cs
- src/contrib/cluster/Akka.Cluster.Sharding/DDataShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/PersistentShard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
Port [#27738](https://github.com/akka/akka/pull/27738)
> Consolidated passivation check on settings used in region and shard

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/ReceiveTimeoutSpec.cs
- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
- src/core/Akka/Actor/ActorCell.ReceiveTimeout.cs
Issue: [#25340](https://github.com/akka/akka/issues/25340)
Port: [#25347](https://github.com/akka/akka/pull/25347)
> Fixed scheduling and cancelling receive timeout

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/Singleton/ClusterSingletonManagerLeave2Spec.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
- src/contrib/cluster/Akka.Cluster.Tools/Singleton/OldestChangedBuffer.cs
Issue [#27487](https://github.com/akka/akka/issues/27487)
Port [#27488](https://github.com/akka/akka/pull/27488)
> Fixed singleton issue when leaving several nodes

- src/core/Akka.Persistence.TCK/Serialization/JournalSerializationSpec.cs
> Akka.Persistence.TCK.JournalSerializationSpec: made error messages clearer

- src/core/Akka.Persistence/Eventsourced.Recovery.cs
Modernizing some of the `EventSourced` internals in Akka.Persistence
> cleaning up Akka.Persistence internals

- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
Port [#27940](https://github.com/akka/akka/pull/27940)
> Fix state non-empty check when starting HandOffStopper

- src/contrib/cluster/Akka.Cluster.Tools.Tests.MultiNode/ClusterClient/ClusterClientSpec.cs
- src/core/Akka.Cluster/Cluster.cs
> Fix MNTR failure

- src/core/Akka.Cluster/ClusterHeartbeat.cs
Close #4055
Basically, simple port of [this](https://github.com/akka/akka/pull/24785/files) changes
> Added delayed heartbeat logging

- src/benchmark/Akka.Benchmarks/IO/TcpOperationsBenchmarks.cs
- src/core/Akka/IO/SimpleDnsCache.cs
> Fix concurrent `SimpleDnsCache.Cleanup` invocation issues

- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
> enable akka.cluster.allow-weakly-up-members by default

- src/core/Akka/Actor/ActorSystem.cs
>  made ActorSystem.Dispose method block until WhenTerminated.IsComplete == true

- build-system/pr-validation.yaml
This to enable CI against the v1.3, v1.4, etc branches
> modify build system to support wildcard PR triggers

- RELEASE_NOTES.md
- src/common.props
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ConstantRateEntityRecoveryStrategySpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
- src/core/Akka.Cluster.Tests/ShutdownAfterJoinSeedNodesSpec.cs
- src/core/Akka.Cluster/Cluster.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterHeartbeat.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka.Tests/Util/TypeExtensionsTests.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/CoordinatedShutdown.cs
- src/core/Akka/Actor/Inbox.Actor.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Event/DeadLetterListener.cs
- src/core/Akka/Util/TypeExtensions.cs
Working on getting some critical bug-fixes in place for Akka.NET v1.3.17.
> V1.3.17 Release

- build.fsx
- src/core/Akka.FSharp/FsApi.fs
> detect and run F# projects during incremental builds

- docs/articles/streams/builtinstages.md
Copy the description of Partition from https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Dsl/Graph.cs#L1057
> Doc improvement. add Partition in Fan-out stage

- src/core/Akka.NodeTestRunner/Program.cs
> Monitored actor terminated error fix

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Tools.Tests/Akka.Cluster.Tools.Tests.csproj
- src/contrib/cluster/Akka.DistributedData.Tests/Akka.DistributedData.Tests.csproj
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Akka.Persistence.Sqlite.Tests.csproj
- src/contrib/serializers/Akka.Serialization.Hyperion.Tests/Akka.Serialization.Hyperion.Tests.csproj
- src/core/Akka.API.Tests/Akka.API.Tests.csproj
- src/core/Akka.Cluster.Tests.MultiNode/Akka.Cluster.Tests.MultiNode.csproj
- src/core/Akka.Cluster.Tests.Performance/Akka.Cluster.Tests.Performance.csproj
- src/core/Akka.Cluster.Tests/Akka.Cluster.Tests.csproj
- src/core/Akka.Docs.Tests/Akka.Docs.Tests.csproj
- src/core/Akka.FSharp.Tests/Akka.FSharp.Tests.fsproj
- src/core/Akka.MultiNodeTestRunner.Shared.Tests/Akka.MultiNodeTestRunner.Shared.Tests.csproj
- src/core/Akka.Persistence.Query.Tests/Akka.Persistence.Query.Tests.csproj
- src/core/Akka.Persistence.TCK.Tests/Akka.Persistence.TCK.Tests.csproj
- src/core/Akka.Persistence.TestKit.Tests/Akka.Persistence.TestKit.Tests.csproj
- src/core/Akka.Persistence.Tests/Akka.Persistence.Tests.csproj
- src/core/Akka.Remote.TestKit.Tests/Akka.Remote.TestKit.Tests.csproj
- src/core/Akka.Remote.Tests.MultiNode/Akka.Remote.Tests.MultiNode.csproj
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Streams.TestKit.Tests/Akka.Streams.TestKit.Tests.csproj
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.TCK/Akka.Streams.Tests.TCK.csproj
- src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj
- src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/ActorState.cs
- src/xunitSettings.props
Close #4076
Let's just see how this will help with running racy tests in this PR
> Added xunitSettings.props to all test assemblies

- src/core/Akka.NodeTestRunner/Program.cs
> Add inner exceptions to NodeTestRunner  spec failure report

- docs/articles/clustering/cluster-sharding.md
> [docs] explain Akka.Cluster.Sharding /system actor paths

- build.fsx
modified build script so if there's a beta version in the release notes, that ges automatically included in the NuGet package metadata
> Use beta version specified in release notes when applicable

- build.fsx
> properly push .snupkg files to NuGet feed

- src/core/Akka.Remote.TestKit/MultiNodeFact.cs
Close #4188
Only minor change here to support how new MNTR from [here](https://github.com/akkadotnet/Akka.MultiNodeTestRunner) will be detected.
> Using environment variable to detect MNTR

- src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/ReplicatorPruningSpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/DataEnvelopeSpecs.cs
- src/contrib/cluster/Akka.DistributedData.Tests/PNCounterDictionarySpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs
- src/contrib/cluster/Akka.DistributedData/ORSet.cs
- src/contrib/cluster/Akka.DistributedData/PNCounterDictionary.cs
- src/contrib/cluster/Akka.DistributedData/ReadAggregator.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.cs
- src/contrib/cluster/Akka.DistributedData/ReplicatorSettings.cs
- src/contrib/cluster/Akka.DistributedData/WriteAggregator.cs
- src/contrib/cluster/Akka.DistributedData/reference.conf
- src/core/Akka.Cluster/Properties/AssemblyInfo.cs
close #3080 
close #4198
close #4199
close #4200
> enabled DData MNTR ReplicatorPruningSpec

- src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/ReplicatorChaosSpec.cs
> enable DData ReplicatorChaosSpec

- src/benchmark/Akka.Benchmarks/Actor/SpawnActorBenchmarks.cs
> ActorSpawn benchmark tweaks

- src/core/Akka.Persistence.Tests/PersistenceConfigSpec.cs
- src/core/Akka/Dispatch/CachingConfig.cs
- src/core/Akka/Dispatch/Dispatchers.cs
close #4234 - added CachingConfig back
> Resolve Akka.Persistence.ConfigSpec bug

- src/core/Akka.Persistence.Tests/ReceivePersistentActorAsyncAwaitSpec.cs
- src/core/Akka.Streams.Tests/Dsl/FlowThrottleSpec.cs
> Racy test pruning

- RELEASE_NOTES.md
- src/common.props
**Stable release candidate for Akka.NET 1.4**
Akka.NET v1.4.0-rc1 represents [the completion of the entire Akka.NET v1.4.0 milestone](https://github.com/akkadotnet/akka.net/milestone/17).
Provided that there are no major bugs, architectural issues, performance regressions, or stability issues reported as we begin the process of moving all of our plugins onto Akka.NET v1.4.0-RC1, Akka.NET v1.4.0 final will ship within two weeks.
For information on the full set of changes, [please see "What's New in Akka.NET v1.4" on the official Akka.NET website](https://getakka.net/community/whats-new/akkadotnet-v1.4.html).
| COMMITS | LOC+ | LOC- | AUTHOR |         
| --- | --- | --- | --- |                  
| 206 | 33015 | 24489 | Aaron Stannard |   
| 47 | 63 | 63 | dependabot-preview[bot] | 
| 33 | …
> added Akka.NET v1.4.1-rc1 release notes

- docs/community/building-akka-net.md
Added a title to the "Building and Distributing Akka.NET" page
> add-title-to-build-docs

- docs/community/whats-new/akkadotnet-v1.4.md
- docs/community/whats-new/toc.yml
Added lots of additional documentation around new HOCON changes and other changes introduced in Akka.NET v1.4.0 that users should be aware of.
> Update "what's new in 1.4" page

- build.fsx
- src/common.props
- src/core/Akka.Cluster.Tests.Performance/Akka.Cluster.Tests.Performance.csproj
- src/core/Akka.Cluster.Tests.Performance/App.config
- src/core/Akka.Cluster.Tests.Performance/Program.cs
- src/core/Akka.Cluster.Tests.Performance/Startup/ClusterStartupSpec.cs
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Remote.Tests.Performance/App.config
- src/core/Akka.Remote.Tests.Performance/Program.cs
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/App.config
- src/core/Akka.Streams.Tests.Performance/Program.cs
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/App.config
- src/core/Akka.Tests.Performance/Program.cs
> adding NBench 2.0 to 1.3 Akka.NET

- build.fsx
- src/common.props
- src/core/Akka.Cluster.Tests.Performance/Akka.Cluster.Tests.Performance.csproj
- src/core/Akka.Cluster.Tests.Performance/App.config
- src/core/Akka.Cluster.Tests.Performance/Program.cs
- src/core/Akka.Cluster.Tests.Performance/Startup/ClusterStartupSpec.cs
- src/core/Akka.Remote.Tests.Performance/Akka.Remote.Tests.Performance.csproj
- src/core/Akka.Remote.Tests.Performance/App.config
- src/core/Akka.Remote.Tests.Performance/Program.cs
- src/core/Akka.Streams.Tests.Performance/Akka.Streams.Tests.Performance.csproj
- src/core/Akka.Streams.Tests.Performance/App.config
- src/core/Akka.Streams.Tests.Performance/Program.cs
- src/core/Akka.Tests.Performance/Akka.Tests.Performance.csproj
- src/core/Akka.Tests.Performance/App.config
- src/core/Akka.Tests.Performance/Program.cs
> Nbench 2.0 Integration (Akka.NET v1.4)

- src/core/Akka.Remote/Configuration/Remote.conf
- src/core/Akka.Remote/Endpoint.cs
- src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs
- src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
Ported some other important Akka.Remote fixes to the v1.3.18 branch
> V1.3.18 backport

- src/core/Akka/Actor/ActorCell.DeathWatch.cs
- src/core/Akka/ActorState.cs
> [v1.4 port] Fix IActorRef leaks in AddressTerminatedTopic when entity terminates immediately after unwatching a remote actor. 

- src/core/Akka.API.Tests/Akka.API.Tests.csproj
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterMetrics.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveDistributedData.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommon.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommonQuery.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.cs
* Akka.Cluster.Sharding
* Akka.Cluster.Metrics
* Akka.DistributedData
* Akka.Persistence.Sql.Common
* Akka.Persistence.Sql.Query
> added missing API checks

- docs/community/whats-new/akkadotnet-v1.4.md
addressing future RCs and releases
> Update to "What's new in Akka.NET v1.4?" page

- src/core/Akka.Persistence.Tests/SnapshotDecodeFailureSpec.cs
- src/core/Akka.Persistence/Eventsourced.Recovery.cs
migrated from https://github.com/akka/akka/pull/26700
> Gracefully handle exception throw in SnapshotOffer

- src/contrib/cluster/Akka.DistributedData.Tests/ORMultiDictionarySpec.cs
- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs
- src/contrib/cluster/Akka.DistributedData/ORMultiValueDictionary.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs
> DData Replicator deserialize ORMultiValueDictionary as ORDictionary causing invalid cast exception

- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka.Tests/App.config
- src/core/Akka.Tests/Configuration/ConfigurationSpec.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
> Fix: ActorSystem.Settings did not load config from app.config file

- src/contrib/cluster/Akka.Cluster.Metrics/Akka.Cluster.Metrics.csproj
- src/contrib/serializers/Akka.Serialization.Hyperion/Akka.Serialization.Hyperion.csproj
> move Akka.Cluster.Metrics and Akka.Serialization.Hyperion out of beta

- src/core/Akka.Tests/Configuration/HoconTests.cs
Hocon unit test was accidentally removed,
> Add hocon unit test back

- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Bugfix4360Spec.cs
Affirms my suspicions about #4360
> test to confirm non-existence of SQLite persistence bug

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.4 includes one major fix for HOCON fallback configurations, a new module (Akka.Coordination), and some major improvements to Akka.Cluster.Tools / Akka.Cluster.Sharding:
* [Akka.Coordination: Lease API & integration](https://github.com/akkadotnet/akka.net/pull/4344)
* [Akka: Timers for self scheduled messages added, FSM timers fixes](https://github.com/akkadotnet/akka.net/pull/3778)
* [Akka **Important** Bugfix: Config.WithFallback is acting inconsistently](https://github.com/akkadotnet/akka.net/pull/4358)
* [Akka.Cluster.Sharding: Updates](https://github.com/akkadotnet/akka.net/pull/4354)
To see the full set of changes for Akka.NET 1.4.4, please [see the 1.4.4 milestone](https://github.com/akkadotnet/akka.net/milestone/35).
| COMMITS …
> v1.4.4 release notes

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/DeployerSpec.cs
- src/core/Akka/Actor/Deployer.cs
- src/core/Akka/Util/WildcardIndex.cs
- src/core/Akka/Util/WildcardTree.cs
> Add double wildcard support for deployment

- docs/articles/networking/io.md
> Fixed samples detection for Akka.IO docs page

- RELEASE_NOTES.md
Akka.NET v1.4.5 consists mostly of bug fixes and quality-of-life improvements.
* [Akka.Cluster.Sharding: release shard lease when shard stopped](https://github.com/akkadotnet/akka.net/pull/4369)
* [Akka.Cluster.DistributedData: ORMultiValueDictionary - DistributedData Serialization InvalidCastException Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet1[System.String]'](https://github.com/akkadotnet/akka.net/issues/4367)
* [Akka.Actor: Support double wildcards in actor deployment config](https://github.com/akkadotnet/akka.net/issues/4136)
To see the full set of changes for Akka.NET 1.4.5, please [see the 1.4.5 milestone](https://github.com/akkadotnet/akka.net/milestone/36).
| COMMITS | LOC+ | LOC- | AUTHOR …
> added v1.4.5 release notes

- docs/articles/clustering/cluster-sharding.md
> fix: improve doc for persistenceId for sharded entity actor

- src/core/Akka/Actor/ActorCell.DefaultMessages.cs
> Harden ActorCell.CurrentMessageId from integer overflow.

- src/contrib/cluster/Akka.DistributedData.LightningDB/Akka.DistributedData.LightningDB.csproj
- src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs
- src/contrib/cluster/Akka.DistributedData.Tests/Serialization/ReplicatorMessageSerializerSpec.cs
- src/contrib/cluster/Akka.DistributedData/DistributedData.cs
- src/contrib/cluster/Akka.DistributedData/Durable/Messages.cs
- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/Proto/ReplicatorMessages.g.cs
- src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatorMessageSerializer.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveDistributedData.approved.txt
- src/protobuf/ReplicatorMessages.proto
> standardize LMDB wire format

- src/core/Akka.Docs.Tests/Streams/StreamRefsDocTests.cs
Need to change the `SinkRef` documentation for now, until we can address issue #4421
> Change the SinkRef documentation temporarily until we can fix serialization

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Cluster.Tests.MultiNode/NodeChurnSpec.cs
- src/core/Akka.Tests/Actor/ActorSystemSpec.cs
- src/core/Akka.Tests/Actor/Setup/ActorSystemSetupSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSetupSpec.cs
- src/core/Akka.Tests/Serialization/SerializationSpec.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/Internal/ActorSystemImpl.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Actor/Setup/ActorSystemSetup.cs
- src/core/Akka/Serialization/Serialization.cs
- src/core/Akka/Serialization/SerializationSetup.cs
- src/core/Akka/Util/Option.cs
> Implement ActorSystemSetup

- docs/articles/actors/finite-state-machine.md
Fixed lines references to .cs files of the "A Simple Example" paragraph
> Fixed documentation of finite-state-machine.md

- docs/articles/clustering/distributed-data.md
close #4288 (only one out of 3 items)
> update documentation: DData is no longer in beta

- RELEASE_NOTES.md
Akka.NET v1.4.7 is a fairly sizable path that introduces some significant new features and changes:
* [Akka: added `akka.logger-async-start` HOCON setting to allow loggers to start without blocking `ActorSystem` creation](https://github.com/akkadotnet/akka.net/pull/4424) - useful for developers running Akka.NET on Xamarin or in other environments with low CPU counts;
* [Akka: ported `ActorSystemSetup` to allow programmatic config of serializers and other `ActorSystem` properties](https://github.com/akkadotnet/akka.net/issues/4426)
* [Akka.Streams: update and modernize Attributes](https://github.com/akkadotnet/akka.net/pull/4437)
* [Akka.DistributedData.LightningDb: Wire format stabilized](https://github.com/akkadotnet/akka.net/issues/4261) - …
> added v1.4.7 release notes

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Remote/Akka.Remote.csproj
- src/core/Akka.Remote/UniqueAddress.cs
- src/core/Akka.Streams/ActorMaterializer.cs
- src/core/Akka.Streams/Properties/AssemblyInfo.cs
- src/core/Akka/Util/Helpers.cs
- src/core/Akka/Util/WildcardIndex.cs
Related to #4436
Several changes needed in the base Akka.NET source code to support Akka.Remote.Artery port.
> Update Akka.NET source code to support Akka.Remote.Artery port.

- build-system/azure-pipeline.mntr-template.yaml
- build-system/azure-pipeline.template.yaml
- build-system/nightly-builds.yaml
- build-system/pr-validation.yaml
- build-system/windows-release.yaml
- build.ps1
- src/common.props
Related to #4434
Upgrade .NET SDK to 3.1.105
> Fix CPU utilization regression due to .NET SDK regression

- RELEASE_NOTES.md
Akka.NET v1.4.8 features some important bug fixes for Akka.NET v1.4:
* [Akka: fix issue with setting IActorRefProvider via BootstrapSetup](https://github.com/akkadotnet/akka.net/pull/4473)
* [Akka.Cluster: Akka v1.4 Idle CPU usage increased comparing v1.3](https://github.com/akkadotnet/akka.net/issues/4434)
* [Akka.Cluster.Sharding: Backport of the feature called ClusterDistribution in Lagom](https://github.com/akkadotnet/akka.net/pull/4455)
* [Akka.TestKit: added ActorSystemSetup overload for TestKits](https://github.com/akkadotnet/akka.net/pull/4464)
To see the [full set of fixes in Akka.NET v1.4.8, please see the milestone on Github](https://github.com/akkadotnet/akka.net/milestone/39).
| --- | --- | --- | --- …
> added v1.4.8 release notes

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
> SqlJournal: Fixed updating the _persistenceIdSubscribers dictionary when adding a subscriber

- docs/articles/clustering/cluster-configuration.md
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
- src/core/Akka.Cluster/ClusterDaemon.cs
- src/core/Akka.Cluster/ClusterReadView.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
> Useful to enable when troubleshooting to log all cluster events.
[#25918](https://github.com/akka/akka/pull/25918)
> Cluster event listener that logs all events

- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/SqlReadJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryApi.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/BatchingSqliteAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteAllEventsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite/Journal/SqliteQueryExecutor.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceQuery.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommon.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommonQuery.approved.txt
- src/core/Akka.Persistence.Query/Interfaces.cs
- src/core/Akka.Persistence.TCK/Query/AllEventsSpec.cs
> Add AllEvents persistent query command

- RELEASE_NOTES.md
Akka.NET v1.4.9 features some important bug fixes for Akka.NET v1.4:
* [Akka: Re-enable dead letter logging after specified duration](https://github.com/akkadotnet/akka.net/pull/4513)
* [Akka: Optimize allocations in `ActorPath.Join()`](https://github.com/akkadotnet/akka.net/pull/4510)
* [Akka.IO: Optimize TCP-related actor creation in Akka.IO](https://github.com/akkadotnet/akka.net/pull/4509)
* [Akka.DistributedData: Resolve "An Item with the same key but different value already exists" error during pruning](https://github.com/akkadotnet/akka.net/pull/4512)
* [Akka.Cluster: Cluster event listener that logs all events](https://github.com/akkadotnet/akka.net/pull/4502)
* [Akka.Cluster.Tools.Singleton.ClusterSingletonManager bug: An element with the …
> added v1.4.9 release notes

- docs/articles/clustering/cluster-overview.md
`You should use clustering in any scenario where you have....Non-Trivial to perform.` didn't make sense to me. I'm actually taking a guess as to what this condition is, but I propose that you're saying that we should use clustering when there is a non-trivial task to perform (because you want complex tasks to be fault-tolerant?).
> Clear language on clustering conditions

- src/core/Akka.Persistence.TCK/Performance/JournalPerfSpec.cs
I'm pretty sure the defaults for the JournalPerfSpec will only work for in-memory datastores, hence why they're overridable in the JVM.
> Allow persistence plugins to customize JournalPerfSpec's default values

- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
Port: [#26611](https://github.com/akka/akka/pull/26611)
> Print TypeName in ShardRegion logs

- src/core/Akka.Persistence.TCK/Query/PersistenceIdsSpec.cs
Added Virtual property `AllocatesAllPersistenceIDsPublisher` and make `ReadJournal_should_deallocate_AllPersistenceIds_publisher_when_the_last_subscriber_left` contingent on it being true.
> PersistenceIdsSpeck TCK Updates -  make deallocate_AllPersistenceIds test opt-out

- src/core/Akka.Cluster/SplitBrainResolver.cs
And then the logs look better!
> Fix ToString for KeepOldest strategy

- docs/articles/actors/schedulers.md
- docs/articles/toc.yml
- src/common.props
- src/core/Akka.Docs.Tests/Actors/ReceiveTimeoutSpecs.cs
- src/core/Akka.Docs.Tests/Actors/SchedulerSpecs.cs
- src/core/Akka.Docs.Tests/Akka.Docs.Tests.csproj
> Document new timers and scheduling APIs

- src/common.props
- src/core/Akka.MultiNodeTestRunner.Shared/Sinks/TimelineLogCollectorActor.cs
- src/core/Akka.MultiNodeTestRunner/Program.cs
> MultiNodeSpecs: turn off debug logging for all of them #4215

- src/contrib/cluster/Akka.DistributedData/Internal/Internal.cs
> Fix KeyNotFound exception thrown by DData DataEnvelope.Equals

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/PatternMatch.cs
> Deprecate PatternMatch

- src/core/Akka.Tests/IO/TcpListenerSpec.cs
- src/core/Akka.Tests/IO/UdpListenerSpec.cs
- src/core/Akka/IO/UdpListener.cs
Fix for https://github.com/akkadotnet/akka.net/issues/4641
> Fix: UdpListener does not react properly on SocketError != Success (Issue 4641)

- src/Akka.sln
- src/contrib/persistence/Akka.Persistence.Query.Sql/AllEventsPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByPersistenceIdPublisher.cs
- src/contrib/persistence/Akka.Persistence.Query.Sql/EventsByTagPublisher.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistence.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceQuery.approved.txt
- src/core/Akka.API.Tests/CoreAPISpec.ApprovePersistenceSqlCommon.approved.txt
- src/core/Akka.Persistence.Query/EventEnvelope.cs
- src/core/Akka.Persistence.TCK/Akka.Persistence.TCK.csproj
- src/core/Akka.Persistence.TCK/Journal/JournalSpec.cs
- src/core/Akka.Persistence.TCK/Query/CurrentEventsByPersistenceIdSpec.cs
- src/core/Akka.Persistence.TCK/Query/CurrentEventsByTagSpec.cs
- src/core/Akka.Persistence.TCK/Query/EventsByPersistenceIdSpec.cs
- src/core/Akka.Persistence/Persistent.cs
- src/core/Akka.Persistence/Serialization/PersistenceMessageSerializer.cs
- src/core/Akka.Persistence/Serialization/Proto/Persistence.g.cs
- src/protobuf/Persistence.proto
> Added Timestamp to EventEnvelope

- src/core/Akka/Dispatch/SysMsg/ISystemMessage.cs
> Update ActorTaskSchedulerMessage with defensive coding to prevent possible NRE problems in the future.

- src/examples/Cluster/Metrics/Samples.Cluster.Metrics.Common/Samples.Cluster.Metrics.Common.csproj
per my review comment on https://github.com/akkadotnet/akka.net/pull/4691
> cleaned up duplicate TargetFramework tag in Samples.Cluster.Metrics.Common

- RELEASE_NOTES.md
Akka.NET v1.4.14 contains some significant bug fixes and improvements. It is a _highly recommended upgrade_ for all Akka.NET users.
**Major Reduction in Idle CPU Usage and Latency for Akka.Remote**
One of the most important fixes introduced in [Akka.NET v1.4.14 is the new self-tuning batching system for Akka.Remote's DotNetty transport](https://getakka.net/articles/remoting/performance.html), which simulatneously reduces idle CPU consumption on low-traffic systems by as much as 55% while improving latency by a factor of 10 for low-traffic systems. 
The batching system no longer needs to be configured - it can scale up and down with workload automatically in order to both maximize throughput with a minimal amount of latency. You can read more about …
> added v1.4.14 release notes

- src/Akka.sln
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Actors/AkkaService.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Actors/HasherActor.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Messages/HashReply.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Program.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Samples.Akka.AspNetCore.csproj
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Services/IHashService.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Services/IPublicHashingService.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/Startup.cs
- src/examples/AspNetCore/Samples.Akka.AspNetCore/app.conf
- src/examples/AspNetCore/Samples.Akka.AspNetCore/appsettings.Development.json
- src/examples/AspNetCore/Samples.Akka.AspNetCore/appsettings.json
close #4454 
Working on adding some documentation for the new DI system as well.
> added full ASP.NET Core + DI sample

- docs/community/getting-access-to-nightly-builds.md
Also added Akka.NET symbol access for nightlies and SourceLink setup.
> Update nightly Akka.NET Urls

- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/Akka.DependencyInjection.Tests.csproj
- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/AkkaDiFixture.cs
> Update Akka.DependencyInjection.Tests to use IHostedService

- src/core/Akka.Persistence.TestKit.Tests/Bug4762FixSpec.cs
- src/core/Akka.Persistence.TestKit/Journal/TestJournal.cs
> Fix TestJournal exception aggregation

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
- src/core/Akka.TestKit.Tests/Akka.TestKit.Tests.csproj
- src/core/Akka.TestKit.Tests/TestEventListenerTests/AllTestForEventFilterBase.cs
- src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs
> Make Expect(0) to throw when any event received

- src/core/Akka.Streams.Tests/Dsl/GraphStageTimersSpec.cs
- src/core/Akka.Streams.Tests/Dsl/RestartSpec.cs
- src/core/Akka.Streams.Tests/Dsl/SinkForeachParallelSpec.cs
- src/core/Akka.Streams.Tests/Dsl/StreamRefsSerializerSpec.cs
- src/core/Akka.Streams.Tests/Dsl/StreamRefsSpec.cs
- src/core/Akka.Streams.Tests/Dsl/UnfoldFlowSpec.cs
- src/core/Akka.Streams/Dsl/IntervalBasedRateLimiter.cs
- src/core/Akka.Tests/Actor/FSMTransitionSpec.cs
Fix racy specs failed in https://github.com/akkadotnet/akka.net/pull/4782 and https://github.com/akkadotnet/akka.net/pull/4783
> Fix few racy specs

- src/core/Akka.Persistence.TCK/Query/CurrentAllEventsSpec.cs
- src/core/Akka.Persistence.TCK/Query/EventsByTagSpec.cs
- src/core/Akka.Persistence.TestKit.Tests/TestJournalSpec.cs
- src/core/Akka.Persistence.Tests/PersistentActorSpecAsyncAwait.cs
- src/core/Akka.Remote.Tests/Transport/DotNettySslSupportSpec.cs
Fixes another set of racy specs failed in https://github.com/akkadotnet/akka.net/pull/4782
> Harden few racy specs

- src/core/Akka.TestKit.Tests/TestEventListenerTests/AllTestForEventFilterBase.cs
- src/core/Akka.TestKit/EventFilter/Internal/EventFilterApplier.cs
> Fix ExpectAsync(0) implementation

- src/core/Akka.Remote.Tests/BugFixes/BugFix4384Spec.cs
- src/core/Akka/Actor/Futures.cs
> Fix finding of temprorary actor for Ask pattern when having multiple ActorSystems

- docs/articles/clustering/split-brain-resolver.md
- src/core/Akka.Cluster.Tests/SBR/SplitBrainResolverSpec.cs
- src/core/Akka.Cluster/Configuration/Cluster.conf
- src/core/Akka.Cluster/SBR/DowningStrategy.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolver.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolverProvider.cs
- src/core/Akka.Cluster/SBR/SplitBrainResolverSettings.cs
Building on the work done in https://github.com/akkadotnet/akka.net/pull/4587 and cleaning up code, updating documenation, working on a clean cut-over path from the current Akka.NET split brain resolver. Delving into the code more some too.
> Cleanup Akka.Cluster.SBR for release

- src/common.props
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Actor/Deploy.cs
- src/core/Akka/Actor/Props.cs
Made the `Deploy` methods virtual so `Deploy` can be overridden in subsequent systems to carry additional actor information.
> made Deploy methods virtual

- src/contrib/cluster/Akka.Cluster.Metrics.Tests/ClusterMetricsExtensionSpec.cs
> Fix ClusterMetricsExtensionSpec racy spec

- src/core/Akka.Cluster/ClusterDaemon.cs
Handle CoordinatedShutdown exiting-completed when not joined
* assertion failed: Nodes not part of cluster have marked the Gossip as seen
* trying to mark the Gossip as seen before it has joined, which may happen
if CoordinatedShutdown is running before the node has joined
migrated from https://github.com/akka/akka/pull/26835
> Handle CoordinatedShutdown exiting-completed when not joined

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka/Annotations/Attributes.cs
> Added DoNotInherit annotation

- src/core/Akka.Remote/RemoteWatcher.cs
This PR doesn't make any substantive changes to the `RemoteWatcher`, but it cleans up the code using newer C# language constructs and eliminates some very awkward conditional branching that could be simplified.
> cleaned up RemoteWatcher

- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/AkkaDiFixture.cs
Rewrite the AkkaDiFixture so that it does not need to start a HostBuilder
close #4919
> Fix for issue 4919

- src/core/Akka.Cluster/ClusterRemoteWatcher.cs
- src/core/Akka.Remote/RemoteWatcher.cs
- src/core/Akka/Event/EventBusUnsubscriber.cs
These should run on the internal dispatcher too
> Fixed some internal-dispatcher usages

- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentEventsByTagSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Batching/BatchingSqliteCurrentPersistenceIdsSpec.cs
- src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Query/SqliteCurrentEventsByTagSpec.cs
Re-enable all the skipped batching specs, these runs just fine now.
> Enable skipped batching SQLite specs

- src/contrib/dependencyinjection/Akka.DependencyInjection/ServiceProvider.cs
Changed `Akka.DependencyInjection.ServiceProvider` deprecation message to read "1.4.21" rather than 1.4.20
> fixed incorrect deprecation message

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/QueryExecutor.cs
> Use TimestampProvider in QueryExecutor.InsertBatchAsync.

- docs/articles/actors/receive-actor-api.md
Closes https://github.com/akkadotnet/akka.net/issues/4973
> Fix documentation flaw for "Forward"

- src/contrib/dependencyinjection/Akka.DependencyInjection/IDependencyResolver.cs
- src/contrib/dependencyinjection/Akka.DependencyInjection/ServiceProviderDependencyResolver.cs
> return `T` from `IDependencyResolver.GetService<T>()`

- src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializer.cs
> Make Hyperion deserialization exception message more verbose to help with debugging.

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingMessageSerializerSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Shard.cs
> Fix persistence cluster sharding serialization failure

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.TestKit/ActorCellKeepingSynchronizationContext.cs
- src/core/Akka.TestKit/Internal/InternalTestActorRef.cs
- src/core/Akka.Tests/Actor/BugFix4823Spec.cs
- src/core/Akka/Actor/ActorCell.cs
- src/core/Akka/Dispatch/ActorTaskScheduler.cs
> Fix actor TestActorRef<> loosing Self reference in async context

- src/core/Akka.Cluster/ClusterDaemon.cs
Minor fix, supposed to be Ack, not Nack
> Fix typo in logging

- docs/articles/clustering/cluster-sharding.md
* Link to https://github.com/petabridge/Akka.Cluster.Sharding.RepairTool
* Add section on what happens if your Akka.Cluster.Sharding persistence data gets corrupted
* Update outdated documentation on creating proper PersistentIds while using Cluster.Sharding
> updated Akka.Cluster.Sharding docs to mention Akka.Cluster.Sharding.RepairTool

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesNewExtractorSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingRememberEntitiesSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ClusterShardingConfigSpec.cs
- src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj
- src/contrib/cluster/Akka.Cluster.Sharding/reference.conf
Reverts akkadotnet/akka.net#5175
> Revert "Remove LightningDB reference in cluster sharding, make ddata non-durable as default"

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
saw this error come up while running benchmarks in https://github.com/akkadotnet/akka.net/pull/5209
> fixed NRE inside ClusterSingletonManager

- docs/articles/utilities/logging.md
There was missing last curly bracket.
> Fix example configuration

- src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManager.cs
> singleton fix cleanup of overdue _removed members

- src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/AsyncWriteProxyEx.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
- src/core/Akka.Tests/Actor/AskSpec.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Reverts akkadotnet/akka.net#5221
Totally did not mean to merge that PR in. 
@Zetanova I'd still like to see a version of #5221 but we should address the feedback I included on it. Sorry for the screw-up on my part here.
> Revert "Ask should push unhandled answers into deadletter"

- src/core/Akka.Streams.Tests/Dsl/UnfoldFlowSpec.cs
Same issue as in https://github.com/akkadotnet/akka.net/pull/5262
> hardened more UnflowFlowSpec

- src/core/Akka.Streams.Tests/Dsl/UnfoldFlowSpec.cs
Removing yet another problematic `ExpectNoMsgs` call....
> harden UnfoldFlowSpec

- src/core/Akka.Remote/Configuration/Remote.conf
Links to our upgrade advisory page here: https://getakka.net/community/whats-new/akkadotnet-v1.4-upgrade-advisories.html#upgrading-to-akkanet-v1426-from-older-versions
> Added HOCON comment for `akka.actor.serialization-settings.primitive.use-legacy-behavior`

- src/core/Akka.API.Tests/CoreAPISpec.ApproveCluster.approved.txt
- src/core/Akka.Cluster/Properties/AssemblyInfo.cs
See [#232](https://github.com/akkadotnet/Akka.Management/issues/232)
> Sets InternalsVisibleTo in Akka.Cluster for Akka.Management.Cluster.Http

- src/core/Akka.TestKit.Tests/TestKitBaseTests/ReceiveTests.cs
- src/core/Akka.TestKit/Akka.TestKit.csproj
- src/core/Akka.TestKit/TestKitBase_Receive.cs
Implement nitpicks from https://github.com/akkadotnet/akka.net/pull/5430
cc @brah-mcdude
> Make updates to `FishUntil`

- .github/workflows/nightly-nuget.yml
> Avoid nightly jobs in forked projects

- docs/toc.yml
https://github.com/akkadotnet/akka.net/issues/4786
Fixes #https://github.com/akkadotnet/akka.net/issues/4786
Added a top-level link to the Github Discussions area for Akka.NET on our website.
> Added Github Discussions to top of website

- build.fsx
MNTR tests were outputting their logs inside the test assembly folder, need to move them to the TestResults/multinode folder.
> Fix build script, MNTR should output to TestResults/multinode

- src/benchmark/Akka.Cluster.Benchmarks/Persistence/JournalWriteBenchmarks.cs
- src/benchmark/Akka.Cluster.Benchmarks/Persistence/PersistenceInfrastructure.cs
- src/benchmark/Akka.Cluster.Benchmarks/Persistence/RecoveryBenchmark.cs
Switch Akka.Cluster.Benchmark persistence benchmark from using SQLite to MemoryJournal to minimize external variable
> [Cluster] Switch Persistence benchmark from using SQLite to MemoryJournal

- build.fsx
- src/examples/Akka.Persistence.Custom.Tests/Akka.Persistence.Custom.Tests.csproj
Ignore all test projects in the examples folder
> Fix build script trying to run tests on test projects in example folder

- src/core/Akka.TestKit/TestActorRefBase.cs
It is just a comment. But a rather important one.
> Added note that Test Receive method violates the actor model

- src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs
Fixes #5546
Handle `StreamDetachedException` @to11mtm
> Catch `StreamDetachedException`

- docs/articles/actors/dispatchers.md
Fixes #5558
Changed the throughput number to 30 from 100
> Correct the `throughput` numbers

- docs/articles/clustering/distributed-publish-subscribe.md
close #5557
Import HOCON properties with docfx code reference
> Docs: Update "Distributed Publish Subscribe in Cluster"

- src/core/Akka.Streams/Dsl/RestartFlow.cs
Deleted `inheritdoc` for external assembly in `Akka.Streams.Dsl.RestartFlow.cs`
> Docs: Fixed `inheritdoc` issue in `Akka.Streams.Dsl.RestartFlow.cs`

- src/core/Akka.Streams/Util/EnumeratorEnumerable.cs
Deleted `inheritdoc` for external assembly in `Akka.Streams.Util.EnumeratorEnumerable.cs`
> Docs: Fixed `inheritdoc` issue in `Akka.Streams.Util.EnumeratorEnumerable`

- src/core/Akka/Actor/ActorBase.cs
- src/core/Akka/Actor/ActorPath.cs
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/ActorSelection.cs
- src/core/Akka/Actor/ActorSystem.cs
- src/core/Akka/Actor/Address.cs
- src/core/Akka/Actor/Cancellation/Cancelable.cs
- src/core/Akka/Actor/ChildrenContainer/Internal/ChildStats.cs
- src/core/Akka/Actor/Extensions.cs
- src/core/Akka/Actor/FSM.cs
- src/core/Akka/Actor/IAutoReceivedMessage.cs
- src/core/Akka/Actor/Inbox.cs
- src/core/Akka/Actor/LocalActorRef.cs
- src/core/Akka/Actor/Props.cs
- src/core/Akka/Actor/RemoteScope.cs
- src/core/Akka/Actor/Scheduler/HashedWheelTimerScheduler.cs
- src/core/Akka/Actor/Scope.cs
- src/core/Akka/Actor/Settings.cs
- src/core/Akka/Actor/SupervisorStrategy.cs
Part of #5542
Deleted `/// <inheritdoc/>`
> Docs: removed `inheritdoc` tags

- src/core/Akka/NotUsed.cs
Part of #5542
Please provide a brief description of the changes here.
> Docs: Fixed Base Documentation in `NotUsed.cs`

- src/core/Akka.Persistence/JournalProtocol.cs
> Docs: Fix unresolved base documentaion in `JournalProtocol.cs`

- src/core/Akka.Persistence/SnapshotProtocol.cs
> Docs: Fix unresolved base documentaion in `SnapshotProtocol.cs`

- docs/articles/clustering/cluster-metrics.md
- docs/articles/configuration/modules/akka.testkit.md
- docs/articles/intro/getting-started/tutorial-overview.md
- docs/articles/networking/io.md
- docs/articles/remoting/performance.md
- docs/articles/testing/multi-node-testing-old.md
- docs/articles/testing/multi-node-testing.md
- docs/community/whats-new/akkadotnet-v1.4.md
- src/contrib/dependencyinjection/Akka.DependencyInjection.Tests/ActorServiceProviderPropsWithScopesSpecs.cs
- src/core/Akka.Docs.Tests/Networking/IO/EchoConnection.cs
- src/core/Akka.Docs.Tests/Networking/IO/EchoServer.cs
- src/core/Akka.Docs.Tests/Networking/IO/TelnetClient.cs
- src/examples/Akka.Persistence.Custom/SqlitePersistence.cs
> Docs: Fixed invalid file links

- docs/api/index.md
- docs/articles/persistence/custom-persistence-provider.md
- docs/articles/remoting/performance.md
- docs/articles/testing/multi-node-testing-old.md
- docs/articles/testing/multi-node-testing.md
- src/common.props
- src/contrib/testkits/Akka.TestKit.Xunit/Internals/AkkaAssertEqualityComparer.cs
- src/examples/Akka.Persistence.Custom/SqlitePersistence.cs
Part fix for https://github.com/akkadotnet/akka.net/pull/5542
> Docs: Fix invalid paths

- src/core/Akka.TestKit/Internal/BlockingQueue.cs
- src/core/Akka.TestKit/TestKitBase_Receive.cs
> Add peek methods into BlockingQueue and TestKitBase

- src/core/Akka.TestKit/TestKitBase_AwaitConditions.cs
Changed `AwaitCondition()` to sync over async that calls `AwaitConditionAsync()`
> `AwaitCondition()` over `AwaitConditionAsync()`

- RELEASE_NOTES.md
> Added placeholder for 1.4.35

- docs/template/styles/main.css
Fixes https://twitter.com/Philco78/status/1501911099184238597 - video embeds on the new documentation website break the layout on mobile.
> fix video embeds on mobile

- src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
- src/core/Akka.Streams.Tests/Dsl/FlowWithContextSpec.cs
- src/core/Akka.Streams.Tests/Dsl/SourceWithContextSpec.cs
- src/core/Akka.Streams/Dsl/FlowWithContext.cs
- src/core/Akka.Streams/Dsl/SourceWithContext.cs
Port: [#27201](https://github.com/akka/akka/pull/27201)
> Add MapMaterializedValue for Source/Flow WithContext

- build-system/pr-validation.yaml
Locked `cspell` on version `[5.18.5](https://www.npmjs.com/package/cspell/v/5.18.5)`
> Lock cspell on version `5.18.5`

- src/core/Akka.Tests/Actor/AskSpec.cs
- Changed `Can_Ask_actor_inside_receive_loop` to `async/await`
- Changed `SomeActor` to `ReceiveActor`
> Port `Akka.Tests.Actor` tests to `async/await` - AskSpec

- src/core/Akka.Tests/Dispatch/DispatchersSpec.cs
- `Dispatchers_must_complain_about_missing_Config`
- `Dispatchers_must_throw_ConfigurationException_if_type_doesnt_exist`
- Changed `Dispatchers_must_be_used_when_configured_in_explicit_deployments` to `async/await`
- Changed `Dispatchers_must_be_used_in_deployment_configuration` to `async/await`
- Changed `Dispatchers_must_be_used_in_deployment_configuration_and_trumps_code` to `async/await`
- Changed `Dispatchers_must_use_pool_dispatcher_router_of_deployment_config` to `async/await`
> Port `Akka.Tests.Dispatch` tests to `async/await` - `DispatchersSpec`

- src/core/Akka.Tests/Routing/ResizerSpec.cs
- Changed `DefaultResizer_must_be_possible_to_define_programmatically` to `async/await`
- Changed `DefaultResizer_must_be_possible_to_define_in_configuration` to `async/await`
- Changed `DefaultResizer_must_grow_as_needed_under_pressure` to `async/await`
> Port `Akka.Tests.Routing` tests to `async/await` - `ResizerSpec`

- src/contrib/cluster/Akka.Cluster.Sharding/Internal/EventSourcedRememberEntitiesCoordinatorStore.cs
Fixes #5862
Fixes incorrect use of Union in sharding recovery
> fix sharding recovery

- build.fsx
- src/common.props
Update to MNTR 1.1.1 to improve AzDo MNTR TRX reporting
> Update MNTR to 1.1.1 and update build script to suit

- docs/articles/streams/builtinstages.md
- docs/articles/streams/integration.md
- src/core/Akka.Streams.Tests/Dsl/ActorRefSourceSpec.cs
- src/core/Akka.Streams/Dsl/Source.cs
- src/core/Akka.Streams/Implementation/ActorRefSourceActor.cs
Port: [#25286](https://github.com/akka/akka/pull/25286)
> Fixes Source.ActorRef not completing

- src/core/Akka.Cluster.Tests/Routing/ClusterRouterSupervisorSpec.cs
> Cluste_aware_router

- src/core/Akka.Cluster.Tests/ClusterHeartbeatReceiverSpec.cs
- src/core/Akka.Cluster.Tests/ClusterHeartbeatSenderSpec.cs
> Cluster Heartbeat Receiver

- src/core/Akka.Streams.Tests/Dsl/HubSpec.cs
Requires #5934 to be merged first.
> Convert Akka.Streams.Tests to async - Dsl.HubSpec

- docs/articles/deployment/akkacluster-troubleshooting.md
- docs/articles/deployment/toc.yml
- docs/articles/discovery/index.md
Fixes #https://github.com/akkadotnet/akka.net/issues/5526
Working on adding an Akka.Cluster troubleshooting guide
> Started Akka.Cluster troubleshooting guide

- src/core/Akka.Persistence.TCK/Query/PersistenceIdsSpec.cs
These changes shouldn't change the test intent, they should be safe.
> Fix Akka.Persistence.TCK Persistence.Oracle issue

- .github/workflows/nightly-nuget.yml
Working on turning on some other GH actions, but want to disable this one for the time being
> Disabling GH NuGet nightly flow

- docs/toc.yml
The Discord experiment is a success. Let's make the switch official.
> migrate project chat from Gitter to Discord

- src/core/Akka.Cluster.Tests/SBR/SplitBrainResolverSpec.cs
- src/core/Akka.Cluster/SBR/DowningStrategy.cs
Keep SBR up to date with the JVM.
> [SBR] Ignore reachability records for invalid nodes

- src/core/Akka/Actor/SupervisorStrategy.cs
Port of https://github.com/akkadotnet/akka.net/pull/6070 to 1.5
> enabled `Directive.Resume` to log the full `Exception`

- docs/community/build-process.html
`contributing/build-process.html` --> `community/contributing/build-process.html`
> added missing redirect for build documentation

- src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSettingsSpec.cs
- src/contrib/cluster/Akka.DistributedData/Replicator.cs
- src/contrib/cluster/Akka.DistributedData/ReplicatorSettings.cs
- src/contrib/cluster/Akka.DistributedData/reference.conf
- src/core/Akka.API.Tests/CoreAPISpec.ApproveDistributedData.verified.txt
Backport of #6080 to v1.4 branch
> [BACKPORT] #6080 Extend DistributedData Replicator settings with VerboseDebugLogging switch

- src/core/Akka.TestKit/TestKitBase.cs
- Change TestKitBase.InitializeTest to virtual so it can be deferred
This is needed for Akka.Hosting.TestKit
> Change TestKitBase.InitializeTest to virtual so it can be deferred

- src/core/Akka.TestKit/TestKitBase.cs
Port of #6093
(cherry picked from commit 63639b9f77792e99672934ed01d3d5bb8fd8a19f)
> [PORT #6093] Change TestKitBase.InitializeTest to virtual so it can be deferred

- README.md
cherry-picked from bfdd559cf9fdc429c0f698b6c764c086f09f0817
> [PORT #6112] made README.md NuGet-friendly

- src/contrib/cluster/Akka.Cluster.Sharding/Akka.Cluster.Sharding.csproj
- src/core/Akka.Cluster/Akka.Cluster.csproj
- src/core/Akka.Persistence/Akka.Persistence.csproj
- src/core/Akka.Remote/Akka.Remote.csproj
- src/core/Akka.Streams/Akka.Streams.csproj
- src/core/Akka/Akka.csproj
Co-authored-by: Gregorius Soedharmo <arkatufus@yahoo.com>
(cherry picked from commit 256235bab7a559496689a178da86757c8ec8195f)
> [PORT #6111] cleaned up NuGet package descriptions

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/Akka.Cluster.Sharding.Tests.csproj
- src/contrib/cluster/Akka.Cluster.Sharding.Tests/ShardRegionQueriesHashCodeSpecs.cs
- src/contrib/cluster/Akka.Cluster.Sharding/ShardRegion.cs
(cherry-picked from 86a06792becb84030f0562cd0f5bff14c0ba9965)
> [Port #6120] Fix GetEntityLocation use wrong actor path

- src/contrib/cluster/Akka.Cluster.Sharding/DDataShardCoordinator.cs
Fixes #6132
It was handled, but the handler method returned false instead of true.
> Fix unhandled RememberShards by DDataShardCoordinator

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/InvalidSettingsSpec.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Cluster.Tests/InvalidClusterSettingsSpec.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka/Configuration/ConfigurationException.cs
> Improve error/exception message for misconfigured cluster provider

- src/contrib/cluster/Akka.Cluster.Sharding.Tests/InvalidSettingsSpec.cs
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Cluster.Tests/InvalidClusterSettingsSpec.cs
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka/Configuration/ConfigurationException.cs
> [PORT #6167] Improve error/exception message for misconfigured cluster provider

- src/contrib/cluster/Akka.Cluster.Sharding/ClusterSharding.cs
- src/core/Akka.API.Tests/CoreAPISpec.ApproveClusterSharding.verified.txt
cherry-picked from f5d5838f91222a582fcefc8478e8904795803f36
> [BACKPORT #6173] Add HashCodeMessageExtractor factory

- RELEASE_NOTES.md
Akka.NET v1.4.44 is a maintenance release for Akka.NET v1.4 that contains numerous performance improvements in critical areas, including core actor message processing and Akka.Remote.
**Performance Fixes**
* [remove delegate allocation from `ForkJoinDispatcher` and `DedicatedThreadPool`](https://github.com/akkadotnet/akka.net/pull/6143)
* [eliminate `Mailbox` delegate allocations](https://github.com/akkadotnet/akka.net/pull/6134)
* [Reduce `FSM<TState, TData>` allocations](https://github.com/akkadotnet/akka.net/pull/6145)
* [removed boxing allocations inside `FSM.State.Equals`](https://github.com/akkadotnet/akka.net/pull/6183)
* [Eliminate `DefaultLogMessageFormatter` allocations](https://github.com/akkadotnet/akka.net/pull/6168)
In sum you should expect to see total memory consumption, …
> added v1.4.44 release notes

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka.Cluster/ClusterSettings.cs
- src/core/Akka/Configuration/ConfigurationException.cs
Port of #6201
* Revert ConfigurationException due to binary incompatibility
* Update API Verify list
(cherry picked from commit 90dde2581c8ae903b5cff7c585dcc6a8725ef2aa)
> [PORT #6201] Revert ConfigurationException due to binary incompatibility

- src/contrib/cluster/Akka.Cluster.Tools/PublishSubscribe/DistributedPubSubMediator.cs
This is a usability improvement aimed at making sure we contain the full context of what topic we were trying to publish to or which `Put`-ed actor we were trying to publish to when there are no subscribers available on the local node.
(cherry picked from commit 9f84438ca4a04efb34b8f5a20ff1dc8c020a256b)
> [PORT #6209] Make sure that `DeadLetter`s published by `DistributedPubSubMediator` contain full context of topic

- src/core/Akka.Streams/ActorMaterializer.cs
Fixes Issue 1 of #6073 
Remove duplicate SubscriptionTimeoutSettings field checking and add check missing MaxFixedBufferSize field
> Remove suspicious code fragment in ActorMaterializer.cs

- src/contrib/cluster/Akka.Cluster.Metrics/Collectors/DefaultCollector.cs
- src/contrib/cluster/Akka.Cluster.Metrics/StandardMetrics.cs
- src/core/Akka/Util/Extensions/DateTimeExtensions.cs
Port of #6203
* Update DefaultCollector.cs
Co-authored-by: Aaron Stannard <aaron@petabridge.com>
(cherry picked from commit dca908baf06d91f4c424af9c116a0d5f07b30054)
> [PORT #6203] Improve Akka.Cluster.Metrics collected values 

- src/common.props
- src/contrib/persistence/Akka.Persistence.Sql.Common/Akka.Persistence.Sql.Common.csproj
- src/core/Akka.Tests/Akka.Tests.csproj
- src/core/Akka/Akka.csproj
close https://github.com/akkadotnet/akka.net/issues/6226
> Upgrade to System.Configuration.ConfigurationManager 6.0.1

- src/common.props
Upgrade to Newtonsoft.Json 13.0.1 as minimum version
> Upgrade to Newtonsoft.Json 13.0.1 as minimum version

- .github/workflows/codeql.yml
Akka.NET is a big project with a large installbase. It's time we add some security scanning tools to our suite. We'll see how CodeQL performs.
> Add CodeQL vulnerability scanning

- docs/articles/utilities/serilog.md
Fixes issues with https://github.com/akkadotnet/akka.net/pull/6260
> Fix serilog aspnet docs

- build-system/nightly-builds.yaml
- build-system/windows-release.yaml
* Added .NET 7.0 support for nightly build pipelines
* added .NET 7 to release pipeline also
Backport of #6288
> [Backport] Added .NET 7.0 support for release pipelines

- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Core.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
- src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.verified.txt
- src/core/Akka/Actor/ActorRef.cs
- src/core/Akka/Actor/Futures.cs
Port of https://github.com/akkadotnet/akka.net/pull/6322 to v1.5
> [PORT] make `FutureActorRef<T>` unsealed

- src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs
> [BACKPORT] FailChunkExecution does not handle `DbExceptions` wrapped in an `AggregateException` (#6361)

- RELEASE_NOTES.md
- src/common.props
Akka.NET v1.4.49 includes some new core Akka.NET APIs and bug fixes to fundamental `Akka.Actor` behavior.
* [Akka.Actor: Read stash capacity from actor's mailbox or dispatcher configuration](https://github.com/akkadotnet/akka.net/pull/6323)
* [Akka.Actor: Added support for `UnrestrictedStash`](https://github.com/akkadotnet/akka.net/pull/6325)
* [Akka.Actor: Add API for `UntypedActorWithStash` types](https://github.com/akkadotnet/akka.net/pull/6327)
* [Akka.Actor: set default `PoolRouter.SupervisorStrategy` to `Restart`](https://github.com/akkadotnet/akka.net/pull/6366)
* [Akka.Persistence.Sql.Common: FailChunkExecution does not handle `DbExceptions` wrapped in an `AggregateException` ](https://github.com/akkadotnet/akka.net/pull/6364)
You can see the [full set of tracked issues for …
> added v1.4.49 release notes

- src/core/Akka/Event/DeadLetterListener.cs
Quality of life improvement, append the message content to the end of deadletter log messages
> Append message content to deadletter log message

- RELEASE_NOTES.md
- docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
Version 1.5.0-beta3 contains **breaking API changes** and new API changes for Akka.NET.
* Removed a number of `Obsolete` APIs that were generally not used much.
* [Akka.Actor: `ActorSystem.Create` throws `PlatformNotSupportedException` on net7.0-android](https://github.com/akkadotnet/akka.net/issues/6459)
* [Akka.Actor: Append message content to `DeadLetter` log messages](https://github.com/akkadotnet/akka.net/pull/6448)
* [Akka.Streams: Use `ActorSystem` for `Materializer`](https://github.com/akkadotnet/akka.net/pull/6453) - *massive* memory improvements for applications that materialize a large number of streams.
* [Akka.Persistence.Query.Sql: backpressure control for queries](https://github.com/akkadotnet/akka.net/pull/6436) - full details on this here: …
> added 1.5.0-beta3 release notes

- docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
> Akka.Cluster.Sharding migration docs: full restart of cluster

- RELEASE_NOTES.md
- docs/articles/clustering/cluster-sharding.md
- docs/articles/deployment/aspnet-core.md
- docs/articles/deployment/headless-service.md
- docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
- docs/community/whats-new/akkadotnet-v1.5.md
- docs/index.md
Version 1.5.0 is a major new release of Akka.NET that is now marked as stable and ready for production use.
You can read the [full notes about what's changed in Akka.NET v1.5 here](https://getakka.net/community/whats-new/akkadotnet-v1.5.html). We also encourage you to watch our video: "[Akka NET v1.5 New Features and Upgrade Guide](https://www.youtube.com/watch?v=-UPestlIw4k)"
If you want to see the [full set of changes made in Akka.NET v1.5.0 so far, click here](https://github.com/akkadotnet/akka.net/milestone/7).
| 95 | 25041 | 24976 | Gregorius Soedharmo |
| 85 | 89784 | 18362 | Aaron Stannard |
| 76 | 95 | 95 | dependabot[bot] |
| 18 | 3201 | 908 | Ismael Hamed |
| 5 | 230 | 251 | Sergey Popov |
| 2 | 77 | 7 | Vagif Abilov | …
> V1.5/release notes
